### ISSUE TITLE
kube-aws 0.9.7 added another nodepool gets updated other nodepools including controllers and etcd

### ISSUE THREAD

**Issue by billyteves** [kubernetes-incubator/kube-aws#1006]
Hi, 

Does anyone encountered this kind of behaviour? 
The cluster is up and running, I just added another nodepool in cluster.yaml, then executed the command `kube-aws update --s3-uri <s3-path>` it then regenerated the contents of credentials and then updated the controlplane (etcds and controller) and all the nodepools that are currently running.

I was wondering if this is normal? I haven't updated the cluster for a while, more than 2 weeks and this kind of behaviour happened.

**Comment by mumoshu** [comment]
@billyteves Hi, thanks as always for using kube-aws!

Probably you have not specified `amiId` in cluster.yaml?
If that's the case, kube-aws could have retrieved a new AMI ID from the CoreOS site and implicitly "injected" it to `amiId`, hence all the nodes replaced one by one in `kube-aws update`.

**Comment by billyteves** [comment]
That's interesting. Upon checking again my cluster.yaml file, all the nodepools including the controller and etcd `amiId` has a defined value.

**Comment by mumoshu** [comment]
@billyteves Sorry I've mislooked this part:

> it then regenerated the contents of credentials

Would you mind sharing me how you got to notice that?

One thing came up in my mind is that, removing all the `*.pem.enc` files under the `credentials/` directory would result in kube-aws regeneratign all the .pem.enc files correspond to .pem files with different cipher texts(=nature of kms encryption), hence all the nodes get replaced.

**Comment by billyteves** [comment]
@mumoshu upon checking you are right, the .enc files are gone which is why it then regenerated and instances got replace. I might check with our team why its missing. May i know the use of it? Thanks @mumoshu !
