### ISSUE TITLE
Cluster TLS certs/keys rotation

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#1013]
@redbaron @c-knowles @danielfm I'm still scratching my head on how to achieve this safely and automatically.

For now, I'm recreating clusters until the certs expire but that's painful!

In general, we'd want to replace all the certs/keys targeted for rotation across all the nodes very fast, without replacing the node one by one just for cert/key update, right?

// Please see https://github.com/kubernetes/kubernetes/issues/25379#issuecomment-281533623 for more context.

Otherwise, delay in update process could result in downtime. For example, when apiservers w/ old key/cert on their nodes got restarted due to some reasons after etcd-server key/cert rotation on etcd nodes but before etcd-client key rotation on controller nodes, each restarted apiserver will fail connecting etcd with old key.

Related topics:

- For kubelets we can rely on TLS bootstraping. See #922.
- For etcd-ca, #907

**Comment by mumoshu** [comment]
I'm not really wanting to introduce an another moving-part to kube-aws but would it be feasible to utilize aws-ssm-agent or somethig for fast key/cert rotation?

**Comment by c-knowles** [comment]
I think for rotation the minimum requirement is for the target system to support two public keys as [noted here](https://github.com/kubernetes/kubernetes/issues/25379#issuecomment-281534343). We could use that facility and introduce a new kube-aws command or deal with it automatically in each `update` call?

**Comment by cheungpat** [comment]
I found myself needing to rotate credentials today which is really painful.

The `--service-account-key-file` option accepts public and private key files, perhaps we can keep previously generated apiserver cert files and use them for this option? Currently this option is set to `apiserver-key.pem` which is recreated each time `kube-aws` render credentials.

I think we can do this as part of `kube-aws render credentials`, but I think it is also okay to do this in a new command.

**Comment by mumoshu** [comment]
@cheungpat Thanks a lot for reminding that flag! I have been forgotten about that since https://github.com/kubernetes-incubator/kube-aws/issues/907#issuecomment-345665123

Yes, it would work.

Regarding the command, something like `kube-aws rotate service-account-key` would be cool but i'm unsure whats a realistic option from implementors perspective, as you need multiple steps to complete a rotation, even with the flag.

1. Add a new private and public key. The public key is appended to the pem file passed to service-account-key-file.
2. Ensure that old service account tokens are deleted and regenerated(any way to automate this process?
3. Remove the old pub key from the pem file.

For example, how `render credentials` work on the 3rd point?

**Comment by mumoshu** [comment]
Also see #1146 #1147

**Comment by davidmccormick** [comment]
Rotating of service account keys comes with risks - I wouldn't do it until there is a consensus within k8s as to how it should be done.  The issue is that you can't rotate out old service keys without regenerating any service accounts created by them, and restarting any pods that use those service accounts (which is disruptive).

I've done live certificate rotation before on k8s but the implementation was vault specific.  I don't personally believe that the cluster deployment tool, i.e. kube-aws, should be run in order to rotate certs- I do think, however, that there should be an automated facility utilising an online pki/api such as Vault.
