### ISSUE TITLE
Create and include a default IamFleetRole per kube-aws cluster

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#1037]
Extracted from https://github.com/kubernetes-incubator/kube-aws/issues/1022#issuecomment-346778723

cc @c-knowles 

Perhaps we could either:

- Include the default IamFleetRole for each spot-fleet based node pool 
- Or include it in the root stack and import it into all the spot-fleet based node pools depending on the default IamFleetRole?

The former would be easier to implement but the latter would consume a lesser num of roles in your aws account.

**Comment by c-knowles** [comment]
[Default limit](http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-limits.html#reference_iam-limits-entities) is 1000 roles per account.

I'm in favour of the simplified version until someone needs it shared.
