### ISSUE TITLE
Do we really need `stackTags` in cluster.yaml?

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#1038]
Especially after `instanceTags` is added to cluster.yaml.

Extracted from https://github.com/kubernetes-incubator/kube-aws/pull/1027#issuecomment-346723345

The context:

- [.stackTags doesn.t propagate to `worker.nodePools[].stackTags`](https://github.com/kubernetes-incubator/kube-aws/pull/1027#issuecomment-346722173)
- [`worker.nodePools[].stackTags` is the only way to tag all the cfn stack resources per node pool](https://github.com/kubernetes-incubator/kube-aws/pull/1027#issuecomment-346752583)
  - but what use-cases would it support?

cc @c-knowles

**Comment by c-knowles** [comment]
I guess there's a use case there somewhere. As a minimum requirement we should use the opportunity to add documentation for this setup and then at least it's clear what the intention of each set of tags is.
