### ISSUE TITLE
`instanceTags` does not seem to work

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#1046]
Extracted from https://github.com/kubernetes-incubator/kube-aws/pull/1027#issuecomment-347761432.

I was trying the config from the PR but could not `instanceTags` to work across any of controller/etcd/worker. Just trying to debug now.

After updating an existing cluster, I also have a root stack has a tag that does not exist any more in the root `stackTags`. This seems to be an AWS problem - the tags are not updated properly using the SDK.

Maybe it's also a concern that `worker.nodePools[].stackTags` is undocumented?

**Comment by camilb** [comment]
@c-knowles Works for me, just deployed a new cluster.

**Comment by c-knowles** [comment]
I’ve yet to find anything in the logs but will have another look.

**Comment by c-knowles** [comment]
I've updated to latest master (v0.9.9-rc.4) and been unable to reproduce this. I believe I did not fully merge the latest stack changes correctly although I don't have a full record. Either way, I cannot reproduce this now so going to close.
