### ISSUE TITLE
Kubernetes networking over AWS VPC

### ISSUE THREAD

**Issue by camilb** [kubernetes-incubator/kube-aws#1047]
https://github.com/aws/amazon-vpc-cni-k8s

**Comment by mumoshu** [comment]
Fun info: Calico will be enchanced to utilize Security Groups as the backend for network policies
Ref: https://github.com/aws/amazon-vpc-cni-k8s/issues/7#issuecomment-348134050

**Comment by mumoshu** [comment]
I'm really looking forward to this!

My only concern is that the limit of IPs per ENI e.g. 10 for c4.large. 10 pods per node at maximum? Sounds a bit low.

It is indeed better than the cni plugin for ECS which is limited by the number of max ENIs per EC2 instance(3 for c3.large. Only 2 pods per node?), though.

**Comment by liwenwu-amazon** [comment]
A c4.large node should be able to run 27 Pods.
Here is the calculation:
 3 ENIs * (10 IP addresses -1)

**Comment by mumoshu** [comment]
@liwenwu-amazon Thanks for chiming in!

Yes, it should -
Does amazon-vpc-cni-k8s already support utilizing multiple ENIs per EC2 instance to serve e.g. 3 ENIs * (10 IPs - 1), btw?

**Comment by liwenwu-amazon** [comment]
Yes.

**Comment by pawelprazak** [comment]
So if I understand it correctly, [according to the proposal](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/proposals/cni-proposal.md) the calculation would be e.g.:

Max IPs = min((N * M - N), subnet's free IP)

for m4.xlarge: 4*15-4 = 56 pods max

please correct me if I'm wrong

**Comment by camilb** [comment]
@mumoshu This looks interesting: https://github.com/lyft/cni-ipvlan-vpc-k8s

https://eng.lyft.com/announcing-cni-ipvlan-vpc-k8s-ipvlan-overlay-free-kubernetes-networking-in-aws-95191201476e

**Comment by mumoshu** [comment]
@liwenwu-amazon Great! Thanks for clarifying 👍 

Would you also mind enlightening us about how amazon-vpc-cni-k8s compares with cni-ipvlan-vpc-k8s?

One gotcha of the latter from lyft folks is that source pod IPs are lost in the Pod-Svc-Pod communication, like kube-proxy was in the user-space mode.

amazon-vpc-cni-k8s doesn't have a such restriction, right?

**Comment by mumoshu** [comment]
https://twitter.com/paulnivin/status/937877736369954816

**Comment by liwenwu-amazon** [comment]
amazon-vpc-cni-k8s will NOT change pod IPs for Pod-Svc-Pod communication.

**Comment by mumoshu** [comment]
@liwenwu-amazon Thanks again for the clarification.
Really looking forward to try it - Please keep up the great work!
