### ISSUE TITLE
Dashboard rejects logins with kubeconfig

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#1051]
kube-aws version: v0.9.9-rc.3

I'm really not sure this is due to kube-aws but my colleague @cw-sakamoto had trouble trying to login kubernetes-dashboard via the recently added login form by uploading kubeconfig.

Even after key/certs are embedded to make the kubeconfig self-contained, dashboard rejects a login saying "Not enough data to create auth info structure".

![image](https://user-images.githubusercontent.com/22009/33588534-b1646f2e-d9b6-11e7-9f55-baff989da5a1.png)

Has anyone encountered the same issue?
How did you manage it to work?

**Comment by camilb** [comment]
@mumoshu it doesn't work when using certificate authentication. Works only when kubeconfig uses token authentication. Ref. https://github.com/kubernetes/dashboard/issues/2474#issuecomment-348811806

https://github.com/kubernetes/dashboard/blob/master/src/app/backend/auth/kubeconfig.go#L107

**Comment by kachkaev** [comment]
@mumoshu do you think this issue can be closed now?

**Comment by mumoshu** [comment]
@kachkaev Thx for your detailed answer in the upstream issue!
If kube-dashboard never supports logins with kubeconfig containing certs/keys, there's no reason I keep this issue open!
Is it? We shouldn't expect dashboard to support that?

**Comment by kachkaev** [comment]
I guess it would be wrong to authenticate using certs, because the cert data is your private key, which should never leave your local filesystem. @floreks explained this in a bit more detail here: https://github.com/kubernetes/dashboard/issues/2474#issuecomment-348912376

**Comment by mumoshu** [comment]
@kachkaev Ah, made perfect sense!
I'm closing this then.
Thank you very much for the explanation 🍻
