### ISSUE TITLE
StatefulSets stuck in ContainerCreating on M5 generation

### ISSUE THREAD

**Issue by mclarke47** [kubernetes-incubator/kube-aws#1053]
I've been trying to use [M5s](https://aws.amazon.com/ec2/instance-types/m5/) as they are slightly cheaper. However whenever the workers are changed to an M5 instance the pods in statefulsets will not start due to the persistent volumes:

from `kubectl describe pod`

```  
21h		59s		630	kubelet, ip-10-172-81-220.eu-west-1.compute.internal			Warning		FailedMount	Unable to mount volumes for pod "zipkin-cassandra-0_default(f65705fa-d8e7-11e7-8cd7-060ac5ac5984)": timeout expired waiting for volumes to attach/mount for pod "default"/"zipkin-cassandra-0". list of unattached/unmounted volumes=[data-storage]
21h		59s		630	kubelet, ip-10-172-81-220.eu-west-1.compute.internal			Warning		FailedSync	Error syncing pod
```

The pvc is definitely bound, I can see it on the console and when I run `kubectl get pvc` it is marked as bound:

```
NAME                              STATUS    VOLUME                                     CAPACITY   ACCESSMODES   STORAGECLASS               AGE
data-storage-zipkin-cassandra-0   Bound     pvc-f6565e28-d8e7-11e7-8cd7-060ac5ac5984   20Gi       RWO           zipkin-cassandra-storage   21h
```

Switching back to M4s fixed this. 

`kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T17:03:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4+coreos.0", GitCommit:"4bb697e04f7c356347aee6ffaa91640b428976d5", GitTreeState:"clean", BuildDate:"2017-08-22T08:43:47Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

kube-aws version 0.9.8

Are you aware of any way this generation is different that we might need to compensate for?

**Comment by mumoshu** [comment]
Hi @mclarke47, it seems like we have to wait until K8S 1.9 for that!

Ref: https://github.com/kubernetes/kops/blob/master/docs/releases/1.8-NOTES.md#significant-changes

**Comment by mclarke47** [comment]
@mumoshu Thanks for the quick response!

**Comment by drywheat** [comment]
For what it's worth, trying to launch etcd instances using M5s also fails.
