### ISSUE TITLE
Enable PodSecurityPolicy by default + Option to choose either Permissive/Restrictive policy

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#1059]
AFAIK, `experiental.admission.podSecurityPolicy` in cluster.yaml only affects admission control (by definition) but PodSecurityPolicy isn't usable only after doing so.

Probably we need reasonable defaults like https://github.com/coreos/tectonic-installer/pull/2102 so that our users have choices to make the cluster even more secure or not, instead of just giving up setting up PSP.

**Comment by mumoshu** [comment]
Also https://github.com/kubernetes-incubator/bootkube/issues/782

**Comment by wwyiwzhang** [comment]
Hi @mumoshu, I think it's useful to add permission/restrictive policy. 
If we can enable PodSecurityPolicy by default (removing it from the experimental option), when cluster gets created, it will generate two pod security policies: one permissive and one very limited for tube-system namespace, also create a role and also do the role binding. Then in the manifest, user need to pass a key, something like `podSecurityPolicy: permissive` or `podSecurityPolicy: limited`.  If user doesn't provide this flag in the template, it will be defaulted as `podSecurityPolicy: permissive`.
I am trying to get an idea if this is similar to what you are thinking. Thanks.
