### ISSUE TITLE
NAT gateway tagging

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#1063]
The CloudFormation release of September 27, 2017 adds the support for tagging "AWS::EC2::NatGateway".
For consistency with other AWS resources managed by kube-aws, NAT gateways should also be tagged with `kubernetes.io/cluster/{{.ClusterName}}`.

Ref: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html

**Comment by vsamidurai** [comment]
issue has been fixed in #1596
