### ISSUE TITLE
Easy to understand descriptions of security groups

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#1064]
The CloudFormation release of November 2, 2017 added the `Description` property for `AWS::EC2::SecurityGroupEgress` and `AWS::EC2::SecurityGroupIngress`.
I would be nice to have descriptions like e.g.:

* "HTTPS access to apiserver from the Internet via NLB" for the inbound rule for 443 of controller nodes,
* "Flannel peer communication for the VXLAN overlay network" for the inbound rule for 8472 of worker/controller/etcd nodes,

and so on.

Ref: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html

**Comment by kiich** [comment]
Small but very helpful idea! I'll read up on what's been set and come up with a possible PR.
