### ISSUE TITLE
K8s version hardcoded? (... or I am wrong)

### ISSUE THREAD

**Issue by ivanilves** [kubernetes-incubator/kube-aws#1070]
Hi guys!

One question:

When I use latest (`v0.9.9`) version of `kube-aws` I always get K8s cluster of version `1.8.4`.

I also see this line of code in `kube-aws`:
https://github.com/kubernetes-incubator/kube-aws/blob/bc100a61283601fa7a82a544f6d8c8f9acf002fc/core/controlplane/config/config.go#L32

**Does this mean that with a particular version of `kube-aws` I could only use one specific version of Kubernetes?**

_Does this also mean that to upgrade Kubernetes version on cluster I always need to get new `kube-aws` ? 
... or once deployed with `kube-aws` cluster should be upgraded to new versions of K8s some other way ?_ 

Thank you!

**Comment by camilb** [comment]
Hi @ivanilves this is the default version, in case you don not override it in [cluster.yaml](https://github.com/kubernetes-incubator/kube-aws/blob/22673054e2e2de1f096980050a5f52060974929a/core/controlplane/config/templates/cluster.yaml#L953).

To upgrade the kubernetes version in a cluster, you have to change the version in [cluster.yaml](https://github.com/kubernetes-incubator/kube-aws/blob/22673054e2e2de1f096980050a5f52060974929a/core/controlplane/config/templates/cluster.yaml#L953),  then render and update the stack using `kube-aws render stack` and `kube-aws update --s3-uri s3://bucket_name` 

If you intent to use previous versions of kubernetes it's better to also use previous versions of `kube-aws`. Sometimes it may work, but it's possible to have changes that are not backward compatible. `kube-aws v0.9.9` works fine with kubernetes v1.8.0 and up.

**Comment by ivanilves** [comment]
Thanks @camilb ! The thing is that I am trying to install Kubernetes `1.8.5` changing the version accordingly in the `cluster.yaml` and still gettings cluster with `1.8.4`... Maybe some my fault, I need to recheck. :thinking:

**Comment by ivanilves** [comment]
@camilb you were right! 

It works! The error was my own misconfiguration (I was loading wrong `cluster.yaml`) Thanks again! Closing the issue!

:tada:

**Comment by drywheat** [comment]
I'm curious, what limitations exist (if any) regarding an upgrade to a more recent version of K8s using `kube-aws`? Stated differently, can I use to `v0.9.9` to upgrade to the latest version of K8s v1.8 (latest tag is **v1.8.7_coreos.0**)? How about K8s v1.9?

**Comment by camilb** [comment]
@drywheat support for Kubernetes 1.9 was added in #1074 here: https://github.com/kubernetes-incubator/kube-aws/pull/1074/files#diff-ef25536c536667a40b993d4d24ab7567R1915, which is not included in v0.9.9. It's a small change, as mentioned in #1076

**Comment by whereisaaron** [comment]
@drywheat I've been using 1.8.7 a lot with kube-aws 0.9.9 without problem. Generally Is expect 1.8.x to work with 0.9.9, since they won't make major API version or component changes.
