### ISSUE TITLE
v0.9.9 tls bootstrap prevents nodepool startup success due to auth issues

### ISSUE THREAD

**Issue by jcrugzz** [kubernetes-incubator/kube-aws#1071]
I can provide full config if needed of what I used to create the cluster but in essence I was creating a HA cluster in 2 availability zones in us-west-1. 5 etcd nodes, 2 controller nodes (in 2 public managed subnets), 2 nodepools (in 2 private managed subnets). Workers failed with this in the logs

```
829 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:422: Failed to list *v1.Node: nodes is forbidden: User "system:node:ip-xxxxxxxxxxx.us-west-1.compute.internal" cannot list nodes at the cluster scope
```
It was failing to list any resource from the API (Pods or Nodes) or create any resource via the API (trying to register itself i believe). 

When i created the cluster without using tls bootstrap, it created it without any issue.

**Comment by kevtaylor** [comment]
I had similar issues due to changes in the system:nodes group and the preferred route is to set Node authorizer. I set it in cluster.yaml using 
nodeAuthorizer:
    enabled: true
which enables that flag

**Comment by mumoshu** [comment]
I had missed where I left a note about this but yes - `nodeAuthorizer` seems to be required now for TLS bootstrapping to actually work.

@danielfm Any thoughts on this? Would it be a good idea to bring back the support for TLS bootstrapping without Node Authorizer?

**Comment by kevtaylor** [comment]
It was related to the note regarding system:node in here https://kubernetes.io/docs/admin/authorization/rbac/

Also, I commented in the slack channel: When I did a roll (using the RC3 version kube-aws to k8s 1.8.2) the clusterrolebinding didn't get altered - it was only when I did a clean install that I saw that it had been removed

As we use home-baked certs, the O:system:nodes group no longer works directly with the RBAC approach

Switching on the node authorizer sorted this issue

**Comment by danielfm** [comment]
@mumoshu I don't think so; actually, I think the correct move would be to turn these on by default. I can send a PR for this if you and the other maintainers think it's the right thing to do.

**Comment by wolstena** [comment]
We have come across similar problem using kube-aws version v0.10.0 with cert rotation and node authorization. kubectl get nodes only shows the master node. We were seeing errors like:

`Jul 04 02:05:29 ip-10-52-14-7.acc1.central1.cc kubelet-wrapper[1491]: E0704 02:05:29.919930    1491 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:482: Failed to list *v1.Node: nodes is forbidden: User "system:node:ip-10-52-14-7.ca-central-1.compute.internal" cannot list nodes at the cluster scope`

We were able to resolve the issue by updating the cluster role binding to:

`apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
  name: kube-aws:node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: kube-worker
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:nodes`
