### ISSUE TITLE
Optional switch for CoreDNS with k8s 1.9

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#1075]
Placeholder based on https://github.com/kubernetes/features/issues/427. We should look to adding the same optional support for CoreDNS.

**Comment by mumoshu** [comment]
Looking forward to try this!

Btw, would there be an equivalent of kube-dns-autoscaler a.k.a [dns-horizontal-autoscaler](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns-horizontal-autoscaler) for coredns?
Can we just start with paring it with kube-dns-autoscaler?

**Comment by etiennetremel** [comment]
The dns-horizontal-autoscaler autoscale based on the number of cores and nodes then update the number of replica of a given deployment name. It works with both kube-dns and coredns.

More info: https://github.com/kubernetes-incubator/cluster-proportional-autoscaler/#implementation-details

**Comment by mumoshu** [comment]
Good to know! Thanks for the info
