### ISSUE TITLE
Is it possible to get two controllers node, going to three for updates

### ISSUE THREAD

**Issue by whereisaaron** [kubernetes-incubator/kube-aws#1080]
I've pondered this before and never worked it out. I think the issue is there is no option to set the desired size of autoScalingGroups (nor a surge size for rolling updates). For controllers I would prefer two always in service, so what I would like to specify is:

```
    minSize: 2
    maxSize:  3
    desiredSize: 2
    rollingUpdateMinInstancesInService: 2
```

But I can't do that, and if I specified a max of three, I get three controllers all of the time, going to two for updates:
```
    minSize: 2
    maxSize: 3
    rollingUpdateMinInstancesInService: 2
```

If I do specify a max of two, I get an error that the rolling update size is smaller than the max (i.e. no surge allowed):
```
    minSize: 2
    maxSize: 2
    rollingUpdateMinInstancesInService: 2
```

So I can't see that I can express what I'd ideally like. Could it be possible to add the desiredSize for the initial creation of autoScalingGroups with kube-aws?

**Comment by whereisaaron** [comment]
Hmm.. while I wrote this, this setting did seem to work. The three controller eventually went away, and I have two. I think desired size is getting set to be equal to the minSize now, which works.

```
    minSize: 2
    maxSize: 3
    rollingUpdateMinInstancesInService: 2
```

**Comment by mumoshu** [comment]
@whereisaaron Hi, thanks as always for the feedback!

As far as I have tested before, your second example should work - if you had not modified the desired capacity after the initial creation of the ASG, the min size should be taken as the desired capacity.

**Comment by mumoshu** [comment]
Oh, that was close! Thanks for the confirmation 👍

**Comment by whereisaaron** [comment]
Yes I think it did work @mumoshu, I just wasn't patient enough for the stack update clean up to complete.
