### ISSUE TITLE
Can you (now) modify targetCapacity without replacing the whole spot fleet?

### ISSUE THREAD

**Issue by whereisaaron** [kubernetes-incubator/kube-aws#1081]
The [manual](https://kubernetes-incubator.github.io/kube-aws/getting-started/step-5-add-node-pool.html) says what I also believed:
> Running kube-aws update to increase or decrease targetCapacity of a spot fleet results in a complete replacement of the Spot Fleet hence some downtime. This is due to how CloudFormation works for updating a Spot Fleet

However, I just changes the `targetCacpacity` of a spotFleet down using kube-aws 0.9.9 and CF simply adjusted the spot request and terminated one worker instance, without replacing the whole node pool / spot fleet.

Note that I did not change the `launchSpecifications` at all. When I change that, then the whole node pool does get remade.

![image](https://user-images.githubusercontent.com/1109585/34092461-8697d04e-e391-11e7-924b-386c54dc0e79.png)

**Comment by mumoshu** [comment]
@whereisaaron Hi again!

SpotFleet w/ CFN does support no-interruption updates to TargetCapacity of a SpotFleet after the [June 6, 2017 release of CFN](http://docs.amazonaws.cn/en_us/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html).

We should fix the doc to reflect it.
