### ISSUE TITLE
CloudFormation service role support

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#1082]
I was greatly surprised that no one including me encountered or reported this but kube-aws as of today doesn't support passing an IAM service role to be assumed/used by CloudFormation.

The IAM user running `kube-aws up`, `update`, `destroy` must have respective IAM permissions or otherwise the stack creation/update/destroy fails due to errors like the below:

Create:

![image](https://user-images.githubusercontent.com/22009/34119343-217cc988-e465-11e7-819e-0cc25a40b08a.png)

Update:

![image](https://user-images.githubusercontent.com/22009/34118982-efb21f08-e463-11e7-917b-c16cb76b92dd.png)

Delete:

![image](https://user-images.githubusercontent.com/22009/34118959-d6ee0d06-e463-11e7-969b-c58fd030aad8.png)

You could easily reproduce this issue e.g. with having an IAM policy like:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*",
            "Condition": {
                "IpAddress": {
                    "aws:SourceIp": [
                        "IP_ADDRESS_WHICH_DOESNT_MATCH_YOURS",
                    ]
                }
            }
        },
```

Even when your own IAM user doesn't have a enough permissions, you should be able to pass a service role assumed by CloudFormation on your behalf so that it can temporarily have a greater permissions than yours to operate on the AWS resources.

This is not about managing IAM roles w/ CloudFormation/kube-aws but rather how an existing IAM role w/ greater permissions than yours could be passed to CloudFormation for use in stack creation/update/destroy.

The fix would be adding `cloudformation.roleARN` to cluster.yaml which is then used when calling stack creation/update/destroy actions via the AWS CFN API.

See http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-iam-servicerole.html for more information about the CFN service role in general.

See http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStack.html#RoleARN for the description of the RoleARN parameter of the CreateStack API.

**Comment by redbaron** [comment]
IAM Role is also helpful when users IAM credentials are time constrained, like for ADFS integrations.  Without CF IAM Role, CF performs all actions passing user credentials around their internal stack. Once credentials expired, not further actions are possible (no instances can be stared, signals received, CF events created etc). 

Switching to CF IAM Role make it use that role, not user credentials, so even after user credentials expire, CF can continue and have chance to finish cluster roll

**Comment by mumoshu** [comment]
Good point! Thanks @redbaron
