### ISSUE TITLE
kube-resources-autosave fails in us-east-2 region with 0.9.9 due to V4 auth

### ISSUE THREAD

**Issue by whereisaaron** [kubernetes-incubator/kube-aws#1084]
The `quay.io/coreos/awscli:master` image used in `kube-resources-autosave` that is deployed with `kubeResourcesAutosave.enabled = true` fails for me in us-east-2 with the authentication errors in the `kube-resources-autosave-pusher` container logs 'You are attempting to operate on a bucket in a region that requires Signature Version 4.'

Is that an outdated image or an indication of another problem?

`
move failed: kube-resources-autosave/complete/2017-12-18_19-56-21/namespaces.json to s3://my-cluster/kube-aws/clusters/my-cluster/backup/2017-12-18_19-56-21/namespaces.json An error occurred (InvalidRequest) when calling the PutObject operation: You are attempting to operate on a bucket in a region that requires Signature Version 4.  You can fix this issue by explicitly providing the correct region location using the --region argument, the AWS_DEFAULT_REGION environment variable, or the region variable in the AWS CLI configuration file.  You can get the bucket's location by running "aws s3api get-bucket-location --bucket BUCKET".
`

The aws-cli version in the pusher container is 1.11.15 which is about a year old, but after v4 I thought? So is the problem the version or something else?

```
/ # aws --version
aws-cli/1.11.15 Python/2.7.12 Linux/4.13.16-coreos-r2 botocore/1.4.72
```

**Comment by mumoshu** [comment]
@whereisaaron Thanks for the report!

Probably you need to run `aws configure set s3.signature_version s3v4; ` before running `aws s3` commands in the autosave-pusher as similar as we're doing on very beginning of cloud-config-*.

Btw, have you enforced Server-Side Encryption on your S3 bucket used by the autosaver?
As far as I remember, the signature v4 was required once you enforced SSE #831

**Comment by whereisaaron** [comment]
Thanks for the idea @mumoshu, I can try patching that into `userdata/cloud-config-controller`.

This is regular/default bucket, but this is the quite new us-east-2 region, so like other recent regions, I don't think it ever supported less than V4.

One fix would be for CoreOS to use the current version of awscli, which would default to V4. 
> "When using AWS SDKs that were released before May 2016, you may be required to request Signature Version 4..."

The CoreOS github project specifically [locks awscli to a really old version](https://github.com/coreos/awscli/blob/master/Dockerfile) for some reason.

```
...
            - name: kube-resources-autosave-pusher
              image: {{.AWSCliImage.RepoWithTag}}
              command: ["/bin/bash", "-c" ]
              args:
                - |
                    set -x ;
                    DUMP_DIR_COMPLETE=/kube-resources-autosave/complete ;
                    aws configure set s3.signature_version s3v4 ;
                     while true; do
                      for FILE in ${DUMP_DIR_COMPLETE}/* ; do
                        aws s3 mv ${FILE} s3://{{ .KubeResourcesAutosave.S3Path }}/$(basename ${FILE}) --recursive && rm -r -f ${FILE} && touch /probe-token ;
                      done ;
                      sleep 1m ;
                    done
...
```

**Comment by whereisaaron** [comment]
This patch did fix 'kube-resources-autosave' @mumoshu , e.g. it is working now in us-east-2

```
index c0757ca..2cc6cd0 100644
--- a/userdata/cloud-config-controller
+++ b/userdata/cloud-config-controller
@@ -1233,6 +1233,7 @@ write_files:
                 - |
                     set -x ;
                     DUMP_DIR_COMPLETE=/kube-resources-autosave/complete ;
+                    aws configure set s3.signature_version s3v4 ;
                     while true; do
                       for FILE in ${DUMP_DIR_COMPLETE}/* ; do
                         aws s3 mv ${FILE} s3://{{ .KubeResourcesAutosave.S3Path }}/$(basename ${FILE}) --recursive && rm -r -f ${FILE} && touch /probe-token ;
```

**Comment by whereisaaron** [comment]
Added PR #1090 to apply this patch
