### ISSUE TITLE
Create a volume or a partition for swap

### ISSUE THREAD

**Issue by Huron** [kubernetes-incubator/kube-aws#1088]
The directive volumeMounts requires the path option for volumes and does not allow to add a volume without mounting to the mount point and create and turn on the swap volume.

I think that it would be useful feature to have a possibility to add a disk without mounting for future using by custom mount or service units.

**Comment by redbaron** [comment]
kubelet refuses to start if SWAP is enabled by default. Generally one really need to know what they are doing and those people can amend cloudformation in the way that swap is enabled

**Comment by mumoshu** [comment]
@redbaron Thanks for the info!

@Huron For more context, please see https://github.com/kubernetes/kubernetes/issues/53533.

Are you still wanting to enable swap?
