### ISSUE TITLE
How does the autoscaler work with spot instances and cluster.yaml?

### ISSUE THREAD

**Issue by whereisaaron** [kubernetes-incubator/kube-aws#1093]
The [manual page for the cluster autoscaler](https://kubernetes-incubator.github.io/kube-aws/getting-started/step-6-configure-add-ons.html) omits to discuss spot instances.

The `cluster.yaml` comments says that if I omit `worker.nodePools.spotFleet.targetCapacity` or set it to zero then the autoscaler will take control of the spot node pool (as well as, I guessed `work.nodePools.autoscaling.clusterAutoscaler.enabled`). However those don't seem sufficient, even with a whole 'spotFleet' specification in place, I found I also needed to set `worker.nodePools.spotPrice` to trigger autoscaling, as well as.

Once it is working, instead of creating a spot fleet and scaling the target size, it instead creates an ASG of spot instances. (This was probably because you didn't used to be able to [scale spot fleet targets without recreating the fleet](https://github.com/kubernetes/autoscaler/issues/519). You can do this now though.)

Also it seems like the ASG of spot instances is only of one instance type, and the `spotFleet` selection of instance types and weightings is ignored? To get instance diversity and guard against a sudden rush on one instance type, you should create multiple autoscaled spot pools of different instance types?

Even if the rest of `spotFleet` is ignore, I and guessing that `spotFleet.iamFleetRoleArn` is still used/required to ensure the spot fleet ASGs can be created?

It seems like when the cluster autoscaler is enabled for spot instances, even if `worker.nodePools.autoScalingGroup.min` is set to zero you still get one instance minimum. ~~I can see the autoscaler wants to scale down, but doesn't think it can scales to zero, even though the ASG has that as the minimum.~~ Whereas in non-spot instance autoscaler ASG, you can set and get zero instances as the starting point. Eventually the spot instance ASG will scale down to zero.

When you have multiple autoscaler controlled node pools, some on-demand and spot, how does the autoscaler decide which to scale up first? Or is it random right now, until the autoscaler has a [price model](https://github.com/kubernetes/autoscaler/pull/486)?

Have I got the above correct? If so, we can inject the info into the documentation.

**Comment by jasonk000** [comment]
Were you able to confirm this?

**Comment by whereisaaron** [comment]
@jasonk000 the confusing bit is that autoscaling spot instance pools don't use spot fleets or any of the `spotFleet` settings. The cluster autoscaler only currently works with ASG of spot instances of a single instance type. The ability to scale the target capacity of a spot fleet is relatively new and the cluster autoscaler doesn't have support.

To have an autoscaling spot instance node pool, you have to:
1. Set `worker.nodePools.spotPrice` to some value suitable for `worker.nodePools.instanceType`
2. Set `worker.nodePools.autoscaling.clusterAutoscaler.enabled` to `true`
3. Omit `worker.nodePools.spotFleet.targetCapacity` or set to 0 (ie. do not create a `spotFleet`)

After that all of the `spotFleet` prices and launch configurations are ignored, and the autoscaler will create an ASG with the instances spot instances, based on the normal `worker.nodePools` settings and ignoring everything under `spotFleet`.

I still don't know for sure if the `spotFleet.iamFleetRoleArn` is required or not for autoscaling ASGs of spot instances. I am guessing not.

I have now seen autoscaling spot instance node pools scale to zero. I think before I was testing changes too fast and a cool-down period was preventing the ASG scaling down to zero.

**Comment by ifzal-capgemini** [comment]
Is spot fleet supported?

**Comment by whereisaaron** [comment]
@ifzal-capgemini you have have spot fleet node pools, with customer launch specifications and targets, but you can combine that with the autoscaler, because the autoscaler currently supports only Auto-scaling Groups (ASG's).

Node pools can be one of:
1. On-demand ASG node pool with or without autoscaler
2. Spot-price ASG node pool for a fixed instance type, with or without autoscaler
3. Spot-fleet node pool with diverse instance types, without autoscaler

So the only combination you can't have is a spot fleet with an autoscaler, because the autoscaler currently supports only Auto-scaling Groups (ASG's).

**Comment by ifzal-capgemini** [comment]
@whereisaaron Thanks.

**Comment by DominicGunn** [comment]
Has there been any progress on this? Did you ever figure out a way to solve it @whereisaaron?

**Comment by whereisaaron** [comment]
No @DominicGunn no solution. Also in testing we find that spot fleets are *much* more stable that spot price ASGs. The same type nodes are frequently terminated in spot-fleet ASGs but at the same time almost permanent in spot fleets. So using a spot fleet and scaling that externally is significantly better than using the k8s autoscaler. This is especially an issue on AWS where instances launch so slowly.
