### ISSUE TITLE
TLSBootstrap set to false requires credentials/worker-ca.pem

### ISSUE THREAD

**Issue by mad01** [kubernetes-incubator/kube-aws#1115]
when exporting the stack with `kube-aws up --export` in 0.9.9 we started to the this error that `credentials/worker-ca.pem` needs to exist but in our cluster.yaml spec we don't have TLSBootstrap set to true. it's default which should be false. even if we set it to false in the cluster.yaml spec it's still complains about missing `credentials/worker-ca.pem`

doing the same thing in 0.9.8 works just fine. 

```
Success! Stack rendered to ./stack-templates.

Next steps:
1. (Optional) Validate your changes to cluster.yaml with "kube-aws validate"
2. (Optional) Further customize the cluster by modifying templates in ./stack-templates or cloud-configs in ./userdata.
3. Start the cluster with "kube-aws up".
Error: Failed to initialize cluster driver: failed to read/create encrypted assets: Error reading credential file credentials/worker-ca.pem: credentials/worker-ca.pem must exist. Please confirm that you have not deleted the file manually
```

**Comment by mad01** [comment]
my guess is that #885 is the issue i see

**Comment by whereisaaron** [comment]
Looks like a good catch @mad01 👍
