### ISSUE TITLE
What are the viable upgrade paths for a kube-aws 0.9.9 k8s 1.8 cluster to k8s 1.9

### ISSUE THREAD

**Issue by whereisaaron** [kubernetes-incubator/kube-aws#1120]
For existing 0.9.9 k8s 1.8.x clusters, what are the viable upgrade paths to 1.9.x?

First backup everything in sight, and then:
1. Upgrade `kube-aws` to 0.9.10, review/render/validate `cluster.yaml`, run `kube-aws update`
2. Stick with `kube-aws` 0.9.9 but bump the hypercube version to 1.9 and update the various container image versions, render/validate, and then run `kube-aws update`
3. Create a new 1.9.x cluster with `kube-aws` 0.9.10, migrate the workload, destroy 1.8.x cluster

**Comment by c-knowles** [comment]
I’ve upgraded 1.8 to 1.9 using the kube-aws update command but had to delete all the secrets generated from service accounts and then cycle all the kube-system pods, after that it’s working. Side note, at least for me there’s an existing latest coreos issue that the Docker version won’t always terminate containers properly but that was present since roughly 1.8 timescales.

**Comment by whereisaaron** [comment]
The @c-knowles, @camilb reports a [similar experience](https://github.com/kubernetes-incubator/kube-aws/issues/1112#issuecomment-361311560), sometimes having to recreate secrets and restart `kube-system` pods (wonder why, if the certificates have not changed?). But that otherwise upgrades can work.

So probably better to stick with the same `kube-aws` version (in case of breaking changes to the CF stack template), but upgrade the component versions and hope for the best 😄

**Comment by whereisaaron** [comment]
k8s 1.10.0 is released to stable but the last stable `kube-aws` release is still at 1.8.x. I guess all the keen people operate off the master branch, bleeding edge, so as to get current versions of k8s. But will new users pick up `kube-aws` if releases lag significantly behind k8s versions?

@c-knowles regards that container termination issue, CoreOS 1688.x.y has docker 17.12.1 which is supposed to fix he bug with not catching container exits.

**Comment by c-knowles** [comment]
@whereisaaron cool, thanks! I'll give it another go shortly. Ref for that issue - https://github.com/kubernetes-incubator/kube-aws/issues/1135.
