### ISSUE TITLE
Is it possible to replace certificate manually on all servers? How important is it of .enc file?

### ISSUE THREAD

**Issue by hpham04** [kubernetes-incubator/kube-aws#1126]
The Kubernetes cluster in my company was suddenly down.
I tried to investigate, and look like it come from CA problem. I connected to my cluster, and saw that there are 2 kinds of certificate .pem & .pem.enc like below:

ls
admin-key.pem          ca-key.pem               etcd-key.pem
admin-key.pem.enc      ca-key.pem.enc           etcd-key.pem.enc
admin.pem              ca.pem                   etcd.pem
admin.pem.enc          ca.pem.enc               etcd.pem.enc
apiserver-key.pem      etcd-client-key.pem      worker-key.pem
apiserver-key.pem.enc  etcd-client-key.pem.enc  worker-key.pem.enc
apiserver.pem          etcd-client.pem          worker.pem
apiserver.pem.enc      etcd-client.pem.enc      worker.pem.enc

Using openssl helps me to generate .pem file, but I don't know how to generate .pem.enc file
So I wonder if it's possible to replace .pem file manually without touching .pem.enc file
It looks to me that .pem.enc was generated by kube-aws, not Kubernetes so .pem.enc is not being use in Kubernetes cluster
Can anyone please help to advise
Thank you so much

**Comment by mumoshu** [comment]
@hpham04 Hi, sorry for the trouble, and thanks for using kube-aws.

*.pem.enc is recreated on `kube-aws validate/update/up` whenever it is removed or changed.
Would you mind trying?
Also, I'd suggest take a backup of the whole credentials or even the project files including cluster.yaml, stack templates, etc. before doing it!

**Comment by hpham04** [comment]
@mumoshu thank you for your reply, I definitely try it tomorrow. Can you please advise if it’s fine if I replace all the .pem file with the new ones
As far as I understand, these files are not being in used in production environment, it would be used when we execute kube-aws only, is it true?

**Comment by mumoshu** [comment]
@hpham04 If I'm following you correctly, no. Non-key pem files are deployed to nodes as-is. kube-aws encrypts `*-key.pem` files like for example `apiserver-key.pem` to `apiserver-key.pem.enc` and uploads both `apiserver-key.pem.enc` and `apiserver.pem`.

**Comment by mumoshu** [comment]
> if it’s fine if I replace all the .pem file with the new ones

If you're talking about replacing pem files including private keys, no!
There's some gotchas on replacing private keys, like recreating serviceaccounts and the pods consuming the serviceaccounts. Please also see #1057 for more info on this topic.

Replacing certificates only would be fine.

General guidance on certification rotation I found useful: https://security.stackexchange.com/questions/55737/ssl-cert-minimize-downtime-key-rotation-strategy

Oh, but I'm not really sure replacing CA cert would be ok.
Honestly, I have never tried that myself. Hope anyone could report me if one successfully rotated CA cert(But this doesn't sound like your case according to your description :) )

**Comment by cmcconnell1** [comment]
Hello this just happened to us again and decided to script a fix to distribute your updated tls x509 etcd2 certs.  The cluster was broken with the etcd x509 cert errors, as it was exactly one year and one day past the deployment.  Our previous attempts at updating the certs following the kube-aws readme didn't work (as noted in https://github.com/kubernetes-incubator/kube-aws/issues/1132)
After running my script in the below gist, the cluster was again functional.  @mumoshu if you could take a peek at this gist to make sure it isn't doing anything that might cause problems down the road, it would be helpful.

Please see:  [dist-upated-tls-certs-etcd-nodes.sh](https://gist.github.com/cmcconnell1/54ae82a71c5a73c9f9bcbaf1edf861d1)

before running script
```
aergo-stage $ for kube_type in etcd ; do /Users/cmcc/GIT/td-kube-aws/scripts/remote-ssh-kube-commands.sh -n aergo-stage -t $kube_type -c "etcdctl cluster-health" ; done
=======================
PRIV IP: 10.1.13.4
Warning: Permanently added '10.1.13.4' (ECDSA) to the list of known hosts.
cluster may be unhealthy: failed to list members
Error:  client: etcd cluster is unavailable or misconfigured
error #0: x509: certificate has expired or is not yet valid
=======================
PRIV IP: 10.1.12.5
Warning: Permanently added '10.1.12.5' (ECDSA) to the list of known hosts.
cluster may be unhealthy: failed to list members
Error:  client: etcd cluster is unavailable or misconfigured
error #0: x509: certificate has expired or is not yet valid
=======================
PRIV IP: 10.1.12.4
Warning: Permanently added '10.1.12.4' (ECDSA) to the list of known hosts.
cluster may be unhealthy: failed to list members
Error:  client: etcd cluster is unavailable or misconfigured
error #0: x509: certificate has expired or is not yet valid
```

after running script
```
for kube_type in etcd ; do /Users/cmcc/GIT/td-kube-aws/scripts/remote-ssh-kube-commands.sh -n aergo-stage -t $kube_type -c "etcdctl cluster-health" ; done

=======================
PRIV IP: 10.1.13.4
Warning: Permanently added '10.1.13.4' (ECDSA) to the list of known hosts.
member a2c5acd8f40430b is healthy: got healthy result from https://ip-10-1-13-4.us-west-1.compute.internal:2379
member 6ca164c03127668e is healthy: got healthy result from https://ip-10-1-12-5.us-west-1.compute.internal:2379
member e03e79bdf36a191e is healthy: got healthy result from https://ip-10-1-12-4.us-west-1.compute.internal:2379
cluster is healthy


=======================
PRIV IP: 10.1.12.5
Warning: Permanently added '10.1.12.5' (ECDSA) to the list of known hosts.
member a2c5acd8f40430b is healthy: got healthy result from https://ip-10-1-13-4.us-west-1.compute.internal:2379
member 6ca164c03127668e is healthy: got healthy result from https://ip-10-1-12-5.us-west-1.compute.internal:2379
member e03e79bdf36a191e is healthy: got healthy result from https://ip-10-1-12-4.us-west-1.compute.internal:2379
cluster is healthy


=======================
PRIV IP: 10.1.12.4
Warning: Permanently added '10.1.12.4' (ECDSA) to the list of known hosts.
member a2c5acd8f40430b is healthy: got healthy result from https://ip-10-1-13-4.us-west-1.compute.internal:2379
member 6ca164c03127668e is healthy: got healthy result from https://ip-10-1-12-5.us-west-1.compute.internal:2379
member e03e79bdf36a191e is healthy: got healthy result from https://ip-10-1-12-4.us-west-1.compute.internal:2379
cluster is healthy

```
Thanks!
