### ISSUE TITLE
Curls in cloud config that are silenced and do not log errors

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#1130]
Extracted from https://github.com/kubernetes-incubator/kube-aws/pull/1127#discussion_r167129037.

Across our `core/controlplane/config/templates/cloud-config-*` files we have many curl commands running that are silenced and do not log any potential errors. We'd like to add `-S` or `--show-error` to as many as we can.

**Comment by kiich** [comment]
Also standardising on short flag throughout would be great!
Will take a look for a possible PR.
