### ISSUE TITLE
Issue with etcd  cluster

### ISSUE THREAD

**Issue by NBCRB** [kubernetes-incubator/kube-aws#1132]
We have 1.5 cluster running since last year. Today when i was trying to deploy new pods their status showing "Creating container". When checked further i found below errors: 

 "using network plugins \"cni\": client: etcd cluster is unavailable or misconfigured; error #0: x509: certificate has expired or is not yet valid\n; error #1: x509: certificate has expired or is not yet valid\n; error #2: x509: certificate has expired or is not yet valid\n; Skipping pod"

Looking at the above errors it seems there is an issue with etcd cluster. 

We have 3 node etcd cluster and all the nodes showing similar errors when checking individually  by running "etcdctl member list".

"etcdctl member list
Error:  x509: certificate has expired or is not yet valid
"

As far I remember we haven't updated any certificates anywhere on the cluster. 

Any help on providing some insight on the issue would be really  appreciated.

Thanks

**Comment by redbaron** [comment]
keep same key file, but regenerate cert files with new expire period, then redeploy them to nodes

**Comment by sivaprakash123** [comment]
How do we implement it via kube-aws ? Updating in cluster.yml will recreate all the controller, etcd and workers. So go to each server and update certificates ?

**Comment by mumoshu** [comment]
Merging a new duplicated issue #1191 to this.

Also see my [comment](https://github.com/kubernetes-incubator/kube-aws/issues/1191#issuecomment-374121921) for suggestions.

**Comment by cmcconnell1** [comment]
Hello All, 
FWIW, we also had older 1.5 (kube-aws ver: v0.9.3-rc.5) clusters deployed via kube-aws.
Unfortunately we were not able to update the certs via the documented process in kube-aws (regenerate certs then kube-aws update AIR?--of course would need to go back to the old tagged versions README for exact steps)
[v0.9.3-rc.5 kube-aws-cluster-updates.md#certificate-rotation](https://github.com/kubernetes-incubator/kube-aws/blob/v0.9.3-rc.5/Documentation/kube-aws-cluster-updates.md#certificate-rotation)

What I saw when trying to update two (2) separate clusters of same versions:

One cluster failed update with only the workers and controllers getting updated and redeployed, but its etcd nodes did not and was left in a hot mess and totally broken.  
The second cluster did not complain or throw errors, but apparently didn't update the certs, then when a year came it just dropped off the map--running remote ssh commands on etcd cluster nodes we can validate:

```
etcdctl cluster-health
cluster may be unhealthy: failed to list members
Error:  client: etcd cluster is unavailable or misconfigured
error #0: x509: certificate has expired or is not yet valid

```
both clusters were the same ancient versions
```
cat ./foo-stage-deployment-stats
##### Kube Cluster Provision Details #####
KUBE-CLUSTER-NAME: foo-stage
DATE: 2017-04-25-18:16:44-PDT
KUBE-AWS-VERSION: v0.9.3-rc.5
AMI-ID: ami-b31d43d3
```

If time permits would like to follow the helpful info on this issue, but we need to redeploy these ancient clusters anyway: 
[Rotate/update TLS cert key issue #1057](https://github.com/kubernetes-incubator/kube-aws/issues/1057)

Hope this information is useful

**Comment by cmcconnell1** [comment]
Hello since this just happened to us again decided to script a fix to distribute your updated tls x509 etdc certs JIC it happens again and to hopefully help others out.  Note you should backup your outdated certs on the dest etcd2 nodes before running if you wish to keep them as this script will overwrite them.  

Please see:  [dist-upated-tls-certs-etcd-nodes.sh](https://gist.github.com/cmcconnell1/54ae82a71c5a73c9f9bcbaf1edf861d1)
