### ISSUE TITLE
Using APIServerFlags?

### ISSUE THREAD

**Issue by kylegoch** [kubernetes-incubator/kube-aws#1136]
I saw this:
https://github.com/kubernetes-incubator/kube-aws/blob/226827e26fc76df62ab94333dc3b1b7bbeb769cd/core/controlplane/config/templates/cloud-config-controller#L2088

And was wondering where exactly I could set these extra APIServer Flags. The documentation doesnt make mention of them at all, so I wasnt sure.

Thanks!

**Comment by whereisaaron** [comment]
Me too @kylegoch, I want to add these flag so API extensions work, and that setting work. I couldn't find any mapping from `cluster.yaml` to `APIServerFlags` in the code or documentation.

```
    - --requestheader-client-ca-file=/etc/kubernetes/ssl/ca.pem
    - --requestheader-allowed-names=
    - "--requestheader-extra-headers-prefix=X-Remote-Extra-"
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-username-headers=X-Remote-User
```

**Comment by ktateish** [comment]
I found the way to use .APIServerFlags.  You can use it with kube-aws plugins.
A test code `test/integration/plugin_test.go` in the kube-aws repo will help you to understand how to use it.

1. Create aggregator plugin directory
Place `plugins` directory under the directory that have cluster.yaml.  Then create the aggregator plugin directory
```
$ mkdir plugins
$ mkdir aggregator
```
2. Create `plugin.yaml`
```
$ cat > plugins/aggregator/plugin.yaml
metadata:
  name: aggregator
  version: 0.0.1
spec:
  values:
  configuration:
    cloudformation:
      stacks:
        controlPlane:
          resources:
            append:
              inline: "{}"
        nodePool:
          resources:
            append:
              inline: "{}"
        root:
          resources:
            append:
              inline: "{}"
    kubernetes:
      apiserver:
        flags:
        - name: "requestheader-client-ca-file"
          value: "/etc/kubernetes/ssl/ca.pem"
        - name: "requestheader-allowed-names"
          value: ""
        - name: "requestheader-extra-headers-prefix"
          value: "X-Remote-Extra-"
        - name: "requestheader-group-headers"
          value: "X-Remote-Group"
        - name: "requestheader-username-headers"
          value: "X-Remote-User"
        - name: "proxy-client-cert-file"
          value: "/etc/kubernetes/ssl/proxy-client.pem"
        - name: "proxy-client-key-file"
          value: "/etc/kubernetes/ssl/proxy-client-key.pem"
    node:
      roles:
        controller:
          storage:
            files:
            - path: /etc/kubernetes/ssl/proxy-client.pem
              permissions: 0644
              contents:
                source:
                  path: assets/proxy-client.pem
            - path: /etc/kubernetes/ssl/proxy-client-key.pem
              permissions: 0600
              contents:
                source:
                  path: assets/proxy-client-key.pem
```
3. Place assets (certs for proxy-client)
```
$ mkdir plugins/aggregator/assets
$ cp /path/to/proxy-client.pem  /path/to/proxy-client-key.pem plugins/aggregator/assets
```
4. Enable the plugin in cluster.yaml
```
# Add following lines to your cluster.yaml
kubeAwsPlugins:
  aggregator:
    enabled: true
```
5. `render stack`, `validate` and `update`
(I'm not sure `render stack` is needed)

**Comment by whereisaaron** [comment]
Nice @ktateish! That looks a lot nicer than patching the generated stack like I am doing!

@ktateish are you using `kube-aws` 0.9.9 or master build?

@mumoshu this looks good, has @ktateish used plugins as intended? Anything we might have missed?

**Comment by ktateish** [comment]
I'm using 0.9.9.
 (+following patch to fix #1171).
```
--- a/core/nodepool/cluster/cluster.go
+++ b/core/nodepool/cluster/cluster.go
@@ -200,7 +201,6 @@ func (c *ClusterRef) validateWorkerRootVolume(ec2Svc ec2CreateVolumeService) err
 	workerRootVolume := &ec2.CreateVolumeInput{
 		DryRun:           aws.Bool(true),
 		AvailabilityZone: aws.String(c.Subnets[0].AvailabilityZone),
-		Iops:             aws.Int64(int64(c.RootVolume.IOPS)),
 		Size:             aws.Int64(int64(c.RootVolume.Size)),
 		VolumeType:       aws.String(c.RootVolume.Type),
 	}
```

**Comment by ArchiFleKs** [comment]
Could we generate a ca in addation to the ca.pem for everything that need to use API aggregator, as per : https://github.com/kubernetes-incubator/metrics-server/issues/22 ? 

I'm not sure it is related but i'm trying to use the AWS service catalog and catalog api server also needs  the `--requestheader-client-ca-file=/etc/kubernetes/ssl/ca.pem` which is supposed to be a different ca that the default cluster CA.

**Comment by mumoshu** [comment]
> @mumoshu this looks good, has @ktateish used plugins as intended? Anything we might have missed?

Definitely yes! I believe I have not documented about the feature at all. Wondering and impressed to see @ktateish managed to use it 👍 

FYI:

> render stack, validate and update
(I'm not sure render stack is needed)

`render stack` isn't needed. You can already see`.Plugins` references across cloud-configs which consumes plugins on `kube-aws validate/update/up`.
