### ISSUE TITLE
Unique identifier for worker/controller nodes

### ISSUE THREAD

**Issue by sonnysideup** [kubernetes-incubator/kube-aws#1137]
Right now, all of the workers/controllers created by `kube-aws` receive the EC2 Name tag **\<cluster-name\>-\<nodepool\>-(worker|controller)**. I'm wondering if it's possible to assign them unique names instead, or using a separate tag.

### Use case

I'm trying to leverage Datadog to monitor all of the EC2 instances in my K8s clusters. Etcd nodes have a numeric suffixes which makes them easy to identify, but workers and controllers do not. The best unique identifier I can find is **host** (e.g. host:i-0f8ee52badf787725). This makes it a little difficult to correlate metrics with nodes that are named something like **ip-X-X.X.X.ec2.internal**.

**Comment by redbaron** [comment]
Feel free to pass `--hostname-override` to kubelet with  whatever value you seem feet. you can make this edit in cloudformation template

**Comment by mumoshu** [comment]
@drywheat Hi! Sounds like what you need is achievable with the redbaron's suggestion.
Do you still need unique values for the Name tags for another use-cases?

**Comment by drywheat** [comment]
Well, unless `--hostname-override` can be templated with something like `<cluster>-<nodepool>-worker-${index}` I'm not sure it's exactly what I need.

Basically, I want to build graphs in DD that will overlay metrics from multiple nodes and have some type of unique identifier that I can then use for deeper investigation.

**Comment by redbaron** [comment]
You can have cluster and nodepool name as part of kube-aws template (golang template) and use instance metadata to get unique id. It will not be an `${index}` as instances in AutoScalingGroup are not ordered
