### ISSUE TITLE
Slim down tests

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#1140]
The travis build often fails due to "panic: test timed out after 20m0s" in the middle of the long integration test.

I could make the timeout longer at the moment but would be better to slim the tests down.

**Comment by c-knowles** [comment]
Could we run any in parallel. Do we have any particular ties to Travis?

**Comment by mumoshu** [comment]
Not sure. Do you know if travis worker has multiple CPU cores gotest could utilize?

> Do we have any particular ties to Travis?

Probably. Anyway, I can't enable any third party CI service integration on my own. I need to get approval from GitHub for each newly integrated service, which is time-consuming and a bit annoying..
