### ISSUE TITLE
Making stack termination protection configurable

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#1152]
Extracted from https://github.com/kubernetes-incubator/kube-aws/issues/249#issuecomment-352236669

Anyone interested in contributing?

cc @whereisaaron

**Comment by luck02** [comment]
I'll give this a try as well.  Mar 27 - April 3rd 2018 (IE if I don't get back in that time I probably got distracted)

**Comment by luck02** [comment]
So after some digging, the result is:
1. Stack termination protection (as I understand the request in this ticket to be) is not something that's settable in CFN via the templates.  
1. It CAN be done via the CLI but that seems to be a pattern that would be both new and unpalatable to kube-aws.
1. There are other similiar sounding options (deletion policy) that don't do anything similiar to what we'd want here.

I don't think this is a good candidate for inclusion in kube-aws (unless I'm totally wrong about point 1 above).   As a roundabout way of offering a similiar mechanism I'd suggest adding some documentation on how to enable stack termination protection via the CLI and suggest it be considered for 'production' assets.  @mumoshu ? @whereisaaron ?  

We (unfortunately) use ansible to deploy our clusters and we could enable stack protection via Ansible, we may do that for our prod assets.
