### ISSUE TITLE
Note the existance of etcd-manager

### ISSUE THREAD

**Issue by whereisaaron** [kubernetes-incubator/kube-aws#1160]
@mumoshu this looks like a similar aim to your `etcdadm` script. Managed etcd bootstrap, backup, and recovery outside of k8s.

   https://github.com/kopeio/etcd-manager

What we have works well, and I don't know that this is useful to us, but I thought you'd be interested.

**Comment by c-knowles** [comment]
kops will supporting this in 1.9 apparently.

**Comment by mumoshu** [comment]
Thx for the info! I did read it and I believe kube-aws should eventually rely on a real app like etcd-manager for managing etcd.

However, from a practioner's perspective etcdadm is sadly better (yet). It doesn't have any of noted shortcomings of etcd-manager except the last one of
easy way to manually trigger disaster recovery process.

I wish I could get more time to contribute it or someone enhances it with knowledges gained from etcdadm!
