### ISSUE TITLE
kube-resources-autosaver fails because of bash line

### ISSUE THREAD

**Issue by kevtaylor** [kubernetes-incubator/kube-aws#1166]
It looks like part of the deployment was changed to use sh instead of bash but the section in the container kube-resources-autosave-pusher is now suffering from the same fate - this was using a k8s 1.8.4 implementation against the master code

```
/bin/bash: ((: 1520239169 -  < 25*60*60 : syntax error: operand expected (error token is "< 25*60*60 ")
```
Liveness check:
```
exec [/bin/bash -c (( $(date +%s) - $(stat -c%Y /probe-token) < 25*60*60 ))] delay=240s timeout=1s period=10s #success=1 #failure=3
```

@mumoshu If you can confirm this, I'll put in a PR to correct it. Thanks

**Comment by mumoshu** [comment]
Resolved via #1167
