### ISSUE TITLE
kube-aws / autoscaler add permissions "autoscaling:DescribeLaunchConfigurations"

### ISSUE THREAD

**Issue by luck02** [kubernetes-incubator/kube-aws#1169]
This autoscaler doc's state that to scale up from 0 instances the permission: `autoscaling:DescribeLaunchConfigurations` is required.

https://github.com/kubernetes/autoscaler/blob/5302c37d6d6e89a2eeac0c74b4afe6caadfa3340/cluster-autoscaler/cloudprovider/aws/README.md#scaling-a-node-group-to-0

How / where do we specify this in kube-aws or is that something we'd do orthogonally?

Thanks!

**Comment by mumoshu** [comment]
@luck02 Thanks for the report!

Adding the action to https://github.com/kubernetes-incubator/kube-aws/blob/9df90636b0ad3df8453cfad6b4d7f9bcedacf228/core/controlplane/config/templates/stack-template.json#L252 would do the job.

You can do it for your `./stack-templates/control-plane.json.tmpl` generated by `kube-aws render stack`, or even better submit a PR to add to the line I've noted above.

**Comment by luck02** [comment]
@mumoshu pushed a PR above.

**Comment by whereisaaron** [comment]
Thanks for identifying this @luck02!

**Comment by luck02** [comment]
So sorry, I :copy-pastad: the wrong Cloud Formation permission :(

New PR: https://github.com/kubernetes-incubator/kube-aws/pull/1181

**Comment by luck02** [comment]
@mumoshu sorry, I'm unable to re-open issue for PR: https://github.com/kubernetes-incubator/kube-aws/pull/1181  

I can open a new issue if that's better for your workflow.
