### ISSUE TITLE
Add API aggregation layer options to 'apiserver'

### ISSUE THREAD

**Issue by whereisaaron** [kubernetes-incubator/kube-aws#1180]
The new version of [`stash` backup](https://github.com/appscode/stash) uses [Kubernetes API aggregation layer](https://kubernetes.io/docs/concepts/api-extension/apiserver-aggregation/) which requires [additional `apiserver` flags](https://kubernetes.io/docs/tasks/access-kubernetes-api/configure-aggregation-layer/#enable-apiserver-flags), e.g.

```
    - --requestheader-client-ca-file=/etc/kubernetes/ssl/ca.pem
    - --requestheader-allowed-names=
    - "--requestheader-extra-headers-prefix=X-Remote-Extra-"
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-username-headers=X-Remote-User
```

This flags are available in [k8s 1.6](https://kubernetes.io/docs/concepts/api-extension/apiserver-aggregation/) and later.

It would nice to either add suitable options by default, or have an 'experimental' setting to add them.

There is an `.APIServerFlags` in the [controller template](https://github.com/kubernetes-incubator/kube-aws/blob/master/core/controlplane/config/templates/cloud-config-controller#L2111), but there ar two problems:
1. I can't see any way to set that configuration from the `cluster.yaml` to add the extra settings.
2. The way the template is coded won't work because the voption values needs to be quoted to enable values like `X-Remote-Extra-`.

```
          {{range $f := .APIServerFlags}}
          - --{{$f.Name}}={{$f.Value}}
          {{ end -}}
```

Is the `.APIServerFlags` an be used from `cluster.yaml` and we add quotes to the controller template then that would work fine for this. Or it could all be mapped to an 'experimental' setting.

**Comment by whereisaaron** [comment]
BTW the `requestheader-client-ca-file` should I think be a separate root certificate from the apiserver one, so we have to generate that. And I think we sign a cert with it for the cluster API domain names and configure that cert/key in these options:
```
--proxy-client-cert-file string
--proxy-client-key-file string
```
https://kubernetes.io/docs/reference/generated/kube-apiserver/

**Comment by jorge07** [comment]
Are you sure that `"--requestheader-extra-headers-prefix=X-Remote-Extra-"` needs to be quoted?

**Comment by jorge07** [comment]
Maybe I'm wrong, but seems you're looking for this https://github.com/kubernetes-incubator/kube-aws/issues/509

The ApiServerFlags are defined [here](https://github.com/kubernetes-incubator/kube-aws/blob/41414144fc3561381b5eca4eea4ed4d3a4179ca9/plugin/clusterextension/extras.go#L64) as part of the plugin system.

**Comment by kylegoch** [comment]
I started #1136 to solve this same issue. We need to enable Api Aggregation as well and have run into the same issue.

**Comment by whereisaaron** [comment]
Thanks @jorge07 the plugin system may be a good way to implement this additional. This k8s feature does require a CA and certificates issued though, so it might not fit into current plug-in capabilities.

@mumoshu recently implement `kiam` support (:tada:) which also required certificates and had to add code into `kube-aws` to bootstrap the certificates. And it is not clear what the plan is to rotate those certificates. I'm hoping we can leverage `cert-manager` to issue and rotate certificates in-cluster services.

**Comment by Fsero** [comment]
hey @whereisaaron how far are you to enable support for this? do you need any help?

**Comment by whereisaaron** [comment]
@Fsero I have just been patching the API server flags into the generated stack. But @ktateish has a more elegant method using `kube-aws` plugins in #1136.
