### ISSUE TITLE
Internet facing ELB and private controllers

### ISSUE THREAD

**Issue by vbogretsov** [kubernetes-incubator/kube-aws#1187]
Hello,

Sorry for maybe dummy question, but I cannot figure out from the manuals and `cluster.yml` whether it's possible to have a ELB and Controllers on separate EC2 instances so that ELB would internet-facing and controllers would in private networks. I assume ELB managed by `kube-aws`, not manually created and provided via `apiEndpoints/loadBalancer/id`.

Thank you!

**Comment by camilb** [comment]
Hi @vbogretsov you need some public subnets tagged with `KuberneetsCluster=your_cluster_name`

**Comment by vbogretsov** [comment]
Hello @camilb!
Thank You, it works!
