### ISSUE TITLE
Integration: cert-manager

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#1190]
Extracted from https://github.com/kubernetes-incubator/kube-aws/pull/1134#issuecomment-374074275.
As I've noted in the original issue, `cert-manager` alone doesn't solve tls key/cert rotation problem. AFAICS, it is more or less a cert issuer, not a rotation manager.

- This would affect to how #1147 #1146 are implemented
- This may be a solution to #1013 #1057, combined with #1146 #1147 

Hey @whereisaaron, thanks for your interest in this topic! We should track the progress towards the integration here, consolidating relevant informations including updates in cert-manager, alternative impls, etc.

**Comment by whereisaaron** [comment]
You are right that `cert-manager` is not always a complete rotation solution, however it will automatically issue certificates for new application deployments, creating the TLS Secrets. And it will renew those certificates and update those Secrets automatically

So anything that automatically reloads it Secrets will get automatic certificate rotation. Ingress controllers do this of course. Other applications like `kiam` may require a Secret watcher or sidecar that triggers the Secret to be re-read.

A strength is that it will operate any number of cluster-internal CAs. So you can easily have a CA and collection of CA-signed certificates per-application deployment, that are then automatically renewed. This fits use cases like API Aggregation Layer, `kiam`, `istio`, `mysql`, and really any application wanting secure inter-component communication with automatic certificate issue and renewal.

None of this solves rotating root CA certs of course! We'd need cross-signing support and applications that support more than one root CA to do that without an outage.

**Comment by davidmccormick** [comment]
There's definitely some potential here.  I'd like to see ingress be a part of the kube-aws build with something like this managing the certs automatically.  If we can also use it for other certs then that would be a bonus - but would only be possible for users that have access to a vault installation.

**Comment by munnerz** [comment]
@davidmccormick FWIW, cert-manager does not depend on Vault at all. It will soon support Vault as an issuing backend, but you can also use it to manage a plain old CA stored in a Kubernetes Secret resource (using the 'CA Issuer'). More info: http://cert-manager.readthedocs.io/en/latest/tutorials/ca/creating-ca-issuer.html
