### ISSUE TITLE
Expired etcd certificates

### ISSUE THREAD

**Issue by sivaprakash123** [kubernetes-incubator/kube-aws#1191]
Is there any way to update the etcd certificates in the whole cluster via kube-aws. There are no proper steps on doing it server by server. A procedure document will be helpful for all the users here.

The etcd certificates for the cluster expires in an year. 365 days is not enough to deal with certificate issues.

**Comment by mumoshu** [comment]
Hi @sivaprakash123, thx for using kube-aws!

Sorry to say, but I usually recreate my cluster to ensure I don't break anything regardless of it is just a certificate rotation or anything else. So I can't provide a concrete example here.

So, my best bet is try running openssl command whose input is `etcd-*-key.pem` and `ca*.pem`, to generate a new certs `etcd-*.pem`. I also appreciate it if you could contribute the result!

**Comment by mumoshu** [comment]
> The etcd certificates for the cluster expires in an year. 365 days is not enough to deal with certificate issues.

I do understand your pain here.
But, let me say, I REALLY don't want our users to leave their clusters with the same cert such long time.

**Comment by mumoshu** [comment]
Closing as duplicate of #1132. Let's keep discussing there!
