### ISSUE TITLE
HPA doesn't work on 1.9 with metricsServer enabled or disabled

### ISSUE THREAD

**Issue by Fsero** [kubernetes-incubator/kube-aws#1196]
It seems since 1.9 these flag is enabled by default on the controller managers

+          - --horizontal-pod-autoscaler-use-rest-clients=false

as explained in this PR https://github.com/kubernetes/kubernetes/issues/57673. However in order to make it work with the metrics server kube-aws should also enable the API agreggation layer as discussed on #1180 so the metrics.k8s.io api is registered and can be used.

If you have heapster in the cluster it won't be used, i have a working workaround that when you disable metric server it will set to false the hpa flag.

To be able to use metric-server API agreggation layer should be enabled, so until API Agreggation sup
port is merged we should not recommend people to deploy metric server.

This is what you would see in an HPA on a 1.9 cluster with metrics server enabled.
```
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  <unknown> / 80%
Min replicas:                                          2
Max replicas:                                          50
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetResourceMetric  the HPA was unable to compute the replica count: unable to get metrics for resource cpu: unable to fetch metrics from API: pods.metrics.k8s.io is forbidden: User "system:anonymous" cannot list pods.metrics.k8s.io in the namespace "default".
Events:
  Type     Reason                        Age                 From                       Message
  ----     ------                        ----                ----                       -------
  Normal   SuccessfulRescale             22m                 horizontal-pod-autoscaler  New size: 2; reason: Current number of replicas below Spec.MinReplicas
  Warning  FailedComputeMetricsReplicas  16m (x12 over 21m)  horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from API: pods.metrics.k8s.io is forbidden: User "system:anonymous" cannot list pods.metrics.k8s.io in the namespace "default".
  Warning  FailedGetResourceMetric       2m (x40 over 21m)   horizontal-pod-autoscaler  unable to get metrics for resource cpu: unable to fetch metrics from API: pods.metrics.k8s.io is forbidden: User "system:anonymous" cannot list pods.metrics.k8s.io in the namespace "default".
```

**Comment by whereisaaron** [comment]
Hi @Fsero yeah many 1.8+ services are now rely on the API aggregation layer being enabled and configured. I hit the same thing with `stash` 0.7.x which now requires the aggregation layer to even run. There is a separate issue #1180 after [enabling the API aggregation layer](#1180).

**Comment by Fsero** [comment]
since #1197 is now merged (thank you so much @mumoshu ) and there are people working already on enabling aggregation layer #1180 #1136  closing this issue
