### ISSUE TITLE
Support for volumeMounts on controllers/etcd

### ISSUE THREAD

**Issue by kiich** [kubernetes-incubator/kube-aws#1204]
This is more of a question - when I try to use `volumeMounts` in controller and etcd, sure enough I get an error:

```
Error: Failed to read cluster config: file cluster.yaml: unknown keys found in controller: volumeMounts
```
And also for etcd
```
Error: Failed to read cluster config: file cluster.yaml: unknown keys found in etcd: volumeMounts
```

I can see that there is no support for this but was wondering why - I have a use case where we need to dump journald logs (filtered) to file system and I was not so keen on catering for this extra data on root file system and thought the extra ebs will do the job for me.

Let me know if there is any other way to do something like this, thanks.

**Comment by mumoshu** [comment]
@kiich Good catch! It sounds like a good feature request.

If you're willing to submit a PR for this, I'd be happy to review!
In that case, the declaration of `systemd-modules-load.service` service seen in `core/controlplane/config/templates/cloud-config-worker` would be a good starting point.

**Comment by kiich** [comment]
Sounds good @mumoshu - I'll take a look!
