### ISSUE TITLE
Any plan to support nvidia as default runtime to support nvidia-docker?

### ISSUE THREAD

**Issue by putcn** [kubernetes-incubator/kube-aws#1207]
Hi there, 

I saw the support for nvidia gpu which is great, but is there any plan to directly support of nvidia-container-runtime as default docker runtime? so that pod yaml doesn't have to mount drivers by default.

thanks

**Comment by mumoshu** [comment]
Hi! Sounds like a good idea. I'm open to any PR related to this 👍

**Comment by putcn** [comment]
great, thanks!

**Comment by Lemmons** [comment]
#1222 addresses this, though it doesn't actually use nvidia-docker.  Instead it uses [device plugins](https://kubernetes.io/docs/concepts/cluster-administration/device-plugins/) and [NVIDIA GPU device plugin used by GKE/GCE](https://github.com/GoogleCloudPlatform/container-engine-accelerators/tree/master/cmd/nvidia_gpu), which is a bit cleaner.  The pr was just submitted, likely needs a bit of cleanup, and only supports kube 1.9+, but it's something to go off at least.

**Comment by putcn** [comment]
@Lemmons awesome! definitely will try it ou when PR is merged.

**Comment by mumoshu** [comment]
I've merged #1222. I believe it does solve the original issue in a different but a better approach.
@Lemmons @putcn Thank you so much for your suggestions and the contribution!
