### ISSUE TITLE
InvalidParameterCombination: The parameter iops is not supported for gp2 volumes.

### ISSUE THREAD

**Issue by mludvig** [kubernetes-incubator/kube-aws#1208]
I started seeing this from around Thursday last week when creating a cluster with pretty much default settings:

    $ kube-aws up --s3-uri s3://[...]/kube-aws/kube98
    Error: Error validating cluster: failed to validate node pool #0: create volume dry-run request failed: 
        InvalidParameterCombination: The parameter iops is not supported for gp2 volumes.
        status code: 400, request id: ...

Apparently `kube-aws` performs a request like this (taken from CloudTrail):

    "eventTime": "2018-03-27T05:34:17Z",
    "eventSource": "ec2.amazonaws.com",
    "eventName": "CreateVolume",
    [...]
    "errorCode": "Client.DryRunOperation",
    "errorMessage": "Request would have succeeded, but DryRun flag is set.",
    "requestParameters": {
        "size": "30",
        "zone": "ap-southeast-2a",
        "volumeType": "gp2",
        "iops": "0"
    },

The same request now fails:

    "eventTime": "2018-04-02T06:08:48Z",
    "eventSource": "ec2.amazonaws.com",
    "eventName": "CreateVolume",
    [...]
    "errorCode": "Client.InvalidParameterCombination",
    "errorMessage": "The parameter iops is not supported for gp2 volumes.",
    "requestParameters": {
        "size": "30",
        "zone": "ap-southeast-2a",
        "volumeType": "gp2",
        "iops": "0"
    },

I have raised that with AWS support but the fix will most likely have to be on `kube-aws` side and omit sending the `iops` attribute for anything else but `io1` volumes.

Note that this is probably being sent by `kube-aws` itself, not as part of CFN template.

**Comment by mumoshu** [comment]
Hi @mludvig, thanks for trying kube-aws!

I sounds like you're hitting #1170, which is fixed on master since #1171
