### ISSUE TITLE
doc: Suggest cluster admins to regularly update AMI ID(s) in cluster.yaml

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#1209]
After #1201. Otherwise the cluster stucks on an old Container Linux release. Formerly, regularly running `kube-aws update` without modifying cluster.yam at all was enuogh.

**Comment by c-knowles** [comment]
It would be good to have a command to update to the latest from the cluster.yaml specified channel.

**Comment by cmcconnell1** [comment]
Hello,

Would like to ask how this will work with versions that hard-code/pin the CoreOS AMI image by default upon cluster.yaml file?

I.e.:  for kube-aws version v0.9.10-rc.3 we have the following 'pinned' in our cluster.yaml file by default:
amiId: "ami-07a6b767"

Would the proposed process (and doc update or commands) involve  removing the above amiID 'pinning?'
And then updates would be made once nodes were restarted?

Thanks
