### ISSUE TITLE
Question: IP addressing in existing VPC

### ISSUE THREAD

**Issue by mludvig** [kubernetes-incubator/kube-aws#1210]
Hi, I'm confused as to how the internal cluster IP addressing is supposed to be set up with regards to the VPC CIDR. For instance I've got a VPC with CIDR 10.0.0.0/16 and these settings in `cluster.yaml`:

    subnets:
    - name: ManagedPublicSubnet1
      private: false
      availabilityZone: ap-southeast-2a
      instanceCIDR: "10.0.10.0/24"
    - name: ManagedPublicSubnet2
      private: false
      availabilityZone: ap-southeast-2b
      instanceCIDR: "10.0.11.0/24"

    serviceCIDR: "10.3.0.0/24"
    podCIDR: "10.2.0.0/16"
    dnsServiceIP: 10.3.0.53

That seems to work, the pods on 10.2.0.0/16 can resolve DNS from 10.3.0.53 and can talk to services on 10.3.0.0/24.

However when I create a new cluster with `serviceCIDR: 172.23.0.0/24`, `podCIDR: 172.22.0.0/16` and `dnsServiceIP: 172.23.0.53` the cluster doesn't work. The pods can't talk neither to DNS nor to the services.

I'm confused because the service and pod CIDRs don't fall under the VPC CIDR, yet it still doesn't work when I change them...

What IPs can I use for the `.serviceCIDR` and for `.podCIDR` in relation to the VPC CIDR? 

What if I want to create my `kube-aws` cluster in an existing VPC with existing Subnets (e.g. each subnet being 192.168.x.0/24) - what service and pod CIDRs can I use there? Do I have to do any special trickery with AWS or instance routing tables? 

And how can I check that the overlay _flannel_ network works as expected? Where is does the routing set up? I haven't found the route to 10.3.0.0/24 on the Node instances.

BTW I'm using `kube-aws` from todays git master and also tried 0.9.9.

Thanks!

**Comment by mludvig** [comment]
Hi, any input on this anyone? Please? :)

Created a working cluster with the attached template with services in 10.3.0.0/24 and pods in 10.2.0.0/16 and when I changed just these two lines and moved services to 10.30.0.0/24 everything stopped working:

    diff --git a/cluster.yaml b/cluster.yaml
    index 866278b..70af3fd 100644
    --- a/cluster.yaml
    +++ b/cluster.yaml
    @@ -815,13 +815,13 @@ subnets:
     
     
     # CIDR for all service IP addresses
    -serviceCIDR: 10.3.0.0/24
    +serviceCIDR: 10.30.0.0/24
     
     # CIDR for all pod IP addresses
     podCIDR: 10.2.0.0/16
     
     # IP address of Kubernetes dns service (must be contained by serviceCIDR)
    -dnsServiceIP: 10.3.0.53
    +dnsServiceIP: 10.30.0.53
     
     # Uncomment to provision nodes without a public IP. This assumes your VPC route
     # table is setup to route to the internet via a NAT gateway.

Why is that? Are these internal IPs hardcoded somewhere?? And if so why are they configurable??

Here is my working [cluster-yaml.txt](https://github.com/kubernetes-incubator/kube-aws/files/1878335/cluster-yaml.txt)

**Comment by c-knowles** [comment]
Hi @mludvig, as far as I'm aware with an overlay network such as flannel the VPC CIDRs are entirely disconnected from the service and pod CIDRs. You can use an existing VPC without any trickery, even deploying multiple clusters with the same service/pod CIDRs to the same VPC (but different subnets). I'm usually customising serviceCIDR a bit but didn't change the others much so can't vouch for whether there's validation issues in some cases, I suggest if you don't need to customise them then leave them commented out. There might be more people able to help in the slack channel mentioned in the readme.

I think it gets a little murkier if you start to use some of the more native networking plugins like those discussed in https://github.com/kubernetes-incubator/kube-aws/issues/1047 but kube-aws doesn't support those yet.

**Comment by cmcconnell1** [comment]
Hello,
Our VPC CIDR has a similar CIDR range and I just learned to **always keep the defaults** for the **service** and **pod** CIDR ranges--I like to break up our smaller clusters.   The instanceCIDR is for each clusters two subnets in two separate AZ's:

```
egrep -i 'CIDR' ./cluster-foo/cluster.yaml
vpcCIDR: "10.1.0.0/16"
    instanceCIDR: "10.1.7.0/27"
    instanceCIDR: "10.1.7.32/27"
serviceCIDR: "10.3.0.0/24"
podCIDR: "10.2.0.0/16"
```

```
egrep -i 'CIDR' ../cluster-bar/cluster.yaml
vpcCIDR: "10.1.0.0/16"
    instanceCIDR: "10.1.7.128/26"
    instanceCIDR: "10.1.7.192/26"
serviceCIDR: "10.3.0.0/24"
podCIDR: "10.2.0.0/16"
```
