### ISSUE TITLE
Tiller permissions too restrictive

### ISSUE THREAD

**Issue by kylehodgetts** [kubernetes-incubator/kube-aws#1212]
## Background
Introduced in #1202. Originally tiller ran with the default service account bound to cluster-admin which is quite bad when you consider that everything that is created without a specified service account will be assigned the default and thus be able to do ANYTHING with the cluster. That's no longer the case.

## New problem.
I ran into an issue when attempting to install the prometheus-operator chart with these new permissions. These permissions are too restrictive and thus don't allow for the creation of service-accounts and cluster role bindings, which it will need when installing these kind of charts.

The easy fix is to bind the new tiller service account added in #1202 to cluster-admin. This is better than what we had before because now a specified service account has cluster-admin permissions for tiller and not just the default.

Ideally, I'd like this to prompt a discussion about what exactly tiller should have permission to do by default.

For instance, cluster-admins are able to create namespaces. Does tiller really need to do this?

**Comment by c-knowles** [comment]
The details and templates in [this chart](https://github.com/kubernetes/charts/tree/master/stable/magic-namespace) may be of use here.

**Comment by c-knowles** [comment]
It seems the current RBAC does not allow Service object access either (for example to use the `--wait` flag).

After the changes I could no longer install/update these charts:
- traefik with RBAC enabled, service account access needed
- kube-state-metrics, service access needed
- external-dns, service account access needed
