### ISSUE TITLE
kube-aws does not always roll nodes as expected

### ISSUE THREAD

**Issue by davidmccormick** [kubernetes-incubator/kube-aws#1218]
In testing out a new kube-aws feature I found that changes made to my cluster.yaml doesn't always result in my cluster nodes rolling even though changes to my choices in the cluster.yaml should have resulted in differences to my resultant node cloud-configs.  On such example, could be toggling kubernetes.networking.selfHosting on and off via the settings in cluster.yaml.

This looks to be because the user-data and cloud config have been modelled as two separate parts; the 'instance' part is a script that loads the second 's3' part (which contains the actual cloud-config configuration).  The 'instance' script will change (causing nodes to roll) if the template changes because the script references the cloud-config file with an added 'fingerprint' (sha256 hash) of the template as part of the filename.  I think the nodes will only roll when there are differences in the template.

If there are no changes to the template - then the nodes will not roll, regardless of any changes that I have made to the settings within my cluster.yaml.  I believe that the nodes should roll as a result of any changes **either in the template or the values** which results in a difference to the **rendered** cloud-config.  i.e. I believe that the actual user-data - the 'instance' part needs to be tied to the rendered s3 part, and not to template itself.

To this end, I would like to propose that we add a fingerprint of the rendered 's3' userdata component to the script in the 'instance' component as a non-executed line (i.e. comment) so that when there is a change to the rendered 's3' userdata component then the 'instance' component will also change, causing the nodes to roll next time we run update.

I will submit a pull request to add this functionality.

regards

Dave

**Comment by mumoshu** [comment]
@davidmccormick Thanks for the detailed feedback!

> the rendered s3 part, and not to template itself.

I was under the impression that we do calculate a fingerprint from a rendered template according to:

- https://github.com/kubernetes-incubator/kube-aws/blob/5e15ac9059a95c051600c378cec204621c3a722f/core/nodepool/cluster/cluster.go#L121
- https://github.com/kubernetes-incubator/kube-aws/blob/548bb386dd14dbee7d9c9fc012e2b3a4fe5c6b75/cfnstack/assets.go#L85
- https://github.com/kubernetes-incubator/kube-aws/blob/0dc583e21ea22dffc42ddc8d1c306ae3499d6305/model/userdata.go#L123

However then, why your node didn't roll at that time? I'm not sure yet.

**Comment by davidmccormick** [comment]
Hi, no the fingerprint in the asset name is made from the template not the rendered template.  This means that the s3 uri does not change in the 'instance' user-data unless the template itself is changed. 

The model.userdata methods are called directly from the cloud-formation stack templates - so it is only at this point that the resultant files are rendered.

My nodes do not roll when I toggle a cluster.yaml field using the same templates.  This is how I discovered the behavoir.  I think there are two possible solutions: -

1) Put a fingerprint within the 'instance' script so that any change to the rendered s3 template will also cause a corresponding change in the instance script.
2) Somehow change the userdata to include the rendered values and use the rendered finger print in the asset filename instead of the fingerprint of the template.

I have a working example of 1 which is fairly simple but not sure how easy 2) would be.

**Comment by davidmccormick** [comment]
The worker user-data has an extra user-data component - 'instance' is moved into 'instance-script' and instance became: -

```
{{ define "instance" -}}
{ "Fn::Base64": { "Fn::Join" : ["", [
  "#!/bin/bash -xe\n",
  {"Fn::Join":["",[ "echo '{{.StackNameEnvVarName}}=", { "Ref": "AWS::StackName" }, "' >> {{.StackNameEnvFileName}}\n" ]]},
  {{ (execTemplate "instance-script" .) | toJSON  }}
]]}}
{{ end }}
```

Do you know what this was for?  I would like to make it the same as the etcd and controller nodes again?

**Comment by davidmccormick** [comment]
The unit tests pass, but the integration test appears to hang - which I can't run from here.  Is it possible you could help me establish what is freezing on the integration test?

**Comment by mumoshu** [comment]
For anyone interested, the work is on-going at #1228 now 🏗
