### ISSUE TITLE
Checksum credentials and ensure hash matches before updating cluster

### ISSUE THREAD

**Issue by SomeoneWeird** [kubernetes-incubator/kube-aws#1238]
It would be great if `kube-aws render credentials` also generated a `credentials.sha256` file or something that we can check into git.

Would propose also adding a `kube-aws check-credentials` command, which can compare your current creds directory against the saved hash, and that `kube-aws update` verifies the same thing, and errors out if the credentials don't match (obviously bypassable with `--ignore-wrong-credentials` or something, if you wish to rotate them)

**Comment by mumoshu** [comment]
@SomeoneWeird Hi! Thanks for the feedback.

Your idea sounds interesting to me. But I'm still unsure if my understanding is correct.

Would you mind clarifying a bit more on your actual use-case? Probably an example user-story would help.
