### ISSUE TITLE
Enable PersistentVolumeClaimResize Admission Controller

### ISSUE THREAD

**Issue by kevtaylor** [kubernetes-incubator/kube-aws#1242]
Would like to be enable this feature to allow dynamic expansion of PVC 

https://kubernetes.io/docs/admin/admission-controllers/#persistentvolumeclaimresize

The feature gate is already enabled by default, and the expander is GA in 1.9, so seems appropriate to introduce it

**Comment by mumoshu** [comment]
Closing this as resolved via #1243. Thanks for your contribution as always @kevtaylor!
