### ISSUE TITLE
Kubernetes.Networking.SelfHosting settings not propagating to nodes

### ISSUE THREAD

**Issue by davidmccormick** [kubernetes-incubator/kube-aws#1246]
This doesn't cause any visible issues because legacy nodes also support the self-hosted daemonsets but it does mean that the nodes do not clean up their local flannel and made me wonder why my nodes were not rolling.

The cloud-config on the worker has customised sections depending on .Kubernetes.Networking.SelfHosting.Enabled and if we correctly propagate this setting that nodes will start up faster with a cleaner configuration.

**Comment by mumoshu** [comment]
Closing this as resolved via #1244. Thanks for the report and the PR @davidmccormick!
