### ISSUE TITLE
Feature request: Automatically detaching nodes marked by node-problem-detector

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#1248]
(Extracted from the discussion in Slack between @c-knowles and me)

This is still more or less a "sounds like a good idea" thing but...

I want kube-aws to automatically detach nodes marked degraded by [node-problem-detector](https://github.com/kubernetes/node-problem-detector)
so that ASG could automatically add a replacement node for availability, while operators can ssh into the node for investigation afterwards.

Context: #681 could be implemented as a custom node-problem-detector check. It, in combination with this feature, would allow you to automatically recover from any node-level failure, while retaining chances for investigation of the problem.

**Comment by mumoshu** [comment]
For debugging purpose, it would be nicer if kube-aws could somehow leave log messages about why and when it is detaching the node.

**Comment by whereisaaron** [comment]
If you are using the `cluster-autoscaler` it is probably enough to taint node. Then the `cluster-autoscaler` should still increase the node count. 

For detaching, this project may be of interest to you [cristim/autospotting](https://github.com/cristim/autospotting) it uses the detaching/attaching facility heavily, to make heterogeneous ASGs with both regular and spot instances.
