### ISSUE TITLE
Enable EBS-optimized flag on nodes

### ISSUE THREAD

**Issue by kiich** [kubernetes-incubator/kube-aws#1252]
We created a node pool specifically to take advantage of [EBS-optimise](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html) so they are of instance type that has it on by default.

However when we spin up a cluster, the AWS console shows the volume with no optimisation. Looking further into it, it looks like the Launch Configuration that creates the instances do not have the EBS optimised flag enabled and hence the instances created from the LC do not have it enabled neither.

If I just spin the instance via ec2 console, ebs is indeed enabled.

**Comment by mumoshu** [comment]
@kiich Thanks for the good catch! I do remember the last time I have literally seen the flag, but somehow overlooked to consider it for kube-aws...

This should be addresseds .

Probably:

- Adding a helper go func named like `EbsOptimized(instanceType string) bool` to return true when and only when the instance type is greater than `t2`, `m3`, and `c3` series.
- And use the helper func inside stack-template.json for etcd, controller, worker nodes

at minimum would work.

**Comment by kiich** [comment]
Sounds good @mumoshu - thanks for the heads up. I'll look into it for possible PR.

**Comment by kiich** [comment]
@mumoshu regarding series that do not support EBS optimise, it seems some type in certain series that supports EBS optimise, does not - such as `i2.8xlarge` that does not support it but the rest of `i2` series do.

What do you think about catching those? Was there a reason for filtering on `t2`,`m3` and `c3` specifically? As I can see some types of `m3` such as `m3.xlarge` supprots EBS optimise.
