### ISSUE TITLE
Controller Manager memory leak

### ISSUE THREAD

**Issue by jorge07** [kubernetes-incubator/kube-aws#1254]
I'm currently fighting with this issue https://github.com/kubernetes/kubernetes/issues/52657

As there's no fix for this ATM, what do you think about add some memory limit as parameter for controller manager as workaround like it's suggested in https://github.com/kubernetes/kubernetes/issues/52657#issuecomment-371804110?

```
$ kubectl top po -n kube-system
NAME                                                    CPU(cores)   MEMORY(bytes)
cluster-autoscaler-6b89b7bfc9-mtk9n                     5m           62Mi
heapster-68db74c6dc-2tnlb                               1m           75Mi
kube-apiserver-ip-YYYYYY.ec2.internal                   17m         741Mi
kube-apiserver-ip-YYYYYY.ec2.internal                  100m         522Mi
kube-controller-manager-YYYYYY.ec2.internal             0m           17Mi
kube-controller-manager-ip-YYYYYY.ec2.internal         21m         2090Mi
```

**Comment by mumoshu** [comment]
@jorge07  Hey! Thx for the detailed report and the suggestion.

Adding memory limit sounds good to me. Would you mind submitting a PR for that? Just my two cents but my quick guess is that `kubernetes.controllerManager.requests.memory` and `kubernetes.controllerManager.limits.memory` in cluster.yaml, propagated as is to controller-manager static pods, would work.

**Comment by jorge07** [comment]
@mumoshu that's sounds like a very clever solution! I'll try it asap

**Comment by jorge07** [comment]
Related with: https://github.com/kubernetes-incubator/kube-aws/pull/1266/files

**Comment by mumoshu** [comment]
kubespray seems to define default limits/requests [here](https://github.com/kubernetes-incubator/kubespray/blob/07cc98197187535619ac8e57ee4e04ae02631a54/roles/kubernetes/master/defaults/main.yml#L28-L31).
`kube_controller_memory_requests ` of `100M` and `kube_controller_memory_limit` of `512M` sound reasonable.
