### ISSUE TITLE
Please can we bump version of golang for Travis tests to 1.10?

### ISSUE THREAD

**Issue by davidmccormick** [kubernetes-incubator/kube-aws#1262]
version 1.8.3 is now fairly old-ish and I'm finding that there are changes and missing functions when developing with 1.10 and then submitting PRs upstream.  Are there reasons why moving to the latest go isn't possible or desirable?

**Comment by mumoshu** [comment]
There's no reason at all not to do so! I just forgot to do so myself... Let's bump.
