### ISSUE TITLE
m3.medium, Failed to set up mount unit: Invalid argument

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#1272]
On our dev cluster, we use m3.medium for the nodes. It seems this log appears almost continuously even on healthy nodes.

```
2018-04-30T20:57:24.000Z {
  "instanceId": "i-0cc90d2b46c92759b",
  "pid": 1,
  "uid": 0,
  "gid": 0,
  "cmdName": "systemd",
  "exe": "/usr/lib64/systemd/systemd",
  "cmdLine": "/usr/lib/systemd/systemd --switched-root --system --deserialize 16",
  "systemdUnit": "init.scope",
  "bootId": "f234d4bc209c45d1a5bbc6e5f644a510",
  "hostname": "ip-10-0-31-213.eu-west-1.compute.internal",
  "transport": "journal",
  "priority": "WARNING",
  "message": "Failed to set up mount unit: Invalid argument",
  "syslog": {
    "facility": 3,
    "ident": "systemd"
  },
  "kernel": {}
}
```

Actually we've had this error for a long time even across kube-aws versions. See https://github.com/kubernetes-incubator/kube-aws/issues/527 for example which has the same log from one year ago.

I'm wondering if m3.medium is even supported any more or has some known issues. The same issue does not appear to show on other instance types with similar setup.

**Comment by kylegoch** [comment]
We get this same log on any type node. I found it was due to an upstream CoreOS issue.
I'll see if I can find the issue again.

**Comment by kylegoch** [comment]
we still see this. cant find the original issue I was thinking of but did find this:
https://github.com/coreos/etcd/issues/977

We use m5.2xlarge, m5.4xlarge, m5.12xlarge, m5.16xlarge, and r4.8xlarge. And see it across most if not all of them
