### ISSUE TITLE
CloudFormation template for cluster prerequisites

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#1288]
I was considering adding a CF template for the prerequisites we list in [the documentation](https://kubernetes-incubator.github.io/kube-aws/tutorials/quick-start.html). It could smooth over part of [Step 2/Render](https://kubernetes-incubator.github.io/kube-aws/getting-started/step-2-render.html). We could easily have something basic with the S3 bucket and KMS key, I have that locally already as we use one per account/region.

Options:
1. Only reference from the docs
1. Add into the render folder automatically

Probably option 1 is fine for now.

**Comment by mumoshu** [comment]
I'm fine with the option 1, too 👍

**Comment by mdgreenwald** [comment]
I still think this would be useful!
