### ISSUE TITLE
Use the etcd-cloud-operator for etcd’s reliability/safety rather than a bash script

### ISSUE THREAD

**Issue by Quentin-M** [kubernetes-incubator/kube-aws#1295]
Hi,

I am obviously biased since I authored the tool, but I have the strong conviction that the [etcd-cloud-operator](https://github.com/Quentin-M/etcd-cloud-operator) is a much safer bet than using a rather simplistic bash script to provide etcd snapshots and recovery mechanisms.

Not only is the state machine more accurate, leading to extremely short recovery times, it also simplifies dramatically the process of executing a “manual” recovery, such as a data rollback for instance, as the tool is able to perform it by itself from any snapshots stored in S3.

**Comment by mumoshu** [comment]
@Quentin-M Hi, thank you so much for sharing the awesome project and the suggestion!

I'm really looking forward to add a smooth integration with etcd-cloud-operator.

Actually one of my motivations to proceed with the huge refactoring #1233 to extract the etcd cluster into a separate CloudFormation stack was to make etcd cluster less coupled to other parts of kube-aws.

That being said, I believe that it is certainly feasible to add support for etcd-cloud-operator if we defined an interface between it and kube-aws.

Probably kube-aws would need to consume the following things output from the operator:

- etcd client key and cert, etcd CA cert.
  - Currently kube-aws worker and controller nodes expect those to be present on EC2 instances. Keys are pem-encoded, KMS-encrypted, and then embedded into worker/controller cloud-config. On node startup, a bash script executed from a systemd unit decrypts the keys. Similarly, certs are pem-encoded and embedded into cloud-configs.
  - We may need to somehow pass keys and certs from the operator to kube-aws nodes
- stable public hostnames of all the etcd nodes
  - Currently kube-aws stabilizes the hostnames by assigining EIPs to etcd nodes, even when etcd nodes are inside privae subnets.
  - Does the etcd nodes managed by the operator has stable hostnames?
  - How can we pass the hostnames from the operator to kube-aws and its nodes?

**Comment by Quentin-M** [comment]
I am thrilled to hear about your excitement.

- stable public hostnames of all the etcd nodes: the general idea is that someone creates an auto-scaling group, with a load-balancer (public or private), of machines that run the etcd-cloud-operator binary with the given configuration. From there, all Kubernetes nodes can/should rely on the load-balancer hostname (or a route53 name) to reach the etcd cluster. The etcd clients used to query the cluster are responsible for retries during the short amount of time some etcd nodes may be unavailable until the load balancer has taken the unhealthy endpoints out. It may also be possible for the clients (as some are already doing), if the members are directly reachable, to read the list of members periodically using the load balancer's endpoint, and then construct a gRPC client that contact them directly, enabling the gRPC client to make decisions on which member to contact when.

- etcd client key and cert, etcd CA cert: those can be pre-generated and given to the operator through its [configuration file](https://github.com/Quentin-M/etcd-cloud-operator/blob/master/config.example.yaml). In the case of the provided Terraform module, it is handled by Terraform itself (alongside generating any other required AWS resources, such as security groups, IAM roles, etc), but that module is more of an example or something that can be used out of the box by someone who already uses Terraform - the operator can be integrated by other means quite easily.

**Comment by mumoshu** [comment]
Thanks for the explanation!

Regarding the load-balancer - I'd encourage users to place AWS-managed LBs like ELB or NLB in front of the etcd cluster, if we are forced to use LBs.

However - you may already know - AWS doesn't have a managed LB supports h2 or gRPC. AFAIK ALB is L7 but doesn't support h2 backends. ELB and NLB work because they are L4, but it doesn't actually load-balance grpc calls flowing over a single tcp session. [Here's an interesting read](https://gist.github.com/bojand/6a604f7e369d7c7d8c39eb77878a42c2) for anyone interested.

That's why kube-aws has chosen to use client-side load-balancing for etcd. For client-side load-balancing, kube-aws needs to know hostnames or ip addresses of etcd members.

WDYT about this? Could etcd-cloud-operator still help in this use-case?

Regarding keys and certs, understood! Thanks for the explanation again.

**Comment by mumoshu** [comment]
@Quentin-M Forgot to mention you!

**Comment by Quentin-M** [comment]
@mumoshu It would be interesting to try ECO with an ALB/NLB. Pretty straight-forward to try out. We (or our existing users) have had no reported production issues so far though.

Actually, the way the etcdv3 client works is that it will actually go ahead with the initially provided endpoint & then [list the members](https://github.com/etcd-io/etcd/blob/e34423b6fff5bd14d7f765944273ed2eee250f3c/clientv3/client.go#L164) to set its targets dynamically. The etcdv3 client already wraps a [gRPC balancer](https://github.com/etcd-io/etcd/blob/e34423b6fff5bd14d7f765944273ed2eee250f3c/clientv3/balancer/balancer.go).

Right now, ECO makes every etcd members advertise the same client URL: the load balancer. This is mostly for network isolation purposes. There is no other reason we would not make them advertise their own IPs if you wanted to leverage the embed gRPC balancing feature by letting clientv3 connect directly to each of them individually. It could also be a selectable mode.
