### ISSUE TITLE
Option to encrypt volumes

### ISSUE THREAD

**Issue by etiennetremel** [kubernetes-incubator/kube-aws#1298]
I was wondering if there was any specific reason not to encrypt all the volumes. For now it seems that only ETCD data volume can be encrypted but not the worker/controle plane.

https://github.com/kubernetes-incubator/kube-aws/blob/dcf8360e91f95452e1da717aa1ecbb774d2bdc01/core/nodepool/cluster/cluster.go#L218-L238

**Comment by jasonrichardsmith** [comment]
I was looking over the code base and I think (I could be wrong) that the volume code could use a little clean up.  Which is a bit of a small overhaul.
