### ISSUE TITLE
Support for multiple k8s versions

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#1301]
Currently many flags/changes we introduce mean that a certain kube-aws version can only be used with some minimum version of Kubernetes. For example we add a flag to apiserver only supported after some version.

I'd like to start documenting those versions somewhere to be clear what versions we tried and/or endorse for each kube-aws version. I also wonder if/how we could consider properly supporting multiple Kubernetes versions.

I did something basic in https://github.com/kubernetes-incubator/kube-aws/pull/1286 but I think something slightly more configurable would be good, maybe even storing each unit file/bootstrap YAML separately against a version or set of versions and then combining it for the final render.

**Comment by jorge07** [comment]
It also should be applied to the documentation versioning.

**Comment by mumoshu** [comment]
Thanks for raising this!

I'm wondering if it would be enough/feasible to support at least two Kubernetes versions for each kube-aws release. For example, k8s v1.9.x and v1.10.x for kube-aws v0.11. Support for v0.11.x(alpha,beta,rc) to kube-aws v0.11 should be done in a manner that doesn't break v1.9.x compatibility.

**Comment by c-knowles** [comment]
@mumoshu I think that's more than enough. We could also add an allowed list so at least other versions produce a warning (but do not block).
