### ISSUE TITLE
kube-aws validate throwing ValidationError: Template error: the attribute in Fn::ImportValue must not depend on any resources, imported values, or Fn::GetAZs

### ISSUE THREAD

**Issue by kiich** [kubernetes-incubator/kube-aws#1304]
After fixing #1303 in my branch, the validation continues but then gets
```
kube-aws validate
Validating UserData and stack template...
generating assets for control-plane, etcd, network, nodepool-a, nodepool-b, nodepool-c
Error: failed to validate control plane: invalid cloudformation stack template xxx/stacks/control-plane/stack.json: ValidationError: Template error: the attribute in Fn::ImportValue must not depend on any resources, imported values, or Fn::GetAZs
	status code: 400, request id: ...
```

**Comment by kiich** [comment]
Looking into it, the resulting stack.json seems to be referencing `${ControlPlaneStackName}`  which I can't find at top under Parameters.

```
"etcd-client-env": {
"files": {
"/var/run/coreos/etcd-environment": {
"content": {
"Fn::Join": [
"",
[
"ETCD_ENDPOINTS='",
"https://",
{
"Fn::Join": [
".",
[
{
"Fn::Join": [
"-",
[
"ip",
{
"Fn::Join": [
"-",
{
"Fn::Split": [
".",
{
"Fn::ImportValue": {
"Fn::Sub": "${ControlPlaneStackName}-Etcd0PrivateIP"
}
}
]
}
```

**Comment by kiich** [comment]
Seems it just needs to be `EtcdStackName` like in the `importedDefaultPublicDNSNameRef` function. Will PR after locally testing.

**Comment by mumoshu** [comment]
> Seems it just needs to be `EtcdStackName` like in the `importedDefaultPublicDNSNameRef` function. Will PR after locally testing.

Good catch! It seems like I missed testing #1233 w/ the eni provider, and your proposed fix sounds great. Thanks for your support!
