### ISSUE TITLE
You can change kubernetes pod and service CIDRs with the kube-aws distribution!

### ISSUE THREAD

**Issue by davidmccormick** [kubernetes-incubator/kube-aws#1307]
Changing an existing kubernetes cluster's pod or service CIDR is not easy to do!

Allowing administrators to change their pod network CIDR or services network CIDR is not something that is well supported by the kubernetes community.  There isn't a way of changing the CIDRs on-the-fly in a live cluster and it is still not straight-forward even if you are willing to accept that the change will require downtime.

And yet there are still inevitably circumstances where you might find that you have no choice but to consider changing your CIDRs: -

- You've run out of room for nodes, if you picked a /16 pod network CIDR then you only have up to a 256 node cluster (because flannel takes the last 8 bits for pod addresses by default).
- Either you find that your pod network or service network clash with duplicate ranges outside your cluster that you need to be able to route to.
- Or you want to run a fancy service mesh across different clusters which can't because both clusters share the same internal ranges.

We have found that we have six clusters that we must change because we have run out of space to grow.  We don't operate multi-clusters and so it is desirable to update them in-place with some downtime (but no loss of app/services when they come back up).

The standard kubernetes response to wanting to change a CIDR is to "build another cluster" but this may not be straight-forward (especially if your cluster is already large with important customers), unless your application deployment tool-set already accommodates a multi-cluster architecture.   This is where I feel that kubernetes distributions like 'kube-aws' can step in and deliver real value for our users and administrators by assisting/facilitating such changes through automation in kube-aws.

I have been able to successfully change both pod and service cidrs in 'kube-aws' clusters by following the procedure below: -

WARNING: The procedure below WILL result in downtime!

1. Update cluster.yaml with new podCIDR, ServiceCIDR (remember to also update dnsServiceIP).
1. Remove and re-generate your apiserver.pem certificate (if you changed your ServiceCIDR).
1. Scale the AWS Autoscaling groups for your controllers and all nodes to 0 (so you are only left with etcd servers)
1. Render stack and roll cluster to bring up controllers and nodes with new CIDRs++

++note: special updated kube-aws version required that handles cluster cidr changes upon start-up required.

Unfortunately, it is not possible to simply stop all controllers and nodes and bring everything back up to change the CIDRs - this will result in some nasty errors that will leave you with a non-functional cluster.  The 'kube-controller-manager' will not start up if it finds objects in etcd with incompatible node, pod or service cidrs:-

```
E0502 17:00:11.998272       1 controllermanager.go:486] Error starting "node"
F0502 17:00:11.998284       1 controllermanager.go:155] error starting controllers: failed to mark cidr as occupied: cidr 192.168.0.0/24 is out the range of cluster cidr 100.64.0.0/10
```

It's not possible to completely catch and remove all the incompatible objects by scaling down your cluster (by removing all controllers and nodes) but we can create a service that runs on each controller as it boots that is able to handle CIDR changes for us and allow the controller to come up and the cluster to migrate to the new values.  The aim of the game is to handle the changes in such way that the cluster roll is successfull and the cidrs have changed at the end of the update - not to eliminate downtime.  

The service must do the following: -

1. delete all nodes which do not fall within the new pod cidr
1. delete all pods which fall outside the new pod cidr
1. delete the 'kubernetes' service if it is not on the right ip address (the first address in the service cidr - it will be automatically recreated correctly)
1. recreate all services which fall outside the service cidr so they pick up new ClusterIP addresses

Whilst I prefer that all previous controllers are stopped prior to migrating pod/service cidrs it is desirable if kube-aws can cope with a new controller coming up with changed CIDRs into an existing cluster with previous controllers and nodes running.  Having multiple controllers running with different cidr range settings is particularly troublesome and so employing something like STONITH (Shoot-The-Other-Node-In-The-Head) might be useful to ensure that our new controller is the only one that is elected as master controller-manager.

If we change CIDRs and there are already existing nodes it is desirable that all nodes roll so that the cluster is left in a fully working state (with new CIDRs) after the kube-aws update command has completed.

The CIDR handling functionality needs to cope with new clusters.

**Comment by davidmccormick** [comment]
Hi, yes that is right.  The validate_* functions work as described.  The only thing I think I can add is that the validate_nodes step is the most important and must run first and this step also will kill any old controllers that it finds.  This must run to completion before we re-create any services.

My recommendation for anyone changing the CIDRs in their clusters is to stop all controllers and nodes leaving only the etcd servers up.  Then when you roll the cluster there are no old controllers to worry about + all the controllers and nodes will come up together - which is much faster than waiting for all nodes to roll.

**Comment by davidmccormick** [comment]
Any more thoughts on this?

**Comment by mumoshu** [comment]
@davidmccormick Would it be feasible/meaningful to hide the feature behind a feature flag? I'm a bit nervous about a slight possibility that it can shoot our head as well when a slight bug slipped in the STONITH controller. WDYT?

Everything other than that LGTM now 😄Awesome job!

**Comment by davidmccormick** [comment]
Yes, I did consider that and can absolutely put it behind a feature flag if you prefer but that would also mean that we risk people changing their CIDRs and not knowing or remembering to enable the flag and crashing their cluster.  I see we need to balance this risk against the risk of it validating for the first time as it is rolled into existing clusters.

I think that long-term it would be best if it was enabled by default but a period of testing would be great (I'm currently running it against all of our clusters to migrate them).  Is there a way to get some good testing if it is not enabled by default?

**Comment by davidmccormick** [comment]
I have an idea, I could remove the validation it does if it has never previously run so that it will only ever run if the CIDRs have actually changed and in that instance you would definitely want it!  Does that sound ok?

**Comment by davidmccormick** [comment]
This is now merged into kube-aws
