### ISSUE TITLE
Difference between #workerInstanceType: t2.medium &  # instanceType: t2.medium in an node pool

### ISSUE THREAD

**Issue by nandakishorebhandari** [kubernetes-incubator/kube-aws#1311]
What is the difference between #workerInstanceType: t2.medium &  #instanceType: t2.medium in an node pool.

**Comment by kiich** [comment]
Can I get that behaviour confirmed as I only have `workerInstanceType` set (to value of m4.xlarge for example) and no `instanceType` in my worker node pool config and the resulting stack.json shows the instance type to be always `t2.medium`.

If I set it via `instanceType` in my node pool config, that value is honoured.

**Comment by mumoshu** [comment]
@kiich Good catch.

I blindly believed that `workerInstanceType` would be used as the default value for `instanceType`s. But as far as I could see from the codebase today, we seem to have a static `t2.medium` as the default. `workerInstanceType` isn't taken into account.

Also, I noticed we somehow missed tests for the defaulting in our [integration test](https://github.com/kubernetes-incubator/kube-aws/blob/master/test/integration/maincluster_test.go
). So there may be a chance we missed it long ago and no one noticed that? 😓 

Can we just remove `workerInstanceType`? I have never used that recently myself. Do you use/need it?

**Comment by kiich** [comment]
Hey @mumoshu 
Yeah that's what I came to conclusion after testing it and looking in the codebase (defaulting always to `t2.medium`).

I personally don't use `workerInstanceType` and have always specified `instanceType` for all my nodepools so I'm in favour of dropping it. I saw that there are other `worker` related default settings - are those also not taken into account i wonder?

**Comment by mumoshu** [comment]
Some of those seem so.

https://github.com/kubernetes-incubator/kube-aws/blob/7b26da668d32f93cb90d1c55440e50dfd74dd4c3/core/root/config/templates/cluster.yaml#L562-L583
https://github.com/kubernetes-incubator/kube-aws/blob/87aa5a9471cf197d97ce3083181d86783492255c/model/node_pool_config.go#L37-L46
https://github.com/kubernetes-incubator/kube-aws/blob/87aa5a9471cf197d97ce3083181d86783492255c/core/nodepool/config/worker.go#L31-L58

**Comment by kiich** [comment]
Hey @mumoshu  - ah I ok, then maybe some people are using those/relying on them so maybe implement `workerInstanceType` if it's not a too much of work? (though like i said, since no tests were there and no issues have been raised about it, maybe it is not used by anyone??!!)

Happy to PR as well.

**Comment by nandakishorebhandari** [comment]
Thanks, @mumoshu, @kiich and  @jorge07 for clarification.
