### ISSUE TITLE
Unable to change instance type of etcd, cluster get faild to create.

### ISSUE THREAD

**Issue by nandakishorebhandari** [kubernetes-incubator/kube-aws#1312]
When ever I change instance type of etcd, cluster get faild to create.

15:27:43 UTC+0550 | CREATE_FAILED | AWS::CloudFormation::Stack | myvpc-cluster-Controlplane-1I1ILGE9CC9YE | The following resource(s) failed to create: [Etcd0].

  | 15:27:42 UTC+0550 | CREATE_FAILED | AWS::AutoScaling::AutoScalingGroup | Etcd0 | Received 0 SUCCESS signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement

**Comment by kiich** [comment]
is the instance type m5 by any chance? reported by #1313

**Comment by nandakishorebhandari** [comment]
Yes its m5 unstance
