### ISSUE TITLE
ETCd not working on m5 instances

### ISSUE THREAD

**Issue by Vrtak-CZ** [kubernetes-incubator/kube-aws#1313]
because root volume is on `/dev/nvme0` and ETCd volume is on `/dev/nvme1`

**Comment by c-knowles** [comment]
Ref https://github.com/coreos/bugs/issues/2399 for upstream.

**Comment by Vrtak-CZ** [comment]
other reference https://github.com/kubernetes-incubator/kube-aws/issues/1230

**Comment by kiich** [comment]
other reference #1312
