### ISSUE TITLE
Duplicate controller role permissions for CloudWatch logging

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#1315]
Small tidy up we could do, we seem to have the permissions for `CloudWatchLogging` inside `IAMManagedPolicyController` twice:
https://github.com/kubernetes-incubator/kube-aws/blob/6c509be4228791ccb3b19083277b2530643b6055/core/controlplane/config/templates/stack-template.json#L198
https://github.com/kubernetes-incubator/kube-aws/blob/6c509be4228791ccb3b19083277b2530643b6055/core/controlplane/config/templates/stack-template.json#L220

As far as I can tell it was like this from the start of this feature so no worries about a bad merge somewhere. Ref https://github.com/kubernetes-incubator/kube-aws/pull/707.

**Comment by A-Hilaly** [comment]
Hello ! Can work on this ? @c-knowles

**Comment by c-knowles** [comment]
@A-Hilaly sure, no rush on this one as it doesn’t block a rollout. Should be an easy fix.

**Comment by mumoshu** [comment]
Closing as resolved via #1360. Thanks for your supports.
