### ISSUE TITLE
Self hosted canal network doesn't work with kube2iam/kiam

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#1316]
Currently when self hosted network is enabled with canal, we configure kube2iam/kiam with network interface of `cni0` (since the `UseCalico` flag is ignored):

https://github.com/kubernetes-incubator/kube-aws/blob/master/core/controlplane/config/templates/cloud-config-controller#L4962-L4966
https://github.com/kubernetes-incubator/kube-aws/blob/master/core/controlplane/config/templates/cloud-config-controller#L5356-L5360

However, this doesn't appear to work. It needs to be `cali+` for canal.

Probably we need it before https://github.com/kubernetes-incubator/kube-aws/pull/1309?

**Comment by davidmccormick** [comment]
Hi, we've not seen any issues with self-hosted canal + kiam in our hcom clusters. Let me have a look at one of our clusters and check which interface is being used.
