### ISSUE TITLE
Debugging documentation

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#1331]
I'd like to add some debugging documentation on our empty [Operator Guide](https://kubernetes-incubator.github.io/kube-aws/guides/operator-guide.html). I think it should include at least:

- How to check up on system components from a controller node
- How to use kubectl from a controller node against localhost
- How to run etcdctl from a etcd node against localhost

Any other suggestions?

**Comment by jorge07** [comment]
Rotate certs

**Comment by mumoshu** [comment]
How about "How to gather information about failed systemd units"?
