### ISSUE TITLE
Separate etcd stack does not work with managed subnet option

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#1332]
Using version 9c735f9485445699d598df5c07fc73c811f682d2, the new separate etcd stack seems to not work with managed subnet options:

```
generating assets for control-plane, etcd, network, pool-A, pool-B, pool-C, pool-S
Error: Error validating cluster: failed to validate etcd plane: invalid cloudformation stack template https://s3.amazonaws.com/BUCKET/k8s-dev-v9/kube-aws/clusters/k8s-dev-v9/exported/stacks/etcd/stack.json: ValidationError: Template format error: Unresolved resource dependencies [ManagedPrivateSubnetWithExistingNGW1RouteToNatGateway] in the Resources block of the template
	status code: 400, request id: a5b59285-60b4-11e8-80b0-c11be6d8f9e1
make: *** [kube-aws-up] Error 2
```

In the autoscaling group of `etcd/stack.json` stored in S3:
```
"DependsOn": ["ManagedPrivateSubnetWithExistingNGW1RouteToNatGateway", "Etcd0EIP", "Etcd0EBS"]
```

Relevant configuration:
```yaml
etcd:
  subnets:
    - name: ManagedPrivateSubnetWithExistingNGW1
    - name: ManagedPrivateSubnetWithExistingNGW2
    - name: ManagedPrivateSubnetWithExistingNGW3
```

Relevant source seems to be this bit, but not sure what an appropriate fix would be:
https://github.com/kubernetes-incubator/kube-aws/blob/c430955dd249bb9629f414ec34f81ee713028848/core/etcd/config/templates/stack-template.json#L449

Ref https://github.com/kubernetes-incubator/kube-aws/pull/1233

**Comment by mumoshu** [comment]
Thanks for the report! Probably we missed to pass those routes from the
network stack to the etcd stack?
Then you'd need to rewrite etcd cluster config in golang to refer the
routes by cross stack references.
2018年5月26日(土) 16:42 Chris Knowles <notifications@github.com>:

**Comment by c-knowles** [comment]
My current workaround is to remove `{{if $etcdInstance.DependencyExists}}{{$etcdInstance.DependencyRef}},{{end}}` from `etcd.json.tmpl` before updating the cluster. Not sure if that affects anything else but the cluster appears to still function ok.

**Comment by jcrugzz** [comment]
@c-knowles hmm tried this same work around and none of the successfully created auto scaling groups that are supposed to create instances in the private subnet seem to have done so... Trying to dig in on this in light of the CVE

**Comment by mumoshu** [comment]
@jcrugzz The CVE won't affect you if you have `--anonymous-auth=false` in your apiserver flags as can be seen in cloud-config-controller, jfyi.

https://github.com/kubernetes/kubernetes/issues/71411#issuecomment-443901666

**Comment by jcrugzz** [comment]
But to follow up on the issue I ran into. the deletion of the one line in `DependsOn` mentioned by @c-knowles worked correctly using kube-aws v0.11 with kubernetes 1.10.11 and the default coreos ami that came with that version but not v0.12 using kubernetes 1.11.5 and the latest stable coreos AMI

**Comment by jcrugzz** [comment]
@mumoshu it seems I am safe! Thanks for saving me a ton of work tonight

**Comment by c-knowles** [comment]
Another similar one, just run the quick start guide with latest master (init/render credentials/render stack/validate):
```
Error: failed to validate control plane: invalid cloudformation stack template https://s3.amazonaws.com/BUCKET/k8s-compare-v1/kube-aws/clusters/k8s-compare-v1/exported/stacks/control-plane/stack.json: ValidationError: Template format error: Unresolved resource dependencies [Subnet0] in the Resources block of the template
```

**Comment by flah00** [comment]
@mumoshu It seems like this bug is related to `model/subnets.go`, the function `ImportFromNetworkStack` calls `NewPrivateSubnetFromFn`. But the method makes no attempt to check if a natgw, route table, or eip are defined. So, the etcd stack can not correctly determine the type of dependency it may require.
