### ISSUE TITLE
Support non-external APIserver endpoint

### ISSUE THREAD

**Issue by trondhindenes** [kubernetes-incubator/kube-aws#1348]
kube-aws should allow an internal ELB for the kube-apiserver endpoint.

**Comment by mumoshu** [comment]
Hi! kube-aws does support it. Just set
`apiEndpoints[].loadBalancer.private` in your cluster.yaml and it should
work.
2018年6月2日(土) 19:25 Trond Hindenes <notifications@github.com>:

**Comment by mumoshu** [comment]
@trondhindenes Did my answer make sense to you?

**Comment by trondhindenes** [comment]
yes it does - I was just struggling to find it in the documentation - but I'm sure its there. Thanks for responding, closing this!
