### ISSUE TITLE
PSA for kube-aws users, skip CoreOS 1745.3.1 and 1745.4.0, go directly to 1745.5.0

### ISSUE THREAD

**Issue by whereisaaron** [kubernetes-incubator/kube-aws#1349]
CoreOS 1745.3.1 and 1745.4.0 include a [networkd bug](https://github.com/systemd/systemd/issues/9102#issuecomment-393147492) that causes problems for clusters with mixed instance types (e.g. T2 and M3/4/5). This is [fixed in 1745.5.0](https://github.com/coreos/bugs/issues/2443#issuecomment-393378968) (stable).

All the 'current' AWS instance types support jumbo frames (MTU = 9001). This is set via DHCP, however the `networkd` in these CoreOS versions fails to do that. This leaves the instances with their default MTU. While T2 instance support MTU=9001 they appear to default to MTU=1500. This leaves you with different nodes in the cluster with different MTUs.

Clients of TCP load balancers will get PMTU errors where they will think the PMTU is 8951 or 1500 when it is actually 1450. You'll tend to get MTU hangs or disconnections if connections heads to T2 worker nodes due to the incorrect MTU.

If you have T2 nodes for your control plane, if you upgrade to this versions (1745.3.1 and 1745.4.0) you'll likely see all your workers go to 'NotReady' and appear to stop reporting state to controllers via the API load balancer. In reality the controller MTU has suddenly gone from 9001 to 1500, and it takes a while for the load balancer and worker nodes to work this out. In my experience the workers should recover in about 10 minutes.

**Comment by jorge07** [comment]
Issues with container Linux releases happen quite often. I think we should have a blacklist to avoid others incur in the same problems.

**Comment by whereisaaron** [comment]
To be fair to Container Linux, the last two issues affecting `kube-aws` have both been 'sabotage' by upstream projects, in this case `systemd`, and in the previous (several!) cases by `docker`.

I do think `kube-aws` should not default to automatically upgrading instances on any `kube-aws update` but lock the versions on `kube-aws render/up` (I think maybe the current 0.10.0 version does that?). Though it could warn users a new version is available.

**Comment by jorge07** [comment]
@whereisaaron yes, you can follow the discussion here: #1209

**Comment by whereisaaron** [comment]
**Update:** If you do have clusters with 1745.3.1 and 1745.4.0 and T2 instances (or any other instance type that defaults to MTU=1500) I can report that you can upgrade the control plane to 1745.5.0 successfully. The `etcd` cluster does upgrade and stay healthy. However, you can expect all the API servers on the controllers to go down for ~20 minutes until the `etcd` upgrade completes and new controller instances take over and the API load balancer adapts to the new MTU.

At one stage I thought the new controllers were going to timeout getting started, which with `kube-aws` 0.9.9 would have rolled back through and undone the successful `etcd` upgrade 😢  (you can only change instance AMI version for the whole control plane as a monolith with 0.9.9, you can't update the AMI for the controller nodes and `etcd` nodes separately). So it is not without risk, but it did work, albeit with API server down time.

![image](https://user-images.githubusercontent.com/1109585/40925140-fe3809e6-67e6-11e8-99c0-a72c7a953a9f.png)

**Comment by mumoshu** [comment]
@whereisaaron @jorge07 I greatly appreciate you for sharing your findings.

Yes, a blacklist would be helpful for users who don't subscribe github issues for kube-aws.

Also, I'm such a perfectonist so that I can't help thinking about improving kube-aws not to be affected by this kind of upstream issues 🤔
Can we systematically postpone the etcd node roll if the apiserver got failed due to it?

**Comment by whereisaaron** [comment]
@mumoshu this is mostly all good. It was just a bit dicey that the time it took the controllers to accommodate to the MTU change was pretty close to the CF success signal signal timeout.

If the newer version of `kube-aws` lets us target either `etcd` or controllers for `kube-aws update` then this wouldn't have been a (potential) problem to deal with this upstream problem. And in my experience 'kube-aws update' did succeed, despite the upstream problems.
