### ISSUE TITLE
Kiam needs to be enabled to render the kube-system namespace manifest

### ISSUE THREAD

**Issue by jasonrichardsmith** [kubernetes-incubator/kube-aws#1353]
The kube-system namespace manifest is stuck in the kiam if statement.  if kiam is not enabled, then the manifest does not get rendered.
https://github.com/kubernetes-incubator/kube-aws/blob/master/core/controlplane/config/templates/cloud-config-controller#L5413-L5442

**Comment by mumoshu** [comment]
Good catch! We should extract it out.

**Comment by kiich** [comment]
Just curious - the `kube-system` namespace will still be created as far as I know and the mentioned manifest only gets applied if Kiam is also enabled at https://github.com/kubernetes-incubator/kube-aws/blob/master/core/controlplane/config/templates/cloud-config-controller#L922-L937 so is it not ok to create the manifest only when kiam is enabled anyways?

**Comment by kiich** [comment]
Ah but I see that we are indeed going to miss out on applying the labels set via `kubeSystemNamespaceLabels` at the moment so actually maybe it is still worht extracting it out afterall...
