### ISSUE TITLE
Metrics Server installation is missing required api flags

### ISSUE THREAD

**Issue by amoskyler** [kubernetes-incubator/kube-aws#1355]
It would seem that the current metrics server configuration is inadequate towards getting a fully operational metrics server up.

In order to enable the metrics server api flags must be set to configure the Kubernetes aggregation layer.

```
--requestheader-client-ca-file=<path to aggregator CA cert>
--requestheader-allowed-names=aggregator
--requestheader-extra-headers-prefix=X-Remote-Extra-
--requestheader-group-headers=X-Remote-Group
--requestheader-username-headers=X-Remote-User
--proxy-client-cert-file=<path to aggregator proxy cert>
--proxy-client-key-file=<path to aggregator proxy key>
```

None of these flags appear in `manifests/kube-apiserver.yaml` even when `metricsServer` is enabled in the cluster configuration.

Currently when I make requests against the metrics server I receive the following error:
```
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\".",
  "reason": "Forbidden",
  "details": {},
  "code": 403
```

Any confirmation that this is in fact an issue would be helpful - or if there's something missing that I should be adding to my kube-aws configuration. Otherwise this would appear to be a bug which should be fixed.

References:
- https://github.com/kubernetes-incubator/metrics-server/issues/35
- https://kubernetes.io/docs/tasks/access-kubernetes-api/configure-aggregation-layer/#enable-apiserver-flags and

**Comment by c-knowles** [comment]
https://github.com/kubernetes-incubator/kube-aws/issues/1136 appears related, but I think we should add first class support to enable the aggregation layer both manually and also automatically when it's needed such as with the metrics server.

**Comment by c-knowles** [comment]
@amoskyler I'm afraid the only way to achieve this with the latest kube-aws is patch the cloud config yourself or use the plugins as per the above issues.

@mumoshu is there some way to we could add this as a built in plugin?

**Comment by mumoshu** [comment]
@c-knowles Definitely yes. But would it be enough if `kube-aws render` output the plugin.yaml? Do we need to add a functionality to generate certs and keys used by metrics-server somehow?

**Comment by c-knowles** [comment]
@mumoshu yes we might have to, although hopefully that could be made available to all plugins or at least built in ones. Or use cert manager as per our other issues. I think this could be part of the same work as separating out some of the cloud config to separate files which I have some time to work on next.

**Comment by kevtaylor** [comment]
@c-knowles @mumoshu Have you actually made this work? We are struggling to get the HPA functioning and wondered if you/anyone else could impart some config wisdom.

**Comment by c-knowles** [comment]
@kevtaylor not yet as the last few times we tried the metrics server it entirely stopped our dev cluster from responding so we gave up for a while. I think those problems have since been fixed but this is one of the next things we'd like for HPA similar to your case.

**Comment by kevtaylor** [comment]
@c-knowles So, we did a bit of experimentation and got 'something' going to try and make sense of this
```
{{ if .Addons.MetricsServer.Enabled -}}
          - --requestheader-client-ca-file=/etc/kubernetes/ssl/ca.pem
          - --requestheader-extra-headers-prefix=X-Remote-Extra-
          - --requestheader-group-headers=X-Remote-Group
          - --requestheader-username-headers=X-Remote-User
          - --enable-aggregator-routing=false
          - --proxy-client-cert-file=/etc/kubernetes/ssl/worker-ca.pem
          - --proxy-client-key-file=/etc/kubernetes/ssl/worker-ca-key.pem
{{ end -}}
```
So here we left off the `--requestheader-allowed-names=aggregator` to allow any cn and used the worker ca as a proxy.

This will then allow `kubectl --v=9 get --raw /apis/metrics.k8s.io/v1beta1/namespaces/kev/pods`
and the hpa fires okay without the rbac issues. This is of course not ideal because it is a fairly open trust here, but at least demonstrates it working

So what we think is that we need to introduce/generate the separate aggregator ca/proxy certs which @davidmccormick is going to have a look at

Apologies, if this is duplicating any details in other issues, but thought worth sharing findings

**Comment by kevtaylor** [comment]
Also, we notice that the metrics-server is periodically dying with OOM - 200Mb is not enough for production servers
