### ISSUE TITLE
GPU support broken for NVidia 390.67 and CoreOS stable-1745.7.0

### ISSUE THREAD

**Issue by dulemars** [kubernetes-incubator/kube-aws#1371]
Hi,

I've ran into an issue with latest NVidia GPU drivers... CoreOS kernel is unable to load nvidia kernel module after building it, throwing an "unknown symbol" error.

Found source of an issue on some CoreOS discussion board, namely, kernel module ipmi_devintf must be loaded beforehand for this to work properly.

Managed to make an ugly hack to make it working but this should be fixed in NVidia setup scripts.

Here's my current workaround, add this to worker config:

      gpu:
        nvidia:
          enabled: true
          version: "390.67"
      customSystemdUnits:
        - name: nvidia-load-ipmi.service
          command: start
          enable: true
          content: |
            [Unit]
            Description=Load ipmi_devintf kernel module
            After=network.target

            [Service]
            Type=oneshot
            ExecStart=/usr/sbin/modprobe ipmi_devintf
            RemainAfterExit=true
            StandardOutput=journal

            [Install]
            WantedBy=multi-user.target

**Comment by mumoshu** [comment]
@dulemars Hey! Thank you so much for sharing your insight and the fix.
Do you have any specific link to relevant discussions about this in the board?
I was unable to find ones myself 😢

**Comment by dulemars** [comment]
Here's one

https://github.com/src-d/coreos-nvidia/issues/3
