### ISSUE TITLE
Cluster proportional autoscaler logtostderr flag removed

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#1395]
I believe `--logtostderr=true` may have been removed accidentally in https://github.com/kubernetes-incubator/kube-aws/pull/1345#pullrequestreview-135224092

**Comment by jorge07** [comment]
This can be closed: https://github.com/kubernetes-incubator/kube-aws/blob/master/builtin/files/userdata/cloud-config-controller#L3858

**Comment by davidmccormick** [comment]
Migrated to plugin
