### ISSUE TITLE
Enable API Aggregation Layer

### ISSUE THREAD

**Issue by ruigulala** [kubernetes-incubator/kube-aws#1430]
In the official documentation of enabling aggregation layer. The following three options were recommended.
https://kubernetes.io/docs/tasks/access-kubernetes-api/configure-aggregation-layer/

--requestheader-extra-headers-prefix=X-Remote-Extra-
--requestheader-group-headers=X-Remote-Group
--requestheader-username-headers=X-Remote-User

What's the purpose of these options? Are they really necessary?

**Comment by whereisaaron** [comment]
Hi @ruigulala see #1180 and #1355 for more info.

`kube-aws` can configure it for you, but only if you enable the metrics server feature (#1384).
