### ISSUE TITLE
Multiple controllers were created after some days.

### ISSUE THREAD

**Issue by nandakishorebhandari** [kubernetes-incubator/kube-aws#1431]
I have 3 node setup (1 Controller, 1 Worker & 1 Etcd).

After some days, I see I have 3 controllers instead of 1 controller.

Can someone let me know, How to get that count to 1 from 3 controllers

**Comment by mumoshu** [comment]
Hey! Perhaps you've manually updated the autoscaling group size to 3?

**Comment by mumoshu** [comment]
Anyway, I'd recommend you to manage number of controller nodes outside of `kube-aws`. That is, use awscli or aws console to modify the controller autoscaling group size. Set its `desired capacity` to `1` and you're done.

**Comment by mumoshu** [comment]
Please reopen if you have still difficulty doing this. Thanks for trying kube-aws.
