### ISSUE TITLE
Add a node annotation to disable scale down in autoscaler

### ISSUE THREAD

**Issue by wolstena** [kubernetes-incubator/kube-aws#1432]
Is there a way to disable the scale down for autoscaler. We would like to be able to do this manually via a scheduled job. 

I was unable to see a way to add the node annotation to do   ##so:
"cluster-autoscaler.kubernetes.io/scale-down-disabled": "true"

Cheers.

**Comment by Matei207** [comment]
Hiya @wolstena,

There was a recent [PR](https://github.com/kubernetes-incubator/kube-aws/pull/1422) that exposes `autoscaler` options in your cluster.yaml file. The options are stored in a map and then iterated over, it might be worthwhile to check it out and see if anything can be done. I'm quite sure if you want it disabled, you can find a flag/option to do so (off the top of my head there is a `scale-down-enabled:` flag).

If you want to do it dynamically, however, I know you can do so by using the dynamic configMaps (again, passed as a flag to your autoscaler). I've heard that's not viable and quite tricky to do however, so you may want to research it a little bit beforehand. 

Last but not least, you can do node annotations according to the [docs](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-prevent-cluster-autoscaler-from-scaling-down-a-particular-node) by interfacing directly with the API server, so you would have to do it via kubectl, e.g 
```
kubectl annotate node <nodename> cluster-autoscaler.kubernetes.io/scale-down-disabled=true
```
so I'm not sure why you weren't able to do it.  Let me know what your thoughts are!

**Comment by wolstena** [comment]
@Matei207 This PR looks fantastic and would solve our issue. I hope it is accepted. Currently, we have a cron job which sets the node annotation during our peak times. In off-peak times, we allow the nodes to scale back. This seems to be working fine for us. Initially, we were looking at how we could set the annotation as the nodes are provisioned. 

The scale down was causing problems for us with some pods  like our Jenkins master and Vault deployments. 

Jenkins is using persistent storage and when the pod is evicted there is a view minutes of down time. We could probably shorten this by tweaking our ELB settings but it is still a pain point.

We haven't setup an auto unseal process on the Vault servers. When the pods our moved they come up sealed. Before we automate the unsealing, we want to setup kube2iam first so we can store our unseal tokens securely in KMS. In the mean time, we don't want them to be evicted. 

On our deployments where we didn't want the pods to be evicted, we tried setting: 

“cluster-autoscaler.kubernetes.io/safe-to-evict”: “false”

This didn't seem to help. We are running k8s 1.9.3. 

Thanks @Matei207! This answers our question.
