### ISSUE TITLE
Unable to connect to the server: x509: certificate is valid for *

### ISSUE THREAD

**Issue by lunchboxav** [kubernetes-incubator/kube-aws#1435]
Hi all,

I tried kube-aws to provision a k8 cluster in AWS. I think I've set up everything properly and the cluster has already up. However, when I tried to do `kubectl --kubeconfig=kubeconfig get nodes` I got the response

`Unable to connect to the server: x509: certificate is valid for *, not kube.mydomain.net`

I've setup kube.mydomain.net as my external dns name. It's also hosted in Route 53. I've checked that that record is already there in my hosted zone, which seems to be pointing to my ELB endpoint. 

Question is, how should I resolve that issue? Is there anyway to update the DNS record if that;s the case? Or is there anything wrong about my DNS or Route 53 configurations?

Thanks

**Comment by mumoshu** [comment]
@lunchboxav Hey!

That error seems to indicate that you have wrong tls cert used server side. How did you create the cert? Are you sure you used `kube-aws render credentials` to generate certs?
