### ISSUE TITLE
What is kube-aws version 2e74b0722ee7967dd56e76fbb3fff7f59af7173a?

### ISSUE THREAD

**Issue by whereisaaron** [kubernetes-incubator/kube-aws#1436]
Hi, I save the `kube-aws` release in each clusters' git repo so I always use the matching version with the matching cluster.

One cluster is based on `kube-aws 0.9.9` and k8s 1.8.x. But I have stored a patched version of `kube-aws 0.9.9` with a commit version:
```
$ ./kube-aws version
kube-aws version 2e74b0722ee7967dd56e76fbb3fff7f59af7173a
```
Sadly I failed to document how this version is patched. But I think it was something important. So I came here to find the commit and see what the changes are. But somehow I can't find the commit in the repository? How can I track down the providence of this version? Anyone remember an important patch to 0.9.9? The 0.9.9 release came out Dec 8, and I think the patch is from early April.

**Comment by redbaron** [comment]
Probably that was something you cherry-picked. Do you have a git repo you normally work with, does it have that commit id?

**Comment by cmcconnell1** [comment]
This made me curious as we can have similar issues.  Curious if you still have your local git branch that you were working from that was patched?  If so, could compare that branch against the tagged v0.9.9?
I am pretty familiar with gitflow and other common models but not so much with _git patch workflows_.  
I had to read up on them and on that note--curious if anything here might be helpful?:
[git patch workflows](https://mindmajix.com/patch-workflows-git)
