### ISSUE TITLE
kube-dns, kube-dns-autoscaler, heapster stuck in pending

### ISSUE THREAD

**Issue by nlarzon** [kubernetes-incubator/kube-aws#1439]
Hi,
I deployed a new cluster with latest kube-aws version v0.10.2 
`
kube-system   kube-dns-autoscaler-c895d6bbd-7h79n                          0/1       Pending   0          1h
kube-system   kube-dns-d87fdd65-wqlnn                                               0/3       Pending   0          1h
kube-system   kube-proxy-gcfwc                                                            1/1       Running   1          1h
`
Is stuck in pending state.
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  4m (x291 over 1h)  default-scheduler  0/2 nodes are available: 2 PodToleratesNodeTaints.

Nodes:
NAME                                          STATUS    ROLES     AGE       VERSION
ip-10-0-0-237.eu-west-1.compute.internal   Ready     master    1h        v1.9.3
ip-10-0-0-44.eu-west-1.compute.internal    Ready     master    1h        v1.9.3

Anyone else with a similar issue? I have read about kube-dns failing because a network subsystem like calico or flannel not in place but it comes out-of-the-box here, correct?

Appreciate all help.

**Comment by davidmccormick** [comment]
Hi, I think the best course of action is to determine why the nodes are not ready. Am I right that there are only 2 if them - is that one controller and one node - that’s not many, what instance type are they?  Can you do a kubectl -n kube-system get pods -o wide and paste the result?  Thanks

**Comment by nlarzon** [comment]
Hi David,

The cluster is 2 controllers, 3 etcd, and 3 workers. I can't explain why the workers doesn't show they are alive and healthy in aws console.
`
$ kubectl -n kube-system get pods -o wide
NAME                                                                  READY     STATUS    RESTARTS   AGE       IP           NODE                                          NOMINATED NODE
heapster-7646ffb865-gz77q                                             0/2       Pending   0          11h       <none>       <none>                                        <none>
kube-apiserver-ip-10-0-0-237.eu-west-1.compute.internal            1/1       Running   0          12h       10.0.0.237   ip-10-0-0-237.eu-west-1.compute.internal   <none>
kube-apiserver-ip-10-0-0-44.eu-west-1.compute.internal             1/1       Running   1          12h       10.0.0.44    ip-10-0-0-44.eu-west-1.compute.internal    <none>
kube-controller-manager-ip-10-0-0-237.eu-west-1.compute.internal   1/1       Running   0          11h       10.0.0.237   ip-10-0-0-237.eu-west-1.compute.internal   <none>
kube-controller-manager-ip-10-0-0-44.eu-west-1.compute.internal    1/1       Running   1          11h       10.0.0.44    ip-10-0-0-44.eu-west-1.compute.internal    <none>
kube-dns-autoscaler-c895d6bbd-7h79n                                   0/1       Pending   0          12h       <none>       <none>                                        <none>
kube-dns-d87fdd65-wqlnn                                               0/3       Pending   0          12h       <none>       <none>                                        <none>
kube-proxy-gcfwc                                                      1/1       Running   1          12h       10.0.0.44    ip-10-0-0-44.eu-west-1.compute.internal    <none>
kube-proxy-hrk2v                                                      1/1       Running   0          11h       10.0.0.237   ip-10-0-0-237.eu-west-1.compute.internal   <none>
kube-scheduler-ip-10-0-0-237.eu-west-1.compute.internal            1/1       Running   0          11h       10.0.0.237   ip-10-0-0-237.eu-west-1.compute.internal   <none>
kube-scheduler-ip-10-0-0-44.eu-west-1.compute.internal             1/1       Running   1          11h       10.0.0.44    ip-10-0-0-44.eu-west-1.compute.internal    <none>
kubernetes-dashboard-54854b5c98-q87k7                                 1/1       Running   0          12h       10.2.21.2    ip-10-0-0-237.eu-west-1.compute.internal   <none>
tiller-deploy-54df45d89c-brlvb   
`

**Comment by davidmccormick** [comment]
Hi, if you do a kubectl describe pod on heapster - what does it say for the reason for being 'pending'.  Also you didn't say what instance types you are using?

**Comment by nlarzon** [comment]
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  31s (x3248 over 15h)  default-scheduler  0/2 nodes are available: 2 PodToleratesNodeTaints.

Workers: m3.medium
Others: t2.medium

**Comment by davidmccormick** [comment]
Ok thanks - I don't see any networking daemons running.
Can you journalctl the install-kube-system systemd unit and post any errors you see in there?  Note, it will be retrying so might have lots of logs, just look at the last one.

**Comment by nlarzon** [comment]
[logs_kube.txt](https://github.com/kubernetes-incubator/kube-aws/files/2347972/logs_kube.txt)
Not 100% what you are asking for, added printout of systemctl

**Comment by davidmccormick** [comment]
Hi to look at the kubelet logs:-

`journalctl -lu kubelet`
can you also try...
`journalctl -lu flannel`

**Comment by nlarzon** [comment]
- Logs begin at Mon 2018-09-03 16:39:05 UTC, end at Tue 2018-09-04 09:32:25 UTC. --
Sep 03 16:40:03 ip-10-0-0-41.eu-west-1.compute.internal systemd[1]: Starting kubelet.service...
Sep 03 16:40:03 ip-10-0-0-41.eu-west-1.compute.internal systemd[1]: kubelet.service: Control process exited, code=exited status=3
Sep 03 16:40:03 ip-10-0-0-41.eu-west-1.compute.internal systemd[1]: kubelet.service: Failed with result 'exit-code'.
Sep 03 16:40:03 ip-10-0-0-41.eu-west-1.compute.internal systemd[1]: Failed to start kubelet.service.
Sep 03 16:40:13 ip-10-0-0-41.eu-west-1.compute.internal systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Sep 03 16:40:13 ip-10-0-0-41.eu-west-1.compute.internal systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 1.
Sep 03 16:40:13 ip-10-0-0-41.eu-west-1.compute.internal systemd[1]: Stopped kubelet.service.
Sep 03 16:40:13 ip-10-0-0-41.eu-west-1.compute.internal systemd[1]: Starting kubelet.service...
Sep 03 16:40:13 ip-10-0-0-41.eu-west-1.compute.internal systemd[1]: kubelet.service: Control process exited, code=exited status=3
Sep 03 16:40:13 ip-10-0-0-41.eu-west-1.compute.internal systemd[1]: kubelet.service: Failed with result 'exit-code'.
Sep 03 16:40:13 ip-10-0-0-41.eu-west-1.compute.internal systemd[1]: Failed to start kubelet.service.
Sep 03 16:40:24 ip-10-0-0-41.eu-west-1.compute.internal systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Sep 03 16:40:24 ip-10-0-0-41.eu-west-1.compute.internal systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 2.
Sep 03 16:40:24 ip-10-0-0-41.eu-west-1.compute.internal systemd[1]: Stopped kubelet.service.
Sep 03 16:40:24 ip-10-0-0-41.eu-west-1.compute.internal systemd[1]: Starting kubelet.service...
Sep 03 16:40:24 ip-10-0-0-41.eu-west-1.compute.internal etcdctl[1365]: member 37c4ec6892d2f8c3 is healthy: got healthy result from https://ec2-18-195-98-99.eu-west-1.compute.amazonaws>
Sep 03 16:40:24 ip-10-0-0-41.eu-west-1.compute.internal etcdctl[1365]: member 68cf0b0e4a38d84d is healthy: got healthy result from https://ec2-18-197-190-74.eu-west-1.compute.amazonaw>
Sep 03 16:40:24 ip-10-0-0-41.eu-west-1.compute.internal etcdctl[1365]: member 9714ee7ecd020561 is healthy: got healthy result from https://ec2-52-28-71-19.eu-west-1.compute.amazonaws.>
Sep 03 16:40:24 ip-10-0-0-41.eu-west-1.compute.internal etcdctl[1365]: cluster is healthy
Sep 03 16:40:24 ip-10-0-0-41.eu-west-1.compute.internal etcdctl[1386]: member 37c4ec6892d2f8c3 is healthy: got healthy result from https://ec2-18-195-98-99.eu-west-1.compute.amazonaws>
Sep 03 16:40:24 ip-10-0-0-41.eu-west-1.compute.internal etcdctl[1386]: member 68cf0b0e4a38d84d is healthy: got healthy result from https://ec2-18-197-190-74.eu-west-1.compute.amazonaw>
Sep 03 16:40:24 ip-10-0-0-41.eu-west-1.compute.internal etcdctl[1386]: member 9714ee7ecd020561 is healthy: got healthy result from https://ec2-52-28-71-19.eu-west-1.compute.amazonaws.>
Sep 03 16:40:24 ip-10-0-0-41.eu-west-1.compute.internal etcdctl[1386]: cluster is healthy
Sep 03 16:40:25 ip-10-0-0-41.eu-west-1.compute.internal docker[1393]: Unable to find image 'k8s.gcr.io/hyperkube-amd64:v1.9.3' locally
Sep 03 16:40:25 ip-10-0-0-41.eu-west-1.compute.internal docker[1393]: v1.9.3: Pulling from hyperkube-amd64
Sep 03 16:40:25 ip-10-0-0-41.eu-west-1.compute.internal docker[1393]: d0c199d1a37e: Pulling fs layer
Sep 03 16:40:25 ip-10-0-0-41.eu-west-1.compute.internal docker[1393]: 9eea4969cc0f: Pulling fs layer
Sep 03 16:40:25 ip-10-0-0-41.eu-west-1.compute.internal docker[1393]: e25b982f4e4f: Pulling fs layer
Sep 03 16:40:25 ip-10-0-0-41.eu-west-1.compute.internal docker[1393]: 39668194e1b9: Pulling fs layer
Sep 03 16:40:25 ip-10-0-0-41.eu-west-1.compute.internal docker[1393]: 259521fecfa9: Pulling fs layer
Sep 03 16:40:25 ip-10-0-0-41.eu-west-1.compute.internal docker[1393]: 7c5dab2ec3a4: Pulling fs layer
Sep 03 16:40:25 ip-10-0-0-41.eu-west-1.compute.internal docker[1393]: 68ed866f0168: Pulling fs layer
Sep 03 16:40:25 ip-10-0-0-41.eu-west-1.compute.internal docker[1393]: d9eba7cd004a: Pulling fs layer
Sep 03 16:40:25 ip-10-0-0-41.eu-west-1.compute.internal docker[1393]: 39668194e1b9: Waiting
Sep 03 16:40:25 ip-10-0-0-41.eu-west-1.compute.internal docker[1393]: 259521fecfa9: Waiting
Sep 03 16:40:25 ip-10-0-0-41.eu-west-1.compute.internal docker[1393]: 7c5dab2ec3a4: Waiting
Sep 03 16:40:25 ip-10-0-0-41.eu-west-1.compute.internal docker[1393]: 68ed866f0168: Waiting
Sep 03 16:40:25 ip-10-0-0-41.eu-west-1.compute.internal docker[1393]: d9eba7cd004a: Waiting
Sep 03 16:40:25 ip-10-0-0-41.eu-west-1.compute.internal docker[1393]: 9eea4969cc0f: Verifying Ch

core@ip-10-0-0-41 ~ $ journalctl -lu flannel
-- Logs begin at Mon 2018-09-03 16:39:05 UTC, end at Tue 2018-09-04 09:33:13 UTC. --
-- No entries --

**Comment by nlarzon** [comment]
Very short :(
journalctl -lu install-kube-system
-- Logs begin at Mon 2018-09-03 16:39:05 UTC, end at Tue 2018-09-04 09:45:03 UTC. --
-- No entries --

**Comment by davidmccormick** [comment]
Apologies - you need to run `journalctl -lu install-kube-system` on one of your controllers.

**Comment by davidmccormick** [comment]
Thanks, that looks ok and so I'm guessing you are using the coreos flanneld for your networking.
Please post files for 
`journalctl -lu kubelet`
`journalctl -lu flanneld`

from one of your nodes  - ta.

**Comment by davidmccormick** [comment]
hi those *controller* logs are good - can you do the same for a worker?

**Comment by nlarzon** [comment]
[journalctl-lu-kubelet-worker.txt](https://github.com/kubernetes-incubator/kube-aws/files/2349245/journalctl-lu-kubelet-worker.txt)
[journalctl-lu-flanneld-worker.txt](https://github.com/kubernetes-incubator/kube-aws/files/2349246/journalctl-lu-flanneld-worker.txt)
Thanks David!

**Comment by nlarzon** [comment]
Hi David,

I have solved the issue thanks for the great help!

I had a faulty CIDR range on apiAccessAllowedSourceCIDRs

//Niklas
