### ISSUE TITLE
kube-aws fail to upgrade Kubernetes version

### ISSUE THREAD

**Issue by devdemos** [kubernetes-incubator/kube-aws#1444]
Hi looking for help with upgrading K8s with Kube-aws, I currently have a 1.9.3 cluster, and trying to upgrade to the latest version. 
I pull down the latest version of kube-aws and add my original cluster.yaml used to bring up the 1.9.3 config. I then render the stack and run kube-aws update. However the cluster does not update to 1.10.x. What could i be doing wrong or missing

**Comment by mumoshu** [comment]
Thanks. What's your kube-aws version and `kubernetesVersion` in cluster.yaml? Those two affects which kubernetes version you chose.

**Comment by devdemos** [comment]
kube-aws version
kube-aws version v0.10.2

 cat cluster.yaml | grep kubernetesVersion
# kubernetesVersion: v1.9.3

As you can see the second value is commented out, and I did not have this vale when I set up the cluster with 1.9.3. 
Could this be my issue

**Comment by mumoshu** [comment]
Ah! Sorry you have to build kube-aws from master in order to use v1.10.x. I forgot that v0.10.2 was still at k8s v1.9.x due to that I deploy k8s clusters from the master myself.

I'm planning to release kube-aws v0.11.0 with k8s 1.10.x. So you can also wait for the upcoming release.
