### ISSUE TITLE
v0.11 fails at controller creation with encryptionAtRest enabled

### ISSUE THREAD

**Issue by edalford11** [kubernetes-incubator/kube-aws#1450]
When kubernetes.encryptionAtRest.enabled is true, the cluster fails at the controller creation phase.

After taking a look at the `cloud-config-controller`, looks like theres a missing equals sign at
```
--experimental-encryption-provider-config /etc/kubernetes/additional-configs/encryption-config.yaml
```

I thought putting in that equals sign might have fixed it but I was still unable to make it work. I am successfully able to spin up a new cluster with encryptionAtRest disabled.

**Comment by mumoshu** [comment]
@edalford11 Hey. Thanks for the report! I just noticed that, too.

The issue is two-fold. One is, as you pointed out, we need `=` between the flag name and value. Another one is that your encryption config becoming empty:

```
I0926 23:43:01.280609       1 server.go:135] Version: v1.10.5
I0926 23:43:01.280697       1 server.go:724] external host was not specified, using 10.0.0.180
error while parsing encryption provider configuration file "/etc/kubernetes/additional-configs/encryption-config.yaml": invalid configuration file, missing Kind
```

```
e@ip-10-0-0-180 ~ $ sudo /opt/bin/decrypt-assets
[  802.043705] awscli[6]: decrypting assets
[  802.044165] awscli[6]: decrypting /etc/kubernetes/ssl/apiserver-key.pem.enc
[  802.457367] awscli[6]: decrypting /etc/kubernetes/ssl/etcd-client-key.pem.enc
[  802.853864] awscli[6]: decrypting /etc/kubernetes/ssl/kube-controller-manager-key.pem.enc
[  803.239312] awscli[6]: decrypting /etc/kubernetes/ssl/kube-scheduler-key.pem.enc
[  803.623096] awscli[6]: decrypting /etc/kubernetes/ssl/service-account-key.pem.enc
[  804.023742] awscli[6]: decrypting /etc/kubernetes/ssl/worker-ca-key.pem.enc
[  804.419102] awscli[6]: decrypting /etc/kubernetes/ssl/kiam/agent-key.pem.enc
[  804.802244] awscli[6]: decrypting /etc/kubernetes/ssl/kiam/server-key.pem.enc
[  805.201147] awscli[6]: decrypting /etc/kubernetes/additional-configs/encryption-config.yaml.enc
[  805.559559] awscli[6]: An error occurred (InvalidCiphertextException) when calling the Decrypt operation:
[  805.583739] awscli[6]: decrypting /etc/kubernetes/auth/kubelet-tls-bootstrap-token.tmp.enc
[  805.968921] awscli[6]: generating /etc/kubernetes/auth/tokens.csv
[  805.970509] awscli[6]: done.
"c697055e-6b79-4bf9-838c-a12f1db24f87"
```

This seems like an issue in assets encryption/decryption, introduced by perhaps my merge mistake. I'll investigate a bit deeper.

**Comment by mumoshu** [comment]
Okay so this is breaking so badly:

```
master|kubeaws1 core@ip-10-0-0-56 ~ $ docker logs a1351d38bcdb
Flag --admission-control has been deprecated, Use --enable-admission-plugins or --disable-admission-plugins instead. Will be removed in a future version.
I0927 00:10:50.261126       1 server.go:135] Version: v1.10.5
I0927 00:10:50.261244       1 server.go:724] external host was not specified, using 10.0.0.56
error while parsing encryption provider configuration file "/etc/kubernetes/additional-configs/encryption-config.yaml": error while creating cipher for named key default: crypto/aes: invalid key size 256
```

**Comment by mumoshu** [comment]
So the key length seems wrong. It should be 32 bytes long rather than 256.

https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#providers

**Comment by VinceMD** [comment]
So this fix is not available yet in https://github.com/kubernetes-incubator/kube-aws/releases/tag/v0.11.0? 
Should I disable encryptionAtRest until next version of kube-aws?

**Comment by davidmccormick** [comment]
This could be 0.11.1 release

**Comment by VinceMD** [comment]
So I downloaded the 0.12 and then did:
```
kube-aws render stack
kube-aws apply
```

My 3 etcd instances are replaced ok. But the controller fails to start with this error from the api docker:

```Error: error while parsing encryption provider configuration file "/etc/kubernetes/additional-configs/encryption-config.yaml": error while creating cipher for named key default: crypto/aes: invalid key size 256```

Am I missing a step for updating?
