### ISSUE TITLE
kube-aws apply deleted by mistake SecurityGroupEtcdIngressFromWorkerToEtcd for Prometheus

### ISSUE THREAD

**Issue by VinceMD** [kubernetes-incubator/kube-aws#1483]
I upgraded kube-aws from v0.11.1 to v0.12.
After downloading I did:

```
kube-aws render stack
kube-aws apply
```

I'm running prometheus operator. After the upgrade my Prometheus target page says it can't reach etcd endpoint. I checked my etcd security group and one inbound has been removed: 2379 from the workers. Prometheus is setup on a worker node.

My setting in cluster.yaml

```
  # When set to true this configures security groups for prometheus between nodes.
  # This includes the following ports: 10252, 10251, 10250, 9100, and 4194
  prometheus:
    securityGroupsEnabled: true
```

In the cloud formation log, I see that the Network stack has had a change:

DELETE_IN_PROGRESS       SecurityGroupEtcdIngressFromWorkerToEtcd

Why did my kube-aws apply went on removing SecurityGroupEtcdIngressFromWorkerToEtcd?

**Comment by mumoshu** [comment]
Hey!

I understand `SecurityGroupEtcdIngressFromWorkerToEtcd` was there to provide flannel on worker nodes to access etcd.

What you might need is either(or both?) 2379 and 2380 open to allow your Prometheus pods to poll etcd on etcd nodes? 

It might require the `prometheus.securityGroupsEnabled` feature to be enchanced to also open up the etcd port(s).

**Comment by VinceMD** [comment]
good finding!

correct . My prometheus operator setup only needs etcd 2379 but other people know better Etcd and its metrics

**Comment by paalkr** [comment]
Can we reopen this issue? It will make monitoring of etcd easier to solve the problem and add support for workers to access etcd on port 2379
