### ISSUE TITLE
Template format error: Unresolved resource dependencies [SubnetPrivate1cRouteToNatGateway] in the Resources block of the template

### ISSUE THREAD

**Issue by cosckoya** [kubernetes-incubator/kube-aws#1496]
Hello everyone,

I have a problem trying to deploy a Multi-AZ cluster with kube-aws v0.11.1 and v0.12.0.
getting the same error on each "kube-aws validate" run:
```
$ kube-aws validate

Validating UserData and stack template...
generating assets for control-plane, etcd, network, worker, monitoring
Error: failed to validate etcd plane: invalid cloudformation stack template https://s3.amazonaws.com/cosckoya.lab/config/kube-aws/clusters/mylab/exported/stacks/etcd/stack.json: ValidationError: Template format error: Unresolved resource dependencies [Subpriv1cRouteToNatGateway] in the Resources block of the template
	status code: 400, request id: 4e7bf6f5-ecb6-11e8-8ac3-nohaypatatasfritas
```

This is my private subnet definition:
```
[...]
  - name: subpriv1c
    private: true
    availabilityZone: us-east-1c
    instanceCIDR: "10.0.2.0/24"
    natGateway:
      eipAllocationId: eipalloc-XXX
```
Any ideas?

Thanks! :)

**Comment by c-knowles** [comment]
Looks quite similar to https://github.com/kubernetes-incubator/kube-aws/issues/1332, different resource but still. I ended up removing the dep from the generated CF template and then it worked but the template generated from source as of latest master still does not work.

**Comment by cosckoya** [comment]
@c-knowles yep. I have read some othe related issues: #1488 #1494 ... I've made a workaround too, generating the aws network resources by hand; VPC, NGW, EIP, Subnet, RouteTables and ELB.Then adding the VPC, ELB and SubnetIDs into the yaml, takes time but it's not hard work.

I've manage to deploy the ec2 instances paired to their network resources. Im still with it, trying with kube-aws v0.12.0.

**Comment by cosckoya** [comment]
Oh my! I was able to deploy Etcd EC2 instances and that's all. No master, no worker, no game :S

**Comment by cosckoya** [comment]
I've managed to deploy a MultiAZ cluster with 3 NGW & 1 IGW with kube-aws v0.9.9 (+hotfix).

Cheers!
