### ISSUE TITLE
New AWS autoscaling groups

### ISSUE THREAD

**Issue by sander-su** [kubernetes-incubator/kube-aws#1500]
AWS recently introduced the option of using autoscalinggroups and combine multiple instances.
https://aws.amazon.com/blogs/aws/new-ec2-auto-scaling-groups-with-multiple-instance-types-purchase-options/

For us this would be a great feature. 

Is someone already working on this or should we create a PR?

**Comment by sander-su** [comment]
Ok, we got this working in a 0.12 branch.
See: https://github.com/koen92/kube-aws/commit/073e95c4902fef2e6b943467b43295520312bbbe

Nodepool now spins an asg with lanchtemplate and mixedInstance options.

@mumoshu is this something for 0.12 of does it go to master only?
What is the timeline for a 0.13 release?

**Comment by mumoshu** [comment]
@sander-su Hey!

Yes, this should go into the master because other versions are in the maintenance modeI and we usually accept only bug fixes and migration-related features only for the maintenance versions.

I think we have no specific blocker for the v0.13 release now

**Comment by sander-su** [comment]
Ok we'll make a PR for the 0.13 branch.
Give us a few days as 0.13 is new for us and it looks like it has a lot of changes.

**Comment by sander-su** [comment]
Pr merged
