### ISSUE TITLE
Allow Online File System Expansion in k8s 1.11+

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#1501]
https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/:

> Kubernetes v1.11 also introduces an alpha feature called online file system expansion. This feature enables file system expansion while a volume is still in-use by a pod. Because this feature is alpha, it requires enabling the feature gate, `ExpandInUsePersistentVolumes`. It is supported by the in-tree volume plugins GCE-PD, AWS-EBS, Cinder, and Ceph RBD. When this feature is enabled, pod referencing the resized volume do not need to be restarted. Instead, the file system will automatically be resized while in use as part of volume expansion. File system expansion does not happen until a pod references the resized volume, so if no pods referencing the volume are running file system expansion will not happen.

I think we apply these universally to the api server, scheduler, controller manager etc:

https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/ (for some reason kubelet lists `ExpandPersistentVolumes` but not `ExpandInUsePersistentVolumes` but that might be a docs issue.

e.g.
https://github.com/kubernetes-incubator/kube-aws/blob/dc29af458cd2677710f5cd9908bc1ad6019d779e/builtin/files/userdata/cloud-config-controller#L369
https://github.com/kubernetes-incubator/kube-aws/blob/dc29af458cd2677710f5cd9908bc1ad6019d779e/builtin/files/userdata/cloud-config-controller#L3126
https://github.com/kubernetes-incubator/kube-aws/blob/dc29af458cd2677710f5cd9908bc1ad6019d779e/builtin/files/userdata/cloud-config-worker#L379

**Comment by vjdhama** [comment]
@c-knowles I would like to pickup this issue, if not already picked up.

**Comment by c-knowles** [comment]
@vjdhama that'd be great!

**Comment by davidmccormick** [comment]
This sounds like it would be a great candidate for implementing via our plugin mechanism (a core plugin).
