### ISSUE TITLE
ELB certificate requirements

### ISSUE THREAD

**Issue by flah00** [kubernetes-incubator/kube-aws#1559]
My employer requires all public facing HTTP connections to be secured with certs issued by known CAs. They have flagged the kube-aws self-signed cert for the API endpoint as insecure. How can I protect the Kubernetes API end point with my wildcard cert/key pair? 

* I was thinking I could create my own ELB and terminate TLS there, but the api server is only listening on port 443
* I also considered replacing `credentials/apiserver*`
    *  If someone renders credentials my cert/key will be overwritten 

I'm on kube-aws 0.10.2, BTW.

**Comment by paalkr** [comment]
Why would you expose the API servers to the public Internet? I would strongly recommend to only expose the API servers to private subnets. And rather use a private gateway to setup a secure VPN tunnel from the on premise network to your AWS private subnets.
