### ISSUE TITLE
Issue with Kiam 2.8

### ISSUE THREAD

**Issue by edalford11** [kubernetes-incubator/kube-aws#1568]
Leaving this here for anyone running into the same issue I did with 12.3. Looks like there is a known issue with Kiam 2.8 here https://github.com/uswitch/kiam/issues/128. Bumping it down to 2.7 got it running again.

**Comment by mdgreenwald** [comment]
I wonder if kiam 3.0 would work?
[https://github.com/uswitch/kiam/releases/tag/v3.0](https://github.com/uswitch/kiam/releases/tag/v3.0)

**Comment by fams** [comment]
> I wonder if kiam 3.0 would work?
> https://github.com/uswitch/kiam/releases/tag/v3.0

Is it possible to use kiam 3 with kube-aws 0.12? The provisioner will create the new certificate format and new pod cmdline?
