### ISSUE TITLE
Fedora CoreOS Migration

### ISSUE THREAD

**Issue by mdgreenwald** [kubernetes-incubator/kube-aws#1577]
Hi!

I am merely curious as to the kube-aws team's thoughts on a migration to Fedora CoreOS? Is it planned? Or are you targeting a different OS altogether? Would you like help with that?

They state: "Meanwhile, we intend to maintain Container Linux at least into 2020, and for at least a year after Fedora CoreOS is available. In-place upgrades from Container Linux to Fedora CoreOS will not be possible, but we plan to provide tooling and documentation to make the transition as straightforward as we can." [[0]](https://coreos.com/blog/fedora-coreos-red-hat-coreos-and-future-container-linux)

The appear to be targeting a GA release for May 7th 2019 as of now, which would imply support for Container Linux through roughly May of 2020.

The release schedule can be found here: [https://fedoraproject.org/wiki/Releases/30/Schedule](https://fedoraproject.org/wiki/Releases/30/Schedule) OR here: [https://github.com/coreos/fedora-coreos-tracker/blob/master/ROADMAP.md](https://github.com/coreos/fedora-coreos-tracker/blob/master/ROADMAP.md)

The project website can be found here: [https://coreos.fedoraproject.org/](https://coreos.fedoraproject.org/)

Thank you!

**Comment by mumoshu** [comment]
@mdgreenwald Hey! Thanks for bringing this up.

I'm looking forward to the migration. I was mainly following https://github.com/coreos/fedora-coreos-tracker/issues/159, which shows no progress(?)

Can we, by any chance, expect the team to provide not just the distro but also a migration guide form Container Linux + Kubernetes users soon?

**Comment by mumoshu** [comment]
@mdgreenwald Hey! I've reread through the roadmap and it seems like what's being released as GA in May 2019 is Fedora 30, not Fedore CoreOS. Am I right?

**Comment by mdgreenwald** [comment]
@mumoshu You are correct! Apologies for my mistake. That being said, they updated the project website and released a preview: [https://getfedora.org/en/coreos/download/](https://getfedora.org/en/coreos/download/).
