### ISSUE TITLE
Why is the cluster-autoscaler cmd option gone in 0.14.X?

### ISSUE THREAD

**Issue by cw-sakamoto** [kubernetes-incubator/kube-aws#1594]
Thanks for maintenance for great products 🙂

I'm trying to try 0.14.0-rc1 right now, but cluster-autoscaler cmd option is gone.
https://github.com/kubernetes-incubator/kube-aws/blob/v0.14.x/builtin/files/plugins/cluster-autoscaler/manifests/deployment.yaml

This option is in 0.12.x. Can you confirm..?
https://github.com/kubernetes-incubator/kube-aws/blob/v0.12.x/core/root/config/templates/cluster.yaml#L1366

**Comment by davidmccormick** [comment]
The setting looks to be there in the controller-userdata file...

```
                    - ./cluster-autoscaler
                    - --v=4
                    - --stderrthreshold=info
                    - --cloud-provider=aws
                    - --skip-nodes-with-local-storage=false
                    - --skip-nodes-with-system-pods=false
                    - --expander=least-waste
                    - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,kubernetes.io/cluster/{{.ClusterName}}
                    {{- range $flag, $value := .Addons.ClusterAutoscaler.Options }}
                    - --{{ $flag }}={{ $value }}
                    {{- end }}
```

**Comment by davidmccormick** [comment]
It's also there in the addons options config...
```
type ClusterAutoscalerSupport struct {
	Enabled          bool              `yaml:"enabled"`
	Options          map[string]string `yaml:"options"`
	ComputeResources ComputeResources  `yaml:"resources"`
	UnknownKeys      `yaml:",inline"`
}
```

**Comment by davidmccormick** [comment]
Oh I see - right - you are comparing the new plugin to the old settings.  Both are still available so you can still use the old one.  It wouldn't be hard to add the setting to the plugin - do you care to raise a PR for it?

**Comment by cw-sakamoto** [comment]
> you are comparing the new plugin to the old settings.

Yes, I thought I was not able to use the old one...

>  Both are still available so you can still use the old one.

if old settings for cluster-autoscaler is available, so PR is unnecessary. Thank you for your consideration.
