### ISSUE TITLE
Failure in controller booting up - v0.14.0-rc1

### ISSUE THREAD

**Issue by leowmjw** [kubernetes-incubator/kube-aws#1604]
Was failing my previous attempt to upgrade from v0.13.1 to v0.14.0-rc1 so tried a fresh install; but it just got worse! Got a failure in controller in even booting up.

How to debug failure of the controller to start up?

Cloudformation does not show much ..
```
UPDATE_IN_PROGRESS | AWS::AutoScaling::AutoScalingGroup | Controllers | Failed to receive 2 resource signal(s) for the current batch. Each resource signal timeout is counted as a FAILURE.
```

**Comment by leowmjw** [comment]
Note that with the same cluster.yaml; at least the cluster boot up and i can run basic kubectl commands  (there had other problems like canal pod crash-looping)

**Comment by davidmccormick** [comment]
Hi, you would need to ssh onto the controllers and have a look at the state of their systemd units.  `install-kube-system` and `cfn-signal` are the two most important ones in debugging the progress of kube-aws boot.
