### ISSUE TITLE
[Question] Launch Template Name in v0.14.0-rc.2

### ISSUE THREAD

**Issue by cw-sakamoto** [kubernetes-incubator/kube-aws#1644]
I tried kube-aws v0.14.0-rc.2, the name of the launch template does not contain the cluster name and nodepool name, why is that? 
It was unnatural because the cluster name was included in launch configuration(clustername-nodepool).

 launch template : WorkersLT_zGS9Sdk5WQlJ

**Comment by paalkr** [comment]
This is because launch templates needs to be unique.
https://github.com/kubernetes-incubator/kube-aws/pull/1582

**Comment by paalkr** [comment]
Of course the name of the launch template could be defined as clustername-nodepoolname, the fix tried to address all scenarios. There is nothing that stops you from launching two clusters with the same name and the same worker pool names in an AWS region, and using the clustername-nodepoolname for launch templates would then break. Remember that the launch template name **must be unique pr region**, not pr zone or VPC.

**Comment by cw-sakamoto** [comment]
>Remember that the launch template name must be unique pr region, not pr zone or VPC.

I see, I understood.　Thanks for your comment!
