### ISSUE TITLE
cluster-autoscaler options not work in 0.14.X

### ISSUE THREAD

**Issue by cw-sakamoto** [kubernetes-incubator/kube-aws#1653]
I tried 0.14.X(this commit https://github.com/kubernetes-incubator/kube-aws/commit/8197201453e7cabdf0d30c7666da975bfa25c914),  deployment manifset of cluster-autoscaler was as follows.
```
      containers:
      - command:
        - ./cluster-autoscaler
        - --cloud-provider=aws
        - --namespace=kube-system
        - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,kubernetes.io/cluster/cwk8s114-test
        - --logtostderr=true
        - --stderrthreshold=info
        - --v=4
        - --skip-nodes-with-local-storage=false
        - --skip-nodes-with-system-pods=false
        - --expander=least-waste - --expendable-pods-priority-cutoff=-20
```
At https://github.com/kubernetes-incubator/kube-aws/blob/master/builtin/files/plugins/cluster-autoscaler/manifests/deployment.yaml#L32-L36, I feel that the gotemplate writing method is wrong, what do you think?

**Comment by cw-sakamoto** [comment]
It seems to work well with or without ```options``` if it is as follows.

```
            {{- if index .Values "options" }}
            {{ range $flag, $value := .Values.options }}
            - --{{ $flag }}={{ $value }}
            {{ end }}
            {{- end }}
```

**Comment by dominicgunn** [comment]
You're right, it looks as though the formatting might be a bit off. I'll take a look.
