### ISSUE TITLE
Suggestion/Proposal: Label nodes accordingly to their roles

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#170]
#147 introduced the `node.alpha.kubernetes.io/role=master` taint to restrict scheduling on controller nodes. It indeed support some use-cases like "dedicated nodes".

However,

* There's currently no way to schedule pods only to controllers
  * For example, adding a toleration to cancel the `node.alpha.kubernetes.io/role=master` doesn't mean pods are scheduled **only** to controller nodes but rather they **(are preferred to|can also) be scheduled to** controller nodes.
* There's currently no out of box way to query just worker nodes for e.g. administrative purpose
  * `kubelctl get no`, of course, shows all the nodes including controller and worker nodes.
  * `kubectl get no --selector "<appropriate label>"` could be used to query just worker nodes.
     * There's currently no well-known label assigned by default, though

I'd suggest:

* `kube-aws.coreos.com/role=master` for controller nodes
* `kube-aws.coreos.com/role=worker` for worker nodes
   * FYI, GKE seems to label worker nodes with `role=worker` by default
      * I'd rather like it namespaced after reading [an upstream issue regarding taints](https://github.com/kubernetes/kubernetes/issues/36272)

I'm not willing to use a namespace like `node.alpha.kubernetes.io` right now because I believe doing so may result in collision with **official** labels used widely among various kubernetes deployments in the future.

Also note that you can achieve this today for workers by editing `cluster.yaml`:

```
experimental:
  nodeLabels:
    kube-aws.coreos.com/role: worker
```

**Comment by mumoshu** [comment]
Please reopen if anyone is interested.

**Comment by yawboateng** [comment]
@mumoshu, is it possible to reopen this? It will be good to schedule pods dedicated to just the controllers, or at least be able to distinguish between master and worker nodes with kubectl

**Comment by mumoshu** [comment]
Sure!
I'd prefer `controller.nodeLabels` today though.

**Comment by mumoshu** [comment]
@yawboateng `experimental.nodeLabels` can be used to label only controller nodes as of today.
It will be renamed to `controller.nodeLabels` in the future though.
