### ISSUE TITLE
Blank line in /run/systemd/system/kubelet.service for controller

### ISSUE THREAD

**Issue by cndbain** [kubernetes-incubator/kube-aws#1711]
In both kube-aws versions 0.13.0 and 0.14.0 a check in cloud-config-controller seems to be leaving a blank line in the /run/systemd/system/kubelet.service file that's generated for my controllers:

```
{{ if checkVersion ">= 1.14" .K8sVer -}}
--bootstrap-kubeconfig=/etc/kubernetes/kubeconfig/worker-bootstrap.yaml \
{{- end }}
```

Which then causes the controllers to not be able to start the kubelet.service.

**Comment by davidmccormick** [comment]
Incorrect golang template whitespace chomping fixed
