### ISSUE TITLE
Kubernetes 1.16 support

### ISSUE THREAD

**Issue by tedmiston** [kubernetes-incubator/kube-aws#1734]
Kubernetes 1.16 (stable) was released yesterday.  I am wondering what are the first steps needed to be able to use it in kube-aws?

https://kubernetes.io/blog/2019/09/18/kubernetes-1-16-release-announcement/

https://github.com/kubernetes/kubernetes/releases/tag/v1.16.0

**Comment by davidmccormick** [comment]
You can start by putting `kubernetesVersion: v1.16.0` in your cluster.yaml and then try it.  It might work as-is but more than likely there will need to be some adjustments to some of the settings, command line options etc. to make it work.

We would, of course, welcome any work or PR which brings v0.16.0 compatibility to kube-aws so have a go!
