### ISSUE TITLE
IAMManagedPolicyController too permissive

### ISSUE THREAD

**Issue by flah00** [kubernetes-incubator/kube-aws#1804]
Our security team has flagged our kube-aws IAM policies as problematic, because all actions, on all resource, are permitted for ec2 and elastic load balancing. Is there an easy way to audit the calls made, so the actions can be scaled back to only those needed? 

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "ec2:*",
            "Resource": "*",
            "Effect": "Allow"
        },
        {
            "Action": "elasticloadbalancing:*",
            "Resource": "*",
            "Effect": "Allow"
        },
```

**Comment by gbs74** [comment]
I'm having the same problem, need urgent fix!

**Comment by arpad9** [comment]
watching
