### ISSUE TITLE
Roadmap update

### ISSUE THREAD

**Issue by jorge07** [kubernetes-incubator/kube-aws#1812]
It will be helpful to define a bit the direction in the roadmap for the new releases. Like in the changelog now says that versions will align with Kubernetes releases but then deal with breaking changes in versioning will be very difficult.

**Comment by davidmccormick** [comment]
The idea isn't to entirely align with kubernetes versions - just the major release number (ok not the 1 but the 13, 14, 15 etc)

**Comment by davidmccormick** [comment]
Bug fixes are put out with minor releases, e.g. 0.15.1
