### ISSUE TITLE
prometheusMetrics for clusterAutoscaler plugin [0.15]

### ISSUE THREAD

**Issue by sei-nicolas** [kubernetes-incubator/kube-aws#1825]
Using kube-aws release 0.15, it's not possible to create a cluster where:
- clusterAutoscaler plugin is enabled
- prometheusMetrics option of the plugin is enabled

Using kube-aws apply will hang while creating/initializing the controller instances with the following message: "Failed to set up mount unit: Invalid argument"

Internally (syslog of the instance being created), the error is the following:

- cmdLine: "/bin/bash /opt/bin/retry 10 /opt/bin/install-kube-system"
- message: "error parsing /srv/kube-aws/plugins/cluster-autoscaler/servicemonitor.yaml: error converting YAML to JSON: yaml: line 9: mapping values are not allowed in this context"

And indeed, in https://github.com/kubernetes-incubator/kube-aws/blob/master/builtin/files/plugins/cluster-autoscaler/manifests/servicemonitor.yaml line 10, there should be two spaces less at the beginning of the line.

However, fixing the template is not enough, it results in the same message from "kube-aws apply", and the instance syslog that time is:

- cmdLine: "/bin/bash /opt/bin/retry 10 /opt/bin/install-kube-system"
- message: "error: unable to recognize /srv/kube-aws/plugins/cluster-autoscaler/servicemonitor.yaml: no matches for kind ServiceMonitor in version monitoring.coreos.com/v1"

I think this is related with https://github.com/coreos/prometheus-operator/issues/1866#issuecomment-419191907 but the solution here is not clear.

**Comment by jorge07** [comment]
I'm not sure you can create a cluster with this service monitors enabled. As the cluster doesn't have prometheus operator installed the crd is missing and installation will fail if I'm not wrong. Try disabling the metrics, installing the operator and doing the cluster upgrade later
