### ISSUE TITLE
Coreos EOL

### ISSUE THREAD

**Issue by jorge07** [kubernetes-incubator/kube-aws#1831]
https://coreos.com/os/eol/

Since CoreOS will be dead the 1th of September, a replacement needs to be found.

**Comment by mumoshu** [comment]
This has been long on my radar but I'm not confident where we should go yet.

I see that they're generally recommending migrations to Fedora CoreOS and I once considered it's legitimate to migrate kube-aws to Fedora CoreOS. But I'm a bit skeptical if Fedora CoreOS is really production-ready at the moment, especially given there's no much time for it to be battle-tested before Container Linux reaches EOL.

Flatcar is also suggested as an alternative. But the point here is, AFAICS, it seems like mostly Container Linux with only trademark-related changes made. So, honestly speaking, I can't believe Flatcar could keep getting the same degree of patches and upgrades as it used to, after the upstream is dead.

So in the short term I don't think either of those two can be a "reliable" alternative to Container Linux from the perspective of a kube-aws maintainer. Fedore CoreOS does seem better to me. But I'd like to hear opinions from others.

**Comment by Fsero** [comment]
Giving that moving to Fedora CoreOS would mean dropping rkt, and hence move rkt pods in kube-aws to systemd-nspawn or other bootstrapping methods, would it make sense to move to Fedora instead of amazon linux or debian as base OS?

**Comment by jorge07** [comment]
Flatcar seems an easy replacement, keeping things quite similar to the current state. 
I'm 👍 to move to a Debian base image rather than Fedora CoreOS.

**Comment by davidmccormick** [comment]
It's going to be a significant piece of work and we are heavily invested in cloud-configuration as a system bootstrapper.  I prefer the sound of Fedora CoreOS just because I trust Fedora/Redhat to provide a solid distribution and am generally not inclined towards forks unless they have an ambitious roadmap planned.

**Comment by jorge07** [comment]
What about supporting both?
https://medium.com/@swade1987/upgrading-to-flatcar-linux-746751e89ab4

**Comment by davidmccormick** [comment]
Supporting two linux distributions sounds like a lot of work.  I propose that we get over the current end-of-life issues on out present v0.15.x branch by allowing a swap onto flatcar as a drop-in replacement for CoreOS.  Then, for the v0.16.x branch we could consider a move to another distribution entirely?  How does sound?  Selfishly, I'm interested in the possibility of spinning up mixed AMD64/ARM clusters (in the hope of saving power and doing our bit for the planet) and so I'd prefer to move a distribution that has good for support for both.

**Comment by mdgreenwald** [comment]
> Selfishly, I'm interested in the possibility of spinning up mixed AMD64/ARM clusters (in the hope of saving power and doing our bit for the planet) and so I'd prefer to move a distribution that has good for support for both.

For whatever its worth, it would be great to get ARM support. ➕💪🏻

**Comment by paalkr** [comment]
I don't have a strong opinion on what would be the best path forward, but I would just like to mention that company (https://geodata.no) that @andersosthus, @spohner and I work for have invested a lot in kube-aws. And we would like to contribute as much as possible to make sure kube-aws continue to be an active project.

**Comment by davidmccormick** [comment]
@paalkr that sounds great, we need all the help we can get.  I no longer work for a company supporting kube-aws so I don’t have the ability to contribute as much as before.  We need PRs to move the project forward:

* supporting the latest kubernetes releases
* adding useful plugins, e.g. ingress, log streaming, monitoring etc.
* other interesting features, such as mixed architecture clusters

**Comment by davidmccormick** [comment]
I have an ingress plugin in the works utilizing contour but it still needs some more work and a lot more testing

**Comment by paalkr** [comment]
I understand. We do not deploy any "functional" components like Ingress controllers, Prometheus, Cert-manager, Rook etc with kube-aws, and would probably not do so if possible either, even if there were plugins available. In my opinion there is a strong community behind most of these CNCF projects, and we would continue to deploy them using either, helm3, kustomiz or other tools that are maintained by the authors of the various tools we use in our clusters.

But the core infrastructure, like the Linux distro, Windows Worker Nodes https://github.com/kubernetes-incubator/kube-aws/issues/1546, IAM authentication and new versions of Kubernetes are the areas that in my opinion kube-aws should focus on, to being a clear alternative to ekscli and Kops.

**Comment by jorge07** [comment]
I agree with @paalkr, specially in maintain the k8s versions up to date. But I would like to see some plugins installation like Prometheus Operator as we're adding the monitoring objects as part of the plugins.

**Comment by dominicgunn** [comment]
FlatCar has been merged into v0.15.x, and v0.16.x.
