### ISSUE TITLE
Support Bottlerocket – Open Source OS for Container Hosting

### ISSUE THREAD

**Issue by qnapnickchang** [kubernetes-incubator/kube-aws#1839]
Hi, 

Do you have any plan to support Bottlerocket – Open Source OS for Container Hosting. 
https://aws.amazon.com/blogs/aws/bottlerocket-open-source-os-for-container-hosting/

**Comment by dominicgunn** [comment]
No on the immediate roadmap, we've just switched to Flatcar. If you'd like to see Bottlerocket we're open for contributions.
