### ISSUE TITLE
kube-aws apply/validate throws "ERROR: Bad template: apiVersion: v1"

### ISSUE THREAD

**Issue by faseyiks** [kubernetes-incubator/kube-aws#1840]
Hi guys
I am using this for the first time.I have followed the documentation and everything seems alright until "apply".  

Further errors are 
Error: failed to initialize control-plane stack: failed to load controller node extras from plugins: failed adding kubernetes manifests to controller: Failed to render plugin kubernetes manifest: failed to execute template: template: template:29:131: executing "template" at <insertTemplateFile .Values.tls.certificates.path.certPath .>: error calling insertTemplateFile: open credentials/dashboard.pem: no such file or directory

**Comment by dominicgunn** [comment]
Hey @faseyiks,

Do you happen to remember which version of `kube-aws` you was using?

**Comment by hbarrington** [comment]
I had this issue today using https://github.com/kubernetes-incubator/kube-aws/releases/tag/v0.16.0 and following the quick-start guide.

I solved it simply by disabling dashboard but for quick start you'd hope that everything would "just work" or that disabling it would be mentioned in the doc.

**Comment by flah00** [comment]
@dominicgunn 
I ran into this issue using 0.15.2. It seems that on the first pass, of a new cluster, `render credentials` cannot consider plugins.  To successfully render everything you have to render credentials, stack, and then credentials again.
