### ISSUE TITLE
Broken render credentials flag for apiserver aggregator key

### ISSUE THREAD

**Issue by mixecan** [kubernetes-incubator/kube-aws#1849]
Hi,
if I run `kube-aws render credentials --help` I get one flag without a name

```
    -- string        path to pem-encoded apiserver aggregator RSA key
```

The effect is that the `render` command replaces the apiserver aggregator key, even if I run 
```
kube-aws render credentials -- credentials/apiserver-aggregator-key.pem
```

**Comment by dominicgunn** [comment]
This should be resolved now, see the attached PR.
