### ISSUE TITLE
0.12.7 Release doesn't include latest feature in changelog

### ISSUE THREAD

**Issue by jorge07** [kubernetes-incubator/kube-aws#1865]
It points to
```
➜ ./kube-aws version
kube-aws version v0.12.x/0ea4367a
```

**Comment by dominicgunn** [comment]
Oh no! My apologies, I'll get this cleaned up tomorrow (I'm U.K. based).

**Comment by jorge07** [comment]
Don't worry @dominicgunn we're all humans

**Comment by dominicgunn** [comment]
I've updated the binaries @jorge07, sorry for the mistake :)

**Comment by jorge07** [comment]
Thanks a lot!
