### ISSUE TITLE
Migrate kube-aws to `node.kubernetes.io/role: control-plane` taint

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#1876]
See https://groups.google.com/forum/#!topic/kubernetes-sig-cluster-lifecycle/6HSVqGlyCrI

We currently use the old taint in the number of places:

- https://github.com/kubernetes-incubator/kube-aws/blob/1ffe330bdcbc43c3f2df4635b3eabfde271f3034/builtin/files/plugins/kiam/manifests/agent-daemonset.yaml#L42
- https://github.com/kubernetes-incubator/kube-aws/blob/bdeadab166e728dbcc130ac3124affc66cc4d682/pkg/api/bash_prompt.go#L33
- https://github.com/kubernetes-incubator/kube-aws/blob/1ffe330bdcbc43c3f2df4635b3eabfde271f3034/builtin/files/plugins/kiam/manifests/server-daemonset.yaml#L34
- https://github.com/kubernetes-incubator/kube-aws/blob/f6e39330006d111ce29222addde6dcec0986c308/builtin/files/plugins/dashboard/manifests/autoscaler.yaml#L50
- https://github.com/kubernetes-incubator/kube-aws/blob/062740bc02cbecc0dfaa58a7bc5936ea2d375918/builtin/files/plugins/dashboard/manifests/deployment.yaml#L86
- https://github.com/kubernetes-incubator/kube-aws/blob/2ed6d7dfc5a8fe3c10cc464fea2a0d2ac1b5bf45/builtin/files/userdata/cloud-config-controller#L387
- https://github.com/kubernetes-incubator/kube-aws/blob/062740bc02cbecc0dfaa58a7bc5936ea2d375918/builtin/files/stack-templates/control-plane.json.tmpl#L66
- https://github.com/kubernetes-incubator/kube-aws/blob/37775a7a9c5b9f06271fd42ea137b8dab98f386d/builtin/files/plugins/upgrade-helper/assets/upgrade-helper-pre.sh#L51
- https://github.com/kubernetes-incubator/kube-aws/blob/1ffe330bdcbc43c3f2df4635b3eabfde271f3034/builtin/files/plugins/aws-iam-authenticator/manifests/daemonset.yaml#L30
- https://github.com/kubernetes-incubator/kube-aws/blob/f6e39330006d111ce29222addde6dcec0986c308/builtin/files/plugins/dashboard/manifests/metrics-scraper.yaml#L38
- https://github.com/kubernetes-incubator/kube-aws/blob/1ffe330bdcbc43c3f2df4635b3eabfde271f3034/builtin/files/plugins/cluster-autoscaler/manifests/deployment.yaml#L65

**Comment by dominicgunn** [comment]
This could be a breaking change for users who might have sets that depend on being able to query by `role=master`. We should plan carefully around implementation here to avoid potential disruption to end-users.
