### ISSUE TITLE
How to pass CA authority certificate with generated certificates

### ISSUE THREAD

**Issue by mixecan** [kubernetes-incubator/kube-aws#1889]
I signed the ca.pem with my company's CA authority. The cluster runs without any problem but SSL requests to the api server fail due to a failure in SSL verification. Requests are performed using the certificate in the service account.
The failure is expected as neither the service account certificate nor the node/pod have the certificate of the CA authority and so are unable to verify the cert chain.

Is there a correct way to pass the authority cert to the cluster?
I was planning to append it to the ca.pem file (and update the cluster deployment) but when a run `kube-aws render credentials ...` the ca.pem file is cleaned of the authority certificated.

**Comment by dominicgunn** [comment]
Sorry it took a while to get back to you, if I'm understanding the question with would this work for you?
 
```
$ kube-aws render credentials --ca-cert-path=./credentials/ca.pem --ca-key-path=./credentials/ca-key.pem
--

**Comment by mixecan** [comment]
That is the command that I use to generate the cluster certificates.
But I choose to sign the cluster CA certificate with my company's CA authority and I missed to provide its public key to the cluster nodes. This results in a failure in SSL verification when performing requests to the cluster API form within a pod.

In fact if I run `curl -vI https://kubernetes` I get
```
*   Trying 10.3.0.1:443...
* Connected to kubernetes (10.3.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

How can I add our CA public key to the cluster nodes?
