### ISSUE TITLE
Render with password protected CA root key fails

### ISSUE THREAD

**Issue by leontebbens** [kubernetes-incubator/kube-aws#193]
Following https://coreos.com/kubernetes/docs/latest/kubernetes-on-aws-render.html I created my own CA key and certificate.
`kube-aws render credentials --ca-cert-path=/path/to/ca-cert.pem --ca-key-path=/path/to/ca-key.pem` displays invalid file error when ca-key.pem is password protected. 

Steps to reproduce:
1. Create CA key: `openssl genrsa -aes256 -out private/ca.key.pem 4096`
2. Create CA certificate: `openssl -key private/ca.key.pem -new -x509 -days 7300 -sha256 -extensions v3_ca -out certs/ca.cert.pem`
3. `kube-aws render credentials --ca-cert-path=/path/to/ca-cert.pem --ca-key-path=/path/to/ca-key.pem`

Password protecting IS highly recommended, so probably more users will run into this. At least the error message should say that the key file must NOT be password protected.

**Comment by mumoshu** [comment]
@leontebbens Thanks for the feedback 👍 

I'd definitely like to fix that.
Would you mind providing me your expectation on kube-aws's behavior to support password-protected keys?
Probably you'd like to protect all the keys with passwords? Then just adding a command-line flag like `--key-password` to kube-aws won't work but `--ca-key-password`, `--worker-key-password`, `controller-key-password` etc would work?

**Comment by leontebbens** [comment]
Indeed all key files are password protected for security reasons. But flags for each seems quite cumbersome and insecure (plaintext passwords on the commandline). I would except kube-aws to detect a pwd-protected file and then prompt me to enter the password. Would that be possible?

**Comment by mumoshu** [comment]
@leontebbens Thanks for your reply!

I'm ok with prompting for manual input when passwords are not provided.

On the other hand, regardless of that, I'd also like to provide way(s) to tell kube-aws which passwords to be used for automation. Do you have any idea/preference on how to do that? For example, do you think env vars like `KUBE_AWS_CA_KEY_PASSWORD` instead of command-line flags would be preferred?

**Comment by leontebbens** [comment]
Env vars seem even more insecure as the are long living. Not a good place for plaintext passwords.

**Comment by mumoshu** [comment]
@leontebbens Thanks for your comment!
Then, how about:

1. recommending users who wants to automate things in exchange of security to pass them via shell variables like `KUBE_AWS_CA_KEY_PASSWORD=... kube-aws up`?
Then, one can limit the lifetime of insecure plaintext passwords in a single `kube-aws up` run, which is better than env vars set via `export KUBE_AWS_CA_KEY_PASSWORD=...`.
2. recommending users who wants security the most to not automate `kube-aws up` and provide passwords manually via the prompt

**Comment by leontebbens** [comment]
Agree

**Comment by c-knowles** [comment]
We'd like to use this during an automated process. Was the switch above from command line flags to shell variables intended as a way of preventing the password from being logged/stored in shell history etc? Understand that putting it in a separate set of variables makes it logically separate from a user perspective, does it end up being much different from the perspective of security?

**Comment by mumoshu** [comment]
AFAIK, no; Using shell variables won't prevent passwords from being logged to the history and being visible from `/proc/<kube-aws's pid>/environ`. If someone could crack into `root` or the linux user kube-aws is run, I believe that he/she can still peak into plain-text passwords. If he/she could crack into `root`, prompting for user input is still vulnerable in my understanding though.

**Comment by leontebbens** [comment]
I think we should offer two options:
- a more secure one: prompt user for typing a password
- a less secure but automatable one: passwords in Shell variables
I see both options in other tools. I do not see often plain text passwords as command line params.

**Comment by mumoshu** [comment]
Thanks. I'll leave this open for pull request(s) 👍

**Comment by mumoshu** [comment]
@tomas-edwardsson I just saw your effort on this! Any chance you could submit a PR for this? 😄
