### ISSUE TITLE
eu-west-2 unsupported ?

### ISSUE THREAD

**Issue by martindanko** [kubernetes-incubator/kube-aws#198]
When attempting to provision a cluster in AWS **London** Region (_**eu-west-2**_) I keep getting the following error.

> Error: Failed to create config: failed getting AMI for config: could not find region eu-west-2 for channel stable

Is this region currently unsupported by **_kube-aws_**?

I can see on this page: https://coreos.com/os/docs/latest/booting-on-ec2.html - There doesn't appear to be an AMI for _**eu-west-2**_ 

Are there any plans to support this region? If not, will I be able to hack it by placing a copy of a CoreOS AMI into that region in my AWS account and manually changing the AMI in the generated CloudFormation config?

**Comment by pieterlange** [comment]
@colhom @aaronlevy Can you forward forward this to the right people? I think it just needs to be included in some ami build automation but can't be sure. :)

**Comment by martindanko** [comment]
@pieterlange - Thanks for the quick response, if this could included in the ami build automation soon(ish) it would be greatly appreciated.

**Comment by colhom** [comment]
cc @crawford

**Comment by crawford** [comment]
https://github.com/coreos/bugs/issues/1733

It'll be available in a few hours.

**Comment by martindanko** [comment]
Thanks very much @all.

**Comment by martindanko** [comment]
Hi all,

FYI

The default instance size: **m3.medium** doesn't appear to be available in the **eu-west-2** region for the **AWS::AutoScaling::LaunchConfiguration** for some strange reason.

Also it appears that only the beta channel was updated so one could not provision the stable channel in that region :-(

**Comment by martindanko** [comment]
Thanks @crawford - I can see it in the stable channel now. Which is handy as my cluster doesn't seem to want to provision correctly using the beta channel, the kube-aws-controller doesn't become healthy.

Would anyone know why despite setting **containerRuntime: docker** in the cluster.yaml file - on the **kube-aws-controller** nothing appears to be running in Docker?

**docker ps** and **docker ps -a** show no output. 

However, **rkt list** shows the following.

```
UUID            APP             IMAGE NAME                                      STATE           CREATED         STARTED         NETWORKS
0d7e37e1        hyperkube       quay.io/coreos/hyperkube:v1.5.1_coreos.0        exited garbage  21 minutes ago  21 minutes ago
10a5bf94        hyperkube       quay.io/coreos/hyperkube:v1.5.1_coreos.0        exited garbage  23 minutes ago  23 minutes ago
37c63bb0        hyperkube       quay.io/coreos/hyperkube:v1.5.1_coreos.0        exited garbage  24 minutes ago  24 minutes ago
3f7fbde6        hyperkube       quay.io/coreos/hyperkube:v1.5.1_coreos.0        exited garbage  23 minutes ago  23 minutes ago
51414ab0        hyperkube       quay.io/coreos/hyperkube:v1.5.1_coreos.0        exited garbage  22 minutes ago  22 minutes ago
518afc53        hyperkube       quay.io/coreos/hyperkube:v1.5.1_coreos.0        exited garbage  22 minutes ago  22 minutes ago
5329a77a        hyperkube       quay.io/coreos/hyperkube:v1.5.1_coreos.0        exited garbage  24 minutes ago  24 minutes ago
55c7a794        hyperkube       quay.io/coreos/hyperkube:v1.5.1_coreos.0        exited garbage  19 minutes ago  18 minutes ago
576c67c6        hyperkube       quay.io/coreos/hyperkube:v1.5.1_coreos.0        exited garbage  20 minutes ago  20 minutes ago
6d18f4d0        hyperkube       quay.io/coreos/hyperkube:v1.5.1_coreos.0        exited garbage  24 minutes ago  24 minutes ago
71e2386d        hyperkube       quay.io/coreos/hyperkube:v1.5.1_coreos.0        exited garbage  24 minutes ago  24 minutes ago
873db12b        hyperkube       quay.io/coreos/hyperkube:v1.5.1_coreos.0        exited garbage  23 minutes ago  23 minutes ago
9416b2e5        flannel         quay.io/coreos/flannel:v0.6.2                   exited garbage  26 minutes ago  26 minutes ago
cbb0a946        hyperkube       quay.io/coreos/hyperkube:v1.5.1_coreos.0        exited garbage  23 minutes ago  23 minutes ago
ef7545ff        flannel         quay.io/coreos/flannel:v0.6.2                   running         26 minutes ago  26 minutes ago
f2dae70d        hyperkube       quay.io/coreos/hyperkube:v1.5.1_coreos.0        exited garbage  22 minutes ago  22 minutes ago
```

**Comment by ipedrazas** [comment]
I tried to build a cluster in eu-west-2 and I've got this other error in the controller node:

```
Jan 06 22:14:40 ip-10-0-0-5.eu-west-2.compute.internal systemd[1]: Failed to set up mount unit: Invalid argument
Jan 06 22:14:40 ip-10-0-0-5.eu-west-2.compute.internal systemd[1]: Failed to set up mount unit: Invalid argument
Jan 06 22:14:40 ip-10-0-0-5.eu-west-2.compute.internal systemd[1]: Failed to set up mount unit: Invalid argument
Jan 06 22:14:40 ip-10-0-0-5.eu-west-2.compute.internal systemd[1]: Failed to set up mount unit: Invalid argument
Jan 06 22:14:40 ip-10-0-0-5.eu-west-2.compute.internal systemd-journald[537]: Suppressed 2102 messages from /init.scope
Jan 06 22:14:40 ip-10-0-0-5.eu-west-2.compute.internal sshd[2214]: pam_unix(sshd:session): session opened for user core by (uid=0)
Jan 06 22:14:40 ip-10-0-0-5.eu-west-2.compute.internal sshd[2214]: Accepted publickey for core from 86.189.205.84 port 54313 ssh2: RSA SHA256:qD5j9RyMMaBTsVHglrNJySudLcon9G4OI0psMn
Jan 06 22:14:39 ip-10-0-0-5.eu-west-2.compute.internal systemd[1]: Started OpenSSH per-connection server daemon (86.189.205.84:54313).
Jan 06 22:14:39 ip-10-0-0-5.eu-west-2.compute.internal systemd[1]: Created slice system-sshd.slice.
Jan 06 22:14:39 ip-10-0-0-5.eu-west-2.compute.internal systemd[1]: kubelet.service: Unit entered failed state.
Jan 06 22:14:39 ip-10-0-0-5.eu-west-2.compute.internal systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
Jan 06 22:14:39 ip-10-0-0-5.eu-west-2.compute.internal systemd[1]: Failed to open directory /usr/lib/systemd/system/var-lib-rkt-pods-run-4e8e9a87\x2d318d\x2d46fe\x2d800c\x2d887acc9
Jan 06 22:14:39 ip-10-0-0-5.eu-west-2.compute.internal systemd[1]: Failed to open directory /run/systemd/generator/var-lib-rkt-pods-run-4e8e9a87\x2d318d\x2d46fe\x2d800c\x2d887acc9a
Jan 06 22:14:39 ip-10-0-0-5.eu-west-2.compute.internal systemd[1]: Failed to open directory /run/systemd/system/var-lib-rkt-pods-run-4e8e9a87\x2d318d\x2d46fe\x2d800c\x2d887acc9adb8
Jan

...

Jan 06 22:14:39 ip-10-0-0-5.eu-west-2.compute.internal systemd[1]: Failed to open directory /etc/systemd/system/var-lib-rkt-pods-run-a977ea30\x2d2218\x2d4212\x2d8568\x2d14dc16c12dc
Jan 06 22:14:39 ip-10-0-0-5.eu-west-2.compute.internal systemd[1]: Failed to open directory /run/systemd/transient/var-lib-rkt-pods-run-a977ea30\x2d2218\x2d4212\x2d8568\x2d14dc16c1
Jan 06 22:14:39 ip-10-0-0-5.eu-west-2.compute.internal systemd[1]: Failed to open directory /run/systemd/transient/var-lib-rkt-pods-run-a977ea30\x2d2218\x2d4212\x2d8568\x2d14dc16c1
Jan 06 22:14:39 ip-10-0-0-5.eu-west-2.compute.internal kubelet-wrapper[2176]: failed to run Kubelet: could not init cloud provider "aws": not a valid AWS zone (unknown region): eu-
Jan 06 22:14:39 ip-10-0-0-5.eu-west-2.compute.internal kubelet-wrapper[2176]: Error: failed to run Kubelet: could not init cloud provider "aws": not a valid AWS zone (unknown regio
Jan 06 22:14:39 ip-10-0-0-5.eu-west-2.compute.internal kubelet-wrapper[2176]: I0106 22:14:39.003863    2176 aws.go:700] Zone not specified in configuration file; querying AWS metad
Jan 06 22:14:39 ip-10-0-0-5.eu-west-2.compute.internal kubelet-wrapper[2176]: I0106 22:14:39.003765    2176 aws.go:746] Building AWS cloudprovider
Jan 06 22:14:39 ip-10-0-0-5.eu-west-2.compute.internal kubelet-wrapper[2176]: I0106 22:14:39.003640    2176 feature_gate.go:181] feature gates: map[]
Jan 06 22:14:39 ip-10-0-0-5.eu-west-2.compute.internal kubelet-wrapper[2176]: Flag --rkt-stage1-image has been deprecated, Will be removed in a future version. The default stage1 i
Jan 06 22:14:39 ip-10-0-0-5.eu-west-2.compute.internal kubelet-wrapper[2176]: Flag --api-servers has been deprecated, Use --kubeconfig instead. Will be removed in a future version.
Jan 06 22:14:38 ip-10-0-0-5.eu-west-2.compute.internal systemd[1]: Failed to set up mount unit: Invalid argument
```

There's this message:

`
Jan 06 22:14:39 ip-10-0-0-5.eu-west-2.compute.internal kubelet-wrapper[2553]: Error: failed to run Kubelet: could not init cloud provider "aws": not a valid AWS zone (unknown region): eu-west-2a
`

and this is the bit of my `cluster.yaml`

```
# Region to provision Kubernetes cluster
region: eu-west-2

# Availability Zone to provision Kubernetes cluster when placing nodes in a single availability zone (not highly-available) Comment out for multi availability zone setting and use the below `subnets` section instead.
availabilityZone: eu-west-2a
```

Validation seems to give it as ok:

```
-> % kube-aws validate --s3-uri s3://kubernetes.clusters/london
Validating UserData...
UserData is valid.

Validating stack template...
Validation Report: {
  Capabilities: ["CAPABILITY_IAM"],
  CapabilitiesReason: "The following resource(s) require capabilities: [AWS::IAM::Role]",
  Description: "Kubernetes cluster compute"
}
stack template is valid.

Validation OK!
```

**Comment by colhom** [comment]
@ipedrazas this one is kubernetic, not AWS

https://github.com/kubernetes/kubernetes/blob/6d0efbc9d644fdfb69a214d8b76417cf581fbf37/pkg/cloudprovider/providers/aws/aws.go#L780-L787

File an issue upstream about this? I feel the kubelet should dynamically fetch a list of valid AWS zones from a well-known URL, probably the metadata service. Hardcoding it is definitely not optimal.

**Comment by ipedrazas** [comment]
There a PR already in place that fixes the hard coding issue using the metadata service

https://github.com/kubernetes/kubernetes/pull/38880

I just wanted to leave trace in case someone else bumps into this problem 😄

**Comment by gmorpheme** [comment]
In the meantime, is there a way to specify `cfg.Global.DisableStrictZoneCheck` to work around the check? Can we get that in through the userdata somehow?

**Comment by martindanko** [comment]
Does this mean *kube-aws* is not currently supported in *eu-west-2* atm? I am still not able to provision a cluster successfully.

How come I incorporate the kubernetes/kubernetes#38880 fix ?

ATM the cluster provisions with Cloudformation however, the controller node never becomes healthy in the ELB and most of the time I am unable to successfully ssh into the controller node with the following error.

> ssh_exchange_identification: read: Connection reset by peer

Although that is probably unrelated the AWS region hard-coding in upstream Kubernetes.

**Comment by bgeesaman** [comment]
@martindanko I ran into this exact issue with us-east-2 (Ohio) and now ca-central-1 (Canada) and eu-west-2 (London).  Kubernetes 1.4.7 added support for us-east-2, but the fix you referenced here: https://github.com/kubernetes/kubernetes/pull/38880 is needed to get the newest two regions in place.  Current tagged milestone on that issue is 1.5.0. So yes, you can't use these two regions ATM.

If you SSH into one of your workers early on in the deployment process and run "journalctl -f", you'll see the kubelet.service crash-looping with an error:

```Error: failed to run Kubelet: could not init cloud provider "aws": not a valid AWS zone (unknown region): eu-west-2a```

The SSH error during this deployment in unsupported regions appears to be resource constraint related and not a region-specific issue, IME.

All that said, as @gmorpheme mentioned, is there a way to add that ```DisableStrictZoneCheck``` setting into the userdata in the meantime?  I'm not looking for kube-aws to do it natively, but I'm willing to drop it into the user data files by hand if someone knows how to link that into the proper place.

**Comment by richiemarshall** [comment]
I'm using the latest stable release and deploying into eu-west-2 as a multi-AZ deployment. I _am_ however having a problem getting the etcd nodes to deploy in the desired subnet.

**Comment by mumoshu** [comment]
I believe this is already resolved in upstream. Closing!
