### ISSUE TITLE
Allow CoreOS updates by adding nodes to etcd as proxy

### ISSUE THREAD

**Issue by ArchiFleKs** [kubernetes-incubator/kube-aws#240]
Currently, updates strategy is off on Worker node and controllers.

I dont know if that would be the right approach but maybe we could add the CoreOS instances to ETCD, maybe as proxy to take advantages of the etcd-lock reboot strategy ?

**Comment by mumoshu** [comment]
Hi, thanks as always!
I'm personally not going to use the automatic update feature of CoreOS in production without an imaginary feature to postpone a reboot until all the pods running on the node moves to existing node(s). I'm open to suggestions though!

**Comment by redbaron** [comment]
doesn't node drain feature help doing it?

**Comment by mumoshu** [comment]
Not really. AFAIK it waits for pods on a node to be deleted but not for new pods on another nodes to be running.

**Comment by redbaron** [comment]
So *wait-before-reboot* logic would be:
 - mark node so that no _new_ pods are scheduled to it (how?)
 - get list of running pods from a node
 - drain a node
 - poll k8s controllers waiting until all pods from (2) are running elsewhere.
 - reboot.

Right?

**Comment by c-knowles** [comment]
Short term we could taint an existing node for now? Longer term I think we should wait for https://github.com/coreos/bugs/issues/1274.

Side note, as a user of kube-aws I had switched a dev cluster over to the `etcd-lock` strategy to try it out. We should add something to the documentation if it's not advised to use it right now.

**Comment by mumoshu** [comment]
@redbaron I wasn't aware of a concrete solution to the problem but your idea sounds great 👍 

Let me also add that we'll need to make enough space in the cluster for pods evicted from the drained node to be run, probably having at least one extra node for that or enable `cluster-autoscaler` to automatically add a node for those pods.

**Comment by mumoshu** [comment]
@c-knowles Thanks for looking into this!

For what part of the process you intended to use taints?

I wasn't aware of it until now but am really looking forward for `klocksmithd`!

**Comment by c-knowles** [comment]
@mumoshu for the taint I meant for the first point of @redbaron's proposal. Perhaps node draining and waiting is enough though?

**Comment by mumoshu** [comment]
@c-knowles Ah, I guessed that `kubectl cordon` would be enough for that!

**Comment by c-knowles** [comment]
@mumoshu, yep makes sense

**Comment by c-knowles** [comment]
Just in case anyone is not following the coreos tracker, they've released https://github.com/coreos/container-linux-update-operator. I think we should proceed by supporting Operators which we could consider as part of https://github.com/kubernetes-incubator/kube-aws/issues/509

**Comment by whereisaaron** [comment]
I didn't understand one bit above @mumoshu, given the pods are already drained/deleted/not-running on a node that needs reboot, why is it advantageous wait until the pods are running elsewhere before rebooting that node? Or is your concern that the *next* node is not rebooted before the previously rebooted node's workload is up and running elsewhere?

The ['container-linux-update-operator'](https://github.com/coreos/container-linux-update-operator) does already limit reboots one node at a time. It wouldn't be hard to add a lengthy pause between each reboot, to ensure the drained workload from the previous reboot had stabilized.

**Comment by mumoshu** [comment]
I believe I've discussed about this somewhere else.
Basically, I think doing this by periodically running `kube-was update` would be a better approach.

IMHO, locksmithd or container-linux-update-operator approach both fall short of custom AMI support.
It also results in unnecessary node replacement in `kube-aws update` as locksmithd or the operator doesn't (of course) update launch configurations to newer AMIs.

**Comment by mumoshu** [comment]
> why is it advantageous wait until the pods are running elsewhere before rebooting that node?

Because there may be insufficient cluster resource resource to migrate the drained pods.

In theory:

(1) we need to add an extra node or
(2) just ensure there's always spare cluster source to prevent such temporary resource shortage
(3) or just make critical deployments to have extra replicas so that it won't affect service availability even when the desired replica number can't be meet in short period
