### ISSUE TITLE
kube-aws should use CF changesets when updating  a stack

### ISSUE THREAD

**Issue by redbaron** [kubernetes-incubator/kube-aws#251]
For ease of troubleshooting , instead of updating stack directly, kube-aws should create changeset and apply it. This way every change is explicitly logged and easy to audit/inspect.

**Comment by mumoshu** [comment]
Related: #410

**Comment by mumoshu** [comment]
Should we show a diff and a prompt before applying updates to cloudformation stacks, by default?
If so, `--force` flag should be added to `kube-aws update` to enable users to skip prompts.

**Comment by mumoshu** [comment]
Does change-sets work with nested stacks? How?

**Comment by redbaron** [comment]
unfortunately no :(

**Comment by mumoshu** [comment]
:sob:
Perhaps we can initiate a change set directly to a sub-stack and then delete it so that we can at least show a diff before/after a `kube-aws update` for each sub-stack?

**Comment by c-knowles** [comment]
I wonder if the new [AWS::Include](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/create-reusable-transform-function-snippets-and-add-to-your-template-with-aws-include-transform.html) is able to help here or still subject to similar limitations.

**Comment by c-knowles** [comment]
Not sure either but maybe worth trying it out.

**Comment by mumoshu** [comment]
This would be feasible after #1112
