### ISSUE TITLE
Add a (optional) feature to enable kube2iam

### ISSUE THREAD

**Issue by ankon** [kubernetes-incubator/kube-aws#253]
(Issue itself is work-in-progress, updating it with the parts I found are needed)

In the kube-aws context it seems reasonable to assume that users have IAM enabled, and have some knowledge about it - and that they want it on pod-level, not on worker-level granularity. It would be awesome if kube-aws would provide some OOBE for setting that up using https://github.com/jtblin/kube2iam.

1. Add an "experimental" feature for kube2iam in cluster.yaml
2. If enabled: add this piece to the worker role:
   ```json
           {
            "Action": "sts:AssumeRole",
            "Resource": "*",
            "Effect": "Allow"
        },
   ```
3. If enabled: Deploy the kube2iam daemonset as part of kube-system (or maybe introduce a kube-aws namespace?)
4. Document how to link the worker role to existing roles (roughly like this: 
   ```sh
   EXISTING_ROLES=....
   ROLE_ID=`aws cloudformation list-stack-resources --stack-name CLUSTER-ID | jq -r '.StackResourceSummaries[]|select(.LogicalResourceId=="IAMRoleWorker")|.PhysicalResourceId'`
   ROLE_ARN=`aws iam get-role --role-name collaborne-20170105-IAMRoleWorker-XX0VV92HCQKG | jq -r .Role.Arn`
   for role in ${EXISTING_ROLES}; do
     aws iam get-role --role-name ${role} | jq ".Role.AssumeRolePolicyDocument|(.Statement |= .+ [{\"Principal\":{\"AWS\":\"${ROLE_ARN}\"},\"Action\":\"sts:AssumeRole\",\"Effect\":\"Allow\"}])" > policy-${role}.json
     aws iam update-assume-role-policy --role-name ${role} --policy-document file://$PWD/policy-${role}.json
   done   
   ```

**Comment by c-knowles** [comment]
There's a helm chart for kube2iam, perhaps supporting helm could be a good idea.

**Comment by ankon** [comment]
Sounds reasonable. Especially since I now found that there is a bug in kube2iam:latest in combination with calico: https://github.com/jtblin/kube2iam/issues/37. The fix proposed there comes via a helm chart, too.

Other than using :0.2.2 everything seems to work though in my setup, so that's promising.

**Comment by c-knowles** [comment]
@mumoshu's overview of the goals for kube-aws in this respect are at https://github.com/coreos/kube-aws/issues/118#issuecomment-267600328. So the result is I think we could allow optional installation of helm in kube-aws.

@ankon Are there any cluster customisations needed for kube2iam to function?

**Comment by ankon** [comment]
The item 2 from my list: the worker role needs to allow sts:AssumeRole. 

Maybe we can take helm support into another issue and link these? I'm not sure how much work that would be, and in the worst case we have this ticket for people googling how to get kube2iam running directly.

**Comment by c-knowles** [comment]
Might be possible to just add that assuming it also needs to be granted on the target role. Yes, I think a good idea to have a helm feature issue.

**Comment by mumoshu** [comment]
The experimental feature `kube2IamSupport` is introduced by #297 and is included since v0.9.4-rc.3. When enabled via `experimental.kube2IamSupport.enabled` and/or `worker.nodePools[].kube2IamSupport.enabled`, it adds permissions for controller nodes and/or worker nodes, respectively, to allow kube2iam to assume roles.

**Comment by mumoshu** [comment]
Is anyone going to write some documentation about the feature?
Then, this issue can be closed 😃

**Comment by c-knowles** [comment]
At some point soon this may be more "native" - https://github.com/kubernetes/features/issues/171.

**Comment by mumoshu** [comment]
Documentation updated. Please review correctness of it and my English 🌷 
https://github.com/kubernetes-incubator/kube-aws/blob/master/Documentation/kubernetes-on-aws-add-ons.md
