### ISSUE TITLE
Continual heapster crash loop at cluster launch (0.9.3-rc.5)

### ISSUE THREAD

**Issue by whereisaaron** [kubernetes-incubator/kube-aws#254]
I just launched a cluster with 0.9.3-rc.5 all seemed good except heapster was restarting repeatedly. This was caused by health check failures with `dial tcp 10.2.89.3:8082: getsockopt: no route to host`.

I deleted the crash-looping Pod and the replacement launched and has been perfectly fine and healthy with no restarts.

```
  42m	37s	13	{kubelet ip-1.1.1.1.region.compute.internal}	spec.containers{heapster}	Warning	Unhealthy	Liveness probe failed: Get http://10.2.89.3:8082/healthz: dial tcp 10.2.89.3:8082: getsockopt: no route to host
```

I am not sure if I should be concerned about that or not. Seems like a situation that shouldn't occur, so maybe there is a problem. Anyone else seen anything similar?

**Comment by mumoshu** [comment]
Hi @whereisaaron!
Two questions for now:

* Does your issue still reproduce after recreating your cluster?
* Are you using calico?

**Comment by whereisaaron** [comment]
Not using Calico. Also I didn't recreate the cluster, I just `kubectl delete pod` the heapster Pod and let the RC create a new Pod. That fixed the problem and it hasn't come back.

I've launched this same cluster config a dozen times and not seen this. It was a 'bad luck' problem I think. I only post it here to collect other reports or info, since I assume it should probably never happen like this.
