### ISSUE TITLE
why does kube-aws not support custom AWS domain names ?

### ISSUE THREAD

**Issue by mariusmitrofan** [kubernetes-incubator/kube-aws#260]
I've been battling with these for over 48 hours.

The certificates that you create for `etcd2` to use automatically assume that my hostname belong to either `<region-name>.compute.internal` or `ec2.internal`, but if it doesn't ?

What do I do then?

**Comment by camilb** [comment]
Hi Marius, a quick method is  to edit these lines and compile your own version of kube-aws.

        ./config/config.go:546
        ./config/tls_config.go:135
        ./config/tls_config.go:151

**Comment by redbaron** [comment]
generate your worn certs for the time being

**Comment by mariusmitrofan** [comment]
Thank you both.

Does running this make sense ->
```
openssl genrsa -out ca-key.pem 2048
openssl req -x509 -new -nodes -key ca-key.pem -days 10000 -out ca.pem -subj "/CN=<my_hostname_suffix>"
kube-aws render credentials --ca-cert-path=ca.pem --ca-key-path=ca-key.pem
```

The output of that would be this ->
```
root@pan:/opt/kubernetes/kubernetes-demo-6/credentials# ls -altr
total 56
-rw-r--r-- 1 root root 1679 Jan 17 13:17 ca-key.pem
-rw-r--r-- 1 root root 1107 Jan 17 13:17 ca.pem
-rw------- 1 root root 1168 Jan 17 13:19 worker.pem
-rw------- 1 root root 1675 Jan 17 13:19 worker-key.pem
-rw------- 1 root root 1168 Jan 17 13:19 etcd.pem
-rw------- 1 root root 1679 Jan 17 13:19 etcd-key.pem
-rw------- 1 root root 1099 Jan 17 13:19 etcd-client.pem
-rw------- 1 root root 1679 Jan 17 13:19 etcd-client-key.pem
-rw------- 1 root root 1294 Jan 17 13:19 apiserver.pem
-rw------- 1 root root 1679 Jan 17 13:19 apiserver-key.pem
-rw------- 1 root root 1090 Jan 17 13:19 admin.pem
-rw------- 1 root root 1679 Jan 17 13:19 admin-key.pem
drwxr-xr-x 3 root root 4096 Jan 17 13:20 ..
drwx------ 2 root root 4096 Jan 17 13:20 .
```

**Comment by mariusmitrofan** [comment]
Later update for whoever follows this thread:

- `redbaron`'s solution is not valid because the hostnames for the container configuration is generated using the same logic, which makes it wrong
- `camilb`'s solution is the `one that actually works` because it fixes both the cert problem and the hostname rednering for the config files

Going further, I agree that if you follow the code's readme to build your own code works flawlessly and was actually faster than the countless hours I spent debugging it, but I do recommend the following for future releases:
1) add a parameter in `cluster.yaml`  to define custom domain name and make it `optional` (for "advanced" users)
2) modify the files that `camilb` was talking to take into consideration said parameter if exists

Just my 2 cents...

And thank you `camilb`. You've saved my life :+1:

**Comment by redbaron** [comment]
sorry, I wasn't clear enough, my solution was to add your domain names to existing ones kube-aws already adds to certs, you can have more than one.

**Comment by mariusmitrofan** [comment]
I'm refering to configurations such as the one `etcd2.service` has in `userdata` which writes this :

`Environment=ETCD_INITIAL_CLUSTER={{.EtcdInitialCluster}}`

After the cluster is created, this creates the incorrect environment variable, because the hostname is rendered inside the code with suffix appended by default, which defeats my business case.

Have a look here -> ./config/config.go:546

**Comment by redbaron** [comment]
AFAIK even with custom domain name, `compute.internal` names are still resolving correctly, therefore instances are accessible

**Comment by mariusmitrofan** [comment]
Not really no, because that domain does not exist. I'm talking about custom domain in dhcp options for an existing vpc, not the custom external dns name...

**Comment by mariusmitrofan** [comment]
Aka this - http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-dns.html

**Comment by mumoshu** [comment]
Hi @mariusmitrofan, thanks for your interest on kube-aws and the info!
It will indeed help future, potential users who has the req same as yours.

Btw, would you mind confirming if it is possible for me to reproduce your use-case by just creating a kube-aws cluster in an existing VPC which the domain name is customized in the DHCP options?
If there's any little thing you've done in order to bring up your cluster, please tell me so that I can add the support for custom domain earlier.

Also, just curious but your use-case isn't the same as https://github.com/coreos/kube-aws/issues/189, right?

**Comment by mariusmitrofan** [comment]
Hi @mumoshu,

In order to replicate it, you'll have to have a working VPC that is set up with a custom DNS to serve requests in DHCP options that is used instead of the AWS one.

This means that your DHCP options config **should look like this**:
![image](https://cloud.githubusercontent.com/assets/14178431/22362542/0a0922d2-e46c-11e6-9125-9d73c7b11f05.png)

(I blurred out the image for obvious reasons, but I guess you'll get the gist).

The normal (default) AWS (which is also hardcoded in the certs) is the only use case currently treated in `kube-aws` : 
![image](https://cloud.githubusercontent.com/assets/14178431/22362607/8c66fb14-e46c-11e6-9bf9-bab0b807cac7.png)

This is not the same issue as #189, because, not only that the certs are created invalid, but **most importantly**, the hostnames are also generated using a hardcoded logic (<region-name>.compute.internal), making the instances not talk to each other, because hey, it can't find the hostname :)

That's why I said that the `cluster.yaml` file should address this use case and rewrite the hostnames + certs using custom hostname instead of AWS hostname where applicable.

**Comment by mumoshu** [comment]
Hi @mariusmitrofan, sorry for the long silence!
I'd been working on #332 for H/A etcd cluster and also the support for your use-case.
With #332, a configuration like:

```yaml
etcdCount: 3
etcd:
  memberIdentityProvider: eni
  manageRecordSets: false
  internalDomainName: <your domain-name resolvable with your custom DNS other than Amazon DNS>
  nodes:
  - fqdn: etcd1.<your domain-name>
  - fqdn: etcd2.<your domain-name>
  - fqdn: etcd3.<your domain-name>
```

while somehow configuring your custom DNS to resolve `etcd1.<your domain-name>` to the first etcd node's private ip, `etcd2.<your domain-name>` to the second etcd node's private ip, and so on, would fit your setup.

`etcd.internalDomainName` is also used by kube-aws to generate appropriate tls cert for that domain.

The `somehow configuring your custom DNS` part is not very elegant but I couldn't figure out what kube-aws could do further to support it. kube-aws has no way to configure your own custom DNS.
If you could configure your custom DNS to forward lookups of `ec2-<public ip>.<region>.amazonaws.com` or `ip-<private ip>.<region>.compute.internal` to Amazon DNS, that part would be unnecessary.

**Comment by mariusmitrofan** [comment]
Hi @mumoshu,

I wasn't expecting the fix to be something this "huge"... In my mind, the only thing you would need to change were the below ones :
```

./config/config.go:546
    ./config/tls_config.go:135
    ./config/tls_config.go:151
```


and one would just replace the `amazon` hostname with what was provided in the config file. I mean... That's all that I had to change anyway...

Either way, if this works, then sure :)

Cheers,
Marius

**Comment by mumoshu** [comment]
@mariusmitrofan Thanks for the feedback!
Excuse me but are you sure that the fixes you've imagined are enough for achieving H/A of etcd clusters?
We need to somehow provide a "stable" hostname to an etcd node so that we can be sure that an actual EC2 instance backing that hostname can fail and then be recreated freely without resulting down time.

**Comment by mariusmitrofan** [comment]
Hi @mumoshu

My fix has nothing to do with etcd. It only adresses the problem in this thread.

The reason it works is simply because instead of using the DNS domain that amazon provides, I hardcoded my own DNS domain.

Again, this has nothing to do with etcd... The original design was hardcoding the amazonaws domain in the config, and etcd was using a hostname config based on that dns. What I need is to specify my own dns domain.

And, of course it is going to work, since I'm handling the dns resolution of the domain. If it doesn't work, it's my problem, not yours. If I choose to have my own dns set up instead of using the amazonaws, it's again my problem, not yours...

You can ping me on skype ( marius.mitrofan.netbears ) if you have any more questions, instead of enlarging this thread for no reason.

PS : I'll edit the comment and blur out the address in a few hours, so add me fast if anything.

**Comment by mumoshu** [comment]
Thanks for clarification, @mariusmitrofan!
I was surprised to see that #332 looked very huge to you; however I can say that it was required in order to support  etcd high availability without breaking everyone's use-case 😃 
JFYI, configuring your own DNS to delegate lookups to `<region>.compute.internal` to the AWS DNS will make the settings mentioned in https://github.com/kubernetes-incubator/kube-aws/issues/260#issuecomment-282221951 unnecessary.
