### ISSUE TITLE
Is there any suggested way to stop-start/upgrade cluster without losing etcd data?

### ISSUE THREAD

**Issue by valichek** [kubernetes-incubator/kube-aws#279]
As for now kubernetes and etcd instances are managed with the same CF and destroying cluster results to destroying etcd machines with data. I know there is feature to make etcd cluster external in progress. But is it possible to save etcd data when using `0.9.1` release

**Comment by gianrubio** [comment]
@valichek try to set the ```controllerCount``` and ```workerCount```to 0

**Comment by valichek** [comment]
@gianrubio it doesn't work (there is some note about it in the docs - https://github.com/coreos/kube-aws/blob/master/Documentation/kubernetes-on-aws-node-pool.md), but actually this is not what I would like to achieve, one of possible scenarios could be suspending all kube ec2 instances, but i'm not able to just stop them in aws console because controllers and workers are being terminated and re-created.

**Comment by gianrubio** [comment]
@valichek you're right. Could you try to scale the asg group for workers and controllers to 0 rather than terminate the instance on ec2 dashboard?

**Comment by valichek** [comment]
@gianrubio yes, editing Auto Scaling Groups to have `Desired: 0, Min: 0, Max:0` did the job.

**Comment by mumoshu** [comment]
@gianrubio @valichek Thanks for the info!
Assuming @valichek's original issue is resolved, would you like me to update the doc now?
