### ISSUE TITLE
Extra validation required for existing VPC plus no IGW spec

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#318]
A combination of existing VPC but no IGW specification means that an IGW is created by kube-aws as expected but it is not attached to the VPC. kube-aws will currently fail on this at the point of stack creation. The fix is to specify an existing IGW in the same VPC within the `cluster.yaml`.

In theory this could be supported by kube-aws, we'd just need to move the `VPCGatewayAttachment` definition inside `controlplane` that is currently inside the `{{if not .VPCID}}` block.

I'm happy to support/not support this scenario if we have a single way we do existing infrastructure (we already support subnet/NAT/EIP management or pre-existing). IGWs do not add additional cost so it could make sense for kube-aws to always add it to keep the setup more uniform? On the other hand, if we choose to not support this in kube-aws then ideally we should support some validation error before stack creation and more explicit details in `cluster.yaml`.

Extracted from https://github.com/coreos/kube-aws/pull/315.

**Comment by mumoshu** [comment]
Thanks for submitting the issue @c-knowles!

kube-aws by design tries its best not to modify existing AWS resources.
Therefore, when `vpcId` is specified, kube-aws should'nt create an IGW and a VPC gateway attachment. It will be even better if we could emit a warning message when the VPC specified via `vpcId` doesn't have a valid IGW and a gateway attachment.

**Comment by cmcconnell1** [comment]
Hello @mumoshu / @c-knowles 

I saw this current issue which seems like it's related so posting here.

We've run into an issue in the most recent `kube-aws version v0.9.6-rc.2` (and the most recent previous version--not sure what version this started happening in), in which kube-aws is creating a n unwanted and detached igw, even though we've specified our route table id for the subnets and that route table has a / the default route to the igw as shown below with the [awless tool](https://github.com/wallix/awless) where we have `0.0.0.0/0->gw:igw-ccb87ca4` 

Below is our external route-table we're using with kube-aws
```
awless show rtb-c1b87ca9
| PROPERTY ▲ |                                 VALUE                                  |
|------------|------------------------------------------------------------------------|
| ID         | rtb-c1b87ca9                                                           |
| Main       | false                                                                  |
| Name       | EXTERNAL                                                               |
| Routes     | 172.31.0.0/24->gw:vgw-95cf9fd0 10.0.1.0/24->gw:vgw-95cf9fd0            |
|            | 10.1.0.0/16->gw:local 10.0.2.0/24->gw:vgw-95cf9fd0                     |
|            | 10.0.3.0/24->gw:vgw-95cf9fd0 0.0.0.0/0->gw:igw-ccb87ca4                |
|            | 10.0.4.0/24->gw:vgw-95cf9fd0                                           |
| Vpc        | vpc-cbb87ca3                                                           |

# Relations:
us-west-1[region]
	↳ @terradatum-main[vpc]
		↳ @EXTERNAL[routetable]

Applied on: @EXTERNAL-1A[subnet], @EXTERNAL-1B[subnet], @METRICS-PPCD-B[subnet], @MLS-PPCD-B[subnet], @OLD-METRICS-PPCD[subnet], @aergo-dev-Subnet0[subnet], @aergo-dev-Subnet1[subnet], @aergo-prod-Subnet0[subnet], @aergo-prod-Subnet1[subnet], @ops-dev-OpsDevIgwPublic1a[subnet], @ops-dev-OpsDevIgwPublic1b[subnet]
```

AFAIK, we have correctly configured our [cluster.yaml per the commented out section below](https://github.com/kubernetes-incubator/kube-aws/blob/master/core/controlplane/config/templates/cluster.yaml#L816) 
```
#   # Advanced: Managed public subnet with an existing route table
#   #
#   # kube-aws tries to reuse the route table specified by id or idFromStackOutput
#   # by assigning this subnet to the route table.
#   #
#   # Please be sure that it's your responsibility to:
#   # * Configure an internet gateway(IGW) and
#   # * Attach the IGW to the VPC you're deploying to
#   # * Add a route to the IGW to the route table being reused
#   #
#   # i.e. kube-aws neither modify route table nor create other related resources like
#   # igw, route to igw, igw vpc attachment, etc.
#   #
#   - name: ManagedPublicSubnetWithExistingRouteTable
#     availabilityZone: us-west-1a
#     instanceCIDR: "10.0.1.0/24"
#     routeTable:
#       # Pre-allocated route table
#       id: "rtb-xxxxxxxx"
#       # Exported output's name from another stack
#       # Only specify either id or idFromStackOutput but not both
#       #idFromStackOutput: myinfra-PublicRouteTable1
```

excerpt from our current cluster.yaml we're working to upgrade to latest version:
```
subnets:
  - name: ops-dev-igw-public-1a
    availabilityZone: us-west-1a
    instanceCIDR: "10.1.16.0/24"
    routeTable:
      # Pre-allocated route table rtb-c1b87ca9 | EXTERNAL
      id: "rtb-c1b87ca9"

  - name: ops-dev-igw-public-1b
    availabilityZone: us-west-1b
    instanceCIDR: "10.1.17.0/24"
    routeTable:
      # Pre-allocated route table rtb-c1b87ca9 | EXTERNAL
      id: "rtb-c1b87ca9"
```

So, we can continue to just delete the (orphaned and unwanted) igw that kube-aws is creating, as it's detached, but wanted to post here and make sure we're doing thing correctly?

Thanks!

**Comment by mumoshu** [comment]
@cmcconnell1 Thanks for bringing this up!
Your configuration looks good.
As you might have seen, the creation of unwanted, orphaned IGW is a bug in kube-aws.
We'd better fix it not to create the IGW and emit a validation error when the existing VPC doesn't have an corresponding VPCGatewayAttachment as @c-knowles suggested.

**Comment by mumoshu** [comment]
internetGatewayId is now required for public managed subnets without existing route tables when vpcId is specified - validations are added accordingly.
Thanks for the detailed feedback @c-knowles
