### ISSUE TITLE
Detailed EC2 monitoring metrics

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#320]
We previously added ASG metrics since they are [free and no longer require EC2 detailed instance monitoring](https://github.com/coreos/kube-aws/pull/137). We left detailed monitoring for ASGs always switched on although it's not required any more for ASG metrics. The current situation seems to be controllers and workers have detailed EC2 monitoring switched on but etcd nodes have it switched off.

We have a choice here:
1. Agree detailed EC2 monitoring will always be switched on, could be especially true if we are going to use these metrics at 1 minute granularity to provide ASG actions.
1. Allow detailed monitoring to be disabled as per the [AWS docs](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-launchconfig.html#cfn-as-launchconfig-instancemonitoring)

**Comment by mumoshu** [comment]
Assuming generally everyone wants it enabled - since #623, detailed monitoring has been enabled on spot fleets by default.
I'll go ahead with etcd nodes, too.
After that, we can decide if we really wants an ability to toggle detailed monitoring on/off.

**Comment by c-knowles** [comment]
Latest release has detailed monitoring enabled across controllers/etcd/node pools/spot fleets. Going to close this off until there is any demand for turning it off. The use case to turn it off would be to cut costs for some dev clusters.
