### ISSUE TITLE
Move s3-uri to init/cluster.yaml

### ISSUE THREAD

**Issue by gianrubio** [kubernetes-incubator/kube-aws#326]
Nowadays all the commands require --s3-uri flag. It's a pain to run every command with --s3-uri, let's move this option to the cluster.yaml file.

**Comment by mumoshu** [comment]
Ah, it is a first year anniversary for such a small improvement!

**Comment by gianrubio** [comment]
Let's have a cake to celebrate 🍰  :)

**Comment by jorge07** [comment]
This issue can finally be closed :tada:

**Comment by jorge07** [comment]
@mumoshu can we close this?

**Comment by ktateish** [comment]
ping @mumoshu
