### ISSUE TITLE
CF rollback wouldn't work because of S3 userdata

### ISSUE THREAD

**Issue by redbaron** [kubernetes-incubator/kube-aws#352]
kube-aws should upload userdata to S3 bucket using hash name of the file, that is because if we use `WaitSignal` and we have an error in userdata, then CF tries to rollback to previous CF state, but that state doesn't include data on S3 bucket, therefore instance which is being rolled back continues to come up with broken metadata and CF rollback fail eventually.

**Comment by mumoshu** [comment]
@redbaron Good catch!
Using the hash of a file's name sounds good.
I'm not saying it shouldn't be fixed but one concern is; how can we clean up old files so that the s3 bucket won't get bloated with already unused ones?

**Comment by gianrubio** [comment]
> I'm not saying it shouldn't be fixed but one concern is; how can we clean up old files so that the s3 bucket won't get bloated with already unused ones?

@mumoshu tagging the template should works?  http://docs.aws.amazon.com/AmazonS3/latest/dev/object-tagging.html

**Comment by mumoshu** [comment]
@gianrubio Tagging 2 revisions(=hashes) of user-data so that we can filter out all the other user-data in S3 to be cleaned up?

**Comment by mumoshu** [comment]
I'm going ahead with changing uploaded files to be named like `cloud-config-worker-<hash>`

**Comment by mumoshu** [comment]
Maybe I'll introduce something like `cloud-config-worker.versions` which is a list of hash values to keep an ordered history of hash values so that we can clean up old `cloud-config-worker-<hash>` files in S3

**Comment by redbaron** [comment]
I'd keep files there forever in version 1

**Comment by mumoshu** [comment]
Shouldn't it be 2 so that we won't clean up old cloud-config necessary for
rolling backs?
2017年3月17日(金) 20:53 Maxim Ivanov <notifications@github.com>:

**Comment by redbaron** [comment]
@mumoshu , that is my  bad English  :) What I meant is for version 1 of this feature, I wouldn't be bothered with bucket cleanup. userdata files are not that big to be a problem

**Comment by mumoshu** [comment]
I see. That sounds reasonable :+1:
2017年3月17日(金) 23:44 Maxim Ivanov <notifications@github.com>:

**Comment by mumoshu** [comment]
The version 1 of the feature is in #430 😄
