### ISSUE TITLE
flannel through DaemonSet and --kube-subnet-mgr

### ISSUE THREAD

**Issue by glerchundi** [kubernetes-incubator/kube-aws#359]
I think the title is self-hosted, emm, self-explanatory :)

But can anyone answer why this project is relying on flannel v0.6 and not on v0.7 and use k8s instead of etcd to configure networking which simplifies host deployment and dependencies.

Release: https://github.com/coreos/flannel/releases/tag/v0.7.0
PR: https://github.com/coreos/flannel/pull/483

**Comment by mumoshu** [comment]
Hi @glerchundi, thanks for posting this!
Is this a feature request or just a question?
If it's the former, I guess you'd need to submit your request to where Container Linux is developed, not here.
We don't manage Container Linux itself but just configure it via cloud-config's.
If it's the latter, probably because v0.7 is still new and Container Linux's "stable" channel doesn't include it.

**Comment by glerchundi** [comment]
sorry for the delay!

> Is this a feature request or just a question?

It's a question about viability and if exists, I'm asking the why not :)

> If it's the latter, probably because v0.7 is still new and Container Linux's "stable" channel doesn't include it.

Umm, then I have another question, why not decouple from the cloud-config and keep your flannel container under control by specifying the specific version you want to use? And then implement this in case it's an interesting feature?

I think this would help keeping things under (even more) control. Something like we do in our custom configs:

```
[...]
    - name: flanneld.service
      command: start
      drop-ins:
        - name: 40-ExecStartPre-symlink.conf
          content: |
            [Service]
            ExecStartPre=/usr/bin/ln -sf /etc/flannel/options.env /run/flannel/options.env
[...]
write_files:
  - path: "/etc/flannel/options.env"
    permissions: "0644"
    content: |
      FLANNEL_VER=v0.6.2
      FLANNELD_IFACE=10.1.0.1
      FLANNELD_ETCD_ENDPOINTS=http://127.0.0.1:4001
[...]
```

WDYT?

**Comment by jeffersongirao** [comment]
@mumoshu I'm going through the process of locking down access to etcd nodes so only the controllers can reach to them at the moment. Do you think allowing for --kube-subnet-mgr (even making it the default) is interesting for the kube-aws project? If so, I would like to give it a shot on getting a PR on it. 
Thanks!
