### ISSUE TITLE
feat: Dump the tail of `journalctl -e` for each node in the ASG failed to be created

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#364]
So that we can encourage everyone to submit his/her question with the journalctl output, which would be helpful for us to investigate further.

**Comment by gianrubio** [comment]
@mumoshu this will be very helpful, in my previous job I had the same visibility problem. I saw 3 options to get this logs.

1 - Connect from kube-aws to the instance over ssh (hard + network connectivity issues like new vpc in a private subnet)
2 - Upload logs to s3 (https://github.com/Factual/s3-journal), can be enabled by flag ```--s3-journal``` (looks easy)
3- Send logs to [cloudwatch](https://aws.amazon.com/blogs/devops/view-cloudformation-logs-in-the-console/) using [coreos](https://github.com/bchecketts/coreos-cloudwatch-logs) (my favourite choice)

**Comment by redbaron** [comment]
I'd prefer `3` , but only up until WaitSignal is fired. Cloudwatch can be expensive to use , but using it as a boottime diagnostic tool shouldn't incur much cost.

**Comment by gianrubio** [comment]
My suggestion is to just enable this when a flag ``--journal-to-cloudwatch`` is set.
BTW the cost is just [$0.57 per GB ingested](https://aws.amazon.com/cloudwatch/pricing/)

**Comment by redbaron** [comment]
yeah, as anything with cloud it is cheap on a small scale :)
