### ISSUE TITLE
v0.9.4: kube-aws doesn't allow cluster names with dots

### ISSUE THREAD

**Issue by Camsteack** [kubernetes-incubator/kube-aws#365]
In the new version of kube-aws, the cluster name cannot contain any dots as is it used in the cloudformation output name of some ressources. I don't know if it was on purpose or not but it would be nice if it was documented in the cluster.yaml for example as the error you get is not straightforward and I had to dig in the cloudformation stack to find out.

```
Error: Error validating cluster: failed to validate control plane: invalid cloudformation stack: ValidationError: Template format error: Output InstanceEtcd0PrivateDnsName is malformed. The Name field of every Export member must be specified and consist only of alphanumeric characters, colons, or hyphens.
	status code: 400, request id: a0f39dfc-fdca-11e6-8e88-f10681bdfd21
```

Just a suggestion and great job with the new release.

Cheers.

Camille

**Comment by mumoshu** [comment]
Thanks for the feedback @Camsteack!
Just for a confirmation, you've set `etcd.memberIdentityProvider: eni` but not `etcd.internalDomainName`, right? (It's a valid configuration. I'm not saying you to not do that! Really just an confirmation.)

**Comment by mumoshu** [comment]
Ideally `clusterName` could be set to anything but as it is used for stack output names and is even going to be used as part of the default internal domain name as per #332, I'd rather like to validate `clusterName` to only include alphanumerics and hyphens and underscores.

**Comment by mumoshu** [comment]
And a documentation in `cluster.yaml` would also help.
Thanks for the suggestion @Camsteack 👍
