### ISSUE TITLE
Controller node should be tagged appropriately

### ISSUE THREAD

**Issue by redbaron** [kubernetes-incubator/kube-aws#370]
Apparently there are some well-known-but-not-documented-tags which are taken into consideration by AWS cloud provide, one example of it would be:
https://github.com/kubernetes/kubernetes/pull/41702/files#diff-07ba008af9c76b0539556ff7fde3105eR162

so we should follow the pattern and tag our nodes

**Comment by mumoshu** [comment]
Thanks as always @redbaron 👍 
After looking into the code, "kubernetes.io/role/master" and "k8s.io/role/master" referred in the PR you've shared are only tags seems to be used as of today.
So just let's tag our with those.

**Comment by zhangtiny123** [comment]
Hi @redbaron @mumoshu 
I'm facing an error when I fetch the instance data and store it into mongodb. ```The dotted field "kubernetes.io/role/master" is not valid for storage``` 

For me this tag does not make any sense, but an error ... 
Since the value of this tag is empty, what do you think about tagging with ``` role: kubernetes.io/role/master ``` or something like that?

**Comment by redbaron** [comment]
@zhangtiny123 controllers are tagged with tag expected by AWS cloud provider code in Kubernetes, so we can't change it

**Comment by zhangtiny123** [comment]
@redbaron  Could you share the reference page about this expectation?

**Comment by redbaron** [comment]
look at the link in the first message

**Comment by mumoshu** [comment]
@zhangtiny123 As @redbaron kindly described, we don't seem to be able to fix/avoid it from k8s side.

AFAIK, you'd need to flatten retrieved object before updating MongoDB with them like [mentioned in a SO question here](http://stackoverflow.com/questions/30014243/mongoerror-the-dotted-field-is-not-valid-for-storage) so that you can still query your MongoDB by something like  `db.find({'node.spec.labels.kubernets.io/role/master': ''})`?

**Comment by zhangtiny123** [comment]
@mumoshu Thanks for your suggestion, but it seems not fit my situation... 

Currently I just delete the tag ```kubernetes.io/role/master``` from my cluster manually, since it seems there's no one else reference the tag, and everything looks OK , but is there any hidden danger?

**Comment by redbaron** [comment]
@zhangtiny123 , just a heads up, that there is new tagging scheme in Kube 1.6, where ALL resources are tagged with `kubernetes.io/cluster/<CLUSTER_NAME>` , and you better not to remove any of those tags, otherwise at least LoadBalancer services wont be able to create ELBs

**Comment by mumoshu** [comment]
@zhangtiny123 Thanks for the reply.
Just a quick thought but can you script to replace every dot with a hyphen(-) or maybe underscore(_) after you've fetched the instance data? so that dots on original keys won't affect MongoDB

**Comment by zhangtiny123** [comment]
@mumoshu Thanks man, good idea ! 

@redbaron I've already add it back... thanks for your patience
