### ISSUE TITLE
Controllers nodes need security group glue

### ISSUE THREAD

**Issue by drywheat** [kubernetes-incubator/kube-aws#375]
### Versions

**kube-aws**: v0.9.3-rc.5
**kubernetes**: v1.5.1

### Problem

I want to create a DaemonSet and have the Pods it spawns (including the controller nodes) connect to an existing service I have running in the same AWS VPC. Currently, I am only able to link K8s worker nodes to existing services using the `workerSecurityGroupIds` attribute in the kube-aws **cluster.yml**.

Does it not make sense to also enable that feature for controllers and consume an attribute called `controllerSecurityGroupIds`?

**Comment by mumoshu** [comment]
@drywheat Thanks for your feedback!
Although the key should better be `controller.securityGroupIds` or even `controller.securityGroups[].id`; Yes, I like your suggestion 👍

**Comment by drywheat** [comment]
I wish I knew go well enough to submit a PR. I'm might try looking at this over the weekend.

**Comment by mumoshu** [comment]
Thanks @drywheat, have you had any chance to work on it?

**Comment by drywheat** [comment]
I just started hacking on this today.

**Comment by jcastillo-cb** [comment]
this sounds like fixed in #552 , #560

**Comment by mumoshu** [comment]
@jcastillo-cb Ah, definitely! I got to add `controller.securityGroupIds` to support the use-case of reusing an existing ELB for an API endpoint. Without the `controller.securityGroupIds`, the ELB seemed to not work until you manually assign a "glue" SG to controller nodes.

So - I believe we can close this now.
Thanks for chiming in 👍
