### ISSUE TITLE
Kubernetes Rebalancing the deployed applications after rolling upgrade of workers

### ISSUE THREAD

**Issue by billyteves** [kubernetes-incubator/kube-aws#380]
Here's my case for my testing:
2 controllers
1 etcd
2 workers
2 subnets from two different availability zone, region us-east-2
kube-aws 0.9.3
hyperkube 1.5.1
Hello-world application deployed to both workers with 10 replicas

rolling upgrade: upgrade AMI ID CoreOS.

After triggering the command `kube-aws update --s3 <path>`, CloudFormation updates. First rolling upgrade on controllers, one-at-a-time. done, no issues. Then here comes the worker's rolling upgrade. Takes down the first worker which before shutting down, kubernetes rescheduled all the running pods to the second worker. Completed. No issues. Then the second worker is being terminated and up, all the deployments in that second worker goes to the first worker. After the completion and health check of the second worker, I was expecting that there will be another rescheduling to rebalance the deployments on the two updated workers. Unfortunately, it only stays on the first. I am not sure if that is to be expected.

**Comment by c-knowles** [comment]
Hi @billyteves, I've experienced the same thing and think right now it's expected although obviously less than desired. I believe the extra rescheduling you mentioned does not happen by default in Kubernetes at of 1.5. For critical Kubenetes functionality this should hopefully be covered by https://github.com/coreos/kube-aws/issues/118 but if the deployments are your own apps I think https://github.com/kubernetes/kubernetes/issues/12140 may be more relevant. I'm not sure if there is a way we could trigger a reschedule on cluster update at this stage, @mumoshu any ideas?

**Comment by mumoshu** [comment]
Hi @billyteves!
I agree to @c-knowles's summary.
It is an expected behavior as of today. Basically, we need to contribute the upstream to make rescheduler covers such case.

**Comment by billyteves** [comment]
@c-knowles thank you for explaining the behavior and tagging the ticket of kubernetes repo. Yes, I think there should be a reschedulesr after cluster upgrade or worker upgrade because if not, the worker load is imbalance. Like what happened on my test case. The work around for me, I just up another worker. Once up, I just remove it again (change again the desired count to 2). With that, the two worker nodes have both my deployment applications.

**Comment by whereisaaron** [comment]
@billyteves you can use two identical node pools to do this cleanly, one pool with no workers and one pool with X workers. To upgrade, scale up the no workers pool to X workers, then cordon all worker on the original pool and scale it down to zero workers. You get evenly scheduled Pods afterwards that way, plus you avoid Pods being rescheduled more that once during the upgrade.

**Comment by billyteves** [comment]
@whereisaaron I see, that's a good one. I think I'm going to try this. Sadly, some of my test cluster that is 0.8.3 does not work for node pool. But yeah, moving forward, node pool is much better and I think easy-to-manage. Kudos guys!

**Comment by krmayankk** [comment]
@bsalamat @davidopp is this something on the charter of scheduling and is this something already supported ?

**Comment by krmayankk** [comment]
yep just found out, just thinking out loud why isnt this part of core kubernetes may be as a scheduler policy etc, i want this to take this discussion to kubernetes/kubernetes

**Comment by bsalamat** [comment]
As we chatted on Slack and c-knowles has also mentioned, this is done by "descheduler". The plan is to integrate descheduler into Kubernetes, but the timeline is not determined yet.
cc/ @aveshagarwal
