### ISSUE TITLE
question: cluster update

### ISSUE THREAD

**Issue by yawboateng** [kubernetes-incubator/kube-aws#391]
what is the recommended way to upgrade a production cluster to the latest from an older version of kube-aws without much impact or outage.

https://github.com/coreos/kube-aws/blob/master/Documentation/kube-aws-cluster-updates.md

Can I just go in and run the full update steps in the documentation? or should I spin up a new cluster and cut the traffic over from the old to new environment?

**Comment by mumoshu** [comment]
Hi @yawboateng, thanks for using kube-aws!
Sorry for the silence but would you mind reading #455 for more information?
Basically, I'd recommend recreating your cluster while in pre-1.0.

**Comment by yawboateng** [comment]
Thanks @mumoshu, 

closing this, question answered in  #455

**Comment by mumoshu** [comment]
Thanks for the confirmation @yawboateng!
Btw, I'd appreciate any suggestion(s) to #455. I do want to upgrade my clusters in a more easier way myself 😆
