### ISSUE TITLE
Specifying which KMS key to be used for etcd data volume encryption

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#393]
This feature request is derived from https://github.com/coreos/kube-aws/issues/383#issuecomment-284662241

Can we just reuse the key specified with `kmsKeyArn` for data volume encryption, too?

**Comment by mumoshu** [comment]
@swestcott I've created an another issue for your feature request

**Comment by swestcott** [comment]
@mumoshu I've had a go at implementing this (https://github.com/swestcott/kube-aws/commit/394b1f0d634a7dde963d3c249d6ef993b0088e22), does this look like a sensible approach? If so, I'll add a test and sort out a PR.

**Comment by swestcott** [comment]
Note to self (or whoever picks this up), attempting to reattach an encrypted volume errors with,

```
aws ec2 attach-volume --volume-id vol-xxx --instance-id i-yyy --device /dev/xvdf
An error occurred (CustomerKeyHasBeenRevoked) when calling the AttachVolume operation: Volume vol-xxx cannot be attached. The encrypted volume was unable to access the KMS master key.
```

Widening https://github.com/coreos/kube-aws/blob/master/core/controlplane/config/templates/stack-template.json#L275 ti `kms:*` works, but clearly overly permissive.

**Comment by mumoshu** [comment]
@swestcott Added a comment to your commit.

**Comment by mumoshu** [comment]
Thanks for your efforts there!
If I understand correctly, on top of your commit, just configuring `cluster.yaml`:

```yaml
etcd:
  kmsKeyArn: <your key for volume encryption>
```

and adding the following policy:

```json
{
  "Action" : "kms:Decrypt",
  "Effect" : "Allow",
  "Resource" : "{{$.Etcd.KMSKeyARN}}"
}
```

to our etcd IAM role would do the job without making it overly permissive?

**Comment by swestcott** [comment]
@mumoshu During my testing I found `kms:decrypt` isn't sufficient to re-attach an encrypted volume on a new EC2 instance (see above `CustomerKeyHasBeenRevoked` error). I pinged AWS support last week and they've come back with the following suggestion which I'll try,

```
            "Action": [
                "kms:CreateGrant",
                "kms:Decrypt",
                "kms:Describe*",
                "kms:Encrypt",
                "kms:GenerateDataKey*",
                "kms:ReEncrypt*"
            ],
```

**Comment by mumoshu** [comment]
@swestcott Any news on this? 😈

**Comment by swestcott** [comment]
The patch is done, just needs an end-to-end before I raise the PR. Having difficultly starting my cluster currently at the moment as etcd bootstrap is failing, both with and without my changes...
