### ISSUE TITLE
Should etcd EBS volumes have deletion policy set?

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#395]
If an etcd instance is terminated the default behaviour is to also delete the EBS. Does this affect the [etcd recovery](https://github.com/coreos/kube-aws/pull/332) given that it relies on the EBS volume? I haven't tested it yet, it's just something I noticed so far with v0.9.4 RC2.

If the above does affect it, we may wish to add `DeletionPolicy` of `Retain` or `Snapshot` on the [AWS::EC2::Volume](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-ebs-volume.html#d0e62602) created for etcd?

**Comment by mumoshu** [comment]
After #332, etcd data volumes are attached and de-attached dynamically but not deleted.
If you'd like volumes to be retained or snapshotted when the cloudformation stack is destroyed, we could set `DeletionPolicy` though.

**Comment by c-knowles** [comment]
Does that dynamic attach/detach happen when terminating an instance on the AWS Console?

**Comment by mumoshu** [comment]
Yes, it is automatically detached by EC2 on termination and attached by our
script on instance startup
2017年3月10日(金) 16:30 Chris Knowles <notifications@github.com>:

**Comment by c-knowles** [comment]
OK sure. Then I will just ignore this for now and we can close the issue. I'm not sure adding instance termination policy is even possible in an ASG, at least not under all circumstances.

**Comment by mumoshu** [comment]
Thanks for the confirmation 👍 

Just to be clear; AFAIK, when an EBS volume definition is one embedded in a launch configuration, we can explicitly set `DeleteOnTermination` to `true` to retain volumes after an EC2 instance managed by an ASG is terminated.

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-launchconfig-blockdev-template.html

However, as the current kube-aws implementation doesn't embed a volume definition into a launch configuration but rather define separately, it doesn't get deleted on an EC2 instance termination.
