### ISSUE TITLE
Travis build and kube-aws occasionally fails while fetching Container Linux AMI data

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#396]
Producing an error like:
> failed getting AMI for config: error getting ami data for channel stable: failed to get AMI data: stable: Get https://coreos.com/dist/aws/aws-stable.json: dial tcp [2400:cb00:2048:1::6814:2fec]:443: connect: network is unreachable

Perhaps we'd better mock out?

**Comment by c-knowles** [comment]
I've had the same on an actual deploy, perhaps worth adding a retry as well?

**Comment by mumoshu** [comment]
It occurred for me, too. Adding a retry would be better.

**Comment by mumoshu** [comment]
Followed up with #442
