### ISSUE TITLE
`.enc` credential files not recreated if existing on `kube-aws validate`

### ISSUE THREAD

**Issue by BertHartm** [kubernetes-incubator/kube-aws#402]
I was having issues with a bad certificate (was using the wrong domain), so I re-rendered credentials and redeployed.

I was still hitting the issue, and noticed that the timestamps for the `.enc` files in the credentials folder were older than the `.pem` files they corresponded to. Removing the credentials files and redoing the whole process fixed the issue.

**Comment by BertHartm** [comment]
I hit this after testing the fix for #397, which worked great (once I got the right set of credentials up). Thanks for the quick response.

**Comment by c-knowles** [comment]
Can confirm I hit the same thing but thought it was since I was upgrading from some custom generated certs. I ended up entirely removing the certs apart from the CA and restarting to cluster creation.

**Comment by mumoshu** [comment]
@BertHartm Thanks again for the feedback.
Only `.enc` files are uploaded to S3 to be read from EC2 instances created by kube-aws. So, what you'd need to remove would be only `.enc` files, which are automatically regenerated from non-enc files if missing

**Comment by mumoshu** [comment]
I want to improve the UX here.
Can I just automatically regenerate `.enc` files if matching non-enc files are updated?

**Comment by mumoshu** [comment]
Note: probably I'll introduce something like `*.pem.hash` to keep the hash of the pem file paired with a `.enc` file and regenerate `.enc` file whenever the newly calculated hash of the pem file doesn't match against the one kept in the `.hash` file.

**Comment by mumoshu** [comment]
Almost certainly #418 is also affected by this issue
cc @danielfm

**Comment by mumoshu** [comment]
The fix is ongoing in #426. It is already working for TLS assets. I'll make a follow-up for #418 soon

**Comment by mumoshu** [comment]
Note: this is confirmed to be fixed in https://github.com/kubernetes-incubator/kube-aws/issues/402#issuecomment-285392973
