### ISSUE TITLE
TLS bootstrapping with the cluster-level CA

### ISSUE THREAD

**Issue by danielfm** [kubernetes-incubator/kube-aws#406]
Kubernetes 1.4 introduces an [experimental API](https://kubernetes.io/docs/admin/kubelet-tls-bootstrapping/) for requesting certificates from a cluster-level Certificate Authority (CA) for TLS client certificate bootstrapping for kubelets.

What do you guys think about this? Do you consider adding this to kube-aws at some point?

**Comment by mumoshu** [comment]
Hi @danielfm!
Yes. Perhaps once kubeadm automated the approval process. AFAIK, it requires us to manually run `kubectl approve`.

**Comment by danielfm** [comment]
According to the documentation, you can set the `--insecure-experimental-approve-all-kubelet-csrs-for-group` flag to the group (specified via `--token-auth-file`) used to send the certificate signing requests.

**Comment by mumoshu** [comment]
Thanks for the info!
Just to be clear, the flag is not intended for production-use:

> Use of this flag circumvents makes the “approval” process described below and is not recommended for production use.

It'll be automated via an external controller in the future according to:

> This is intended to eventually be an automated process handled by an external approval controller, but for the alpha version of the API it can be done manually by a cluster administrator using kubectl

**Comment by danielfm** [comment]
Just took a quick look at kube-adm, it seems to be [using this experimental flag](https://github.com/kubernetes/kubernetes/blob/v1.5.4/cmd/kubeadm/app/master/manifests.go#L280) for the TLS bootstrapping.

**Comment by xdrus** [comment]
@mumoshu 
> It'll be automated via an external controller in the future according to...

Do you know any specific plans on it or alpha/beta projects? I'm using [heptio-authenticator](https://github.com/kubernetes-sigs/aws-iam-authenticator) for worker nodes and it works like a charm, but I need to auto-sign kubelet server certificates to make kubectl logs/exec/port-forward commands work in a cluster. As far as I can see right now kubelet generate clients and server certificates in a bit different ways (NewKubeletClientCertificateManager and NewKubeletServerCertificateManager [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/certificate/kubelet.go)) and the main difference that client's certificate signing request doesn't include IPs and DNSnames of a host. And [this line](https://github.com/jcbsmpsn/kubernetes/blob/master/pkg/controller/certificates/approver/sarapprove.go#L183) in auto approver controller prevents them from being auto signed.

I would love to do this automatically, but can't find the way, as '--insecure-experimental-approve-all-kubelet-csrs-for-group' doesn't work for me too.

**Comment by jpsriram** [comment]
Looks like, the experimental flag '--insecure-experimental-approve-all-kubelet-csrs-for-group' for kube-controller-manager has beed removed in version 1.13  [1]

[1] https://github.com/kubernetes/sig-release/blob/master/releases/release-1.13/release-notes-draft.md
