### ISSUE TITLE
Feature: API client certs on controllers

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#409]
While looking at [fluent-plugin-kubernetes_metadata_filter](https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter), I found it has some configuration to set CA and cert files. If running this under a Daemon Set, the ideal situation is to have API client certs in a uniform place across the control plane and worker node pools so it's possible to mount it as read only.

It's currently possible to connect to `http://localhost:8080/api` on controllers to access the kube API but there are no API client certs available as far as I can see. Would it be possible to also place API client certs on the controllers? I'm not sure if this poses any additional issues/risks.

There may be some overlap with https://github.com/coreos/kube-aws/issues/335.

**Comment by redbaron** [comment]
why it can't use service account credentials?

**Comment by c-knowles** [comment]
Ah yes, [it does support that](https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/master/lib/fluent/plugin/filter_kubernetes_metadata.rb#L133) but I had previously missed that point somehow. Ignore this issue then, user error 😆

**Comment by c-knowles** [comment]
Thanks @redbaron, we can close this issue.

**Comment by mumoshu** [comment]
Thanks to both for the info 👍

**Comment by c-knowles** [comment]
@redbaron @mumoshu @pieterlange are any of you successfully using service account credentials from pods on HA controller nodes? I'm experiencing frequent pod termination due to kube API timeouts whereas the same pod setup functions perfectly on workers (not just fluentd but pods from other daemonsets).

**Comment by mumoshu** [comment]
@c-knowles Haven't tried it yet myself 😢 
Could you raise an another issue if you could have a step to reproduce the issue?

**Comment by redbaron** [comment]
@c-knowles AFAIK service accounts are used by Calico pods and they seem to wok fine.
