### ISSUE TITLE
Manually changing CloudFormation - want to update stack (cloud init), possible?

### ISSUE THREAD

**Issue by martindanko** [kubernetes-incubator/kube-aws#410]
After creating a stack, I manually changed the cloud formation stack to add security groups and RDS instances, I now need to change cloud-init to include extra API extensions, if I change this on the controller node and re-render my stack and update, will it delete my RDS instance and security groups?

**Comment by mumoshu** [comment]
Hi @martindanko!
Your case is really up to how CloudFormation works, rather than kube-aws so I'm afraid to say concretely because I can't guarantee anything but; No, it won't delete your RDS instance as long as you don't have any change to the definition of a RDS instance.
Also, I'd suggest to consider using [CloudFormation Change Sets](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-changesets-create.html) to see changes being made before you actually apply updates to a stack.

**Comment by mumoshu** [comment]
Hi @martindanko, did my answer make sense to you?

**Comment by martindanko** [comment]
Hi @mumoshu - Yes it made sense. Thanks for answering my question.

Basically, I've concluded, provision the cluster with kube-aws, export the cloud formation template and just update the stack using pure cloud formation. If I want to do a cluster level update (not AWS specific updates), I re-generate using kube-aws and export that and do a diff on the two cloud formation templates and apply via diff what's not present in the one generated via kube-aws.

Doing this is quite long winded - but it works. I was basically wondering whether kube-aws has a more robust way of doing this. I've tried just apply an kube-aws update and it does indeed delete resources it doesn't know about.

I should; when I get some spare time take a look at cloud formation change sets, thanks for pointing it out. 

Thanks again,

Martin.

**Comment by mumoshu** [comment]
Thanks Martin,
Ah, it seems like I've misunderstand your use-case.
Let me suggest you, to create a completely separate cloudformation stack for your SGs and RDS instances, outside of kube-aws.
Then, you can reference the SGs by putting their security group IDs into `worker.nodePools[].securityGroupIds`. This way, you don't need to manually customize the stack template generated by kube-aws anymore?

**Comment by mumoshu** [comment]
Hi @martindanko, just confirming but did my suggestion make sense to you? 😄

**Comment by martindanko** [comment]
Hi @mumoshu - yes that totally makes, I do apologise but I didn't see your penultimate answer and that one seems the most sensible. Thanks for your insights into this. :+1: 

Martin.

**Comment by mumoshu** [comment]
@martindanko Thanks for the reply! I'm happy that I could help you.
