### ISSUE TITLE
kube-apiserver TLS handshake errors from controller IPs that no longer exist

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#415]
Using v0.9.5-rc.3 and stable Container Linux (1298.5.0), I'm experiencing some odd kube-apiserver behaviour. I'm not sure exactly where the issue is yet so wondered if anyone had seen similar.

I have two setups experiencing this. One has a few worker node pools and 2 controller nodes and the other only has a single controller node.

Taking the example of the HA controller setup:
* Controller subnets are 10.0.53.0/24, 10.0.54.0/24, 10.0.55.0/24
* Workers and etcd are all in subnets 10.0.50.0/24, 10.0.51.0/24, 10.0.52.0/24
* Service CIDR of 10.3.0.0/16

I have terminated some of the controller nodes in both setups via `kube-aws update` (just to update the k8s patch version) and also manually to try out the HA setup. All the apiserver pods look healthy from the perspective of they are running/up but they are continuously logging the following:

```
http: TLS handshake error from 10.0.55.125:61975: EOF 
http: TLS handshake error from 10.0.54.210:18575: EOF 
http: TLS handshake error from 10.0.53.191:20347: EOF 
http: TLS handshake error from 10.0.55.125:61971: EOF 
http: TLS handshake error from 10.0.54.210:18569: EOF 
http: TLS handshake error from 10.0.53.191:20339: EOF 
```

The controllers currently have IPs of 10.0.53.204 and 10.0.54.207. It seems that these are IPs from previous controller nodes that do not exist any more. So I'm a bit confused about where this traffic is originating from. I've tried various diagnostics but didn't find much, any ideas welcome.

**Comment by mumoshu** [comment]
Can you ping to one of those IPs? If it responds, I guest it is coming from underlying machines backing an ELB. See https://github.com/kubernetes-incubator/kube-aws/issues/295

Even before running `kube-aws update`, I'm seeing the same-looking errors:

```
I0316 02:51:18.633833       1 logs.go:41] http: TLS handshake error from 10.0.0.133:48904: EOF
I0316 02:51:21.277178       1 logs.go:41] http: TLS handshake error from 10.0.0.10:29234: EOF
I0316 02:51:28.634010       1 logs.go:41] http: TLS handshake error from 10.0.0.133:48912: EOF
I0316 02:51:31.276491       1 logs.go:41] http: TLS handshake error from 10.0.0.10:29246: EOF
```

In my case, non of those IPs are assigned to my EC2 instances.

**Comment by redbaron** [comment]
These are ELB interfaces,if you lis tall your network interfaces, you  find those IPs there and ENIs are assigned to ELB

**Comment by c-knowles** [comment]
Yes I tried to ping and determine what they are before filing the issue. Also saw #295 but couldn't find the IPs previously. However, I've just repeated the same thing and found they are ELB interfaces. Not sure how I missed that as I specifically checked it, my guess is I checked the wrong region. I'm having a good week! Let's close this as a dupe of #295.

**Comment by mumoshu** [comment]
Thanks for confirmation 👍 
Closing this in favor of #295
