### ISSUE TITLE
support subCAs

### ISSUE THREAD

**Issue by Thermi** [kubernetes-incubator/kube-aws#435]
As far as I know and could test, kube-aws (and kms) don't seem to be able to handle
subCAs. To authenticate a TLS server, it must present the root certificate, any intermediate (sub) CAs and the leaf certificate of the server itself. Currently, it is not possible to provide kube-aws with a multi tiered PKI (sub CA) which to use for the different certificates the kubernetes cluster requires.
For a production ready system, that is required, because different branches of an organization will have different sub CAs under a common root CA and nobody will give the root certificate's key into a cloud environment. The proper way to handle this is to enable kube-aws to handle a root CA, arbitrary sub CAs and a key for a sub CA.

**Comment by mumoshu** [comment]
@Thermi Thanks for the feedback!
I'm afraid if I'm following you correctly but;
* Do you want kube-aws to use sub-CA and the key to sign certs generated by kube-aws? If so, would `kube-aws render credentials --ca-key-path ... --ca-cert-path ...` while bringing your own sub-CA cert&key pair work? Perhaps you'd need to include both a root CA and the sub CA in the cert file passed to `--ca-cert-path`?
* Or do you want kube-aws to generate sub-CA signed by a root-CA [here](https://github.com/kubernetes-incubator/kube-aws/blob/master/tlsutil/x509.go#L58)? However, it would imply passing the root CA key to kube-aws and I suppose that's not what you want

**Comment by Thermi** [comment]
I want kube-aws to 
1) take an existing PKI structure with an arbitrary number of CA certificates and use it to authenticate other TLS peers
2) take an existing subCA certificate and key to issue the certificates with

I already tried storing several CA certificates in a file in a previous version, but KMS complained the file size was too large. I don't have a way to test it with the new version right now, but I might in a couple of days.

**Comment by mumoshu** [comment]
Ah, certainly we're hitting kms's 4kb limit in size of plaintext to be
encrypted. We can avoid the limit by encrypting our data key at first and
then use the key to actually encrypt/decrypt our pem files, as recommend in
kms docs.
Once we work arounded the kms limit, would the current solutions,
--ca-cert-file and --ca-key, be fine? Or do you still need an another
feature to handle sub CAs in an another way?
2017年3月23日(木) 19:00 Thermi <notifications@github.com>:

**Comment by Thermi** [comment]
Hm. A more versatile solution would be nice. Imagine using another coreos image with custom changes that use the same PKI that is provided by kube-aws via the userdata section, but with seperated CA certificates (one CA certificate per file), or in the format that openssl creates it under /etc/ca-certificates/extracted/cadir on Arch. In the latter format, symlinks from hashes of the files are created pointing to the original certificates in the same directory. Something like that would be nice.
But of course, it's not necessary just for supporting a PKI infrastructure. It's just this idea thought to the end.
