### ISSUE TITLE
Fix locksmith etcd-lock reboot strategy

### ISSUE THREAD

**Issue by Thermi** [kubernetes-incubator/kube-aws#436]
Right now, the reboot-strategy "etcd-lock", which is the only suitable one for a HA cluster, doesn't work and is disabled by default (reboot-strategy: "off").
To make a production ready cluster, automatic updates which don't impair or disrupt the cluster's operation have to be possible.

**Comment by mumoshu** [comment]
@Thermi Thanks for creating the issue 👍 
I personally prefer to turn it off for my production clusters so that I have a complete control over when to automatically upgrade Container Linux for nodes.
Would it be enough to allow selecting a reboot strategy per sub-clusters including etcd, controller, each worker node pool?

**Comment by mumoshu** [comment]
Related: https://github.com/kubernetes-incubator/kube-aws/issues/240

**Comment by Thermi** [comment]
I think selecting a reboot strategy per sub-cluster would be fine.
I like clusters to take care of themselves as much as possible to keep down OPEX and possibility for human error.

**Comment by mumoshu** [comment]
Thanks for the confirmation 👍 
I generally agree to you.
JFYI, probably you may already know but to be clear; I believe we need an extra care to have enough replicas and/or extra nodes to allow your services to be kept up and runnig while upgrading Container Linux over all the nodes. Please see the relevant discussion at https://github.com/kubernetes-incubator/kube-aws/issues/240#issuecomment-272134598

**Comment by Thermi** [comment]
Yes, sure. That's the point of the etcd-lock: To ensure only one node reboots at a time.

**Comment by c-knowles** [comment]
Could we replace this one and https://github.com/kubernetes-incubator/kube-aws/issues/240 with an issue to support https://github.com/coreos/container-linux-update-operator?

**Comment by mumoshu** [comment]
@c-knowles I believe so 👍
