### ISSUE TITLE
Repository Renamed but not Code?

### ISSUE THREAD

**Issue by jeremyd** [kubernetes-incubator/kube-aws#450]
I noticed this repository changed from github.com/coreos/kube-aws to github.com/kubernetes-incubator/kube-aws.  However, the code still imports from the old github.com/coreos/kube-aws.  Should we rename all these imports to kubernetes-incubator?  Otherwise, we can't compile in a fresh checkout.

**Comment by mumoshu** [comment]
Thanks for the report and the PR 👍 
Closing this as #451 is merged.
