### ISSUE TITLE
Document recommendations on rollingUpdateMinInstancesInService

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#458]
Extracted from https://github.com/kubernetes-incubator/kube-aws/issues/283#issuecomment-283669466

**Comment by c-knowles** [comment]
I can pick this up, where would you like it documented?

**Comment by mumoshu** [comment]
Thanks!
How about adding `Documentation/kubernetes-on-aws-high-availability.md` and a section explains about `rollingUpdateMinInstancesInService`?
Perhaps linking it from a newly added `kubernetes-on-aws-going-producion-checklist` would be even better.
