### ISSUE TITLE
Assign the kube-admin user to the super-user role

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#461]
Extracted from https://github.com/kubernetes-incubator/kube-aws/issues/344#issuecomment-282001008

**Comment by mumoshu** [comment]
Hi @ankon!

I'm revising your old commnt in https://github.com/kubernetes-incubator/kube-aws/issues/344#issuecomment-282001008:
> Looking at other recent changes in that area: with k8s 1.5+ this change would make it unneeded to add the /srv/kubernetes/rbac/cluster-role-bindings/kube-admin.yaml (#230) binding I think: having the kube-admin user assigned to the super-user role removes the need to further provide any role bindings for that user. 

As of today, `kube-aws` user is assigned the `cluster-admin` role. Is this what you meant?
https://github.com/kubernetes-incubator/kube-aws/blob/8e0f0e9/core/controlplane/config/templates/cloud-config-controller#L1080
If so, can we close this issue now?

cc @danielfm

**Comment by ankon** [comment]
Actually, I still think that the whole kube-admin.yaml is unneeded now, as kubernetes will use the information from the certificate to figure out that kube-admin is member of the 'systems:master' group, and that group gets 'cluster-admin' by default.

See the table 'User-facing Roles' on https://kubernetes.io/docs/admin/authorization/rbac/#default-roles-and-role-bindings.

**Comment by mumoshu** [comment]
We need some love for this issue :)
