### ISSUE TITLE
document possible git workflow

### ISSUE THREAD

**Issue by redbaron** [kubernetes-incubator/kube-aws#462]
there are many requests coming in for feature which are alredy possible to be implemented without  a change to kube-aws. Deepest level of customisation can be achieved with simple git workflow:

Initial setup:
 1. `git checkout --orphan vanilla` creates `vanilla` branch with no history
 1. `kube-aws init --cluster-name CHANGEME ....  && git add .&& git commit -m "update with $(kube-aws version)"` - create initial structure and commit it with no modifications/customizations. All mandatory values are `CHANGEME` placeholders
 1. `git checkout -b cluster/main1 vanilla` - create new branch based on latest vanilla
 1. `vim cluster.yaml; vim userdata/....; git commit -m "my changes to cluster1"` - apply any customization to your templates,userdata, cluster.yaml etc. Feel free to change security groups, IAM roles,add ebs volumes, whatever...

Updating to new kube-aws:
 1. `git checkout vanilla` - go back to vanilla branch.
 2. `rm -rf * && kube-aws init --cluster-name CHANGEME && git add .  && git commit -m "update with $(kube-aws version)"` - create new version of vanilla commit, replacing entire content of previous one. Because there were no modifications to it, no need to carefully merge changes or anything
 3. `git checkout cluster/main1 && git merge vanilla` - pull changes from recent vanilla into your cluster branch, resolve conflicts, remove obsoleted bits etc.

Important thing is that every commit to vanilla must be a direct result of `kube-aws` calls,no editing afterwards.they use power of git to propagate those changes to your heavily customized clusters.

If you have multiple cluster branches, you can use `git rerere` to avoid redoing conflicts resolution for each one of them when it is possible.

If there are many cluster branches, it is benefitial to have additional level in the form of `tailored` branch,which is created from `vanilla` ,but contains customizations needed by all clusters. Cluster branches then pull changes not from `vanilla`, but from `tailored`.

Maybe we should add suggested workflow like that to official docs?

**Comment by mumoshu** [comment]
Definitely! How about adding `Documentation/kubernetes-on-aws-workflow.md` with a title like "Recommended workflow for managing multiple kube-aws clusters in code"? The shorter the better though 😃
