### ISSUE TITLE
Suggestion for consolidating our efforts

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#464]
To be short, I'd like to find a way to merge our efforts in the area of kubernetes deployment tools.
Would "you" mind suggesting how's and/or express agreement(s) to one of the suggestions possibly in this thread?

Please read [the kubernetes-dev thread](https://groups.google.com/forum/#!topic/kubernetes-dev/diN0KIOpLro) for more context.

Merging our efforts would enable:

* Every kubernetes user easily get to one or two appropriate tools according to one's requirements
* We, tool developers, won't need to redo works already done for another tools

The list of tools includes:
* kube-aws
* kops
* kargo
* kubernetes-anywhere
* bootkube
* kubeadm
* etc.

---

As of today, kube-aws already plans to [integrate with bootkube in the future](https://github.com/kubernetes-incubator/kube-aws/blob/master/ROADMAP.md#v09x).

However I want more; just for example, how about merging kube-aws into kops? More concretely, I imagine about kube-aws being the cloudformation provider for kops.

Of course, being one of providers for kops doesn't mean kube-aws can lose the following important features:

* Manageable with SCM like Git to support customizations of clusters (#238)
* Based on CloudFormation 😃 
* Integrated node pools
* H/A everywhere
* Flexibility to allow customizing via cluster.yaml, stack template templaets, stack templates, userdata
* Bring your own AWS resources to be used (where necessary, where possible)
* Various work-arounds to go beyond AWS limits(16KB in userdata, 512KB in cfn stack template's size)
* etc.

I'll keep every aspect of kube-aws for our current users, as much as possible. However, I don't believe that is something prevents us from merging our efforts.

Personally, [I suggested in sig-aws about merging kube-aws into kops](https://groups.google.com/forum/#!topic/kubernetes-sig-aws/L1E2F2Easbw).
Would someone agrees and/or wants to take a leadership to make it a reality?

**Comment by redbaron** [comment]
I appreciate effort to avoid duplication, but merging with kops would be a major disappointment for us, for following few, but very important reasons:
 1. kops codebase is huge, last time I checked it was ~40k LOC vs ~4k LOC in kube-aws (excluding tests and vendored libs). Kops tries to reimplement what TF/CF do well. Relative ease of adding custom features to  a tool influenced our choice significantly.
 2. ease of adding features _without_ modifying a tool.  Intermediate template which is then rendered into a massive CF stack is life saver. It provides endless flexibility in what one can do. Many features which started like flags in `.customSettings` were contributed back to kube-aws. Closest we can get to in `kops` would be to render terraform and then ammend it, but `kops` model doesn't have clean and easy to understand vars + template files, so making similar customisations won't be as easy.

**Comment by c-knowles** [comment]
I have also been following developments here, mostly kops and kubeadm. kube-aws has been doing really well recently in terms of production readiness and other new features, thanks @mumoshu 🙇. Even with this, I think we could benefit from the additional community of the kops project.

Definitely agree with @redbaron about CloudFormation and customisation. It's not an obvious combination at first with kops. I suppose if the parts of kops that manage state are/were separated out and there's some good interfaces to plug in kube-aws like functionality or bypass the state management then perhaps there's some way to combine.

**Comment by rochdev** [comment]
I concur with merging with another project. It's still quite difficult to find a stable solution for deploying/managing kubernetes clusters because the community effort is so spread out at the moment.

**Comment by c-knowles** [comment]
Interestingly I believe kops has some support for Container Linux and also CloudFormation now.

**Comment by mumoshu** [comment]
@rochdev Thanks for the feedback 👍 Yeah, I think so too.

Anyway, the problem is that we as the whole k8s community still don't know how it can be achieved without bloating code-base or slowing-down the development.

For example, how can we merge kops(multi os, terraform/cfn/cloudup, go), kubespray(ansible-based), kube-aws(cfn, bash, cloud-init) into one? Extracting a common provisioning scripts from these into an another project and use it all over the places? Wouldn't it slow down the development?

Similarly, for example, how can we merge kops and kube-aws without fattening code-base too much? kube-aws as a kops plugin or vice versa? How and who takes lead?

For me, integrating bootkube seems to be the only way to go ahead with consolidating our efforts without big down-side. WDYT?

**Comment by mumoshu** [comment]
@c-knowles FYI hereis a bit more context on that: https://groups.google.com/forum/#!topic/kubernetes-sig-aws/L1E2F2Easbw

**Comment by c-knowles** [comment]
Thanks @mumoshu! It seems there is a reply in that thread worth looking at and some confusion over who the owner of kube-aws. I now consider that to be you rather than CoreOS since they seem to be concentrating on Tectonic primarily. As for backing and getting this done, happy to help out in any way I can.

**Comment by camilb** [comment]
@mumoshu @redbaron @danielfm @c-knowles   I'm traveling this month and don't have time to investigate it but [kubecorn](https://github.com/kris-nova/kubicorn/blob/master/docs/aws/walkthrough.md) looks very promising.

**Comment by mumoshu** [comment]
I basically agree - Not sure if re-invention of terraform or cfn is
sustainable. I definitely like it being just an idiomatic go library to
define a uniform interface among various tools and cloudproviders though!
2017年7月19日(水) 22:04 Camil Blanaru <notifications@github.com>:

**Comment by discordianfish** [comment]
I'm right now looking into kubernetes deployment options on AWS.
At a first glance it seems to me, never having used kops nor kube-aws before, that kube-aws was built because some people weren't happy with design decisions in kops as mentioned by @redbaron.

So I think more important than merging efforts would be to clarify the difference and maybe different believes behind the design. That would make it much easier for me to figure out which option I prefer.

**Comment by ctownsen357** [comment]
Just adding another comment to consider and this is just my opinion.  I've recently tried using both kops and kube-aws to deploy to AWS GovCloud.  So far I have not been able to do that with kops.  It was rather trivial to do with kube-aws.  The major hurdles for kops on GovCloud are:
- The AMIs being used by kops don't exist on GovCloud
- Route53 doesn't exist as a service on GovCloud
- The documentation for possible workarounds is very fragmented

kube-aws works on AWS Govcloud VERY well and very easy.  I'd hate to see a merge take away any of the simplicity of kube-aws.
