### ISSUE TITLE
Flannel intermittantly fails to startup, error indicates wrong reverse DNS?

### ISSUE THREAD

**Issue by jeremyd** [kubernetes-incubator/kube-aws#477]
I had a new cluster fail to come up.. The error is pasted below with the IP replaced by xx-xx-xx-xx.  It looks like something told flannel the ETCD ip address had a suffix of "compute-1.amazonaws.com".  I've never seen this before and it should be (as stated in the log) one of us-east-1.compute.internal or simply ec2.internal.  When I deleted and created the exact same cluster, it worked the 2nd time.  Should we add compute-1.amazonaws.com to the list of allowed suffixes? (an easy change).

```
Mar 29 19:03:36 ip-xx-xx-xx-xx.ec2.internal etcdctl[27962]: Error:  x509: certificate is valid for *.us-east-1.compute.internal, *.ec2.internal, not ec2-xx-xx-xx-xx.compute-1.amazonaws.com
Mar 29 19:03:36 ip-xx-xx-xx-xx.ec2.internal systemd[1]: flanneld.service: Control process exited, code=exited status=4
Mar 29 19:03:36 ip-xx-xx-xx-xx.ec2.internal systemd[1]: Failed to start flannel - Network fabric for containers (System Application Container).
Mar 29 19:03:36 ip-xx-xx-xx-xx.ec2.internal systemd[1]: flanneld.service: Unit entered failed state.
Mar 29 19:03:36 ip-xx-xx-xx-xx.ec2.internal systemd[1]: flanneld.service: Failed with result 'exit-code'.
```

**Comment by jeremyd** [comment]
PS this is with the latest code from master using EIPs for etcd discovery.

**Comment by mumoshu** [comment]
Hi @jeremyd, thanks for the report!
That's odd... The cert should already have `compute-1.amazonaws.com` in the list of CNs as coded in https://github.com/kubernetes-incubator/kube-aws/blob/master/model/region.go#L28
Perhaps you've reused certs generated by an older version of kube-aws?

**Comment by jeremyd** [comment]
Ah, ok that must have been it.  I may not have re-generated the credentials.  Thanks! Closing.

**Comment by mumoshu** [comment]
Thanks for the confirmation 👍 
I've opened #478 as a follow-up.
