### ISSUE TITLE
kube-aws 0.9.5 incorrectly reports version

### ISSUE THREAD

**Issue by aschofie** [kubernetes-incubator/kube-aws#482]
ubuntu@ip-172-31-57-109:~/kube-aws$ kube-aws version
kube-aws version 2517c176e5dff10ea6777cec4f5a33e6a46a5a17

**Comment by mumoshu** [comment]
@aschofie Thanks for the report 👍
I'll fix that asap

**Comment by mumoshu** [comment]
Done.
Please reopen if the problem still persists.
Thanks again for the report @aschofie 🍺
