### ISSUE TITLE
Bug: Auth tokens file not found

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#484]
On latest master, perform the following:
1. `init`
2. `render credentials` with any CA
3. `render stack`

On 3, this receives
```
Error: Failed to initialize cluster driver: failed to read/create auth token assets: auth tokens file not found: credentials/tokens.csv

To fix this, please run the following command to create it: kube-aws render token-file
```

Which is ok apart from the output also says:
```
3. (Optional) Add more authentication tokens in ./credentials/tokens.csv
```

I think it's a little bit confusing. The output stating what can be done next probably needs to be improved. Perhaps on `render credentials` it should be saying `render token-file` is next, or it should be optional.

**Comment by mumoshu** [comment]
@c-knowles Thanks for the report :bow:
@danielfm I've missed in my last review that it does generate an empty token file when `kube-aws render` is executed but not `kube-aws render credentials`.
I'm not quite sure what's the best option here but how about making a token file to be optional like @c-knowles suggested?

**Comment by danielfm** [comment]
Thanks for the report.

I'll try a few things and come back here to ask for your feedback.
