### ISSUE TITLE
Reconsider apiserver-count

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#499]
Context: https://github.com/kubernetes-incubator/kube-aws/pull/360

As per https://github.com/coreos/tectonic-installer/pull/136 and https://github.com/kubernetes/kubernetes/issues/22609, I believe we should:

* At least document that to change number of controller nodes, always use `kube-aws update` rather than changing the desired capacity of the controller ASG, to update apiserver-count accordingly.
  * Without that, especially when you've decreased number of controller nodes lower than the original `apiserver-count`, some of endpoints remains unreachable forever(or until you finally increase the number to the original one).

cc @jollinshead

**Comment by mumoshu** [comment]
@c-knowles I believe that the latter case in https://github.com/kubernetes-incubator/kube-aws/pull/360#issuecomment-285565818 relates to this issue. It would result in an error rate of 50% because only 1(minInstancesInService) of 2(minSize) are available while a rolling-update is in progress.

**Comment by jollinshead** [comment]
I agree documentation is a must - the cluster provisioners/supporters should be made aware of the behaviour.

**Comment by redbaron** [comment]
Another option would be to have a termination script similar to node drain, which removes apiserver which is being shut down from etcd

**Comment by mumoshu** [comment]
@redbaron Thanks for the suggestion!
If I understand it correctly, would it work even `apiserver-count` was kept as-is - less than the actual num of controller node?

**Comment by c-knowles** [comment]
@mumoshu yes I see. I wonder if it's possible to simplify here, i.e. remove the option for the user to ensure HA.

**Comment by mumoshu** [comment]
@c-knowles Good point! I guess we can consider that.

Hey @jollinshead, what was your use-case for #360 which required you to ensure the list of k8s api endpoints to be stabilized?
After reading issues like [this](https://github.com/coreos/coreos-kubernetes/pull/823#issuecomment-284505138), I'm wondering if we could omit `--apiserver-count` completely and set `--advertise-address` instead so that we can ensure that api is accessed via LB, without a gotcha like this?

**Comment by redbaron** [comment]
Doesn't it meant that in-kube access to apiserver will happen via non-flannel IP? There can be use cases where pods are resticted not to be able to communicate outside kube

**Comment by mumoshu** [comment]
I believe so - should we also support the use-use that pods are restricted as such?

**Comment by mumoshu** [comment]
Or can we just provide k8s an alternative k8s service to serve k8s api?
The service would have a podSelector with the label `k8s-app: apiserver`.
This can be utilized in kube-aws, whose k8s-apiserver is self-hosted by static pods.

**Comment by mumoshu** [comment]
Hi @jollinshead, I'm still needing your reply on https://github.com/kubernetes-incubator/kube-aws/issues/499#issuecomment-292054205 😃 
Is there any specific reason we can't always set apiserver-count to 1 regardless of actual num of controller nodes?

**Comment by jollinshead** [comment]
@mumoshu I'll configure a cluster with apiserver-count to 1 to test if we see the error message that we had seen previously ```W1205 05:56:14.299380 5 controller.go:392] Resetting endpoints for master service "kubernetes" to &TypeMeta{Kind:,APIVersion:,}``` does not occur.

If there are no issues then we can configure apiserver-count to 1.

**Comment by jollinshead** [comment]
@mumoshu 
The issue we originally had was that the Kubernetes service endpoint kept resetting, I can confirm this still persists if the apiserver-count is less than the actual number. As an example, if we describe the Kubernetes service multiple times we see the endpoint changes from time to time, which in turn causes us problems.
```
kubectl describe service kubernetes
Name:			kubernetes
Namespace:		default
Labels:			component=apiserver
			provider=kubernetes
Selector:		<none>
Type:			ClusterIP
IP:			192.168.128.1
Port:			https	443/TCP
Endpoints:		10.29.183.227:443
Session Affinity:	ClientIP
No events.
➜  ~ kubectl describe service kubernetes
Name:			kubernetes
Namespace:		default
Labels:			component=apiserver
			provider=kubernetes
Selector:		<none>
Type:			ClusterIP
IP:			192.168.128.1
Port:			https	443/TCP
Endpoints:		10.29.183.227:443
Session Affinity:	ClientIP
No events.
➜  ~ kubectl describe service kubernetes
Name:			kubernetes
Namespace:		default
Labels:			component=apiserver
			provider=kubernetes
Selector:		<none>
Type:			ClusterIP
IP:			192.168.128.1
Port:			https	443/TCP
Endpoints:		10.29.168.24:443
Session Affinity:	ClientIP
No events.
```

**Comment by mumoshu** [comment]
@jollinshead Thanks for the info 👍 
Setting apiserver-count to less than the actual number of nodes would result in spamming etcd cluster a little for unnecessarily updating the endpoint info, right?
If that's the only obvious issue implied by the phenomenon, I guess I'm ok with the apiserver-count 1.
WDYT?

**Comment by mumoshu** [comment]
Instead of just setting it 1, I'm wondering if it would be better to set `min(RollingUpdateMinInstancesInService, MinControllerCount)` so that we can avoid both down time while rolling update and the fighting endpoint issue?

**Comment by c-knowles** [comment]
After upgrading an existing cluster to v0.9.9-rc.2 from 5780b5929bc225f9aea6b6044966dc2a6fe13629, I was investigating a few issues especially around the dashboard and CLI breaking frequently. I ended up finding the same `Resetting endpoints for master service "kubernetes"` in the logs a lot which lead me to here.

The cluster in question has always had 2 controllers and has always had this setup inside the `cluster.yaml`:
```
controllers:
  autoScalingGroup:
    minSize: 1
    maxSize: 2
    rollingUpdateMinInstancesInService: 1
  instanceType: t2.medium
```

So `/etc/kubernetes/manifests/kube-apiserver.yaml` on the controllers had `--apiserver-count=1` for quite some time without me know as it never caused any problems. I also two other clusters with min/max of 2/3 and checking those also shows no problems. I'm not sure of the cause within the latest k8s and kube-aws, I assume something in the latest API server is causing this config issue I always had to become more obvious.

Perhaps the controller ASG min/max just needs to be verified to be the same value?

**Comment by mumoshu** [comment]
@c-knowles Thanks for reporting!

Just for clarification but:

> I ended up finding the same Resetting endpoints for master service "kubernetes" in the logs a lot which lead me to here.

This specific "issue" doesn't break anything apart from bloated logs.

If we "fix" the bloated logs issue right now, a reliability issue arrises.

Say If we had apiserver-count=3 and one of the controller nodes failed somehow, any request to apiserver w/ in-cluster config would fail 33% of the time. This is explained in https://github.com/kubernetes/kubernetes/issues/22609.

Fortunately, there's https://github.com/kubernetes/kubernetes/pull/51698 which will be alpha in Kuberentes v1.9 which fixes the reliability issue when apiserver-count is set "correctly".
Let's hold on and add the support for the alpha flag once 1.9 is released!

**Comment by mumoshu** [comment]
#51698 seems to be alpha in 1.9 and becoming beta in 1.10.

Could anyone try and hopefully contribute a fix for this?

**Comment by c-knowles** [comment]
FYI the name was changed to remove the `alpha` part in https://github.com/kubernetes/kubernetes/pull/54419.
