### ISSUE TITLE
Using dex with kube-aws

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#506]
Extracted from https://github.com/kubernetes-incubator/kube-aws/issues/502#issuecomment-292064360
cc @qpaulson

**Comment by camilb** [comment]
Hi @mumoshu, we plan to start working on this next week, if there is no one already working on it.

**Comment by mumoshu** [comment]
AFAIK, no one is working on this yet. I'd greatly appreciate it if you could 👍

**Comment by c-knowles** [comment]
Dex is already support with issues https://github.com/kubernetes-incubator/kube-aws/issues/601 and https://github.com/kubernetes-incubator/kube-aws/issues/668 still outstanding.
