### ISSUE TITLE
Configuration/docs for apiEndpoints

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#520]
I just got around to using the multiple API endpoints from https://github.com/kubernetes-incubator/kube-aws/pull/468. I have some issues configuring it to achieve the addition of a DNS name to the cert without another ELB.

The relevant details of my cluster.yaml are:

```
#externalDNSName: k8s-dev-v1.REDACTED
#createRecordSet: true
#recordSetTTL: 60
#hostedZone: ""
#hostedZoneId: REDACTED

apiEndpoints:
  - name: versioned
    createRecordSet: true
    dnsName: k8s-dev-v1.REDACTED
    hostedZone:
      id: REDACTED
    recordSetTTL: 60
  - name: unversioned
    dnsName: k8s-dev.REDACTED

worker:
  apiEndpointName: versioned
  nodePools:
    - name: worker-pool-a
    - name: worker-pool-b
    - name: worker-pool-c
```

The output of `kube-aws validate` is:

```
WARN: the worker node pool "worker-pool-a" is associated to a k8s API endpoint behind the DNS name "k8s-dev-v1.REDACTED" managed by YOU!
Please never point the DNS record for it to a different k8s cluster, especially when the name is a "stable" one which is shared among multiple k8s clusters for achieving blue-green deployments of k8s clusters!
kube-aws can't save users from mistakes like that
WARN: the worker node pool "worker-pool-b" is associated to a k8s API endpoint behind the DNS name "k8s-dev-v1.REDACTED" managed by YOU!
Please never point the DNS record for it to a different k8s cluster, especially when the name is a "stable" one which is shared among multiple k8s clusters for achieving blue-green deployments of k8s clusters!
kube-aws can't save users from mistakes like that
WARN: the worker node pool "worker-pool-c" is associated to a k8s API endpoint behind the DNS name "k8s-dev-v1.REDACTED" managed by YOU!
Please never point the DNS record for it to a different k8s cluster, especially when the name is a "stable" one which is shared among multiple k8s clusters for achieving blue-green deployments of k8s clusters!
kube-aws can't save users from mistakes like that
Error: Failed to initialize cluster driver: file cluster.yaml: unknown keys found in worker.nodePools[0].apiEndpoints[0]: createRecordSet, hostedZone, recordSetTTL
```

Side note - it seems the default cluster.yaml does not have all the details yet. For example `worker.apiEndpointName` which I found out about by accident:

```
Error: Failed to initialize cluster driver: file cluster.yaml: worker.apiEndpointName must not be empty when there're 2 or more API endpoints under the key `apiEndpoints` and one of worker.nodePools[] are missing apiEndpointName
```

**Comment by mumoshu** [comment]
Sorry if I had been making mistakes in cluster.yaml but your cluster.yaml should look like:

```
apiEndpoints:
  - name: versioned
    dnsName: k8s-dev-v1.REDACTED
    loadBalancer:
      createRecordSet: true
      hostedZone:
        id: REDACTED
      recordSetTTL: 60
  - name: unversioned
    dnsName: k8s-dev.REDACTED
```

Because a record set is created for a load balancer, rather than an api endpoint itself(IMHO)

**Comment by mumoshu** [comment]
And the `unknown keys found in worker.nodePools[0].apiEndpoints[0]` error is very odd. Seems like I made a bug there... It should only validate unknown keys in the top level `apiEndpoints` rather than the ones under `worker.nodePools[]`

**Comment by c-knowles** [comment]
I also found kubeconfig comes out with empty server but it may be related to the same issues:

```
- cluster:
    certificate-authority: credentials/ca.pem
    server: https://
```

Let me try what you mentioned above first and I'll see if it's resolved.

**Comment by c-knowles** [comment]
About `loadBalancer` - the template in default cluster.yaml is wrong but the examples just below it are correct, I had not spotted the difference. There's no validation errors for the `apiEndpoints` perhaps?

**Comment by c-knowles** [comment]
I can confirm with latest master I get the same error messages:

```
WARN: the worker node pool "worker-pool-a" is associated to a k8s API endpoint behind the DNS name "k8s-dev-v7.REDACTED" managed by YOU!
Please never point the DNS record for it to a different k8s cluster, especially when the name is a "stable" one which is shared among multiple k8s clusters for achieving blue-green deployments of k8s clusters!
kube-aws can't save users from mistakes like that
[...]
Error: Failed to initialize cluster driver: file cluster.yaml: unknown keys found in worker.nodePools[0].apiEndpoints[0]: createRecordSet, hostedZone, recordSetTTL
```

Moving `createRecordSet`, `hostedZone` and `recordSetTTL` works so at least it's ok if the config is valid. Will probably submit a PR to fix the default `cluster.yaml` but not sure about the validation part yet.

**Comment by mumoshu** [comment]
Thanks for your confirmation.
Just a quick reply but I've submitted the fix for the validation at
https://github.com/kubernetes-incubator/kube-aws/pull/521
Would you mind confirming if it works for you?
2017年4月11日(火) 10:34 Chris Knowles <notifications@github.com>:

**Comment by c-knowles** [comment]
@mumoshu sure, can take a look now.

**Comment by c-knowles** [comment]
@mumoshu ah yes the commit above. I saw that but for some reason I thought you'd merged it already 😆   I just built your branch and re-validate but I still get the same error using the invalid config above.
