### ISSUE TITLE
Tests failing locally, not sure why?

### ISSUE THREAD

**Issue by jeremyd** [kubernetes-incubator/kube-aws#523]
When I run make test-with-cover (just like Travis does) I get the following error in my test run.  However, the same builds pass in Travis.  Any ideas why locally this is failing but not on TravisCI?

```
coverage: 0.0% of statements
ok  	github.com/kubernetes-incubator/kube-aws/test/integration	271.299s
?   	github.com/kubernetes-incubator/kube-aws/tlsutil	[no test files]
core/controlplane/config/config_test.go:459: arg c.Subnets for printf verb %s of wrong type: []github.com/kubernetes-incubator/kube-aws/model.Subnet
exit status 1
make: *** [Makefile:16: test-with-cover] Error 1
```

**Comment by camilb** [comment]
@jeremyd Encountered similar issues because still had `github.com/coreos/kube-aws` in "~/go/src" and kube-aws still looks there for some libraries that probably are outdated.

**Comment by jeremyd** [comment]
ah, indeed, this was likely the issue.  works for me now, thanks!
