### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by paalkr** [kubernetes-incubator/kube-aws#524]
Are there any plans for releasing kube-aws as a Windows executable? I'm managing a Kubernetes cluster on AWS, and all other operations than deploying the cluster is done from Windows ;)

Developing and deploying containers and services to the cluster works perfectly from a Windows 10 workstation, as both docker, minikube and kubectl executables are supported on Windows. 

Regards

**Comment by redbaron** [comment]
Linux subsystem on windows 10 can run linux binaries natively.

**Comment by paalkr** [comment]
Ahh. You are absolutely right. Thanks for reminding me ;) Kube-aws works like a charm when executed in the Windows 10 Linux subsystem bash shell.
