### ISSUE TITLE
Dedicated website for kube-aws Documentation

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#534]
Extracted from https://github.com/kubernetes-incubator/kube-aws/pull/526#issuecomment-293787922

**Comment by mumoshu** [comment]
@calebamiles Hi caleb!
Would you mind providing us e.g. a permission to publish kube-aws documentation to https://coreos.com/kubernetes/docs/latest/kubernetes-on-aws.html?

In old days of kube-aws when it was still at coreos/kube-aws, the documentation had been published to there.
I don't have access to there myself but @colhom had been kindly taken the role to do it for us.
Would you mind discussing here how should we maintain and publish the documentation site, after kube-aws is transferred to kubernetes-incubator?
Would you guys at CoreOS still like to have the doc hosted under coreos.com, in the first place? (I personally prefer that because kube-aws heavily rely on various softwares thankfully developed by CoreOS 😄

**Comment by c-knowles** [comment]
@mumoshu what should we do here? I suggest we take the initiative and start our own docs site as we have quite a backlog of users asking for more docs.

**Comment by mumoshu** [comment]
@c-knowles Agree to your suggestion - Would you mind if I created a dedicated site `https://kube-aws.github.io` backed by `kube-aws/docs` github repo while putting all the necessary documentation sources and build scripts in this repo?
This way we can handle whole the process under our control and the url for the doc is pretty 😄

**Comment by c-knowles** [comment]
@mumoshu agree, that's exactly what I would expect and doesn't change our existing workflow so much. I'll start on it very soon.

**Comment by c-knowles** [comment]
I just thought of one downside, documentation cannot be committed in the same PR as the feature. If you think this is ok, let's proceed. Otherwise if we put the docs here the URL without any custom domain would be https://kubernetes-incubator.github.io/kube-aws/.

**Comment by mumoshu** [comment]
@c-knowles I'm assuming that we can still bundle a documentation update and a code improvemente a same PR. That's because I expect to put all the necessary documentation sources and build scripts in this repo but not kube-aws/docs repo.

**Comment by smrutiranjantripathy** [comment]
@mumoshu and @c-knowles I would suggest it would be easier from the point of maintenance and creation to use gitbook.com.
Any thoughts ?

**Comment by mumoshu** [comment]
@c-knowles If you by any chance have e.g. a prototype of the doc site in your laptop, would you mind sharing it in https://github.com/kube-aws/docs so that we can start improving it anyway? 😃
Btw you already have an admin access to the `docs` repo.

**Comment by c-knowles** [comment]
Looks like CoreOS are now posting this on their docs site. See https://coreos.com/kubernetes/docs/latest/cluster-dump-restore.html for an example.
```
There's a better way!
The Tectonic Installer provides a Terraform-based Kubernetes installation. It is open source, uses upstream Kubernetes and can be easily customized.

Install Kubernetes with Tectonic
This guide will not be maintained in the future and is not currently tested against current releases of Kubernetes.
```

So I will proceed with our new docs next.

**Comment by c-knowles** [comment]
@mumoshu I took @smrutiranjantripathy's advice and started to a gitbook. It's available at https://kube-aws.gitbooks.io/manual/content/ and also synced to our GitHub docs repo. I will port in what we have plus my extras over the next few days. We can accept comments and I can add the maintainers to allow [change requests](https://help.gitbook.com/books/what-are-change-requests.html).

**Comment by mumoshu** [comment]
@c-knowles Good job!

I have never heard of the change requests feature but it seems COOL.
Do you need to add maintainers to enable the feature?
Then, yes, please do so! 😄

**Comment by c-knowles** [comment]
@mumoshu I'll add maintainers once I commit the other parts. I've found what I think is a critical issue for documentation in gitbook - it seems anchors don't work properly and I spent a while trying to fix it in my own test repo but gave up as I think it should not be so difficult. I'm probably going to swap to Read the Docs using the same markdown files, unless anyone has objections I'll do that before I commit the next updates.

**Comment by c-knowles** [comment]
@mumoshu I investigated Read the Docs but maintaining that is going to be a bit more difficult and there are some issues in the markdown to reStructuredText connectivity needed for that to work for us. I had some inspiration about revisiting GitBook and got the various parts I think we need working.

So some good news! I've synced up almost all our current docs - https://kube-aws.gitbooks.io/manual/.

The main input I'd like to collect from you is are you rough ok with the sections? I think it's good enough to start on next steps.

What I plan next:
- [ ] Bug fixes for any linking issues although I fixed most of it
- [ ] Add collaborators to GitBook
- [ ] Remove documentation from this repo and update links in README to point to new docs
- [ ] Start to flesh out developer and operator guides a bit more
- [ ] Start on various new docs, we have 5-6 tickets I will pick up about docs plus I have a list of questions/issues that have come up which basically need better documentation
- [ ] Consider if we can combine in any of the contrib docs?

If you're ok with that plan, I want to do 1-3 then close this PR and then work on the later points.

**Comment by redbaron** [comment]
Sorry, missed all ongoing effort here somehow, thanks for doing it! Quick question: github pages (https://pages.github.com/) provide static hosting and automatic rendering from gh-pages branch, can we make it work for us? 

Anyway, looking forward for it to become ready for contributions, I'd try to dedicate a bit of time regularly to update docs once I understand how :)

**Comment by c-knowles** [comment]
@redbaron it's a good question. Although maybe I didn't mention it I looked at gh-pages too. GitBook is nice to get us started as @smrutiranjantripathy kindly pointed out, mostly due to the navigation/search all done for us. Themes built into github pages seem less than desirable for documentation purposes but can be customised with Jekyll. I kept us on markdown so we can switch to github pages if we ever want/need to (rather than switch to the reStructuredText preferred by Read the Docs).

**Comment by mumoshu** [comment]
@c-knowles Thank you very much for your efforts 🍻 
I love the contents and the style of the doc site. Also, I almost agree to the plan you've suggested.
Regarding the plan, the only thing I'd appreciate if we could discuss is where the actual source code of the doc site is hosted, as commented in https://github.com/kubernetes-incubator/kube-aws/pull/834#issuecomment-321560820

**Comment by c-knowles** [comment]
@mumoshu yes, I agree with that. However, I'm not sure mirroring to another repo is going to work so well. If we use gitbook it will sync to one repo. If we use native github pages, it's better we just use the built in github.io domain name provided to us.

**Comment by mumoshu** [comment]
@c-knowles Thanks!
I meant not mirrorring sub-contents of this repo to kube-aws/docs repo but choose this repo for the one repo connected to the kube-aws.gitbooks.io/manual site. For me, reconfiguring the gitbooks side and then modifying book.json seemed to allow that.
One of kubernetes-incubator admins must approve gitbook access to the github org though. Otherwise git-pushes won't trigger updates to the gitbook.

**Comment by c-knowles** [comment]
@munoshu sure that's fine with me, I prefer that doc updates can go in the same PR. I'm considering how to version relevant parts as well.

**Comment by mumoshu** [comment]
Thanks to @c-knowles, the dedicate website for kube-aws documentation has been realized!

It is hosted on GitHub Pages at https://kubernetes-incubator.github.io/kube-aws.

The publishing process has been scripted via #858 and then automated using Travis via #859.
You can contribute documentation fixes via a pull request as before. Merging a PR to the master branch results in a new version of doc to be automatically published.

Anyone can edit documentation sources from the editor on GitHub and submit pull requests for contirubtion. Although maintainers can commit it directly to the master branch, submitting it via a pull request created from a button on the editor is recommended for reviewing.

**Comment by mumoshu** [comment]
Closing this as resolved.

@c-knowles Probably you want to revise [your TODO list](https://github.com/kubernetes-incubator/kube-aws/issues/534#issuecomment-319934132) and create dedicated github issues for the items in it?

**Comment by c-knowles** [comment]
Yeah, I can create separate issues for those.

I'd also like to add that there is information in the developer guide about documentation at https://kubernetes-incubator.github.io/kube-aws/guides/developer-guide.html#documentation. Maybe we can add some of your detail there.
