### ISSUE TITLE
Pod security policies can't work

### ISSUE THREAD

**Issue by soellman** [kubernetes-incubator/kube-aws#537]
I've been playing around with pod security policies and I've come to realize that they cannot work with kube-aws as it is now.

Reading the very last paragraph in the pod security policy page (https://kubernetes.io/docs/concepts/policy/pod-security-policy/), we can see that pod security policies don't work with RBAC if the controller manager contacts the api server on the insecure port, which is how kube-aws configures the controller manager (to talk to localhost:8080).

I haven't thought through how to address this but it'd probably involve creating client certs for each controller and redirecting them to one of the apiEndpoints instead of localhost:8080. I just wanted to get this issue up there and I'll continue to think about a solution :)

Unrelated to the insecure port issue, we'd also need a bootstrap pod security policy (installed in the same fashion as the bootstrap rbac policies) to allow the kubelets to create the mirror pods for the control plane and actual pods for the addons before handing management off to cluster admins.

**Comment by mumoshu** [comment]
Hi @soellman, thanks for bringing this up!
I've never realized about that and the detailed feedback like yours is very helpful 👍 

Just to be extra clear, your use-case is to schedule pods with certain pod security policie(s) applied, from controller nodes(hence via kubectl run against the insecure ports of the controller nodes), right?

**Comment by soellman** [comment]
Thanks @mumoshu! Our use case is a locked-down cluster where we'd like to disallow users from submitting pods which are privileged, or using hostports.

However, the use case is not limited to the controller nodes; in the case of deployments or replicasets where the pod is not created directly by the user, the pod security policy roles are applied when the controller-manager manages creation of the pods, and it then matters that the controller-manager is using the unsecured port to access the API.

That last paragraph on the pod security policy page documents this - there's a lot in there :)

**Comment by mumoshu** [comment]
@soellman I was about to misunderstand the scope of the issue - Thanks for the clarification!

> I haven't thought through how to address this but it'd probably involve creating client certs for each controller and redirecting them to one of the apiEndpoints instead of localhost:8080

I basically agree to your suggestion. More concretely, how about:

* In shorter term, point all the kubelet, controller-manager on a controller node to the DNS name of one of the apiEndpoints
  * It implies the kubelet and the controller-manager connects to one of the apiservers via an ELB
* In longer term, if you'd like them to connect to apiservers directly(not through an ELB), implement #281 and provide users an option to do so by allowing to configure the API endpoint for controller nodes to be powered by not an ELB but DNS round-robin.

**Comment by soellman** [comment]
I agree with your concrete suggestions.

There may be some cascading consequences because requests to the apiserver would now go through the secured port and therefore need an identity; these identities and their api operations need to be considered with regards to RBAC. I haven't dug deeply enough into the architecture to provide concrete cases though! To be clear- I'm talking about regular RBAC here, not the pod security policies. Pod security policies represent a different can of worms!

**Comment by mumoshu** [comment]
@soellman Yes, I believe so 👍 
I don't understand all the consequences and enabling pod security policy myself for now.
So, I'm going to tackle them one by one.
For now, I'm going to add a bootstrap policy as you've suggested.
Do you think if we can just start with the "privileged" policy [in the upstream repo](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/podsecuritypolicies)?

**Comment by mumoshu** [comment]
Hi @soellman, any thoughts on this? 😄

**Comment by soellman** [comment]
Hi! Sorry.. My focus has changed and I suspect I won't be able to help here, other than saying that yes, I think starting with the upstream privileged policy sounds like a good idea!
