### ISSUE TITLE
Rethink where to persist automated etcd snapshots

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#562]
Extracted from https://github.com/kubernetes-incubator/kube-aws/issues/532#issuecomment-295571132

An automated etcd snapshot doesn't seem to be usable for restoring a completely different/new cluster.
Therefore, persisting it under a S3 prefix which can be shared among clusters would result in a new cluster with the clusterName used before to be [configured unappropriately](https://github.com/kubernetes-incubator/kube-aws/issues/532#issuecomment-295571132).

**Comment by mumoshu** [comment]
@c-knowles Any preferences on where to persist automatic etcd snapshots?

@redbaron @jollinshead I guess you haven't enabled the automated etcd snapshot but I'd appreciate it if you could share your preferences/thoughts  :bow:

Are you guys ok with automatic etcd snapshots to be persisted under e.g. `<s3-uri>/kube-aws/clusters/<clusterName>/etcd-snapshots/<cluster UUID(new!)>/snapshot.db` so that it won't be accidentally shared among different clusters with the same clusterName?

**Comment by c-knowles** [comment]
@mumoshu Where are they now? I think just in the existing bucket as `/<STACK NAME>/etcd-backup/` would be ok?

BTW, I checked out my S3 bucket and as far as I can see I had no snapshots so whatever is causing my DNS+dashboard issue doesn't seem to be this.

**Comment by mumoshu** [comment]
@c-knowles Thanks for the reply. AFAICS, when the automated etcd snapshot feature is enabled, `/<STACK NAME>/etcd-backup/` would be problematic when you reused the same clusterName for e.g. 2 kube-aws clusters, without emptying the directory `/<STACK NAME>`.

I guess you can reproduce the issue by running `kube-aws destroy` and then `kube-aws up` with the same cluster.yaml wih the automated etcd snapshot enabled by setting `etcd.snapshot.automated` to `true`.

If you have never enabled the automated etcd snapshot feature, your issue would be an another one!

**Comment by c-knowles** [comment]
Yep, I've checked my config and I never enabled it. Maybe I meant `/<CLUSTER NAME>/etcd-backup/`? But based on your description it seems like that would also cause issues. Perhaps a UUID needs to be assigned to each deploy and store under `<S3 BUCKET>/etcd-backups/<DEPLOY UUID>`, the UUID would be a parameter to the CF.

**Comment by mumoshu** [comment]
@c-knowles 

> Maybe I meant /<CLUSTER NAME>/etcd-backup/

Could be, and I believe you're correct on the consequence.

Also, thanks for the deeper design on UUIDs! That sounds great.

If I add something to your idea, more concretely, an UUID should be persistend in e.g. a cfn stack's tag rather than a key in cluster.yaml which is populated via `kube-aws init`. The latter would still result in the same issue when you've reused cluster.yaml. On the other hand, the former results in unique UUIDs across multiple different deployments of the same cluster.yaml
