### ISSUE TITLE
Updating apiEndpoints results in incomplete x509 certificate

### ISSUE THREAD

**Issue by jpb** [kubernetes-incubator/kube-aws#567]
Adding an additional `apiEndpoint` after cluster creation does not add new DNS name to controller's x509 certificate.

**Steps to Reproduce**
- Create cluster with one `apiEndpoint` called `original-api-endpoint.example.com`
- Update cluster adding an additional `apiEndpoint` called `new-api-endpoint.example.com`
  - Update node pool to use this new `apiEndpoint`

**Expected Result**
Worker connects successfully to the new `apiEndpoint`.

**Actual Result**
Worker cannot connect to new `apiEndpoint` as the controller's x509 certificate does not include `new-api-endpoint.example.com`.

Example error message from worker node after switching to newly created `apiEndpoint`:

```
E0420 15:05:56.242755       1 reflector.go:201] k8s.io/kubernetes/pkg/proxy/config/api.go:49: Failed to list *api.Endpoints: 
Get https://new-api-endpoint.example.com/api/v1/endpoints?resourceVersion=0: 
x509: certificate is valid for kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, original-api-endpoint.example.com, not new-api-endpoint.example.com
```

**Comment by c-knowles** [comment]
Did you run `render credentials` to regenerate the certs? It's not explicit in the config but that needs to be done to add the new names.

**Comment by jpb** [comment]
I did not run `render credentials` when updating - that was the issue 😅  Thank you for your quick and helpful response!
