### ISSUE TITLE
etcdadm scripts should be written to files at `render` phase, not `up`

### ISSUE THREAD

**Issue by redbaron** [kubernetes-incubator/kube-aws#580]
right now `etcdadm` script is embedded in kube-aws binary and "materializes" itself only when we run "kube-aws up/update" which makes it harder to track full kluster config in git

**Comment by mumoshu** [comment]
@redbaron Thanks for the feedback 👍 
Yes, it should be. It was even in the "remaining issues" list in “the original PR](https://github.com/kubernetes-incubator/kube-aws/pull/417) which introduced etcdadm.

How about `scripts/` directory to store scripts like etcdadm?
Any preference on the naming of the directory?

**Comment by redbaron** [comment]
why `scripts` is everything else is in `write_files`?

**Comment by mumoshu** [comment]
@redbaron My intention was to ensure users place only scripts inside the directory. The same as `credentials` for `/etc/kubernetes/ssl`.

Would you like to embed `etcdadm` directly into cloud-config-etcd like:
```yaml
  - path: /opt/bin/etcdadm
    content: |
      // the content of etcdadm here
```
or anything else?

**Comment by redbaron** [comment]
either way works for me. `scripts` is more convenient, but probably would require more work
