### ISSUE TITLE
configmap and serviceaccount for kube-dns

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#584]
Extracted from https://github.com/kubernetes-incubator/kube-aws/issues/542
Although we've upgraded kube-dns to the latest 1.14.1 via #582, we're still missing (1)configmaps mounted as volumes and (2) serviceaccount for kube-dns.
Survey the upstream setups for those and adapt if necessary.
cc @c-knowles

**Comment by c-knowles** [comment]
What do we lose out on without this? At least RBAC won't work right?

**Comment by danielfm** [comment]
I'm fixing a regression bug in TLS bootstrapping, and since TLS bootstrapping should go along with RBAC, I'm also attacking this in the same PR.

**Comment by mgreenwald-pm** [comment]
@mumoshu Does this permit usage of this feature?

http://blog.kubernetes.io/2017/04/configuring-private-dns-zones-upstream-nameservers-kubernetes.html

**Comment by mumoshu** [comment]
@mgreenwald-pm Yes, it should 👍 Just edit the kube-dns confgimap to add settings mentioned in the article.

**Comment by mgreenwald-pm** [comment]
@mumoshu Yes, thank you and it worked!
