### ISSUE TITLE
Failing-fast or warn when tried to update cluster created with older kube-aws

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#585]
According to #455, you need to recreate your cluster to upgrade kube-aws as of today.
However, I believe some people are still getting into trouble trying to run `kube-aws update` with newer kube-aws on their old clusters.
Making kube-aws failing fast when tried to do so would allow people to notice the fact.

**Comment by danielfm** [comment]
Couldn't we add a metadata to `cluster.yaml` to specify the kube-aws version used to generate it, and then only allow further commands, like `render`, `up` and `update` to go through if the versions match?

**Comment by mumoshu** [comment]
@danielfm Thanks for the suggestion. That sounds good to me 👍 
Actually, I was initially thinking about adding a version tag to the root cfn stack so that we can use it to prevent `kube-aws update` to be run. Probably yours is better though.

**Comment by c-knowles** [comment]
I think users may just update it in the yaml if it's in there? Especially if they use the git flow style mechanism of updating. Having said that, ideally we only want to prevent updates where we know running update will break.

**Comment by mumoshu** [comment]
@c-knowles 
> I think users may just update it in the yaml if it's in there? Especially if they use the git flow style mechanism of updating. 

Good point. Then, we'd better add a cfn tag via a template snippet like `"Value": "{{.KubeAwsVersion}}"` so that the git workflow like described in #462 #238 won't accidentally update the version number associated to a cluster.

**Comment by c-knowles** [comment]
@mumoshu if we do that though, how do we support upgrade path for cases that do work? We reject by default unless an update is allowed? Or allow by default unless an update is disallowed?

**Comment by mumoshu** [comment]
@c-knowles I guess the former is better because then we can ensure that only upgrade paths tested by contributors can be allowed explicitly in code.

**Comment by redbaron** [comment]
{{ .KubeAwsVersion }} is not informative enough as it mightbe just  a git commit of a private fork :)

**Comment by mumoshu** [comment]
@redbaron Thanks for the feedback 👍 

1. How about tagging some commits in your private fork with version numbers so that you can explicitly control one version is updatable or not in code?
2. Or I guess you can just leave it just as a git commit id so that kube-aws can prevent `kube-aws update` among different commit ids by default?
3. If none of the above sounds good, how about adding an another flag in cluster.yaml to disable update prevention at all...? 😃

**Comment by redbaron** [comment]
how kube-aws itself defines which version is updatable and which is not?

**Comment by mumoshu** [comment]
@redbaron Probably in a golang type and func which is used like:

```golang
func (g UpdateGate) ValidateClusterUpgradableTo(v Version) error {
    // All the upgrade paths tested by contributors
    allowedUpgradePaths := TestedUpgradePaths{
        // Tested by @mumoshu
        TestedUpgradePath{ClusterVersion: NewVersion("v0.9.5"), KubeAwsVersion: NewVersion("v0.9.6")},
        // Tested by @redbaron
        TestedUpgradePath{ClusterVersion: NewVersion("v0.9.5"), KubeAwsVersion: NewVersion("v0.9.7")},
    }

    for p, _ := range allowedUpgdatePaths {
        return fmt.Errorf("")
    }
    return fmt.Errorf("Automatic upgrade path from kube-aws %s to %s is not tested: Updating a cluster created by kube-aws %s  with kube-aws %s is not not allowed.", g.ClusterKubeAwsVersion, v, g.ClusterKubeAwsVersion, v))
}

// And somewhere in the code path of `kube-aws update`

if err := NewUpdateGate(clusterKubeAwsVersion).ValidateUpgradableTo(kubeAwsVersion); err != nil {
    return err
}
```

**Comment by mumoshu** [comment]
@redbaron Does my idea make sense to you? I'd appreciate your feedback :bow:
