### ISSUE TITLE
With loadbalancer option is correct? apiEndpoints or controller?

### ISSUE THREAD

**Issue by Vrtak-CZ** [kubernetes-incubator/kube-aws#586]
After introducing apiEndpoints there is two loadbalancer subsection in `cluster.yaml` one is in `apiEndpoints` and another one is in `clontroller`. With one is used and correct?

kube-aws - `v0.9.6-rc.4`

**Comment by camilb** [comment]
@Vrtak-CZ I'm using  only the `apiEndpoints.loadBalancer` and it works fine. Had the same doubt.

**Comment by mumoshu** [comment]
@Vrtak-CZ @camilb Sorry for the confusion and thanks for reporting 👍 
Yea - `controller.loadBalancer` is deprecated in favor of recently added `apiEndpoints[].loadBalancer`.
I wonder if I added a deprecation warning when you've specified `controller.loadBalancer`

**Comment by mumoshu** [comment]
@Vrtak-CZ Can we close this? 😄

**Comment by Vrtak-CZ** [comment]
fixed by #603
