### ISSUE TITLE
Broken ElasticFileSystem on node-pools

### ISSUE THREAD

**Issue by Vrtak-CZ** [kubernetes-incubator/kube-aws#587]
This [commit](https://github.com/kubernetes-incubator/kube-aws/commit/2a43f03164e5d56ae0cccd8f1ae10564dd7d7c25) broke elasticFileSystem definition per node-pool. And global elasticFileSystem for whole cluster won't work because we have different subnets for each node-pools but they are in same AZ. So after this commit is not possible to use EFS in our cluster anymore 😢 .

**Comment by mumoshu** [comment]
@Vrtak-CZ Thanks for reporting this and sorry for breaking your use-case 😢 
Would you mind helping me to know about your use-case a bit more?
You had been using

* existing subnets rather than kube-aws managed ones, and
* EFS mount targets managed by you rather than kube-aws, and
* different EFS file systems by specifying a different `nodePools[].elasticFileSystemId` per node pool

Am I correct?

**Comment by Vrtak-CZ** [comment]
Sure,
we have existing VPC and subnets (because we have better control).

And we have one "big" cluster instead of few separate smaller cluster (because of saving money for another etcd and controller nodes). But we have few separate nodePools with separate subnets (each pool has different resposibility - eg. managemennt (gitlab, monitoring etc), staging, develeopment etc).

And we need persistent storage only on management node-pool because on other we are running stateless containers. So we have `nodePools[0].elasticFileSystemId` defined actually only on management pool.

About EFS mount targets because is not possible to define with mount target kube-aws should use we are using mount targets with kube-aws creates.

Until 0.9.6-rcX (i'm not sure if problem is really this commit or version) where old way doesn't work.

**Comment by Vrtak-CZ** [comment]
> So, I still assume that you've brought your own:
> 
> - existing subnet
> - existing efs
> - mount target for the existing subnet + the existing efs
> 
> to your management node-pool. Am I correct?

Yes

**Comment by mumoshu** [comment]
@Vrtak-CZ Thanks for the confirmation 👍 
I'll try to fix it until next rc.

**Comment by mumoshu** [comment]
@Vrtak-CZ The fix is included in v0.9.6-rc.6 which has been just released. Would you mind testing it? Thanks!

**Comment by mumoshu** [comment]
@Vrtak-CZ Did it work for you?

**Comment by Vrtak-CZ** [comment]
yes it works as expected

**Comment by mumoshu** [comment]
@Vrtak-CZ Good to know! Thanks for the confirmation 👍
