### ISSUE TITLE
taint-and-uncordon fails on controllers in VPC with custom DNS domain

### ISSUE THREAD

**Issue by Cptn727** [kubernetes-incubator/kube-aws#597]
This regards a cluster built in an already-existing VPC with custom DNS domain and servers in DHCP options. The kube-aws version used was v0.9.6-rc.4.

In trying to get cluster-autoscaler working, I noticed that the controller nodes were status SchedulingDisabled. Ultimately, I found that /opt/bin/taint-and-uncordon on the controller had not succeeded because on the controller, hostname returns ip-172-23-45-67.custom.dns but the node registers into the cluster as ip-172-23-45-67.ec2.internal. As a result, when /opt/bin/taint-and-uncordon initially runs, the output looks like this, 

```
#  hostname="ip-172-23-45-67.ec2.internal" /opt/bin/taint-and-uncordon
tainting this node.
echo "tainting this node."
+ echo 'tainting this node.'
     hostname="ip-172-23-45-67.custom.dns"
+ hostname=ip-172-23-45-67.custom.dns
     kubectl="/kubectl --server=http://127.0.0.1:8080"
+ kubectl='/kubectl --server=http://127.0.0.1:8080'
     taint="$kubectl taint node --overwrite"
+ taint='/kubectl --server=http://127.0.0.1:8080 taint node --overwrite'
     $taint "$hostname" "node.alpha.kubernetes.io/role=master:NoSchedule"
+ /kubectl --server=http://127.0.0.1:8080 taint node --overwrite ip-172-23-45-67.custom.dns node.alpha.kubernetes.io/role=master:NoSchedule
Error from server (NotFound): nodes "ip-172-23-45-67.custom.dns" not found
```

It seems as though kube-aws uses the value of /usr/bin/hostname in some cases, like /opt/bin/taint-and-uncordon but the value from AWS metadata in other cases. Maybe I'm doing something wrong (I didn't see any way in cluster.yaml to specify a custom DNS domain to expect) but if not, I'd imagine you'd want to stick with one method or the other for node identification.

It's not clear to me yet if this has impacted any other functionality, or just this taint-and-uncordon instance. I'm happy to provide any other details I can if they'd be helpful.

**Comment by mumoshu** [comment]
@Cptn727 Thanks for the detailed feedback!
Would you mind answering several questions:

* What `curl http://169.254.169.254/latest/meta-data/hostname` on the controller nodes return for you? `ip-172-23-45-67.custom.dns?
* Is `ip-172-23-45-67.ec2.internal` resolvable from other nodes? I.e. Does your custom DNS forward  DNS queries to `*.ec2.internal` to the AWS DNS?

**Comment by mumoshu** [comment]
How can we "fix" this?
Do we need to add an another setting key in cluster.yaml to customize how nodes determine its names in the k8s cluster, or can we do the customization automatically?

**Comment by mumoshu** [comment]
@Cptn727 BTW, taint-and-uncordon is dropped in favor of the `--register-with-taints` flag added to kubelet since v1.6.x. So, if `taint-and-uncordon` was the only problem, I guess the latest kube-aws rc would work.
Would you mind trying to recreate your cluster with the latest kube-aws rc?

**Comment by Cptn727** [comment]
Not at all, I'll give it a try today and report back, thanks!

**Comment by mumoshu** [comment]
Also - please consider not specifying `kubernetesVersion` to 1.5.x but 1.6.x or completely omit it if by any chance you've been doing so.
The latest rc lost the support for k8s 1.5.x temporarily.

**Comment by mumoshu** [comment]
@Cptn727 Thanks! I'm looking forward to your report.

**Comment by Cptn727** [comment]
@mumoshu just checked re: your earlier questions and 

- http://169.254.169.254/latest/meta-data/hostname gives the custom domain rather than ec2.internal.
- ip-172-23-45-67.ec2.internal is resolvable from other nodes, and yes, this is likely due to the fact that the custom DNS servers use Amazon's DNS servers as forwarders (for all domains not authoritatively hosted, including ec2.internal)

**Comment by Cptn727** [comment]
@mumoshu just finished the new cluster and you are correct, this issue does not persist in the new RC. Seems like we can close this, and if any other similar issues pop up I'll just open a new issue. Thanks!!

**Comment by mumoshu** [comment]
@Cptn727 Glad to know it worked! Thanks for the report :bow:
