### ISSUE TITLE
Required changes to bring back Kubernetes 1.5.x support

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#599]
I intended to support only k8s 1.6.x starting kube-aws v0.9.6-rc.1.
However, some people seem to still want 1.5.x.

Could anyone help me bringing back the 1.5.x support?

AFAIK, required changes to re-add the support for 1.5.x would be:

* Conditionally strip `updateStrategy` in daemonset manifests if any
* Conditionally replace `affinity` fields in pod specs in various manifests to annotations
* Conditionally replace `tolerations` fields in pod specs in various manifests to annotations

**Comment by mumoshu** [comment]
See https://github.com/kubernetes-incubator/kube-aws/pull/492/files#diff-ef25536c536667a40b993d4d24ab7567L631 for how tolerations was changed.

**Comment by mumoshu** [comment]
rescheduler and cluster-autoscaler, if any, seem to have been downgraded to work with k8s 1.5
https://github.com/kubernetes/kubernetes/issues/25320#issuecomment-279294927

**Comment by mumoshu** [comment]
I guess ClusterRoleBinding to bind `kube-worker` to `cluster-admin` must be added again, by partially reverting [this part](https://github.com/kubernetes-incubator/kube-aws/pull/618/files#diff-ef25536c536667a40b993d4d24ab7567R1077) of #618

**Comment by danielfm** [comment]
@mumoshu 

> I guess ClusterRoleBinding to bind kube-worker to cluster-admin must be added again, by partially reverting this part of #618

Why is that? Does Kubeletes in Kubernetes 1.5- require other permissions than the ones listed in the `system:nodes` ClusterRole created by default in Kubernetes 1.6+? If not, it's probably a matter of creating those roles and bindings ourselves, instead of giving cluster admin access to every Kubelet in the cluster.

**Comment by mumoshu** [comment]
@danielfm Thanks - Probably I misunderstood what is going on under the hood at the time 😃 Yes, the binding wouldn't be needed.

**Comment by mumoshu** [comment]
It is already v1.7.0. Closing this as unneeded for now.
