### ISSUE TITLE
`render credentials` causes `update` failure

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#600]
I believe I have found roughly where my issue from https://github.com/kubernetes-incubator/kube-aws/issues/532 is coming from. It seems the minimum steps to reproduce are:
1. Create a cluster
1. Run `render credentials` to get new credentials
1. Run `update` to update the stack with new credentials

My test cluster was working perfectly prior to this, I didn't didn't change anything particularly significant other than regenerate credentials:

On `update --s3-uri s3://REDACTED/k8s-dev`, I got this:
```
INFO: generated "credentials/ca.pem.enc" by encrypting "credentials/ca.pem"
INFO: generated "credentials/ca-key.pem.enc" by encrypting "credentials/ca-key.pem"
INFO: generated "credentials/apiserver.pem.enc" by encrypting "credentials/apiserver.pem"
INFO: generated "credentials/apiserver-key.pem.enc" by encrypting "credentials/apiserver-key.pem"
INFO: generated "credentials/worker.pem.enc" by encrypting "credentials/worker.pem"
INFO: generated "credentials/worker-key.pem.enc" by encrypting "credentials/worker-key.pem"
INFO: generated "credentials/admin.pem.enc" by encrypting "credentials/admin.pem"
INFO: generated "credentials/admin-key.pem.enc" by encrypting "credentials/admin-key.pem"
INFO: generated "credentials/etcd.pem.enc" by encrypting "credentials/etcd.pem"
INFO: generated "credentials/etcd-key.pem.enc" by encrypting "credentials/etcd-key.pem"
INFO: generated "credentials/etcd-client.pem.enc" by encrypting "credentials/etcd-client.pem"
INFO: generated "credentials/etcd-client-key.pem.enc" by encrypting "credentials/etcd-client-key.pem"
INFO: generated "credentials/dex.pem.enc" by encrypting "credentials/dex.pem"
INFO: generated "credentials/dex-key.pem.enc" by encrypting "credentials/dex-key.pem"
Update stack: {
  StackId: "arn:aws:cloudformation:eu-west-1:REDACTED"
}
Success! Your AWS resources are being updated:
Cluster Name:		k8s-dev
Controller DNS Names:	k8s-dev-REDACTED
``` 

At least these error logs after the update "succeeded":

```
kube-dns-1455470676-2bv8n kubedns E0427 06:18:48.242814       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Service: the server has asked for the client to provide credentials (get services)
kube-dns-1455470676-2bv8n kubedns E0427 06:18:48.242814       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: the server has asked for the client to provide credentials (get endpoints)
kube-dns-1455470676-2bv8n kubedns E0427 06:18:48.243005       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.ConfigMap: the server has asked for the client to provide credentials (get configmaps)

kube-apiserver-ip-10-0-34-26.eu-west-1.compute.internal kube-apiserver E0427 06:18:46.394061       1 authentication.go:58] Unable to authenticate the request due to an error: [invalid bearer token, crypto/rsa: verification error]

k8s.io/contrib/rescheduler/vendor/k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:447: Failed to list *v1.Pod: the server has asked for the client to provide credentials (get pods)
kube-rescheduler-3155147949-n39ch kube-rescheduler E0427 06:18:46.392063       1 reflector.go:201] 
```

It seems something related to authentication is broken after the `update`.

**Comment by mumoshu** [comment]
@c-knowles Hi, thanks for the feedback as always 👍 

I guess old default tokens being verified by new credentials are causing the issue.

Does removing the kube-system default token and then recreating all the kube-dns pods by first setting replicas to zero and then to the original value solve your issue?

For example, the default token for me was `default-token-kcvtp` in the `kube-system` namespace.

```
kubectl get secrets --all-namespaces
NAMESPACE     NAME                  TYPE                                  DATA      AGE
default       default-token-7nm0h   kubernetes.io/service-account-token   3         4h
kube-public   default-token-724vh   kubernetes.io/service-account-token   3         4h
kube-system   calico-etcd-secrets   Opaque                                3         4h
kube-system   default-token-kcvtp   kubernetes.io/service-account-token   3         4h
```

I've used `kubectl edit deployment kube-dns --namespace kube-system` to open my editor to modify its number of replicas.

**Comment by mumoshu** [comment]
serviceaccount tokens are signed by `--service-account-private-key-file` and verified by `--service-account-key-file`. kube-aws seems to pass `apiserver-key.pem` to both.

relevant kube-aws code: https://github.com/kubernetes-incubator/kube-aws/blob/d3f5986/core/controlplane/config/templates/cloud-config-controller#L1262
relevant upstream issue: https://github.com/kubernetes/kubernetes/issues/22351#issuecomment-262611927

**Comment by c-knowles** [comment]
I guess I can also just delete the DNS pods as then they are recreated anyway. I will try when I recreate this situation next.

**Comment by c-knowles** [comment]
The latest master has a mandatory credentials render due to requiring a dex cert even if dex is turned off, see above issue I just filed. However, I just updated a different cluster successfully but first copying the credentials, then rendering new ones and copying back the older cert/keys apart from the new dex one it added. So I think we're on the right track with @mumoshu's above comments.

**Comment by mumoshu** [comment]
@c-knowles Thanks for the feedback 👍 

How should we "fix" this? Could there be ways to replace credentials and serviceaccount tokens while preventing down time at all?

**Comment by c-knowles** [comment]
Interesting question. Maybe there are two cases:
1. User changes the CA before rendering credentials
   * I can't immediately see a way to prevent service disruption as I don't know what options some of the kube components support for that. 
   * At the very least running `update` should result in a cluster that still works or `update` should be prevented.
1. User renders new credentials with the existing CA
   * Maybe we need to run two sets of core services during switchover?
   * Worth noting that in this scenario any old kube admin client certs continue to work. Actually since I first generated my clusters I've never updated my client certs in my local keychain and I'm still able to auth against brand new clusters with freshly rendered credentials (using same CA)

**Comment by gleeb** [comment]
It is more important for me to be able to roll only the API-SERVER key until there's a full solution.  Any idea how to work around that?
Thanks.

**Comment by mumoshu** [comment]
Hi @gleeb - Would you like to achive it without downtime or not?
If you'd like no downtime, it seems to be not easy according to [my finding above](https://github.com/kubernetes-incubator/kube-aws/issues/600#issuecomment-297635464).

**Comment by gleeb** [comment]
@mumoshu Sorry I think I was mistaken, I might be referring to the Admin-key (the key that kubectl uses to access the server). in any case, downtime is a problem.

**Comment by jorge07** [comment]
Same issue here when updating from 0.9.7 to 0.9.9

Kube-dns logs
```
9 15:54:20.432308       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
E0109 15:54:20.432698       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:150: Failed to list *v1.Service: Get https://10.3.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.3.0.1:443: i/o timeout
E0109 15:54:20.432705       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:147: Failed to list *v1.Endpoints: Get https://10.3.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.3.0.1:443: i/o timeout
>>>>>TONS OF:
I0109 15:54:49.932287       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
>>>>>
F0109 15:54:50.432330       1 dns.go:167] Timeout waiting for initialization
```

Api Server logs:

Tosn of:
```
E0109 15:47:14.843457       1 authentication.go:64] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, crypto/rsa: verification error]]
```

**Comment by jorge07** [comment]
To bring back dns we removed `default-token`s but also killed all `kube-proxy`
