### ISSUE TITLE
Dex certificate/key should be mandatory only when dex is turned on

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#601]
Running `kube-aws validate` on a cluster without Dex turned on but also without `credentials/dex.pem` causes this:

```
Error: Failed to initialize cluster driver: failed to read/create TLS assets: open credentials/dex.pem: no such file or directory
```

Same with `kube-aws update`. Perhaps the cert+key for Dex should only be validated as present when that feature is turned on? Otherwise this forces a user to run `render credentials` which in turn causes `update` to fail, see https://github.com/kubernetes-incubator/kube-aws/issues/600.

**Comment by camilb** [comment]
@c-knowles Missed this part on tests. Yes, we should remove validation for dex certificates, if dex is turned off. I'll take a look to see if we can fix this quickly.

**Comment by VinceMD** [comment]
any update?

**Comment by camilb** [comment]
@c-knowles @VinceMD Completely removed the certificates generation in #820. Closing.
