### ISSUE TITLE
Regression: Broken cluster when Kubelet TLS bootstrapping and Calico are both enabled

### ISSUE THREAD

**Issue by danielfm** [kubernetes-incubator/kube-aws#605]
I was trying to spawn a new cluster with both TLS bootstrapping and Calico enabled, but some pods failed to come up with the following error:

```
  27m	5m	488	kubelet, ip-10-0-0-38.sa-east-1.compute.internal						Warning	FailedSync	Error syncing pod, skipping: failed to "CreatePodSandbox" for "kubernetes-dashboard-v1.5.1-8khgd_kube-system(5ea55bb1-2b5c-11e7-b619-02b8aba0cd11)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kubernetes-dashboard-v1.5.1-8khgd_kube-system(5ea55bb1-2b5c-11e7-b619-02b8aba0cd11)\" failed: rpc error: code = 2 desc = NetworkPlugin cni failed to set up pod \"kubernetes-dashboard-v1.5.1-8khgd_kube-system\" network: invalid configuration: [unable to read client-cert /etc/kubernetes/ssl/worker.pem for  due to open /etc/kubernetes/ssl/worker.pem: no such file or directory, unable to read client-key /etc/kubernetes/ssl/worker-key.pem for  due to open /etc/kubernetes/ssl/worker-key.pem: no such file or directory]"
```

It seems that [this change](https://github.com/kubernetes-incubator/kube-aws/blame/master/core/controlplane/config/templates/cloud-config-worker#L821) is responsible for this issue, since the certificate files generated via the CSR workflow has different names (`kubelet-client.crt` and `kubelet-client.key`).

**Comment by mumoshu** [comment]
@danielfm Thanks for the report and the fix 👍
I'd greatly appreciate your continuous efforts for supporting the TLS bootstrapping feature, which is very useful.
