### ISSUE TITLE
ALB as a k8s API endpoint load balancer

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#608]
Extracted from https://github.com/kubernetes-incubator/kube-aws/issues/598#issuecomment-297921158

**Comment by mumoshu** [comment]
In the meantime, I'm going to add `apiEndpoints[].loadBalancer.classic` which defaults to `true`, can be set to `false ` to turn it into an ALB.
Probably in v0.9.8, `classic` would start defaulting to `false` - ALB by default.

**Comment by mumoshu** [comment]
Let me note that in the future `apiEndpoints[].loadBalancer.targetGroups[].arn` could be added to reuse existing an ALB - not provision ELB nor ALB for an endpoint but just add controller nodes to target group(s).
This supports similar use-cases like one with specifying `apiEndpoints[].loadBalancer.id` to reuse an existing ELB.
Would anyone like to work on it?

**Comment by mumoshu** [comment]
"ALB as a K8S API load balancer" seems to be not a realistic option at the moment - please see my comments and the relevant discussion in https://github.com/kubernetes-incubator/kube-aws/pull/651
If no one would use it, I'm going to abandon the PR (at least for now).

**Comment by mumoshu** [comment]
Hi @Vrtak-CZ @gleeb @camilb, thanks for expressing your interests on this featur!
Could I have your thoughts?
Would you use ALB as API load balancer even if it degrades security?

**Comment by Vrtak-CZ** [comment]
Hi @mumoshu I'm forgot information about missing pass-through option for TLS connection in ALB. So for me classic ELB is better for security reasons.

**Comment by mumoshu** [comment]
@Vrtak-CZ Thanks for the confirmation! Yes, it is a major missing feature affecting us now.

On the other hand, I began to believe ALB as a L7 loadbalancer doesn't provide us an additional benefit over a classic ELB when what we want was L4(=tcp pass-through) - ALB will never support the pass-through thing.

The next best feature could be supported by ALB would be ALB filling a certain HTTP header with the client TLS cert so that apiserver could be modified to identify and authenticate the client with it but.. it will never happen as long as there's still ELB available.

**Comment by camilb** [comment]
Hi @mumoshu looks like the classic ELB fits better in this case.  At the moment ALB makes more sense when you have multiple backends, something like the [alb-ingress-controller](https://github.com/coreos/alb-ingress-controller) from CoreOS to expose several services using a single ALB.

**Comment by mumoshu** [comment]
Closing this issue until ALB by any chance start to support tls pass-through

**Comment by Vrtak-CZ** [comment]
Good news! https://aws.amazon.com/blogs/aws/new-network-load-balancer-effortless-scaling-to-millions-of-requests-per-second/

**Comment by redbaron** [comment]
@Vrtak-CZ , created https://github.com/kubernetes-incubator/kube-aws/issues/937
