### ISSUE TITLE
 The valid uri pattern for it is s3://mybucket/mydir or s3://mybucket [recovered]

### ISSUE THREAD

**Issue by rahmanusta** [kubernetes-incubator/kube-aws#614]
Hello, I'm following the instruction on getting started tutorial and I get this when I validate my cluster. 

```
Validating UserData and stack template...
panic: failed to determin location for userdata-controller-99e19cc475452c63b79557cf3561a75a3ab4730eba57c2dee83ac2a11d1a830d: failed to parse s3 uri(=/kube-aws/clusters/usta-cluster/exported/stacks): The valid uri pattern for it is s3://mybucket/mydir or s3://mybucket [recovered]
        panic: failed to determin location for userdata-controller-99e19cc475452c63b79557cf3561a75a3ab4730eba57c2dee83ac2a11d1a830d: failed to parse s3 uri(=/kube-aws/clusters/usta-cluster/exported/stacks): The valid uri pattern for it is s3://mybucket/mydir or s3://mybucket
```

**Comment by redbaron** [comment]
value you pass `--s3-uri` argument should start with a  valid S3 bucket, like s3://mybucktname

**Comment by rahmanusta** [comment]
Thanks, it is like that.

`kube-aws validate --s3-uri=s3://kuberusta`

**Comment by prasadkatti** [comment]
Hi. I am also seeing the same issue. How was this resolved? I have a bucket called `somebucket` which has `kube-aws/kube-aws/kube-aws/clusters/my-cluster-name/exported/stacks/my-cluster-name/stack.json`. What should be the value for `--s3-uri`?

**Comment by mumoshu** [comment]
Hi @prasadkatti, I'm quite confused with the repeated `kube-aws`'s in your s3 prefix but could you try with `--s3-uri s3://somebucket/kube-aws/kube-aws` ?

**Comment by prasadkatti** [comment]
Hi @mumoshu. I have joined the kube-aws Slack channel to ask for help there.

**Comment by mumoshu** [comment]
@prasadkatti Thanks, I've replied to you there
