### ISSUE TITLE
[docs] some pointers for complete kubernetes newbs

### ISSUE THREAD

**Issue by hangtwenty** [kubernetes-incubator/kube-aws#621]
I am a newb to both kubernetes and kube-aws. I was able to create my cluster with kube-aws very easily, but then when I went onto some hello-world style tasks (like deploying nginx), things are not working, and I am pretty sure my cluster is broken. This probably has to do with my AWS account or something I misconfigured. What would help me as a newb is to to see examples re: a hello-world deployment, with various outputs expected from `kubectl get` and `kubectl describe`. This would let a newb like me know quickly if something fundamental is wrong with my cluster.

I know this could be seen as out of scope, but ... I'm not saying that it's the kube-aws docs' job to teach Kubernetes basics - rather saying it should show how to smoketest the cluster using a basic deployment and inspecting some outputs.

Thoughts?

**Comment by hangtwenty** [comment]
(I can provide more detail on my specific issue but I thought it was better to generalize this. LMK.)

**Comment by hangtwenty** [comment]
On second thought, maybe hello world is irrelevant, and some basic `kubectl` expected outputs would do the trick.

**Comment by hangtwenty** [comment]
FWIW, I found my own issue was that I specified `apiEndpoints.loadBalancer.apiAccessAllowedSourceCIDRs` in `cluster.yaml` ... to restrict to my own IP (as CIDR block) and some internal network IPs. This is kneejerk for me, I restrict every experiment to these IPs. Others might do similar..?

The failures were silent, at least for what I was looking at ... None of the `kubectl` `get` or `describe` things I saw really clued me to this. Cluster didn't look particularly broken. My best hint was that none of my `deployments` were working but I couldn't tell why. I just did some rubber-duck debugging and realized this was the one customization I was doing, and maybe I should not do it. Et voila, heh.

Maybe the docs could stress that newbs should just review the `cluster.yaml` but **not** customize anything, on their first run. Does that make sense?

**Comment by hangtwenty** [comment]
And/or: the docs could suggest trying the [Conformance Tests](https://coreos.com/kubernetes/docs/latest/conformance-tests.html) against your cluster

**Comment by mumoshu** [comment]
Hi @hangtwenty, thanks a lot for the detailed feedback 👍 

> Maybe the docs could stress that newbs should just review the cluster.yaml but not customize anything, on their first run. Does that make sense?

Agreed.

> And/or: the docs could suggest trying the Conformance Tests against your cluster

Agreed. I also wondered before if we'd better add a command to easily run conformance tests which would look like `kube-aws run-conformance-tests`. This way users can just grab a kube-aws binary from the github releases page and even running the tests can be done with the binary, without checking out kube-aws source. Any thoughts on the idea?

> FWIW, I found my own issue was that I specified `apiEndpoints.loadBalancer.apiAccessAllowedSourceCIDRs` in `cluster.yaml` ... to restrict to my own IP (as CIDR block) and some internal network IPs. This is kneejerk for me, I restrict every experiment to these IPs. Others might do similar..?

Would you mind sharing me the specific mistake(?) you've made into the cluster?
You've restricted the range too much which resulted in the kubelets to be unable to work at all?
Anyway, I guess we can add more validations to enable users to notice mistakes early.

**Comment by mumoshu** [comment]
@hangtwenty I'd appreciate it if I could have one more feedback from you -
Running all the conformance tests takes approx 1 hour for me to complete. Do you really want to do so, or I guess you'd actually like to have a smaller set of conformance tests completes within a reasonable time(=maybe several minutes?)

**Comment by hangtwenty** [comment]
> Agreed. I also wondered before if we'd better add a command to easily run conformance tests which would look like `kube-aws run-conformance-tests`. This way users can just grab a kube-aws binary from the github releases page and even running the tests can be done with the binary, without checking out kube-aws source. Any thoughts on the idea?

I think that's a great idea! I didn't realize the conformance tests take an hour, so it doesn't really address the exact case I'm talking about here (total newb looking for immediate feedback), but it's good to add in anyways I think.  As a next step.

I do not know exactly why messing with that setting led to a non-functional cluster. Once I did a cluster with no customization, it worked. I could deploy some services etc. I think I will have to get further along in my understanding of kubernetes before I can elaborate more.

For a newb to catch their own mistakes immediately, probably 2-4 small things could help:

* Maybe tell them that if they are totally new to kubernetes, they might want to [start with minikube](https://kubernetes.io/docs/tutorials/stateless-application/hello-minikube/)
* With `kube-aws`, ncourage them not to customize anything upon the first run (unless they are already comfortable running k8s in aws and they are just coming over from `kops` previous experience or something)
* Include some small examples of `kubectl` output for basic sanity checking ...
* Maybe [link them right to Kubernetes tutorials](https://kubernetes.io/docs/tutorials/)
