### ISSUE TITLE
SpotFleet pools are deployed without detailed monitoring

### ISSUE THREAD

**Issue by paalkr** [kubernetes-incubator/kube-aws#623]
Any spot fleet pools defined the cluster.yaml are deployed with only regular (5 minutes) monitoring. Detailed monitoring should be enabled for spot fleets.

PS, the regular node pools does have detailed (1 minutes) monitoring enabled.

**Comment by paalkr** [comment]
Just adding a reference to the AWS CloudFormation documentation to pinpoint whats missing ;)
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-spotfleet-spotfleetrequestconfigdata-launchspecifications.html#cfn-ec2-spotfleet-spotfleetrequestconfigdata-launchspecifications-monitoring

**Comment by paalkr** [comment]
Detailed monitoring is enabled by default in a regular AWS CloudFormation LaunchConfiguration resource
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-launchconfig.html#cfn-as-launchconfig-instancemonitoring
But as I pointed out in my previous message, detailed monitoring is disabled by default in a Spot Fleet LaunchSpecification

**Comment by mumoshu** [comment]
Hi @paalkr, thanks as always for the detailed feedback 👍 

Let me first add the reference to the related issue #320 

AFAIK, a detailed monitoring for EC2 is not free; it costs $2.1 per instance per month. I guess not everyone wants to enable it by default?

However just to be clear, I personally agree to enable it by default :) Who wants to build a production cluster without enabling it?

If no one is opposing I believe we can just start enabling it by default as long as we at least add an explanation like "you need to modify stack templates to disable the detailed monitoring" somewhere in our documentation.
Your thoughts?

**Comment by paalkr** [comment]
Hi @mumoshu , tanks for the replay

First, I wouldn't recommend anyone to deploy a production grade cluster without detailed monitoring ;) On the other hand, it could very well be a configurable parameter for a worker pool.

What's confusing right now is the difference in behavior between a regular worker pool and a spot fleet worker pool, and this is AWS's fault not kube-aws. 
A regular AutoScaling group in CloudFormation enables detailed monitoring if nothing else is specified. A spot fleet on the other hand does not.

What a about just adding a config keyword to the worker pool in the cluster.yaml, that let people turn on or off detailed monitoring?

I added the necessary changes to my worker pool template file before deploying the cluster, but I guess it would be more convenient to have this option in the config. And the user experience would also be harmonized between the different types of worker pools (spot fleet and regular).

**Comment by mumoshu** [comment]
@paalkr Thanks for the reply 👍 

> First, I wouldn't recommend anyone to deploy a production grade cluster without detailed monitoring ;)

So am I :)

> What's confusing right now is the difference in behavior between a regular worker pool and a spot fleet worker pool,

Agreed.

> What a about just adding a config keyword to the worker pool in the cluster.yaml, that let people turn on or off detailed monitoring?

As I prefer not to unnecessarily complicate cluster.yaml and I strongly believe it should be enabled by default, how about doing this in 2 steps?
For the step 1, we just enable detailed monitoring even for spot fleet by default.
For the step 2, enhance cluster.yaml to allow toggling detailed monitoring per node pool, only if anyone submits a feature request to do so.

**Comment by paalkr** [comment]
@mumoshu , thanks for the reply

I have no trouble with kube-aws applying detailed monitoring as default behavior, it think it is wise to help users applying best practices. Your suggested step 1 is a very easy fix, only require adding one line of code to the worker pool template. You can decide if in the future adding a config keyword to any worker pool configs to control detailed monitoring would be needed or not

**Comment by mumoshu** [comment]
@paalkr Thanks for the confirmation! Let's go ahead with the 2-steps way then.

**Comment by mumoshu** [comment]
This is already resolved by #693. Thanks again for your contribution @paalkr 👍
