### ISSUE TITLE
Documentation about kube-aws internals

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#628]
My colleague @everpeace suggested me to write a documentation to help users better understand kube-aws internals,
which may or may not contain (at least) the following topics:
* List of tools involved in the lifecycle of a kube-aws cluster, and their roles
  - kube-aws binary, s3, cfn, cloud-init, systemd, kubelet(controller, worker), k8s apps(installed via manifests, the install-kube-system unit)
* List of systemd units(services and timers, ones bundled with Contaier Linux, ones from kube-aws), their roles, dependencies, etc. involved in the lifecycle of a kube-aws cluster
   - etcd-member.service, kubelet.service, cfn-etcd-environment.service, etcdadm-reconfigure.service, etcdadm-check.(service,timer)

Anyone especially likes to one of the topics listed above?
Wants to add more?
Any suggestions on tools used to draw easy diagrams of the topics, the structure and the format of the documentation, and vice versa?
I'd appreciate your ideas.

**Comment by everpeace** [comment]
If it could be added more, it would be a time-consuming task though,  I would suggest automatic etcd failover.

> etcdadm-reconfigure.service, etcdadm-check.(service,timer)
If these units responsible for it, my suggestion was included by mumoshu's proposal.

**Comment by mumoshu** [comment]
@everpeace Thanks for the feedback 👍 

Yes, those units are responsible for the feature.

Also, your feedback made me come up with adding something like below to draw a big picture of kube-aws before internal details like [mentioned above](https://github.com/kubernetes-incubator/kube-aws/issues/628#issue-226921501)

* Define all the features involved in the lifecycle of a kube-aws cluster
   * k8s cluster bootstrapping
   * automatic etcd failover/backup/restore
   * others(Please remind me!)

**Comment by everpeace** [comment]
> adding something like below to draw a big picture of kube-aws before internal details

@mumoshu That's good idea!  Big picture must be great help when users will dive into internals.

**Comment by c-knowles** [comment]
Good idea, I'd be happy to cover some basics here and then we can iterate on them. @mumoshu I'm just awaiting the result of https://github.com/kubernetes-incubator/kube-aws/issues/534.

**Comment by ivanilves** [comment]
Great initiative! I would love having this kind of documentation. :pray:

**Comment by VinceMD** [comment]
great idea. I'm happy with the topics
