### ISSUE TITLE
ETCDADM-save.service failed

### ISSUE THREAD

**Issue by billyteves** [kubernetes-incubator/kube-aws#630]
I have received an error upon creating kubernetes cluster. My testing setup:
- kube-aws: 0.9.6
- controller: 1; public subnet
- worker: 1; public subnet
- etcd: 1; private subnet; set version to: "3.1.3" based on the comment in the cluster.yaml (but it just installed the 2.3.7 version)

No issues returned after CF completed the provisioning of resources. But when I open the etcd server via my bastion host, the etcdadm-save.service failed to start. Upon looking on the logs:

`
core@ip-172-50-5-223 ~ $ systemctl status etcdadm-save.service
etcdadm-save.service - etcd snapshot
   Loaded: loaded (/etc/systemd/system/etcdadm-save.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2017-05-09 05:30:41 UTC; 20s ago
  Process: 18097 ExecStart=/opt/bin/etcdadm save (code=exited, status=1/FAILURE)
  Process: 18087 ExecStartPre=/usr/bin/systemctl is-active etcd-member.service (code=exited, status=0/SUCCESS)
 Main PID: 18097 (code=exited, status=1/FAILURE)
      CPU: 2.009s

May 09 05:30:39 ip-172-50-5-223.us-east-2.compute.internal etcdadm[18097]: /opt/bin/etcdadm: info: member_upload_snapshot: uploading /var/run/coreos/etcdadm/snapshots/etcd0.db to s3://my-bucket-name/kube-aws-096/kube-aws/clusters/ha-096/instances/80bceda0-3476-11e7-9ed8-50a68a05d035/etcd-snapshots/snapshot.db
May 09 05:30:40 ip-172-50-5-223.us-east-2.compute.internal etcdadm[18097]: [442B blob data]
May 09 05:30:40 ip-172-50-5-223.us-east-2.compute.internal etcdadm[18097]: /opt/bin/etcdadm: info: member_upload_snapshot: verifying the upload...
May 09 05:30:40 ip-172-50-5-223.us-east-2.compute.internal etcdadm[18097]: /opt/bin/etcdadm: info: member_remote_snapshot_exists: checking existence of s3://my-bucket-name/kube-aws-096/kube-aws/clusters/ha-096/instances/80bceda0-3476-11e7-9ed8-50a68a05d035/etcd-snapshots/snapshot.db
May 09 05:30:41 ip-172-50-5-223.us-east-2.compute.internal etcdadm[18097]: An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied
May 09 05:30:41 ip-172-50-5-223.us-east-2.compute.internal etcdadm[18097]: /opt/bin/etcdadm: info: member_remote_snapshot_exists: s3://my-bucket-name/kube-aws-096/kube-aws/clusters/ha-096/instances/80bceda0-3476-11e7-9ed8-50a68a05d035/etcd-snapshots/snapshot.db does not exist
May 09 05:30:41 ip-172-50-5-223.us-east-2.compute.internal systemd[1]: etcdadm-save.service: Main process exited, code=exited, status=1/FAILURE
May 09 05:30:41 ip-172-50-5-223.us-east-2.compute.internal systemd[1]: Failed to start etcd snapshot.
May 09 05:30:41 ip-172-50-5-223.us-east-2.compute.internal systemd[1]: etcdadm-save.service: Unit entered failed state.
May 09 05:30:41 ip-172-50-5-223.us-east-2.compute.internal systemd[1]: etcdadm-save.service: Failed with result 'exit-code'.

`

I did try the simulation of the policy given to the etcd instance and it seems the S3 permissions are not allowed. So I tried to modify the policy and just set the S3:* allow all for the sake of testing. And it works. 

Is this a bug on the etcd policy? the S3 url including the sub-directories exist*

**Comment by mumoshu** [comment]
Hi @billyteves, thanks for the feedback 👍 
Just a quick question but which part of iam policies passde to etcd nodes didn't to seem to correct permissions?
AFAIK, it should have according to the part of the stack template below:

```
{
                  "Effect": "Allow",
                  "Action": [
                    "s3:List*"
                  ],
                  "Resource": "arn:{{.Region.Partition}}:s3:::{{$.EtcdSnapshotsS3Bucket}}",
                  "Condition": {
                    "StringLike": {
                      "s3:prefix": { "Fn::Join" : [ "", [{{$.EtcdSnapshotsS3PrefixRef}}, "/*" ]]}
                    }
                  }
                },
```

**Comment by mumoshu** [comment]
Also

> (but it just installed the 2.3.7 version)

Excuse me but I don't understand here - Would you mind sharing me how you confirmed the version of etcd installed?
For example, `etcdctl` in the container linux host isn't modified even when the running etcd is version 3.

**Comment by billyteves** [comment]
@mumoshu 
Apologies on the simulation, I forgot to set the ARN while doing the simulation of the policy. And yes it did passed the simulation. Unfortunately, upon checking the etcd instance, the etcdadm-save.service still not working. It is still showing the same issue: ` An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied `

here's the generated role for etcd:

`
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "kms:Decrypt",
            "Resource": "<kms-arn>",
            "Effect": "Allow"
        },
        {
            "Action": "ec2:DescribeTags",
            "Resource": "*",
            "Effect": "Allow"
        },
        {
            "Action": "ec2:DescribeVolumes",
            "Resource": "*",
            "Effect": "Allow"
        },
        {
            "Action": "ec2:AttachVolume",
            "Resource": "*",
            "Effect": "Allow"
        },
        {
            "Action": "ec2:DescribeVolumeStatus",
            "Resource": "*",
            "Effect": "Allow"
        },
        {
            "Action": "ec2:AssociateAddress",
            "Resource": "*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "s3:GetObject"
            ],
            "Resource": "arn:aws:s3:::<my-s3-bucket>/kube-aws-096/kube-aws/clusters/ha-096/exported/stacks/control-plane/userdata-etcd*",
            "Effect": "Allow"
        },
        {
            "Condition": {
                "StringLike": {
                    "s3:prefix": "/<my-s3-bucket>/kube-aws/clusters/ha-096/instances/efcb3620-3480-11e7-9930-50faf8bfacd1/etcd-snapshots/*"
                }
            },
            "Action": [
                "s3:List*"
            ],
            "Resource": "arn:aws:s3:::<my-s3-bucket>",
            "Effect": "Allow"
        },
        {
            "Action": [
                "s3:*"
            ],
            "Resource": "arn:aws:s3:::<my-s3-bucket>/kube-aws-096/kube-aws/clusters/ha-096/instances/efcb3620-3480-11e7-9930-50faf8bfacd1/etcd-snapshots/*",
            "Effect": "Allow"
        },
        {
            "Action": "ec2:DescribeInstances",
            "Resource": "*",
            "Effect": "Allow"
        }
    ]
}
`

as for the version, the etcd image that runs via rkt is 3.1.3 . I just invoke the command etcd2 --version not knowing that the etcd of kubernetes is running via rkt.

**Comment by billyteves** [comment]
@mumoshu 

it's weird, the service able to do snapshot and upload to s3 bucket. but listing fails. I also watch the snapshot in s3 and it seems that it is constantly being updated by the etcdadm-save.service (based on the changes of the last modified date) .

**Comment by mumoshu** [comment]
@billyteves Thanks for the reply.

It does seem like ListObjects called to confirm an upload was successful is failing due to a missing permission. The upload itself seems to have succeeded hence the snapshot is being updated(as expected).

Would you mind modifying the `Resources` section for the action `[ "s3:List*" ]` from:

```
"Action": [ "s3:List*" ], "Resource": "arn:aws:s3:::<my-s3-bucket>"
```

to

```
"Resource": [
  "arn:aws:s3:::<my-s3-bucket>",
  "arn:aws:s3:::<my-s3-bucket>/*",
]
```

to see if it resolves the issue?

**Comment by jeremyd** [comment]
I have this same issue, found the problem by manually adjusting the iam role.  The policy we generated has a leading slash.  Without the leading slash, the permissions errors go away.

example without the slash (works).  PR incoming
```
"Condition": {
                "StringLike": {
                    "s3:prefix": "kube-aws/clusters/mycluster/instances/ac46bac0-341a-11e7-b9d4-500c21792a35/etcd-snapshots/*"
                }
            },
```

**Comment by mumoshu** [comment]
Great job @jeremyd! It seems like I somehow missed that

**Comment by kylegato** [comment]
So, one of my ETCD nodes attempted an auto-recovery and re-launched it and it failed, I believe as a result of this bug, being unable to check for the snapshot, and now it won't join the cluster. I tried terminating the instance and letting it re-create after fixing the IAM perms but it's still broken. Any suggestions?

**Comment by jeremyd** [comment]
@kylegato if you had the wrong IAM permissions it's possible you have no backups.  You can modify the IAM permission manually to remove the leading slash but you will need to manually add the etcd node back into the cluster by removing the node from the cluster, erasing the data volume, and joining it to the running cluster.  Assuming you have 2 good nodes left.
