### ISSUE TITLE
ETCD1 failed to UP

### ISSUE THREAD

**Issue by billyteves** [kubernetes-incubator/kube-aws#631]
Test case: Add another ETCD instance
Setup:
Kubernetes is Up with only ETCD0, runs in private subnet

Tried to update the etcd number of instances from 1 to 2, cloudformation rolled back the changes. Here's the result inside ETCD1 instance:

`
etcdctl cluster-health
cluster may be unhealthy: failed to list members
Error:  client: etcd cluster is unavailable or misconfigured
error #0: client: endpoint https://ec2-ip-here.us-east-2.compute.amazonaws.com:2379 exceeded header timeout
...............
etcdadm-check.service - etcd health check
   Loaded: loaded (/etc/systemd/system/etcdadm-check.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2017-05-09 08:36:03 UTC; 9s ago
  Process: 3545 ExecStartPre=/usr/bin/systemctl is-active etcd-member.service (code=exited, status=3)
      CPU: 2ms

May 09 08:36:03 ip-172-50-5-246.us-east-2.compute.internal systemd[1]: Starting etcd health check...
May 09 08:36:03 ip-172-50-5-246.us-east-2.compute.internal systemctl[3545]: activating
May 09 08:36:03 ip-172-50-5-246.us-east-2.compute.internal systemd[1]: etcdadm-check.service: Control process exited, code=exited status=3
May 09 08:36:03 ip-172-50-5-246.us-east-2.compute.internal systemd[1]: Failed to start etcd health check.
May 09 08:36:03 ip-172-50-5-246.us-east-2.compute.internal systemd[1]: etcdadm-check.service: Unit entered failed state.
May 09 08:36:03 ip-172-50-5-246.us-east-2.compute.internal systemd[1]: etcdadm-check.service: Failed with result 'exit-code'.
...............
May 09 08:35:06 ip-172-50-5-246.us-east-2.compute.internal etcd-wrapper[2457]: 2017-05-09 08:35:06.930817 E | rafthttp: request sent was ignored (cluster ID mismatch: peer[97cb6f55fb0dba17]=924cc7ceff9b62df, local=6a725d19235b1607)
May 09 08:35:06 ip-172-50-5-246.us-east-2.compute.internal etcd-wrapper[2457]: 2017-05-09 08:35:06.931880 E | rafthttp: request sent was ignored (cluster ID mismatch: peer[97cb6f55fb0dba17]=924cc7ceff9b62df, local=6a725d19235b1607)
May 09 08:35:07 ip-172-50-5-246.us-east-2.compute.internal etcd-wrapper[2457]: 2017-05-09 08:35:07.042099 E | rafthttp: request sent was ignored (cluster ID mismatch: peer[97cb6f55fb0dba17]=924cc7ceff9b62df, local=6a725d19235b1607)
May 09 08:35:07 ip-172-50-5-246.us-east-2.compute.internal etcd-wrapper[2457]: 2017-05-09 08:35:07.043190 E | rafthttp: request sent was ignored (cluster ID mismatch: peer[97cb6f55fb0dba17]=924cc7ceff9b62df, local=6a725d19235b1607)
May 09 08:35:07 ip-172-50-5-246.us-east-2.compute.internal etcd-wrapper[2457]: 2017-05-09 08:35:07.058289 I | raft: 87e8bbdbbf34d4f2 is starting a new election at term 376
May 09 08:35:07 ip-172-50-5-246.us-east-2.compute.internal etcd-wrapper[2457]: 2017-05-09 08:35:07.058463 I | raft: 87e8bbdbbf34d4f2 became candidate at term 377
May 09 08:35:07 ip-172-50-5-246.us-east-2.compute.internal etcd-wrapper[2457]: 2017-05-09 08:35:07.058631 I | raft: 87e8bbdbbf34d4f2 received MsgVoteResp from 87e8bbdbbf34d4f2 at term 377
May 09 08:35:07 ip-172-50-5-246.us-east-2.compute.internal etcd-wrapper[2457]: 2017-05-09 08:35:07.058825 I | raft: 87e8bbdbbf34d4f2 [logterm: 1, index: 2] sent MsgVote request to 97cb6f55fb0dba17 at term 377
May 09 08:35:07 ip-172-50-5-246.us-east-2.compute.internal etcd-wrapper[2457]: 2017-05-09 08:35:07.060773 E | rafthttp: request sent was ignored (cluster ID mismatch: remote[97cb6f55fb0dba17]=924cc7ceff9b62df, local=6a725d19235b1607)
May 09 08:35:07 ip-172-50-5-246.us-east-2.compute.internal etcd-wrapper[2457]: 2017-05-09 08:35:07.154089 E | rafthttp: request sent was ignored (cluster ID mismatch: peer[97cb6f55fb0dba17]=924cc7ceff9b62df, local=6a725d19235b1607)
`

**Comment by redbaron** [comment]
@billyteves , my understanding is that change of number of instances in etcd is not supported.

**Comment by mumoshu** [comment]
Thanks @redbaron - yes, your understanding is correct.
@billyteves Sorry for the confusion but It isn't supported - perhaps we can add the support by somehow improving [`etcdadm reconfigure`](https://github.com/kubernetes-incubator/kube-aws/blob/master/etcdadm/etcdadm#L631) to instruct newly added etcd nodes to join an existing etcd cluster but I'm not yet sure if it is really feasible.

**Comment by billyteves** [comment]
@redbaron @mumoshu thanks! I missed that documentation regarding the change of number of instances.

**Comment by mumoshu** [comment]
@billyteves It wasn't even documented. I'm going to document it like #635. Would it sound good to you?

**Comment by billyteves** [comment]
@mumoshu yup! looks good to me. thanks!

**Comment by mumoshu** [comment]
@billyteves Thanks for the confirmation 👍

**Comment by mumoshu** [comment]
To be extra clear on the current situation and space of possible improvements, I've opened #647. This this as the original question was answered!
