### ISSUE TITLE
ETCD Data Management

### ISSUE THREAD

**Issue by billyteves** [kubernetes-incubator/kube-aws#636]
I was wondering if there is this kind of mechanism in kubernetes old state of data or something that is not in used anymore. So that the data in etcd will be manage.

**Comment by mumoshu** [comment]
@billyteves Seems like you've missed several words in your question but you meant "to find old state of data or something that is not in used anymore", right?
I'm also interested but unfortunately not aware of any solution.
Anyone?

**Comment by mumoshu** [comment]
Regardless of there are such solutions or not, basically, I won't try to find such "leaks" made by k8s in an etcd cluster until a sign of a leak is observed. I guess k8s is responsible to clean up all the unnecessary data from etcd.
@billyteves Would you mind syncing up with me about why you'd like to do so?
