### ISSUE TITLE
Etcd management does not clean up old/stopped docker containers

### ISSUE THREAD

**Issue by jeremyd** [kubernetes-incubator/kube-aws#640]
Etcdadm runs docker for awscli actions periodically.  It does not use --rm so these stopped containers grow over time and eventually will fill the root disk.  We just need to use --rm on the docker run to prevent this.  PR incoming.

**Comment by mumoshu** [comment]
Closing this as the fix #641 has been merged.
@jeremyd Thanks for the report and the fix 👍
