### ISSUE TITLE
kube-aws up failed - AWS::AutoScaling::AutoScalingGroup Received 0 SUCCESS signal(s) out of 1.

### ISSUE THREAD

**Issue by brant4test** [kubernetes-incubator/kube-aws#642]
Hi, Team, 
An error I met is attached. Need your help. Thanks!
[https://groups.google.com/forum/#!topic/coreos-user/M0b-YM6lWnQ](url)

The CloudFormation status changed from
	
Workers    cilium-Nodepool1-29BC7GBPBUWJ-Workers-1I99OW72S5073    AWS::AutoScaling::AutoScalingGroup    CREATE_IN_PROGRESS    Resource creation Initiated

To

Failed to receive 1 resource signal(s) for the current batch. Each resource signal timeout is counted as a FAILURE.

FYI,
core@ip-172-31-14-45:~/cilium$ kube-aws up --s3-uri s3://coreos-***-***-state-store
WARN: the worker node pool "nodepool1" is associated to a k8s API endpoint behind the DNS name "***.***" managed by YOU!
Please never point the DNS record for it to a different k8s cluster, especially when the name is a "stable" one which is shared among multiple k8s clusters for achieving blue-green deployments of k8s clusters!
kube-aws can't save users from mistakes like that
Creating AWS resources. Please wait. It may take a few minutes.

Error: Error creating cluster: Stack creation failed: CREATE_FAILED : The following resource(s) failed to create: [Nodepool1].

Printing the most recent failed stack events:
CREATE_FAILED AWS::CloudFormation::Stack cilium The following resource(s) failed to create: [Nodepool1].
CREATE_FAILED AWS::CloudFormation::Stack Nodepool1 Embedded stack arn:aws:cloudformation:us-west-1:851411223196:stack/cilium-Nodepool1-29BC7GBPBUWJ/12136f10-3277-11e7-9a12-500c5967ce56 was not successfully created: The following resource(s) failed to create: [Workers].

**Comment by mumoshu** [comment]
Hi @brant4test, thanks for trying kube-aws!
As the warning message `WARN: the worker node pool "nodepool1" is associated to a k8s API endpoint behind the DNS name "***.***" managed by YOU!` says, it seems like you've configured `worker.nodePools[].apiEndpointName` or any of `apiEndpoints[]`.
Could you share your cluster.yaml and your intentions on those two settings?

**Comment by brant4test** [comment]
![cloudformation creation error - auto scaling group is ok](https://cloud.githubusercontent.com/assets/7472674/25935695/e8689e9a-3656-11e7-869e-2c30bed7c8c0.JPG)
![cloudformation creation error](https://cloud.githubusercontent.com/assets/7472674/25935696/e8695056-3656-11e7-87ef-4ab6be4d5046.JPG)

**Comment by mumoshu** [comment]
The zero-success-signals could happen due to various reasons and therefore the concrete settings in cluster.yaml is essential for debugging!

**Comment by brant4test** [comment]
[cilium-ds.yaml.txt](https://github.com/kubernetes-incubator/kube-aws/files/992046/cilium-ds.yaml.txt)

**Comment by brant4test** [comment]
I only changed one spot after command "kube-aws init ..."
useCalico: true

**Comment by mumoshu** [comment]
Excuse m but how the `cilium-ds.yaml.txt` relates to this issue?

**Comment by mumoshu** [comment]
@brant4test Perhaps you've missed some flags to `kube-aws init`?

**Comment by brant4test** [comment]
uploaded a wrong file. 
[cluster.yaml.txt](https://github.com/kubernetes-incubator/kube-aws/files/992131/cluster.yaml.txt)

**Comment by brant4test** [comment]
This is the command I used.
$ kube-aws init \
--cluster-name=cilium \
--external-dns-name=**.*** \
--region=us-west-1 \
--availability-zone=us-west-1c \
--key-name=cilium \
--kms-key-arn="arn:aws:kms:us-west-1:********:key/***************"
Success! Created cluster.yaml

**Comment by brant4test** [comment]
following this guide, Initialize an asset directory, missing "--hosted-zone-id" here.
[https://coreos.com/kubernetes/docs/latest/kubernetes-on-aws-render.html](url)
I'll have a try with "--hosted-zone-id"

**Comment by mumoshu** [comment]
@brant4test Sorry for the confusion but the doc in the coreos.com site is not maintained anymore.
Please see #534 for more info

**Comment by brant4test** [comment]
@mumoshu Thanks! You're right! I missed  --hosted-zone-id  flag. Now everything is fine. :)
