### ISSUE TITLE
Support cross-stack references of VPC, IGW

### ISSUE THREAD

**Issue by gleeb** [kubernetes-incubator/kube-aws#643]
For deployment in an existing VPC, it would be more reliable and idiomatic if you could cross-stack reference the desired parameters

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-importvalue.html

**Comment by mumoshu** [comment]
Thanks for the feedback @gleeb!

I guess we can deprecate `vpcId` in cluster.yaml while adding `vpc.id` and `vpc.idFromStackOutput` instead. The latter is specified when you'd like to import the VPC from an another stack by a cross-stack reference. This ability of allowing to select either id or idFromStackOutput has been already implemented for `subnets[]` and known to work.

The same thing can be done on `internetGatewayId`.

Would it work for you?

**Comment by paalkr** [comment]
+1 for the ability to import vpcid from a stack export. We already use this functionality for subnets, and it works as expected.

**Comment by gleeb** [comment]
Yep, that would be grate

**Comment by mumoshu** [comment]
I'll try to include this in v0.9.8-rc.1

**Comment by mumoshu** [comment]
@gleeb @paalkr FYI, `vpc.idFromStackOutput` and `internetGateway.idFromStackOutput` are added via #760! It isn't included in any kube-aws release yet but you can test it by building a kube-aws binary from the latest master yourself.

**Comment by paalkr** [comment]
Thanks!
