### ISSUE TITLE
document password for ssh into node ec2 instance

### ISSUE THREAD

**Issue by tom-thorne** [kubernetes-incubator/kube-aws#644]
Apologies if this is an obvious question, but I can't find the answer anywhere.
I have a running cluster built by `kube-aws`, and am able to use `kubctl` with no trouble.
In order to try and increase logging, I'm trying to ssh directly to a EC2 node in the cluster using:
```
ssh -i my-ec2-key.pem root@ec2-XX-XX-XX-XX.compute-1.amazonaws.com
```
I see a connection, but I'm asked for a password.  What's the password?  Or should I be using a different username?

**Comment by c-knowles** [comment]
Yep, it's `core`. Covered by CoreOS docs at the moment - https://coreos.com/os/docs/latest/quickstart.html

**Comment by tom-thorne** [comment]
```
ssh -i my-ec2-key.pem core@ec2-XX-XX-XX-XX.compute-1.amazonaws.com
```
works for me - thanks
