### ISSUE TITLE
Controller nodes should be labeled `node-role.kubernetes.io/master`

### ISSUE THREAD

**Issue by redbaron** [kubernetes-incubator/kube-aws#649]
Currently we taint, but do not label masters. Label set by `kubeadm` is official and used at least here:

https://github.com/kubernetes/kubernetes/blob/f542fe12837560d991218289e8297dac7362c7ba/pkg/controller/service/servicecontroller.go#L627

**Comment by mumoshu** [comment]
For anyone interested - The node label is defined in https://github.com/kubernetes/kubernetes/blob/f542fe12837560d991218289e8297dac7362c7ba/cmd/kubeadm/app/constants/constants.go#L88
