### ISSUE TITLE
Master nodes fail to register due to invalid taint value

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#661]
It seems the changes from https://github.com/kubernetes-incubator/kube-aws/issues/543 introduced a different issue with kubelet registration:

```May 18 13:40:22 ip-10-0-33-84.eu-west-1.compute.internal kubelet-wrapper[1701]: E0518 13:40:22.410586    1701 kubelet_node_status.go:101] Unable to register node "ip-10-0-33-84.eu-west-1.compute.internal" with API server: Node "ip-10-0-33-84.eu-west-1.compute.internal" is invalid: metadata.labels: Invalid value: "node.alpha.kubernetes.io/role=master:NoSchedule": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')```

The cluster I just updated is running ok (apps are running) but master nodes are not registered/listed at all in kubectl. I'm using k8s 1.6.2. It's strange as the documentation for `--register-with-taints` indicates that our format is acceptable.

**Comment by mumoshu** [comment]
Thanks for the report!
Hmm, why is it complaining on metadata.labels even though what we specify
are taints?
2017年5月18日(木) 23:01 Chris Knowles <notifications@github.com>:

**Comment by c-knowles** [comment]
Yeah that is weird, I haven't customised it at all - my `cloud-config-controller` exactly mirrors what is produces from latest master @ 1e2ac13b1e06acc4e50d549de0b7d99c0381b9a6. Still investigating the cause but thought I'd put this here early for tracking.

**Comment by redbaron** [comment]
@c-knowles , sorry for breaking it for you :)

**Comment by c-knowles** [comment]
Thanks! I went to sleep and it was fixed when I woke up 👍  One missing character ☹️

**Comment by c-knowles** [comment]
I can confirm I have performed the small update from master then and update and master nodes are registering ok again 🎉
