### ISSUE TITLE
Documentation or a diagram of the way cluster.yml file tries to configure kube-aws

### ISSUE THREAD

**Issue by smrutiranjantripathy** [kubernetes-incubator/kube-aws#664]
Hi 
Cluster.yml is too long and a person often ends loosing the context after going through more than 1000 lines of configuration and comment.It would be better if we have a documentation or diagram of that .
I'm using v0.9.6.

Thanks

**Comment by c-knowles** [comment]
Hi @smrutiranjantripathy, I totally agree with you and it should be covered by https://github.com/kubernetes-incubator/kube-aws/issues/534 which is actively being worked on (by me).
