### ISSUE TITLE
A slack channel for kube-aws users just like for kubernetes-users.

### ISSUE THREAD

**Issue by smrutiranjantripathy** [kubernetes-incubator/kube-aws#665]
It would be easier for the end user if we have a slack channel for kube-aws users where people can ask each other and discuss regarding kube-aws issues and the optimum configuration for their needs.

**Comment by mumoshu** [comment]
Hi @smrutiranjantripathy, good idea!
Perhaps a dedicated slack team, rather than a chat room in the k8s.slack.io, would be better because then we won't lose messages due to the shared limit in number of messages 10000?
Any thoughts or ideas?

**Comment by smrutiranjantripathy** [comment]
@mumoshu That would be great !!!

**Comment by redbaron** [comment]
I'd vote for a room in existing kubernetes slack, reason is that there is a much bigger audience already present and it would be easy to move kube-aws discussions from main crowded rooms to quieter #kube-aws should they start elsewhere

**Comment by mumoshu** [comment]
How can I create/request a new chat room in the k8s slack btw? It seems like I don't have a permission to do so.

**Comment by mumoshu** [comment]
#kube-aws has been created in the k8s slack
