### ISSUE TITLE
Add support for FlexVolume plugins

### ISSUE THREAD

**Issue by paalkr** [kubernetes-incubator/kube-aws#666]
Currently a cluster built with kube-aws does not support FlexVolume plugins. Because in CoreOS the /usr/libexec/ is a read only file system
`--volume-plugin-dir=/etc/kubernetes/volumeplugins`
should be added to the kubelet service to get plugins like the [K8s CIFS plugin](https://github.com/sigma/cifs_k8s_plugin) to run

Should be a pretty easy one-liner addition to the cloud-config-worker template.

**Comment by mumoshu** [comment]
Hi @paalkr, thanks for the request 👍 

Could you help me to clarify a bit more about what you'd want to enable a flex-volume-based plugin like CIFS plugin overall and which part of it you want to configure via cloud-config?

I assume what we'd need are:

- Put all the assets from a flex-volume-based plugin into `{{volume-plugin-dir}}/<vendor~driver>/<driver>`
- Change the value for `--volume-plugin-dir` of kubelets to something other than the default `/usr/libexec/kubernetes/kubelet-plugins/volume/exec/`

Am I correct?
// Then, it isn't an one-liner addition?

**Comment by paalkr** [comment]
I implemented this in my cluster by modifying the parameters of kubelet in the kubelet.service for controllers and workers (cloud-config-controller and cloud-config-worker) templates. 

```
        --cluster_domain=cluster.local \
        --volume-plugin-dir=/etc/kubernetes/volumeplugins \
        --cloud-provider=aws
```

and I deployed the asses to the nodes using a container, that executes as a systemd service (under customSystemdUnits:) in the cluster.yaml file

```
  - name: cifs_k8s_plugin.service
    command: start
    enable: true
    content: |
      [Unit]
      Description=cifs_k8s_plugin
      Before=kubelet.service
      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStartPre=/bin/bash -c "docker run -v /etc/kubernetes/volumeplugins/hodique.info~cifs:/target sigma/cifs_k8s_plugin /target"
      ExecStart=/bin/true          
      [Install]
      WantedBy=kubelet.service 
```

**Comment by paalkr** [comment]
@mumoshu , any thought on how support for FlexVolumes can be added as an option?
FYI, the cifs plugin repo has been forked and fixed to work with K8s 1.6.x.
https://github.com/fvigotti/cifs_k8s_plugin 
I'm currently running this plugin in a production cluster, and it works as expected.

**Comment by mumoshu** [comment]
@paalkr I'm not yet sure but would it be enough to make kube-aws defaults to `--volume-plugin-dir=/etc/kubernetes/volumeplugins`, so that you can use `customSystemdUnits` in cluster.yaml to populate `/etc/kubernetes/volumeplugins/<driver>` as you like?

**Comment by mumoshu** [comment]
@paalkr Just realized we also need to pass `--enable-controller-attach-detach=false` to kubelets. Is this true for all the other FlexVolume plugins, too? If that's the case, we can also make kube-aws defaults to pass that flag to kubelet, too.

**Comment by paalkr** [comment]
@mumoshu , I'm not sure about other FlexVolume plugins, but at least for the CIFS-plugin you need to. I have modified my templates according to the guides given by fvigotti, and the plugins has been working great in my setup for production workloads for week. No issues observed so far.

**Comment by paalkr** [comment]
@mumoshu , any chance to get this additions into the next RC release?

**Comment by VinceMD** [comment]
I'm also interested in FlexVolume support. 

We use Ansible + Packer to bake our AMI (prebake all docker and rkt images for speed + install Corporate stuff and certs). This is what we are adding:

```- name: Create Kubernetes volume plugins directory
  file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
    mode: 0644
  with_items:
    - "/etc/kubernetes"
    - "/etc/kubernetes/volumeplugins"```

And in cluster.yaml
`       kubeletOpts: --volume-plugin-dir=/etc/kubernetes/volumeplugins`

We are testing that

**Comment by georgej-github** [comment]
I work with @VinceMD, we tested with : 
`kubeletOpts: --volume-plugin-dir=/etc/kubernetes/volumeplugins`
but this does not seem to make any difference.  We are running CoreOS.  On the node looking at the kubelet process args, it still does not show `--volume-plugin-dir` in the list of args.

If not `kubeletOpts` is there another option that allows us to pass --volume-plugin-dir to kubelet?
