### ISSUE TITLE
Dex integration is putting secrets inside ConfigMap

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#668]
Dex supports separating out secrets by having substitutions like `$GITHUB_CLIENT_SECRET` in the config file and then having them in environment variables. See https://github.com/coreos/dex/blob/master/examples/k8s/dex.yaml.

The Dex integration in kube-aws has the security flaw that such secrets are stored directly in the ConfigMap. It's quite major if all developers are granted the RBAC `view` access which grants ConfigMap read but not Secret read.

**Comment by mumoshu** [comment]
@c-knowles Thanks for the good catch!
I have never realized that dex supported such templating.
Indeed It should be a `Secret` then.
Would you mind submitting a PR for the fix?
cc @camilb

**Comment by c-knowles** [comment]
I will do if/when I have a working Dex setup otherwise it's going to be hard for me to verify it end to end. I might need to co-ordinate with @camilb on that but will follow up on that in https://github.com/kubernetes-incubator/kube-aws/pull/568

**Comment by camilb** [comment]
@c-knowles @mumoshu I can work on a PR these days.

**Comment by camilb** [comment]
If we plan to only allow Github connector it will be simpler but allowing more connectors I can't see the way to do it right now. Maybe Helm will solve this problem better. @c-knowles if you have any ideas, please let me know.

**Comment by c-knowles** [comment]
I think we'd have to:
1. Let the user define strings like `$GOOGLE_CLIENT_ID` for their `clientSecret` etc (no changes for us, just we'll let these strings through as normal)
1. Add config to define some map of secrets like `GOOGLE_CLIENT_ID: <client_id>`
1. In our templating, loop through these secrets and add them as env vars to the deployment

I think Helm will hit the same problems if done this way but generally as the charts are app specific a chart for Dex would likely hard code `$GOOGLE_CLIENT_ID` as the config value and add the client ID to a Secret of the same hard coded name if Google is enabled. I don't think it will be good to add that level of config/validation to kube-aws since it will be quite specific to each connector etc.

**Comment by camilb** [comment]
My thoughts right now are to keep only the OIDC config in `kube-aws`. This will allow a user to use only one provider if this fits his needs and even dex. Then provide a good example of how to configure dex to work with `kube-aws`. I see there is already some work done for a dex [chart](https://github.com/samsung-cnct/k2-charts/tree/master/dex) that we can use as start point.

**Comment by c-knowles** [comment]
I agree. Dex crashes without any connector config so right now to use the OIDC setup without Dex one has to place some dummy config in the Dex connectors section and have this "fake" Dex run in the cluster.

**Comment by camilb** [comment]
Fixed in #820. Closing.
