### ISSUE TITLE
Support apiserver client x509 authentication

### ISSUE THREAD

**Issue by flah00** [kubernetes-incubator/kube-aws#672]
Based on my reading of the [docs](https://kubernetes.io/docs/admin/authentication/#x509-client-certs), the kubernetes API server can authenticate users with x509 certificates. But it expects to use a CA separate from the cluster authentication CA (apiserver includes the flag `--client-ca-file=SOMEFILE`). 

Should kube-aws enable this by default, by creating the requisite files during `kube-aws render credentials` and copying them into place? Or should it be an explicit option, which is controlled in `cluster.yaml`? 

Or have I misread something?

**Comment by redbaron** [comment]
Default setup uses X509 auth . Look at your `credentials` folder, there is an admin cert which your local kubeconfig is using to access cluster.

**Comment by flah00** [comment]
Sorry, I was too wrapped up in the issue I was trying to solve. I didn't fully explain myself.

I'm interested in sparingly using the admin cert, and providing devs, qa, and ops with their own certs.  It seems like the apiserver encourages the separation of CAs for the cluster and user auth (my reading of the api server `--client-ca-file=SOMEFILE` flag). After reading (x509)[https://kubernetes.io/docs/admin/authentication/#x509-client-certs] and (tls management)[https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/] I came away thinking that cluster CA and certificates should only be used for purpose of node/service communication within the cluster. 

Is the management of two separate CAs overkill, in the community's view? Is it something that kube-aws should support? Or, should I use my existing self-signed CA to sign user CSRs?

**Comment by redbaron** [comment]
`--client-ca-file` is used to authenticate *any* incoming request to API server made over SSL which present a client certificate. In default setup that would be:
  * kubelet on all worker nodes
  * kubectl commands issued by users

If you want to manage 2 CA feel free to do so, just append second CA to ca.pem generated by kube-aws. Then hand out certs signed by  a second CA to your users, they'll be able to talk to cluster just fine.

**Comment by flah00** [comment]
Thanks for the clarification
