### ISSUE TITLE
Docker health check

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#681]
I think we should consider adding a health check to Docker similar to @jeremyd mentioned in https://github.com/kubernetes/kubernetes/issues/41916#issuecomment-304074252. Having run kube-aws clusters for a number of months now, we do experience flakes with Docker that tend to take out a node that looks healthy otherwise to Kubernetes.

In a perfect world we'd fix all these issues at source but that is not always practical to do immediately especially with some of the more exotic issues where it's hard to determine the source. I think a health check here would re-inforce the general stability of our Kubernetes cluster in case of Docker failure.

**Comment by redbaron** [comment]
There is https://github.com/kubernetes/node-problem-detector which seems to be doing exactly that

**Comment by c-knowles** [comment]
@redbaron looks interesting, it detects hangs in the docker task via kernel logs. It [supports file and journald logs](https://github.com/kubernetes/node-problem-detector/blob/92e67b86150e6b571a8de99c9464550a4a68d3f8/pkg/systemlogmonitor/README.md#limitations) so should work ok for us. We already use some of the other addons so it makes sense to use that project.

**Comment by mumoshu** [comment]
@redbaron @c-knowles Just for my education but once `docker ps` started failing, we should see [this message mentioned in the part of node-problem-detector](https://github.com/kubernetes/node-problem-detector/blob/master/config/kernel-monitor.json#L53), right?

**Comment by c-knowles** [comment]
@mumoshu I've not used the node problem detector but I suppose so yes.

**Comment by c-knowles** [comment]
In case it helps anyone, I currently have this as a basic patch (with help from some nice folks on the kube-aws Slack channel):

```yaml
controller:
  customSystemdUnits: &customSystemdUnits
    - name: docker-healthcheck.service
      command: start
      enable: true
      content: |
        [Unit]
        Description=Run docker-healthcheck once
        After=docker.service
        [Service]
        Type=oneshot
        ExecStart=/opt/bin/docker-healthcheck
        [Install]
        WantedBy=multi-user.target
    - name: docker-healthcheck.timer
      command: start
      enable: true
      content: |
        [Unit]
        Description=Trigger docker-healthcheck periodically
        After=docker.service
        [Timer]
        OnUnitInactiveSec=30s
        Unit=docker-healthcheck.service
        [Install]
        WantedBy=multi-user.target
  customFiles: &customFiles
    - path: "/opt/bin/docker-healthcheck"
      owner: root:root
      permissions: 0700
      content: |
        #!/bin/bash
        if timeout 10 docker ps > /dev/null; then
        exit 0
        fi
        echo "docker failed"
        echo "Giving docker 30 seconds grace before restarting"
        sleep 30
        if timeout 10 docker ps > /dev/null; then
        echo "docker recovered"
        exit 0
        fi
        echo "docker still down; triggering docker restart"
        systemctl restart containerd docker
        echo "Waiting 60 seconds to give docker time to start"
        sleep 60
        if timeout 10 docker ps > /dev/null; then
        echo "docker recovered"
        exit 0
        fi
        echo "docker still failing"

worker:
  nodePools:
    - name: pool-A
      customSystemdUnits:
        *customSystemdUnits
      customFiles:
        *customFiles
```
