### ISSUE TITLE
Cluster autoscaler missing critical pod annotation

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#683]
According to https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#deployment we should mark the cluster autoscaler with the `scheduler.alpha.kubernetes.io/critical-pod` annotation. While we may by default deploy to controllers only I think it's probably better to have the annotation to mirror the other Deployments we have?

**Comment by mumoshu** [comment]
@c-knowles Good catch 👍 I completely agree to your suggestion.

FYI, what make the annotation even more needed is that we can optionally use worker nodes to run cluster-autoscaler by specifying `worker.nodePools[].clusterAutoscalerSupport.enabled`.
