### ISSUE TITLE
Add Heapster service account

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#685]
Our Heapster deployment should probably be using a separate service account similar to the [Heapster repo](https://github.com/kubernetes/heapster/tree/master/deploy/kube-config) and [kops](https://github.com/kubernetes/kops/blob/master/addons/monitoring-standalone/v1.6.0.yaml)

**Comment by c-knowles** [comment]
I tried adding the RBAC setup above to a dev cluster and got the same issue as https://github.com/kubernetes/heapster/issues/1589, https://github.com/kubernetes/kubeadm/issues/248.

I can no longer find the ref to the heapster-nanny so wondering if it's still needed. @mumoshu any ideas about that?

**Comment by c-knowles** [comment]
I've done the changes locally, will submit a PR but the nanny still isn't working (doesn't seem to work already with RBAC).

**Comment by c-knowles** [comment]
PR above, still an issue with the nanny sidecar though.

**Comment by mumoshu** [comment]
@c-knowles Thanks for your help here 👍 
Sry if i'm not answering your question correctly, but AFAIK the nanny sidecar is used toy constantly update a heapster deployment to set more/less resource limits according to cluster size.

Relevant code in nanny: https://github.com/kubernetes/contrib/blob/master/addon-resizer/nanny/nanny_lib.go#L109

So, it makes sense for me to provide the heapster role permission(s) required to update a heapster deployment.

**Comment by c-knowles** [comment]
@mumoshu I think the problem is then heapster will have a privilege escalation path. Do you know of other examples of nanny being used? I was trying to find some other similar examples to see how they are tackling this issue.

**Comment by mumoshu** [comment]
@c-knowles Sorry but I'm not aware of any other example usage of nanny. I'm looking forward to see @piosz's reply in the upstream issue, too.

**Comment by piosz** [comment]
cc @mwielgus @x13n

**Comment by x13n** [comment]
Right now only heapster and eventer are using nanny for vertical scaling. But since this is all a single deployment, this problem does not show up anywhere else. As I wrote in https://github.com/kubernetes/heapster/issues/1595#issuecomment-307470310, short term solution would be just to give those permissions to Heapster.

**Comment by c-knowles** [comment]
I found https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/cluster-monitoring/heapster-rbac.yaml which seems like it's what we need.

@x13n Please could you help me understand the difference between the sources in https://github.com/kubernetes/heapster/tree/master/deploy/kube-config and https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/cluster-monitoring? Is there a definitive one?

**Comment by x13n** [comment]
@c-knowles Files in kubernetes repository are used by startup scripts there (e.g. kube-up.sh) and are more config templates than regular configs - some parameters are set up by those scripts. Deployment scripts from heapster repository can be used as they are and there is in fact a significant number of people using them. There is an open issue to merge the two: https://github.com/kubernetes/heapster/issues/1598

**Comment by c-knowles** [comment]
@x13n awesome! Thanks so much for explaining, I had not noticed the issue prior to this so will definitely follow that one.

**Comment by c-knowles** [comment]
Submitted the above PR to finish this work off.
