### ISSUE TITLE
Support tag prefix kubernetes.io/cluster/XXX for kube-aws clusters and deprecate KubernetesCluster legacy tag

### ISSUE THREAD

**Issue by Fsero** [kubernetes-incubator/kube-aws#699]
after 1.6 release a new tagging scheme has been introduced in aws provider https://github.com/kubernetes/kubernetes/blob/v1.6.4/pkg/cloudprovider/providers/aws/tags.go#L34

legacy tag Kubernetescluster behaviour is still maintained and didn't see any plan to remove it entirely very soon, however the new tag semantics regarding ownership opens up the possibility of deploying more than one cluster in the same VPC which is very interesting for me.

The use case is, i maintain an external VPC from kube-aws with several VPC peerings, if i want to deploy a new cluster i can deploy using that same VPC however new cluster will be unable to use any AWS resource until VPC, subnets and other resources are retagged which is... inconvenient.

I open the issue to hear about feedback from kube-aws community, i'm interested on bringing support to this on kube-aws and make a PR.

**Comment by redbaron** [comment]
Are you talking about https://github.com/kubernetes-incubator/kube-aws/pull/652 ?

**Comment by Fsero** [comment]
indeed i am! thanks @redbaron im really happy for closing this issue as fixed :+1:
