### ISSUE TITLE
Support `hostPort` with CNI

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#704]
According to https://github.com/kubernetes/kubernetes/issues/23920#issuecomment-307981726 we will need to update versions of Calico and configuration to enable this on k8s 1.7. I'm not sure what if anything needs to change for flannel to also work.

**Comment by mumoshu** [comment]
@c-knowles Thanks for the info!
Perhaps I'll verify it to work until v0.9.8-rc.1 and then remove the note in [the limitations doc](https://github.com/kubernetes-incubator/kube-aws/blob/master/Documentation/kubernetes-on-aws-limitations.md).

**Comment by c-knowles** [comment]
Sure, let's verify that I can try on our clusters. FYI I hit this from datadog's latest install notes which use the host port functionality.

**Comment by andrejvanderzee** [comment]
Ha! This just cost me a couple of hours :-)
+1 for hostPort with CNI.

**Comment by chen-anders** [comment]
I'm having issues getting CNI working with the proper conflist config for flannel on k8s 1.7.3.

This is along the lines of what I have: 
```
{
    "name": "cbr0",
    "cniVersion": "0.3.0",
    "plugins": [
      {
        "type": "flannel",
        "delegate": {
          "isDefaultGateway": true
        }
      },
      {
        "type": "portmap",
        "capabilities": {"portMappings": true}
      }
    ]
}
```

I've searched over the web and there only seems to be instructions for Calico, but not flannel.

**Comment by klausenbusk** [comment]
@chen-anders That is the file extension? I have [read](https://github.com/kubernetes/kubernetes/issues/23920#issuecomment-308254308) it should be `.conflist`..

**Comment by chen-anders** [comment]
@klausenbusk - `.conflist` is correct. (Edited the original post for clarity)

Update: I was able to get it working with the v0.6.0-rc2 release downloaded from here: https://github.com/containernetworking/plugins/releases

**Comment by drywheat** [comment]
I guess I'm still a little confused on how one would configure `hostPort`. Like @c-knowles mentioned earlier, I'm seeing this problem when trying to install Datadog into our cluster.

FYI – Running kube-aws version **v0.9.9-rc.2**

**Comment by mumoshu** [comment]
@drywheat Hi! If you have not tried yet - Perhaps you need to include the portmap plugin in the cni config?
Ref: https://github.com/kubernetes/kubernetes/issues/23920#issuecomment-315119176

**Comment by c-knowles** [comment]
On the datadog side they are adding/migrating to unix socket support in their next agent which will remove this as an issue and allow for better pod introspection. But it’s still a problem I’d like to resolve for other cases.

**Comment by 9len** [comment]
kubernetes 1.9 includes CNI 0.6.0, which should support hostPort with flannel.

**Comment by whereisaaron** [comment]
@9len I think it was Calico+flannel that had the hostPort issue? And this was [fixed in Kubernetes 1.7](https://github.com/kubernetes/kubernetes/issues/23920#issuecomment-299535316). Certainly hostPort works with `kube-aws` today (with Calico enabled). I [updated the `kube-aws` documentation](https://github.com/kubernetes-incubator/kube-aws/pull/1097) recently. Is that the same issue you are talking about, or something different?

**Comment by 9len** [comment]
I believe this was about flannel + cni, for which (as far as I was able to determine) hostPort doesn't work without cni 0.6.0 (which was added in kube 1.9)

**Comment by fengyd2018** [comment]
hostPort cannot work with kubernetes 1.9.2 and CNI 0.6.0 ?

**My enviroment:**
[root@worker ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

kubernetes-cni-0.6.0-0.x86_64

**Comment by whereisaaron** [comment]
Calico is CNI provider. Certainly Calico+CNI+hostPort works in k8s 1.8.x because that is what we run. Reportly this combo works in 1.7 also, but I haven't personally tested that. There used to be a problem with hostPort but the fix for that was merged 1 Jun 2017 (via the port-forwarded plugin) and so [made it into k8s 1.7](https://github.com/kubernetes/kubernetes/issues/23920#issuecomment-306543120).

**Comment by fengyd2018** [comment]
Flannel+CNI+HostPort cannot work?

**Comment by 9len** [comment]
Based on the changelog, hostPort/flannel works with kubernetes >1.9, which includes cni >0.6.0

**Comment by fengyd2018** [comment]
[root@worker ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

It means kubernetes version is 1.9.2?

**Comment by fengyd2018** [comment]
I downloaded cni-plugins-amd64-v0.7.0-rc2.tgz from https://github.com/containernetworking/plugins/releases. 
It's enough I extracts the files and copy them to /opt/cni/bin?
Anything else is needed?

**Comment by fengyd2018** [comment]
With https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml, hostPort can work

**Comment by c-knowles** [comment]
So to get this working using flannel with calico, I assume we need to use https://github.com/coreos/flannel-cni. @mumoshu how much do you know about the various network fabrics? My knowledge is a bit limited so I could work on some of this but need a little guidance about what we need to add. I hit this issue again today, I have a Daemon Set with some `hostPort` set and need to also access that in some cases via a k8s Service. It's a weird use case but mainly due to not being able to migrate all systems at the same time. With the current flannel setup there's no way to achieve that without manual intervention as far as I can tell, but I think setting up CNI fully can help resolve it.

**Comment by c-knowles** [comment]
I confirmed that enabling https://github.com/kubernetes-incubator/kube-aws/pull/1195 solves this issue, at least using the canal setup which I think should be the recommended one until we support amazon-vpc-cni-k8s in https://github.com/kubernetes-incubator/kube-aws/issues/1047.

**Comment by c-knowles** [comment]
For some reason this worked in my previous tests with k8s 1.9.9 and canal self hosted but I checked again yesterday with kube-aws cb6766d24e55ac536670294b63c9d0049f9c6229 and it seems hostPort is not working again. Not entirely sure why as the canal config looks fine.

**Comment by c-knowles** [comment]
Nevermind, ignore my above comment - I've since found an unrelated configuration issue which made it look like this wasn't working but it was fine. I've re-confirmed all expected paths work:

- A pod using downward `spec.nodeName` can communicate to another pod on the same host that exposes `hostPort`
- A host can communicate with a pod on itself exposing `hostPort` via `localhost`
- A host can communicate with a pod on itself exposing `hostPort` via `` `hostname` ``
