### ISSUE TITLE
Dex is not working when RBAC is turned on

### ISSUE THREAD

**Issue by andromedarabbit** [kubernetes-incubator/kube-aws#712]
Since kube-aws does not set up any service account for dex, a user would see the error messages like: 

```
from server for: "myserver.yaml": User "guy@company.com" cannot get deployments.extensions in the namespace "default". (get deployments.extensions myserver)
```

**Comment by redbaron** [comment]
Is it error from Dex or from kubectl user guy@company.com runs?

**Comment by c-knowles** [comment]
Dex is deployed to kube-system which has quite permissions RBAC in kub-aws right now. I've used the feature in the current releases but not all the setup was obvious as is shown by my questions in https://github.com/kubernetes-incubator/kube-aws/pull/568. However, I did not have RBAC specific problems that side of things worked ok. @andromedarabbit do you have the relevant section of your `cluster.yaml`?

**Comment by camilb** [comment]
@andromedarabbit Are those errors from dex pod?

**Comment by camilb** [comment]
@andromedarabbit I suppose that you created a user that has a token assigned and by default that user has no permissions associated. I have an example [here](https://www.camil.org/create-a-secure-kubernetes-ha-cluster-in-aws-using-kube-aws/), please take a look at **Dex** section  and let me know if this resolve your issue.

**Comment by camilb** [comment]
First you have to create the role with the desired permissions.
Example of a role that allows a user to list the pods in `kube-system`namespace.

    kind: Role
    apiVersion: rbac.authorization.k8s.io/v1beta1
    metadata:
      namespace: kube-system
      name: pod-reader
    rules:
    - apiGroups: [""] # "" indicates the core API group
      resources: ["pods", "secrets"]
      verbs: ["get", "watch", "list"]

Then you have to bind this role to your user like this:
 
    kubectl create rolebinding pod-reader --role=pod-reader --user=user@example.com --namespace=kube-system

**Comment by andromedarabbit** [comment]
@camilb I believe that you should be right. I will let you guys know the result once the test is done.

**Comment by andromedarabbit** [comment]
@camilb You were perfectly right. It was not working for my misunderstanding. Thanks for the help. 👍
