### ISSUE TITLE
Possibility to use different AWS profile than default

### ISSUE THREAD

**Issue by Vrtak-CZ** [kubernetes-incubator/kube-aws#716]
Is there any solution how to pass AWS profile to kube-aws? We have 2 separate clusters in two separate AWS accounts and it's not so easy to do something with these to cluster because every time i need to check which account i currently have set as default.

**Comment by redbaron** [comment]
I run it like this:

`AWS_PROFILE=.... kube-aws update`

and my default profile is empty, so that it cant' run at all unless I set it. Would it work for you?

**Comment by Vrtak-CZ** [comment]
Thank you @redbaron it works as expected. But I think it should be documented somewhere.

**Comment by mumoshu** [comment]
@Vrtak-CZ @redbaron Thanks for taking your time 👍 Yes, it should be documented. Perhaps adding a FAQ.md containing this would help?
