### ISSUE TITLE
Support Kubernetes 1.7 new TLS bootstrapping features

### ISSUE THREAD

**Issue by danielfm** [kubernetes-incubator/kube-aws#721]
More details [here](https://kubernetes.io/docs/admin/kubelet-tls-bootstrapping/#approval-controller) and [here](https://kubernetes.io/docs/admin/authorization/node/).

**Comment by mumoshu** [comment]
Thanks for bringing this up!
I'm especially looking forward to the creds rotation alpha feature 😃

**Comment by mumoshu** [comment]
@danielfm Can we close this as resolved now?

* For the cert rotation feature, I've created #881 
* Probably we'd want to enable this feature by default at some point. If you agree, could you create a separate issue for that?

**Comment by danielfm** [comment]
Of course, closing!
