### ISSUE TITLE
Nodepools created with spot instances fail to register in cluster.

### ISSUE THREAD

**Issue by camilb** [kubernetes-incubator/kube-aws#727]
The new method of getting the `KUBE_AWS_STACK_NAME` from `aws:cloudformation:stack-name` tag  doesn't work with Spot Instances because these instances are not tagged by Cloudformation. 

`cfn-etcd-environment.service` fails to start without `KUBE_AWS_STACK_NAME` value in `/etc/environment`

**Comment by mumoshu** [comment]
@camilb Thanks for the good catch 👍
As we need to tag spot instances manually, relying on `aws:cloudformation:stack-name` wouldn't be an universal option as it does result in the chicken-and-the-egg problem.
We need to somehow pass the stack name from `{"Ref":"AWS::StackName"}` to the userdata...

**Comment by mumoshu** [comment]
I have considered to use multi-part cloud-config so that we can use the first part to populate the env var with the stack name as the value. However, unfortunately, coreos-cloudinit doesn't support it.
https://github.com/coreos/bugs/issues/912

**Comment by mumoshu** [comment]
A possible solution(which doesn't need to revert the recent improvements on userdata made by @redbaron) came up in my mind is to utilizing ignition with:

```
"UserData": {{ .UserDataWorker.Parts.instance.Base64 true | checkSizeLessThan 16384 | quote }}
```

modified to:

```
"UserData": {{ .UserDataWorker.Parts.instance.IgnitionConfigRef }}
```

where the IgnitionConfig func is:

```golang
func quoteForCfn(jsonLike string) string {
  return strings.Replace(strings.Replace(jsonLike, "\n", "\\n", -1), ```"```, ```\"```, -1)
}

func (self UserDataPart) IgnitionConfigRef() string {
  splits := []string{
    quoteForCfn(```{
  "ignition": {
    "version": "2.0.0"
  },
  "storage": {
    "files": [
      {
        "filesystem": "root",
        "path": "/var/run/coreos/kube-aws-stack-name",
        "contents": {
          "source": "data:,```),
    base64StackNameRef,
    quoteForCfn(fmt.Sprintf(```"
        }
      },
      {
        "filesystem": "root",
        "path": "/opt/bin/bootstrap-worker-node",
        "contents": {
          "source": "data:,%s"
        }
      }
    ]
  },
  "systemd": {
    "units": [
      {
        "name": "bootstrap-worker-node",
        "enable": true,
        "contents": "#!/bin/bash -xe\n/opt/bin/bootstrap-worker-node"
      }
    ]
  }
}```,
  self.Base64(false))

  // TODO should emit a validation error when sum(sizeOf(split in splits)) > 16384

  return fmt.Sprintf(```{"Fn::Join": ["", [%s]]}```, strings.Join(splits, ","))
}
```

**Comment by mumoshu** [comment]
@redbaron Could I have your comments on this?

**Comment by redbaron** [comment]
1. that manual escaping looks crufty, encoding given string into a json string should be enough.
2. config data in kube-aws binary goes against flexibility of having all configs in a text form
3. Stack name passing can be achieved in a much simpler way, just just instance userdata to CF Json function calls
```
{ "Fn::Base64": [ {"Fn::Join": [ "", 
"!#/bin/bash\n"
"echo ", {"Ref": "AWS::Stack::Name" }
....
```
and then 

```
"UserData": {{ .UserDataWorker.Parts.instance.Template | quote }}
```

in your stack config json.

You'll lose  `checkSizeLessThan`, but that is not  a big deal. You might also want to introduce validateJSON function for this instance userdata part to be a bit more robust.

**Comment by mumoshu** [comment]
@redbaron Thanks 👍

* I imagined that we'd better have something like `CloudConfigRef` which "injects" `{"Ref": "AWS::Stack::Name" }` to the instance part of a cloud-config. Would you agree?
* The only problem in my proposed solution with ignition is that it is just too much for the job for now, right? (The simpler way you've suggested still require us to embed a very small part of cloud-config to the kube-aws binary?

**Comment by redbaron** [comment]
Fix I propose can be implemented even by an end user in his userdata/cloud-config-worker and sta-template.json

**Comment by mumoshu** [comment]
@redbaron Thanks!
I thought so too at first but wouldn't `"UserData": {{ .UserDataWorker.Parts.instance.Template | quote }}` you've suggested transforms `{"Ref": "AWS::Stack::Name" }` to a plain string in a json string without resulting to an actual stack name?

**Comment by mumoshu** [comment]
@camilb I've submitted the PR #732 to demonstrate a possible fix for this. I don't know whether we're going to merge it as-is - but could you verify that the change introduced in the PR fix your problem anyway?

**Comment by camilb** [comment]
Thanks @mumoshu , I'll test it today and let you know of any issue.

**Comment by camilb** [comment]
@mumoshu I can confirm that #732  works fine. Thanks!

**Comment by redbaron** [comment]
@mumoshu 

sorry, was in  a rush, yes you are right, `quote` isn't what we want, there, so it would be:

```
"UserData": {{ .UserDataWorker.Parts.instance.Template  }}
```

**Comment by mumoshu** [comment]
@redbaron I've tried my best to make an implementation of your suggestion in #732 👍 Would you mind reviewing it?

**Comment by camilb** [comment]
A less elegant method, but that also works: 

    echo KUBE_AWS_STACK_NAME=$(curl http://169.254.169.254/latest/meta-data/iam/info | jq .InstanceProfileArn | cut -d ":" -f 6 | cut -d "/" -f 2 | cut -d "-" -f 1-3) >> /etc/environment

**Comment by redbaron** [comment]
My take on it is in #735, code changes are purely to make it more ergonomic and avoid manually escaping all strings in a script.

I didn't try to create cluster with it though, we don't use SpotFleet

**Comment by camilb** [comment]
@redbaron I'll test it

**Comment by camilb** [comment]
Just finished to create a cluster based on #735 with  SpotFleet. Works fine.
