### ISSUE TITLE
Drain node on spot instance termination notice

### ISSUE THREAD

**Issue by danielfm** [kubernetes-incubator/kube-aws#734]
We need to improve our new node drainer daemonset to also handle spot instance termination notice; when the instance is scheduled for termination, we need to drain the node, just like we do when instances are being rotated out of the auto scaling group.

**Comment by camilb** [comment]
@danielfm I'm already using @mumoshu's [kube-spot-termination-notice-handler](https://github.com/mumoshu/kube-spot-termination-notice-handler)

**Comment by redbaron** [comment]
@danielfm spot instance can execute same logic , but on shutdown . It will be best-effort, but still better than just disappearing.

**Comment by danielfm** [comment]
Can't we put the logic from kube-spot-termination-notice-handler into our daemonset? What's the downside?

**Comment by redbaron** [comment]
> Can't we put the logic from kube-spot-termination-notice-handler into our daemonset? What's the downside?

No downside, I didn't check for notice handler before answering :( yes indeed, drainer can poll for either termination notice or ASG status or maybe even both if possible.

Will it work with kube2iam where it intercepts requests to metadata service?

**Comment by danielfm** [comment]
> Will it work with kube2iam where it intercepts requests to metadata service?

I don't use kube2iam in my clusters, but I think so; the documentation does not mention the need for any specific custom roles or policies.

**Comment by camilb** [comment]
@redbaron  I'm using it with kube2iam. 
kube2iam only blocks access to `http://169.254.169.254/latest/meta-data/iam/security-credentials/`.  
`http://169.254.169.254/latest/meta-data/spot/termination-time` can be accessed by any pod.

**Comment by danielfm** [comment]
I'll send a PR for that in the next few hours.
