### ISSUE TITLE
Update Kubernetes to v1.7.0

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#744]

**Comment by camilb** [comment]
@mumoshu already have a dev cluster running Kubernetes v1.7.0 deployed using `kube-aws` and didn't find any issue yet. Of course it will be nice to enable some features, like secret encryption, but at compatibility level, looks fine.

**Comment by mumoshu** [comment]
@camilb Thank you very much for the helpful info 👍 Good to know there's no huge compatibility issues 😄

**Comment by mumoshu** [comment]
@camilb Did you also update heapster from v1.3.0 to v.1.4.0?
If so, have you also observed that heapster-nanny is consistently failing due to https://github.com/kubernetes-incubator/kube-aws/pull/746#issuecomment-313323840?

**Comment by camilb** [comment]
@mumoshu, no, still running v1.3.0.

**Comment by danielfm** [comment]
I suspect kube-aws support for Kubelet TLS Bootstrapping won't work with Kubernetes 1.7 as `--insecure-experimental-approve-all-kubelet-csrs-for-group` flag is now no-op. Seems easy enough to fix though.

**Comment by mumoshu** [comment]
@danielfm Thanks for the info 👍 

I'm still in process of catching up but according to https://kubernetes.io/docs/admin/kubelet-tls-bootstrapping/#approval-controller, we now need to create roles and role bindings to enable controller-manager to auto-approve csrs?

**Comment by danielfm** [comment]
@mumoshu Yes, I think it's just a matter of defining the right roles and bindings. We could keep the `--insecure-experimental-approve-all-kubelet-csrs-for-group` flag for now for backward compatibility.

**Comment by mumoshu** [comment]
Closing this via #746. Please see #721 to fix the TLS bootstrapping feature after the k8s update.
