### ISSUE TITLE
Reusing existing IAM roles for etcd nodes and ASG lifecycle notification

### ISSUE THREAD

**Issue by mclarke47** [kubernetes-incubator/kube-aws#747]
Really happy to see [607](https://github.com/kubernetes-incubator/kube-aws/pull/607) make it into 0.9.7 but it would be great to have it in for etcd nodes too.

**Comment by mumoshu** [comment]
@mclarke47 Thanks for the feedback 👍 Just curious but would you mind clarifying what's your use-case for having the flexible IAM configuration for etcd nodes?

**Comment by mumoshu** [comment]
I just noticed that you've modified the subject to contain "ASG notification role" - but what do you mean by that?

**Comment by mclarke47** [comment]
Frequently developers do not have direct control over IAM and networking in their aws account. Kube-aws has solved the networking issue by allowing users to define VPCs/subnets which already exist. iAM however seems to be a bit half implemented, you can define existing instan

**Comment by VinceMD** [comment]
I'm in the same scenario as mclarke47. My AWS user cannot alter anything IAM. Instead I have prepared the roles and instanceProfile and handed over to my SEC/cloud department so they can set them up as one-off after review.

But for etcd I have to manually edit the cloudformation script before applying via console. I'm not sure how it will work with kube-aws update.

Separate but related topic, I've worked out minimum set of policies.  ec2:* and elasticloadbalancing:* was too broad and not accepted where I work. I've created a smaller set of policies in a form of a cloudformation script. I took inspiration from kops guy who are also working on that problem. My policies seem to work for kube-aws but wouldn't mind getting it reviewed and part of the kube-aws documentation for others to reuse. What's the best way to publish my work?

**Comment by mumoshu** [comment]
@mclarke47 Thanks for the confirmation!

> would you agree that we should add support for existing IAM roles/instanceprofiles?

Definitely 👍 
I'll try to address this in v0.9.8-rc.1 - would you mind testing it if I could made it into the release?

**Comment by mumoshu** [comment]
It is WIP at #761

**Comment by VinceMD** [comment]
I can test too. In the same spirit, is there already a PR in progress for allowing usage of a pre-created ASGNotificationRole? ASGNotificationRole is always attempted to be created, even with autoscaler disabled

**Comment by mumoshu** [comment]
@VinceMD Thanks!

Regarding the reusability of existing notification roles, we don't have one for that yet.

I'm even not sure how we make it customizable.
Would you mind discussing about the spec with me?

Firstly, would it be enough for you to provide kube-aws an existing notification role to be reused?

```yaml
autoscalingNotification:
  iam:
    role:
      arn: arnofexistingnotificationrole
```

Secondly, would it be also necessary to provide an existing notification target's arn too,
because otherwise you will be unable configure the notification role's policy properly by specifying which SQS queue the notification role is allowed to access?

```
autoscalingNotification:
  iam:
    role:
      # The existing role would have a policy like:
      # {
      #   "Effect": "Allow",
      #   "Action": [
      #      "sqs:SendMessage",
      #      "sqs:GetQueueUrl"
      #     ],
      #   "Resource": "arnofexistingsqsqueue"
      #  }
      arn: arnofexistingnotificationrole
  target:
    arn: arnofexistingsqsqueue
```

**Comment by mclarke47** [comment]
That looks good, I think it might also make sense to have a flag to turn off the queue creation? As the SQS queue doesn't do anything atm some users might want to not incur that cost.

**Comment by mumoshu** [comment]
@mclarke47 Thanks for the confirmation 👍 

REgarding the queue creation - AFAICS, the queue is used by ASG lifecycle notification. Do you really want to disable the notification at all? Wouldn't disabling it make your life in debugging harder when kube-aws' node draining feature didn't work somehow?

cc @danielfm

**Comment by mumoshu** [comment]
FYI the first in https://github.com/kubernetes-incubator/kube-aws/issues/747#issuecomment-314756229 is addressed in the second commit of the PR fe547ac

**Comment by VinceMD** [comment]
@mumoshu agree with specs. I might say something silly, but what if the SQS was named by kube-aws, then I could create a policy by hand affecting SQS resource that satisfies a regex. That's what I do with my Controller IAM role and the S3 bucket:
arn:aws:s3:::knownprefix-*/* 
Even if that works, it is not bulletproof

Otherwise fully satisfied with your solution to have the user provide both arnofexistingnotificationrole and arnofexistingsqsqueue.

**Comment by mumoshu** [comment]
@VinceMD Thanks for the confirmation 👍 
Perhaps you meant that if kube-aws named a SQS queue with the [queue name](http://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html#aws-sqs-queue-name) given by the user?
Yes, it would work like you expected, perhaps with the imaginary cluster.yaml contents like:

```yaml
autoscalingNotification:
iam:
    role:
      # The existing role would have a policy like:
      # {
      #   "Effect": "Allow",
      #   "Action": [
      #      "sqs:SendMessage",
      #      "sqs:GetQueueUrl"
      #     ],
      #   "Resource": "arn of the sqs queue named sqs-queue-name-given-by-the-user "
      #  }
      arn: arnofexistingnotificationrole
  target:
     queue:
       name: sqs-queue-name-given-by-the-user
```

However, I guess allowing to specify `target.arn` instead would also enable more broader use-cases(like using sns instead 😃 not sure if anyone really likes it), plus your use-case.
So, if you're ok with the `target.arn` approach, I'd like to go ahead with it.
WDYT?

**Comment by redbaron** [comment]
@VinceMD , @mumoshu with latest CloudFormation update neither RoleARN nor NotificationTargetARN are mandatory anymore. If they can be omitted and ASG LifecycleHook continues to change instance state to `Terminating: Wait` then we can remove it

**Comment by mumoshu** [comment]
@redbaron Thanks, really good to know! (For anyone interested, see [June 6, 2017](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html) in the cfn release note.)
My only concern to leave it is now for debugging purpose https://github.com/kubernetes-incubator/kube-aws/issues/747#issuecomment-314771757
Do you think we really want to remove it in that regard, too?

**Comment by mclarke47** [comment]
I think it might be fine to leave it for debugging purposes

**Comment by VinceMD** [comment]
I'm happy with any solution listed above.

**Comment by mumoshu** [comment]
Created the separate issue #771 for the customization of autoscaling notification target
