### ISSUE TITLE
Adding stub domain using kube-aws

### ISSUE THREAD

**Issue by nlarzon** [kubernetes-incubator/kube-aws#750]
Hi,
Is there a way to add stub domains in cluster creation ? 

http://blog.kubernetes.io/2017/04/configuring-private-dns-zones-upstream-nameservers-kubernetes.html

Or how can I add it after the cluster is formed?

I appreciate all tips I can get.

**Comment by mumoshu** [comment]
@nlarzon Hi! Thanks for trying kube-aws.

A cluster created by recent versions of kube-aws has a configmap named `kube-dns` in it:

```
kubectl --namespace kube-system get configmap
NAME                                 DATA      AGE
cluster-autoscaler-status            1         10h
extension-apiserver-authentication   1         10h
kube-dns                             0         10h
kube-dns-autoscaler                  1         10h
```

I have not yet tested it myself but it would be a matter of editing it and add a `stubDomains` section as described in the article, by running `kubectl edit --namespace kube-system kube-dns`.

**Comment by nlarzon** [comment]
Thanks @mumoshu that did the trick.
