### ISSUE TITLE
Remove deprecated keys in cluster.yaml

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#753]
Finally remove keys deprecated via #372 #545 

More concretely, remove:

* [ ] `externalDNSName` in favor of `apiEndpoints[].dnsName`
* [ ] `createRecordSet` in favor of `apiEndpoints[].loadBalancer.createRecordSet`
* [ ] `recordSetTTL` in favor of `apiEndpoints[].loadBalancer.recordSetTTL`
* [ ] `hostedZoneId` in favor of `apiEndpoints[].loadBalancer.hostedZone.id`
* [x] `controllerCount` in favor of `controller.count`
* [ ] `controller.loadBalancer` in favor of `apiEndpoints[].loadBalancer`
* [x] `controllerCreateTimeout` in favor of `controller.createTimeout`
* [x] `controllerInstanceType` in favor of `controller.instanceType`
* [x] `controllerRootVolumeSize` in favor of `controller.rootVolume.size`
* [x] `controllerRootVolumeType` in favor of `controller.rootVolume.type`
* [x] `controllerRootVolumeIOPS` in favor of `controller.rootVolume.iops`
* [x] `controller.managedIamRoleName` in favor of `controller.iam.role.name`
* [x] `etcdCount` in favor of `etcd.count`
* [x] `etcdInstanceType` in favor of `etcd.instanceType`
* [x] `etcdRootVolumeSize` in favor of `etcd.rootVolume.size`
* [x] `etcdRootVolumeType` in favor of `etcd.rootVolume.type`
* [x] `etcdRootVolumeIOPS` in favor of `etcd.rootVolume.iops`
* [x] `etcdDataVolumeEphemeral` in favor of `etcd.dataVolume.ephemeral`
* [x] `etcdDataVolumeSize` in favor of `etcd.dataVolume.size`
* [x] `etcdDataVolumeType` in favor of `etcd.dataVolume.type`
* [x] `etcdDataVolumeIOPS` in favor of `etcd.dataVolume.iops`
* [x] `etcdDataVolumeEncrypted` in favor of `etcd.dataVolume.encrypted`
* [x] `etcdTenancy` in favor of `etcd.tenancy`
* [x] `worker.nodePools[].rootVolumeSize` in favor of `worker.nodePools[].rootVolume.size`
* [x] `worker.nodePools[].rootVolumeType` in favor of `worker.nodePools[].rootVolume.type`
* [x] `worker.nodePools[].rootVolumeIOPS` in favor of `worker.nodePools[].rootVolume.iops`
* [x] `worker.nodePools[].spotFleet.launchSpecifications[].rootVolumeSize` in favor of `worker.nodePools[].spotFleet.launchSpecifications[].rootVolume.size`
* [x] `worker.nodePools[].spotFleet.launchSpecifications[].rootVolumeType` in favor of `worker.nodePools[].spotFleet.launchSpecifications[].rootVolume.type`
* [x] `worker.nodePools[].spotFleet.launchSpecifications[].rootVolumeIOPS` in favor of `worker.nodePools[].spotFleet.launchSpecifications[].rootVolume.iops`
* [x] `worker.nodePools[].managedIamRoleName` in favor of `worker.iam.role.name`

**Comment by mumoshu** [comment]
cc @redbaron @danielfm @c-knowles @camilb

**Comment by mumoshu** [comment]
Although we definitely have been noted about deprecations/removals of `externalDNSName`, `createRecordSet`, `recordSetTTL`, `hostedZoneId`, `controller.loadBalancer` in cluster.yaml, I just realized that we had been missing warning messages emitted when they were used.

So, my question is: is everyone aware of deprecations and removals of those 5 keys?

**Comment by c-knowles** [comment]
Is the init command linked up correctly to the new host/record set entries? I only ask as I've not tried init in a very long time.

**Comment by mumoshu** [comment]
@c-knowles Thanks for the confirmation 👍 
Yes, they have been emptied by default since long time ago:
https://github.com/kubernetes-incubator/kube-aws/blob/master/core/controlplane/config/templates/cluster.yaml#L6-L28

and new keys are explicitly filled with values passed via `init` flags:
https://github.com/kubernetes-incubator/kube-aws/blob/master/core/controlplane/config/templates/cluster.yaml#L43-L70

**Comment by camilb** [comment]
@mumoshu I'm currently not using any of the deprecated keys.

**Comment by drywheat** [comment]
FYI, just hit this.

**kube-aws version:** 0.9.9

The docs for [kube2iam support](https://kubernetes-incubator.github.io/kube-aws/getting-started/step-6-configure-add-ons.html#kube2iam) reference the deprecated key `managedIamRoleName` instead of pointing to the new keys for both the controller and workers.

**Comment by drywheat** [comment]
Referencing #698 and the docs inside of `cluster.yaml`, it's a little unclear what the correct key for changing the IAM role name of a worker node pool is. Here are all the options I see in the docs and in PRs/Issues:

- `worker.nodePools[].managedIamRoleName` (removed in v0.9.9 and now should be removed from the docs)
- `worker.nodePools[].iam.managedRoleName` (mentioned by @c-knowles but no docs given in v0.9.9)
- `worker.nodePools[].iam.role.name` (listed in docs and works)

**Comment by mumoshu** [comment]
Thx for catching these all up! iam.role.name shfud be the correct one as
far as I remember, and also as confirmed by you.

Would you mind sending a PR for fixing doc?
2018年3月14日(水) 0:24 Bernhard (Sonny) Köhler <notifications@github.com>:

**Comment by drywheat** [comment]
Sure thing, I'll submit that today.

**Comment by c-knowles** [comment]
Just submitted an update for the docs as part of https://github.com/kubernetes-incubator/kube-aws/pull/1285.

**Comment by dominicgunn** [comment]
We should probably still do this for things that still are, or have been deprecated since this.

/reopen
