### ISSUE TITLE
Disallow specifying `experimental.taints`

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#754]
The `experimental.taints` key had been added to cluster.yaml via #132 in the end of last year for tainting controller nodes.
As the name doesn't express the fact that it is only for controller nodes very well, and also it has been several releases since it is added as an experimental feature, I suggest renaming.

cc @redbaron @c-knowles @danielfm @camilb

**Comment by mumoshu** [comment]
Similarly, we're going to rename `experimental.nodeLabels` to `controller.nodeLabels` via #578

**Comment by mumoshu** [comment]
I can't remember why we've added `experimental.taints` but anyway, in the first place, tainting controller nodes with custom keys doesn't make sense at all because doing so would prevent critical
 pods like apiserver from scheduling 😄 

So, we'd better remove `experimental.taints` rather than renaming it.

**Comment by mumoshu** [comment]
Btw, `experimental.taints` is not read from anywhere in the current code base and therefore can be safely removed.

**Comment by camilb** [comment]
@mumoshu I have never used it and I think only allowing to taint the workers is enough
