### ISSUE TITLE
v0.9.7 comes with subPath config file bug by default

### ISSUE THREAD

**Issue by mclarke47** [kubernetes-incubator/kube-aws#762]
Using kube-aws 0.9.7 [installs hyperkube 1.6.3](https://github.com/kubernetes/kubernetes/issues/45613) by default which comes with [this nastiness](https://github.com/kubernetes-incubator/kube-aws/blob/v0.9.7/core/controlplane/config/templates/cluster.yaml#L977).

```
mkdir /var/lib/kubelet/pods/af7543c4-66da-11e7-900e-0e8359b8329c/volumes/kubernetes.io~secret/subpath/secret.fileextension: not a directory
```

Should be fixed with the upgrade to 1.7.0 in 0.9.8 of kube-aws so this is more of an FYI and can probably be closed. The work around should be to set the hyperkube version to `kubernetesVersion: v1.6.4_coreos.0` (haven't tested this yet).

**Comment by it-svit** [comment]
I have the same issue:
`778250574-p0q6h      0/1       mkdir /var/lib/kubelet/pods/b58bf20e-6889-11e7-9130-060368e48631/volumes/kubernetes.io~secret/certificates/server.crt: not a directory`
kube-aws 0.9.7

**Comment by redbaron** [comment]
everybody who is affected, easy workaround is to update k8s version in your cluster yaml to v1.6.7_coreos.0

**Comment by it-svit** [comment]
Thank you, @redbaron ! 
It works!
Updated `kubernetesVersion` should be included into new kube-aws release.

**Comment by danielfm** [comment]
> Updated `kubernetesVersion` should be included into new kube-aws release.

Will do!
