### ISSUE TITLE
etcdadm externalise etcd and awscli images to cluster.yml

### ISSUE THREAD

**Issue by VinceMD** [kubernetes-incubator/kube-aws#767]
Some organisations have to use an internal repository to host the images and cannot rely on public repositories. Most of the time a proxy can be used, but not always.

This is about being able to specify the repository url and version/tag for etcd and awscli instead of hard coded values in etcdadm/etcdadm

**Comment by mumoshu** [comment]
@VinceMD Thanks for trying kube-aws and the feedback 👍 
It does make sense to me allowing customizations to where etcd and awscli docker images used in etcdadm are hosted.

Regarding awscli, I'm going to extend the `AwsCliImage` configuration which is already present in cluster.yaml to be also used in etcdadm.
For etcd, probably we'd add `etcdImage`.

**Comment by VinceMD** [comment]
ok. Let me know if you need help (coding, testing)

**Comment by mumoshu** [comment]
@camilb Perhaps you also need this for your cn region deployments?

**Comment by camilb** [comment]
@mumoshu Yes, this will be useful for cn region.

**Comment by VinceMD** [comment]
So I would like to compile kube-aws to use a different repo for etcd. And as far as I can see it's hardcoded in 2 places:

https://github.com/kubernetes-incubator/kube-aws/blob/master/builtin/files/etcdadm/etcdadm#L506
https://github.com/kubernetes-incubator/kube-aws/blob/master/builtin/files/etcdadm/etcdadm#L802

I haven't made any change yet, I got the v0.12.x and tried to compile but get this error:

```# github.com/kubernetes-incubator/kube-aws/model
model/custom_file.go:58: undefined: strings.Builder
make: *** [build] Error 2
```
