### ISSUE TITLE
official repo for kube-aws born docker images

### ISSUE THREAD

**Issue by redbaron** [kubernetes-incubator/kube-aws#769]
Right now we have one docker image created as part of kube-aws feature: `journald-cloudwatch-logs` which lives in a @jhollinshead's private repo which is less than desirable. We should have kube-aws project in docker hub and quay.io where images like that can be published. 

We already have https://github.com/kube-aws GitHub org, so we can start using it more or less straigh away, right?

Rough plan looks like following:

- [x] (@mumoshu) invite members of kube-aws project to kube-aws GitHub organisation
- [ ] (@jhollinshead) move journald-cloudwatch-logs code to kube-aws github project
- [ ] configure quay.io and hub.docker.com repositories. Who owns write access to these repos?
- [ ] configure CI (CircleCI?) to automatically build and publish images

**Comment by mumoshu** [comment]
@redbaron @jollinshead Thanks for the suggestion 👍 

I've invited you two to the org. @redbaron you have an admin privilege - please feel free to invite @jollinshead to the org temporarily or permanently to transfer not code but whole the journald-cloudwatch-logs repo from your account to the org.

If you'd like to just push code, I've created https://github.com/kube-aws/docker-journald-cloudwatch-logs and https://github.com/kube-aws/journald-cloudwatch-logs for you, the former is prefixed with `docker-` to better represent that it will be hosting Dockerfile and its companions.
If you'd like to transfer the whole repo, please delete these repos I've created 👍

**Comment by mumoshu** [comment]
@jollinshead @redbaron Please let me know if there is anything I can help to get this done.

**Comment by mumoshu** [comment]
FYI we already have [the "kubeaws" org. at DockerHub](https://hub.docker.com/u/kubeaws/dashboard/), which currently hosts only awscli image.

Feel free to open dedicated issue for each docker image you'd want to host. I believe I've provided you two enough GitHub permissions to create your own git repositories to start with, under the kube-aws org.
I can also invite you to the org in DockerHub for managing repositories and automated-builds, etc.
Please share me your usernames in DockerHub when necessary!
