### ISSUE TITLE
Reusing an existing autoscaling notification target

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#771]
Extracted from https://github.com/kubernetes-incubator/kube-aws/issues/747#issuecomment-314756229
cc @VinceMD @mclarke47

**Comment by VinceMD** [comment]
Will test. Could you remind what to  change to cluster.yml

**Comment by mumoshu** [comment]
@VinceMD Thanks 👍 Please fill in `autoscalingNotification.target.arn` in cluster.yaml with the arn of your sns topic or sqs queue.

**Comment by VinceMD** [comment]
So the generated Cloud Formation contains the following:

`    "Resources": {
        "ASGNotificationRole": {
            "Properties": {
                "AssumeRolePolicyDocument": {
                    "Statement": [
                        {
                            "Action": [
                                "sts:AssumeRole"
                            ],
                            "Effect": "Allow",
                            "Principal": {
                                "Service": [
                                    "autoscaling.amazonaws.com"
                                ]
                            }
                        }
                    ],
                    "Version": "2012-10-17"
                },
                "Policies": [
                    {
                        "PolicyName": "root",
                        "PolicyDocument": {
                            "Version": "2012-10-17",
                            "Statement": [
                                {
                                    "Effect": "Allow",
                                    "Action": [
                                        "sqs:SendMessage",
                                        "sqs:GetQueueUrl"
                                    ],
                                    "Resource": "arn:aws:sqs:ap-southeast-2:MYACCOUNT:kuve-aws-asg-notificationtarget-001-ASGNotificationTarget-1H3UPX661G2FQ"
                                }
                            ]
                        }
                    }
                ]
            },
            "Type": "AWS::IAM::Role"
        },`

I was under the impression that we were trying to avoid IAM role creation. So that kube-aws can be used in tightly controlled environment where any IAM role is created centrally by a Security/Cloud team as a one off activity.
I expected to see no resource created and just the autoscalingNotification Arn passed onto the Control-Pane script.
Correct me if I'm wrong here :)

**Comment by mumoshu** [comment]
@VinceMD Thanks for the report!
Are you sure you've specified an arn like:

```yaml
autoscalingNotification:
  target:
    arn: <arnhere>
```

The role should not be created by CFN when you've specified `autoscalingNotification.role.arn`.
Similarly the notification target should not be created by CFN when you've specified `autoscalingNotification.target.arn`.

**Comment by mumoshu** [comment]
@VinceMD Anyway, we're going to decide that the autoscaling notification role and target to be unnecessary. Would you mind testing #780 instead, which removes the role and the target altogether?

**Comment by mumoshu** [comment]
Closing this in favor of #780

**Comment by VinceMD** [comment]
`autoscalingNotification:
  target:
    arn: arn:aws:sqs:ap-southeast-2:MYACCOUNT:kuve-aws-asg-notificationtarget-001-ASGNotificationTarget-1H3UPX661G2FQ
`
is that I had in my cluster.yml . The SQS blocked had indeed disappeared but role remained. Anywy

ok re #780 , this will make my life even easier. I will test soon

**Comment by mumoshu** [comment]
@VinceMD Yes, just for clarification but you also had to specify the role arn to skip creation of a role.
Thanks for your cooperation anyway 👍

**Comment by whereisaaron** [comment]
@mumoshu if I want to get my own SNS notifications for ASG events (without disturbing node drainer lifecycle hooks), is that some I can specify in `cluster.yaml` or that would require some sort of add on, to add my SNS topic to the CF output?
