### ISSUE TITLE
journald-cloudwatch-logging: Streaming details of failed units

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#772]
@jollinshead This is a feedback on the great feature you've introduced 👍 

I have:

```
Creating AWS resources. Please wait. It may take a few minutes.
Printing filtered Journald logs for log group 'k8s1'...
NOTE: Due to high initial entropy, failures may occur during the early stages of booting.
ip-10-0-0-65.ap-northeast-1.compute.internal: "journald-cloudwatch-logs.service: Failed with result 'exit-code'."
ip-10-0-0-65.ap-northeast-1.compute.internal: "etcdadm-check.service: Failed with result 'exit-code'."
ip-10-0-0-169.ap-northeast-1.compute.internal: "kubelet.service: Failed with result 'exit-code'."
ip-10-0-0-169.ap-northeast-1.compute.internal: "install-kube-system.service: Failed with result 'exit-code'."
ip-10-0-0-169.ap-northeast-1.compute.internal: "install-kube-system.service: Failed with result 'exit-code'."
ip-10-0-0-169.ap-northeast-1.compute.internal: "install-kube-system.service: Failed with result 'exit-code'."
```

which made me an idea that it would be more useful if it streamed why `install-kube-system.service` failed.
WDYT?

**Comment by redbaron** [comment]
Change filter to include install-kube-system.service. You can play in AWS CloudWatch console with filters to find one which works best for you

**Comment by mumoshu** [comment]
@redbaron Thanks for the info! I'll try and report back here.

**Comment by jollinshead** [comment]
@mumoshu The customisable 'filter' variable gives a user the ability to specify their own AWS logs filter. The default filter `{ $.priority = "CRIT" || $.priority = "WARNING" && $.transport = "journal" && $.systemdUnit = "init.scope" }` at least notifies .service failures.

It's possible that more complex filters are implemented to help diagnose the .service failures (or any other issues logged by Journald). If someone produces an improved filter definition, we can always replace the existing default filter definition for the better.
