### ISSUE TITLE
Passing security parameters to rkt when fetching

### ISSUE THREAD

**Issue by VinceMD** [kubernetes-incubator/kube-aws#776]
In my corporate network,  quay.io and gcr.io are proxied. 
The solution is to pass those parameters to rkt:  `--insecure-options=image,tls`

Example:  
`rkt fetch --insecure-options=image,tls quay.io/coreos/etcd:v3.2.1`

Could we specify it as an option for all rkt fetch? Something configurable in cluster.yml? Is there another alternative?

**Comment by redbaron** [comment]
You can have custom systems unit file which will prefetch necessary imaged with flags you like
 
If tat is not enough, you can use gir workflow https://github.com/kubernetes-incubator/kube-aws/issues/462 to customize any part of your setup.

**Comment by VinceMD** [comment]
thanks. I was wondering why the fetch is harcoded in etcd user data. Everywhere else (controller and node userdata scripts), the scripts will try to use the image and if not found, I believe rkt will automatically fetch it.

By having rkt fetch command coded in this script, it does not matter if I've pre-fetched the image. It will still try to run this command, even if the image is already there. And in my case it will fail.
No big deal, just annoying. If it's required, I can live with that.

Thanks for the tip for git workflow, I'll use that for now.
