### ISSUE TITLE
Suggestion: Validate if existing subnets have appropriate tags added

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#779]
As required by K8S, and emit validation errors accordingly so that users can notice what action(s) are required in order to deploy a kube-aws cluster into existing subnet(s).

Ref https://github.com/kubernetes-incubator/kube-aws/issues/52#issuecomment-316167577

cc @redbaron @c-knowles @danielfm @camilb

**Comment by redbaron** [comment]
It can't be an error as tags are not mandatory for cluster to function. lets say if service type LoadBalancer is never used, then no tags is needed. It can be a warning at best.

**Comment by mumoshu** [comment]
@redbaron Good point 👍 
I was under the impression that we'd want to enable `type: LoadBalancer` services even for a cluster deployed into existing subnet(s) but yes, the service type isn't addressed even in the K8S conformance test hence it can not be said as a "requirement" of a K8S cluster.
A warning would be nice.
