### ISSUE TITLE
Use placement groups for low latency networking between nodes in an instance group

### ISSUE THREAD

**Issue by kylegato** [kubernetes-incubator/kube-aws#784]
Placement groups can lower the latency for network traffic between nodes and increase bandwidth between nodes. kube-aws should allow for an option which allows people to use placement groups in AWS when spinning up instance groups.

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/placement-groups.html

**Comment by redbaron** [comment]
Hi, this would be a good improvement for all latency sensitive tasks indeed.

Power of kube-aws is that it provides endless customization options. You can add placement group to `stack-templates/node-pool.json.tmpl`  and make it work for you. Then you can have feature you want without waiting for kube-aws to support it.

Once you made it work and feel like it worth contributing back, please make a PR so other users running latency sensitive workloads can benefit from it.
