### ISSUE TITLE
kube-aws render credentials fails with `structure error: tags don't match`

### ISSUE THREAD

**Issue by sdanieru** [kubernetes-incubator/kube-aws#785]
Hi,
I'm following the instructions here:
https://coreos.com/kubernetes/docs/latest/kubernetes-on-aws-render.html

since I have an existing CA, i'd like kube-aws to create credentials with my existing CA, but when I attempt to run the `kube-aws render credentials` command, I get:
`Generating credentials...
-> Parsing existing TLS CA
Error: failed parsing ca key: asn1: structure error: tags don't match (2 vs {class:0 tag:16 length:64 isCompound:true}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} int @2`

My ca key does need a passphrase, but I see no way to supply the passphrase to kube-aws; perhaps this is why it's failing.

Does kube-aws support interacting with a CA that requires a passphrase?

**Comment by redbaron** [comment]
We are in the same boat, I am trying to make kube-aws work with external CA, so expect usability of this aspect to somewhat improve in the future (maybe :) )


As for now, contrary to what docs say, I'd recommend not to export ca-key from CA (many correctly configured CAs wont even allow you to do so), but use your CA to generate all certificates and place them under appropriate locations

**Comment by sdanieru** [comment]
@redbaron - good to know, thanks! this being my first go w/ kube-aws, i'm not quite sure what the system will look like/ what instances I'll need to create certs for so I suppose I'll just forge ahead and then create certs once I can see what I've got.

Sounds like you're working on contributing an improvement to kube-aws in this regard?

**Comment by redbaron** [comment]
When you run `kube-aws render credentials` it creates .pem files, so use them as a reference which certs need to be created, just overwrite files with those, issued by your CA.

If you feel like contributing you can add new command `kube-aws render csr` where it produces .csr files you can use to submit to your CA for signing.

**Comment by sdanieru** [comment]
so I ran `kube-aws render stack` and it's looking like I need to generate certs before I actually stand up the k8s cluster - where in the generated configs/templates can I look to figure out what instances will be created and their respective hostnames so I can generate certs and place them in the `certificates` dir?

**Comment by redbaron** [comment]
`kube-aws render credentials`
