### ISSUE TITLE
Custom resource tag does not propagate to worker

### ISSUE THREAD

**Issue by VinceMD** [kubernetes-incubator/kube-aws#790]
From my  cluster.yml:
`stackTags:
  'companystuff:focalPoint:applicationId': XXX` where XXX is a number

Etcd and Controllers get the tag. Worker does not. Tag is not present on the ASG for worker but is for etcd and controller ASG.
Is this on purpose? 

Small thing, easily fixed by fixing tagging on ASG

**Comment by redbaron** [comment]
I don't see the difference between how tags are handled for worker and controller. Could it be that tags are propagated from the AWS Stack when ASG is created, but not updated? 

Worker: https://github.com/kubernetes-incubator/kube-aws/blob/61d2c058ab234e98f4cb2b0acdc680eeeaa8319a/core/nodepool/config/templates/stack-template.json#L129-L152

Controller: https://github.com/kubernetes-incubator/kube-aws/blob/61d2c058ab234e98f4cb2b0acdc680eeeaa8319a/core/controlplane/config/templates/stack-template.json#L28-L44

**Comment by VinceMD** [comment]
Note that all the other tags are present on the worker (kubernetes.io/cluster/clustername=true, etc) Only the custom one `companystuff:focalPoint:applicationId` is missing, and only for worker.

**Comment by VinceMD** [comment]
Problem solved with kube-aws v0.9.8
