### ISSUE TITLE
Update kube-proxy to match the upstream way of deployment

### ISSUE THREAD

**Issue by danielfm** [kubernetes-incubator/kube-aws#793]
Our method of deploying kube-proxy is somewhat outdated. As far as I know, these are the things we must do to address that:

- Convert kube-proxy to a DaemonSet (pay attention to the required tolerations)
- Use the `kube-proxy` service account to authorize requests from kube-proxy pods
- Use the `--kubeconfig` flag to specify the API server location + service account credentials

Reference: [kubeadm](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/addons/manifests.go)

**Comment by redbaron** [comment]
These in theory can be solved by calling kubeadm in "render only mode" at "kube-aws render" time should it support it.

Manifests should be then saved to `manifests` directory as in https://github.com/kubernetes-incubator/kube-aws/issues/920 . Remaining quesiton how to communicate relevant params to kubeadm (such as cluster dns ip, or serviceCIDR should it be important)

**Comment by redbaron** [comment]
Remaining quesiton is how to make kubeadm produced manifests play nicely with templating. Lets say daemonset needs `serviceCIDR` param from cluster.yaml, so kubeadm need to produce "templatable" manifests, is it even possible? Maybe it would be easier to vendor whole kubeadm and pull and transform templates the use. 


I'd say either way wont save you any work, as unless we use kubeadm to produce whole cluster (which doesnt seem to be tailored well to ASG usecase), relying on kubeadm's templates would be more troublesome than just copying what they do from time to time.
