### ISSUE TITLE
Update Kubernetes to 1.7.3

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#799]

**Comment by Vrtak-CZ** [comment]
1.7.3 released - https://github.com/kubernetes/kubernetes/releases/tag/v1.7.3

**Comment by c-knowles** [comment]
@Vrtak-CZ hopefully CoreOS publishes it soon - https://quay.io/repository/coreos/hyperkube?tag=latest&tab=tags.

**Comment by mumoshu** [comment]
Resolved via #817.
Thanks for the contribution 👍

**Comment by Vrtak-CZ** [comment]
CoreOS released 1.7.3 hyperkube https://quay.io/repository/coreos/hyperkube?tab=tags we should open new issue and close this one.

**Comment by c-knowles** [comment]
Let's get it updated.

**Comment by redbaron** [comment]
Fixed by #830
