### ISSUE TITLE
Observability of the cluster provisioning process

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#802]
This is an umbrella issue for #748 #801.

According to those improvements, I believe we'd generally want more observability in your cluster provisioning process.
If the process failed due to AWS resource limit(s), invalid userdata, etc., kube-aws should tell the user about those failure reasons so that the user can act accordingly without wasting time trouble-shooting.

cc @jollinshead @redbaron

**Comment by jollinshead** [comment]
Once https://github.com/kubernetes-incubator/kube-aws/pull/801 is implemented, we could introduce a filter to show CREATE_FAILED (and any other similar) events.

**Comment by mumoshu** [comment]
@jollinshead That sounds great 👍
