### ISSUE TITLE
`awsNodeLabels` is broken for node pools backed by spot fleets

### ISSUE THREAD

**Issue by paalkr** [kubernetes-incubator/kube-aws#803]
Currently if you enable

```
      awsNodeLabels:
        enabled: true 
```

in a pool that is powered by spot fleet resources the

`kube-node-label.service`

will fail because it tries to access an AutoScalingGroup and a LaunchSpesification which is of course not present with a spot fleet.

Now that AWS has launched proper tagging of spot fleet resources, this bug could be fixed (not just the feature disabled for spot fleet pools ;) ).
https://aws.amazon.com/about-aws/whats-new/2017/07/tag-your-spot-fleet-ec2-instances/

**Comment by camilb** [comment]
Hi @paalkr, thanks for the notice. I was aware of this issue and personally used a [workaround](https://github.com/camilb/kube-aws-spot-fleet-tags) to tag proper the instances from a spot fleet. 

Unfortunately the new tag property is not yet present in CloudFormation, or I was unable to find it. In consequence we have to use the same workaround but applied directly to the spot fleet, until we have the "tag" property in CloudFormation.

**Comment by paalkr** [comment]
I agree. I didn't find support for spot fleet tagging in CloudFormation as of yet either. I could ask my AWS technical account manager if there are any ETA on CF support for spot fleet tagging. It must be in the works.

**Comment by paalkr** [comment]
BTW, thanks for the workaround.

**Comment by camilb** [comment]
Your welcome

**Comment by mumoshu** [comment]
@paalkr Hi, thanks for the feedback!

Just to be clear, `awsNodeLabels` is also used for tagging nodes with instance ids, which isn't accessible via cloudformation and therefore the new tagging feature of spot fleet won't be applicable here.

However, it would be useful to throw away the `tag-spot-instance` systemd service which is used to tag spot instances with kube-aws cluster name and node pool name.

Anyway, I'll address those two in v0.9.9-rc.1 👍

**Comment by paalkr** [comment]
Perfect, thanks.
