### ISSUE TITLE
Accessing the worker iam role name from cloud-config-controller

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#805]
So that we can fully automate configuration of kube2iam.

Extracted from https://github.com/kubernetes-incubator/kube-aws/pull/713#issuecomment-311415479

cc @camilb

**Comment by camilb** [comment]
@mumoshu This is not necessary anymore as by using `--auto-discover-default-role` in kube2iam and not providing the role annotation in "kube-resources-autosave"  deployment it will automatically fallback to the default role. Fixed in #809.

**Comment by mumoshu** [comment]
@camilb Great 👍 Thanks for the improvement.
