### ISSUE TITLE
Injecting the AWS account ID into a kube2iam k8s manifest

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#806]
Probably via kube-aws' templating so that we can fully automate creation of [the kube2iam daemonset](https://github.com/kubernetes-incubator/kube-aws/pull/713/files#diff-5186d04bb20c1e42f69eab17092849d2).

Extracted from https://github.com/kubernetes-incubator/kube-aws/pull/713#issuecomment-317328034

cc @camilb @redbaron

**Comment by camilb** [comment]
@mumoshu This is also not necessary anymore. Solved in #809 by setting the `--auto-discover-base-arn`flag.
