### ISSUE TITLE
ci: bash linting tool appropriate to be integrated into our CI

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#811]
@redbaron Hi, thank you as always for your continuous efforts on the project.

I'm asking about this topic firstly to you because I assume you are the CBO(Chief Bash Officer) of kube-aws, who writes best bash in the project 😉 
Please forward this to anyone you'd think appropriate if necessary.

I'd like to integrate something like a bash linting tool into our CI so that we can effectively ensure everyone writes "good" enough bash scripts.
Doing so would save time consumed by reviewing/fixing bash scripts on both side of the contribution - the author and the reviewer.

Would you mind advising me on the idea?

* Any tool you would recommend? (Honestly I'm aware of none)
* Any requirement(s) you'd want for the tool?
* Which lint rules should be activated?
  * func/variable names?
  * comments?
  * shell options? (`pipefail` shouldn't be enabled?)
  * idioms?

**Comment by c-knowles** [comment]
Many companies, including Google it seems, recommend using something else if the scripts are anything more than basic wrappers. For instance see https://google.github.io/styleguide/shell.xml, specifically the section on when to use shell. There they call out anything doing work with arrays or over 100 lines.

So while not directly solving this issue I might suggest we write in something like Python for more complex scripts. Those are also easier to write unit tests for using the built in test framework.

**Comment by mumoshu** [comment]
@c-knowles Thanks for the suggestion!

I think I basically agree with you.
Speaking more concretely, I don't like introducing too many programming languages & DSLs as we already have too many IMHO 😉 
So, I'd rather like to reimplement the huge script `etcdadm` in golang.
For smaller scripts like node drainer, I'd like to leave them as-is because doing so would allow users to fix them in place by running `kubectl edit`.
WDYT?

**Comment by c-knowles** [comment]
I agree, I don't mind even combining some things for example etcdadm into the same binary. For small scripts we'll need to judge whether we want users to edit without recompile etc. Then if the remaining bash scripts are still complex there's an argument to choose another scripting language and try to ensure we only use one.

https://carlosbecker.com/posts/lint-shell-scripts/ seems helpful for anything we need to do with bash.

**Comment by redbaron** [comment]
Best shell linter is https://www.shellcheck.net/ which is also available as a standalone tool

**Comment by Fsero** [comment]
shellcheck is the best linter, https://github.com/koalaman/shellcheck/wiki/TravisCI

**Comment by mumoshu** [comment]
Thanks everyone - I'll go ahead with shellcheck
