### ISSUE TITLE
Provide Container Linux SSM agent in kube-aws github org

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#813]
Recently we've been adding other kube-aws related images/apps we need to fork to the [kube-aws github organisation](https://github.com/kube-aws).

Based on https://github.com/kubernetes-incubator/kube-aws/pull/730, I'd like to add a repo and CI for a SSM agent based on the work at https://github.com/DailyHotel/amazon-ssm-agent. I'm happy to take that task, @andromedarabbit as original owner are you ok if we take that into kube-aws org and make it the default URL?

**Comment by redbaron** [comment]
We don't do it for any other images, why do it for  Amazon SSM image? There is nothing kube-aws specific there.

**Comment by c-knowles** [comment]
According to @andromedarabbit's [comment](https://github.com/kubernetes-incubator/kube-aws/pull/730#discussion_r125457859), AWS does not distribute AMD64 binaries for CoreOS so you have to build it by yourself. If we build it, it will be easier for users to link to our binary and we can ensure similar control over it without so much overhead. Ideally AWS removes this by publishing releases at some point. Similar thing applies to the journald logging which already has some repos in kube-aws.

**Comment by redbaron** [comment]
My argument is that AWS SSM image is not kube-aws project, same as dex and calico and many other images we pull in during cluster startup. We dont republish them, and users are fine with it (I assume), why we should republish https://github.com/DailyHotel/amazon-ssm-agent? 

Journald logging daemon had no official published images, DailyHotel publishes images as far as I know.

**Comment by andromedarabbit** [comment]
I believe @redbaron is right. DailyHotel/amazon-ssm-agent can not be a part of kube-aws project. If @c-knowles want to provide amazon-ssm-agent binaries for CoreOS, I am ok with that. You can replace the default Docker image on `cluster.yaml` with better-managed yours.

**Comment by c-knowles** [comment]
Ah ok. Maybe let me try to explain why I wished for us to do this. What I mean to say is my idea is to republish it under the kube-aws organisation as kube-aws/amazon-ssm-agent, make it community owned and have open CI/build/publish.

@redbaron I don't know about your company requirements but I think we cannot install such binaries that are not from the original project provider and don't provide open/transparent build and publish process. Dex, Calico etc are all ok in that respect.

Amazon SSM is a slightly different case where someone has to build the binary. If AWS did it, we wouldn't need this conversation. As far as I can see the build process for the DailyHotel repo is not open and therefore while it may be a well known company in some countries we can't justify installing it and would have to build our own. However, maybe it won't just be me who is hesitant to install such binaries in which case those users would miss out of the box setup for the nice feature @andromedarabbit has added.

**Comment by redbaron** [comment]
>  don't provide open/transparent build and publish process. 

I agree with end goal, but in reality you can't verify neither how calico images are built, nor how AmazonSSMAgent by DailyHotel. You just decide who to trust :)

Anyway, I looked at this AmazonSSM agent and it appears to be a go binary. Difference in packaging is more about init file and packaging format itself with .deb provided for Debian derivatives. So what we can do is download `ExecStartPre=`  their officially published RPM file `https://s3-${REGION}.amazonaws.com/amazon-ssm-${REGION}/${VERSION}/linux_amd64/amazon-ssm-agent.rpm`,  then unpack it and use on CoreOS. This way we'd have no need to build/pull third part images, would it be OK?

**Comment by c-knowles** [comment]
My belief is that would be acceptable from a trust perspective for the majority of users.

**Comment by redbaron** [comment]
Totally untested

```
PrivateTmp=True
ExecStartPre=/usr/bin/curl -f -o /tmp/amazonn-ssm-agent.rpm https://s3-${REGION}.amazonaws.com/amazon-ssm-${REGION}/${VERSION}/linux_amd64/amazon-ssm-agent.rpm
ExecStartPre=/usr/bin/rkt run \
                  --insecure-options=image \
                  --trust-keys-from-https \
                  --volume tmp,kind=host,source=/tmp \
                  --mount volume=tmp,target=/tmp \
                  docker://amazonlinux -- /bin/bash -c 'rpm2archive /tmp/amazon-ssm-agent.rpm | tar -C /tmp -xv'
ExecStartPre=/bin/mv /tmp/amazon-ssm-agent/bin/... /opt/ssm/bin/
ExecStart=/opt/ssm/bin/....
....
```
