### ISSUE TITLE
Intermittent container image pull errors?

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#822]
I personally have never encountered such issues but we'd better retry `rkt run`s on image pull errors?

All the `cloud-config` referencing `rkt run` would be affected.

cc @redbaron 

Extracted from https://github.com/kubernetes-incubator/kube-aws/pull/765#discussion_r127253007

**Comment by redbaron** [comment]
Most of our pulls are *not* in Type=oneshot systemd unit, so no real need for a pull loop, as there is a systemd restart loop :) Where it was really crucial is during initial userdata pull from S3

**Comment by mumoshu** [comment]
@redbaron Thanks! As userdata pulls are already wrapped into while-loops, can we close this issue then?
