### ISSUE TITLE
Autoscaling a node group to 0

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#846]
Details at https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/aws#scaling-a-node-group-to-0.

**Comment by whereisaaron** [comment]
Confirming that scaling to zero works with the cluster autoscaler and `kube-aws` 0.9.9 for both regular and spot node pools.

**Comment by c-knowles** [comment]
Fixed in https://github.com/kubernetes-incubator/kube-aws/issues/1169 by https://github.com/kubernetes-incubator/kube-aws/pull/1181.
