### ISSUE TITLE
aws ELB scaling event deletes network interfaces and makes nodes NotReady

### ISSUE THREAD

**Issue by meonkeys** [kubernetes-incubator/kube-aws#854]
We have a `kube-aws`-provisioned k8s cluster in us-west-2. A couple times a month EC2 "scaling events" take down our cluster. In their own words...

> Thank you for contacting AWS Support. I have looked into why ENIs eni-deadbee0 and eni-deadbee1 were deleted, and found they both belonged to the underlying hardware that runs Elastic Load Balancer "k8s-test-ElbAPISe-XXXXXXXXX-999999999.us-west-2.elb.amazonaws.com". These interfaces were deleted because the load balancer itself experienced a scaling event, which automatically scales the underlying hardware of the ELB up and down in response to changes in traffic over time. This is a normal process, and nothing to worry about.
http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/introduction.html
> From the ENI page in the EC2 console, you can actually see ENIs associated with your load balancers. You can usually identify them by their description, which should be the name of the ELB.
>
> Please let me know if you have any other questions or concerns.
>
> Best regards,
> 
> Nick S.
> Amazon Web Services

The root cause looks like this in CloudTrail:

![cloudtrail management console](https://user-images.githubusercontent.com/50639/29585815-590a6ab6-873d-11e7-837b-596091e42ea1.png)

https://github.com/kubernetes/kubernetes/issues/48638 looks like the same issue/symptom but I'm creating a bug in this github repo in case (a) there's something we can do in kube-aws to deal with the issue or (b) other folks experiencing this issue will be rightly led to the upstream issue.

I hope this helps!

-Adam

**Comment by camilb** [comment]
I think is the same problem described in #598 as kubernetes/kubernetes#41916 was closed in favor of kubernetes/kubernetes#48638

**Comment by danielfm** [comment]
Closing this as dup of #598. If you find anything that diverges from what is described in that issue, please feel free to reopen this.
