### ISSUE TITLE
Automationg release notes gathering

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#857]
I had been manually writing a release note for each kube-aws release by reading git-diffs and a github issues list relevant to the release.
However the process is error-prone and time-consuming.

**Comment by c-knowles** [comment]
Any ideas how it is done for other k8s projects?

**Comment by mumoshu** [comment]
@c-knowles For the kubernetes project itself, it seems to be done by https://github.com/kubernetes/release/blob/master/relnotes
I couldn't fully understand how it works though(seems a bit lengthy shell script)
