### ISSUE TITLE
Apiserver fails to start when tokens.csv is supplied and AssetsEncryptionEnabled is false

### ISSUE THREAD

**Issue by kevtaylor** [kubernetes-incubator/kube-aws#875]
If a non-empty tokens.csv file is supplied, then the AssetsConfig.HasAuthTokens is fulfilled and the file is copied to /etc/kubernetes/auth/tokens.csv.tmp

The /opt/bin/decrypt-assets is only constructed when AssetsEncryptionEnabled is fulfilled and within that section is the section to copy the tmp file back to its correct tokens.csv form

So, if the AssetsEncryptionEnabled is not fulfilled, the apiserver cannot find the tokens file and will not start

A workaround was to force the asset copy part by
```
{{if or .AssetsEncryptionEnabled .AssetsConfig.HasAuthTokens}}
  - path: /opt/bin/decrypt-assets
```
and
```
{{- if or .AssetsEncryptionEnabled .AssetsConfig.HasAuthTokens}}
ExecStartPre=/opt/bin/decrypt-assets
{{- end}}
```

But this seems clumsy and incorrect and it seems that the decryption and hastokens components should be separated

**Comment by danielfm** [comment]
Thanks for bringing this up.

/assign
