### ISSUE TITLE
Cluster role and binding, service account for tiller

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#878]
We'd need those until RBAC is enabled by default.

https://github.com/kubernetes/helm/blob/3f336517135233ae4a65e4ea931e200adf6f7f27/docs/service_accounts.md

**Comment by mumoshu** [comment]
Tiller still works without any change after RBAC is enabled by default. I was missing that it is relying on the kube-aws-admin or the system:masters role bound to pods w/ the default service account in kube-system.

**Comment by mumoshu** [comment]
However, we should assign a dedicated service account security-wise.

**Comment by kylehodgetts** [comment]
I'm working on this now 👍
