### ISSUE TITLE
List of IAM permissions

### ISSUE THREAD

**Issue by ArchiFleKs** [kubernetes-incubator/kube-aws#88]
Hi, it would be nice to have  precise list of IAM permissions needed to be successfully deploy a cluster.

For example to delegate cluster creation to a non-admin IAM account.

**Comment by pieterlange** [comment]
The controller IAM permissions are here:
https://github.com/coreos/kube-aws/blob/master/config/templates/stack-template.json#L193

And directly continues with the IAM permissions for the worker here:
https://github.com/coreos/kube-aws/blob/master/config/templates/stack-template.json#L269

**Comment by ArchiFleKs** [comment]
@pieterlange thanks a lot ;)

**Comment by pieterlange** [comment]
Oh, like that. I think that's going to be difficult, as you need to be able to create new IAM roles from the account that's used for `kube-aws`. And with those IAM resources you can assign yourself admin privileges.

**Comment by pieterlange** [comment]
Related: https://aws.amazon.com/blogs/devops/aws-cloudformation-security-best-practices/

I don't have time to dive into this, but it's seems doable.

**Comment by gianrubio** [comment]
@ArchiFleKs currently there's no documentation for which type of permission you need. To found all the permission you can run the kube-aws up command, wait for finish, go to cloudtrail and parse all the logs.

**Comment by ArchiFleKs** [comment]
@gianrubio Thanks that a good ideas, i'll test it and report back here with a list if other find this information useful

**Comment by mumoshu** [comment]
Hi @ArchiFleKs, thanks for taking time on this!
Any chance you could find the list of IAM permissions required by kube-aws since then?
I'd greatly appreciate it if you could share your findings :bow:

**Comment by ArchiFleKs** [comment]
@mumoshu I completly forgot about it, thanks for reminding me :)
