### ISSUE TITLE
Missing autoscaler documentation in new Docs

### ISSUE THREAD

**Issue by Vrtak-CZ** [kubernetes-incubator/kube-aws#880]
In old "documentation" we have autoscaler documentation section https://github.com/kubernetes-incubator/kube-aws/blob/9dbc388be6c4d9140eaf518f8fb4dfb581688143/Documentation/kubernetes-on-aws-add-ons.md#cluster-autoscaler but in new documentation this documentation section is missing.

**Comment by Vrtak-CZ** [comment]
Yep sorry

**Comment by mumoshu** [comment]
Ok, never mind! Hope the new doc site works for you too. Please don't hesitate to leave any feedback for it 😄
