### ISSUE TITLE
Releasing v0.9.8 final

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#883]
@redbaron @danielfm @c-knowles @camilb Since we've addressed all the things planned for v0.9.8, in [our roadmap](https://github.com/kubernetes-incubator/kube-aws/pull/807/files#diff-38574c080d4e2eb38c49b86e6588ad98R59), I'm going to release kube-aws v0.9.8 final once several E2E tests have passed.

Any request, question, etc., before it actually happens? 😄

**Comment by danielfm** [comment]
![image](https://user-images.githubusercontent.com/29534/29777728-5e8558ca-8be3-11e7-8561-29483efbfdcd.png)

**Comment by camilb** [comment]
Used a build from master today to update 2 clusters. Everything looks fine.

**Comment by mumoshu** [comment]
@danielfm @camilb Thanks for the confirmation 👍 Done.
