### ISSUE TITLE
kube2iam needs to run before all other pods

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#891]
# Setup
* kube2iam enabled
* Run any pod that needs to assume a role with some access privilege that the default controller/worker role does not have
* Perform any action which will cause instances to be created - create/update stack, autoscaling up

# Expected Outcome

Newly created nodes work transparently with kube2iam and pod startup on new nodes is deterministic.

# Actual Outcome

What happens in this situation is currently a bit non-deterministic:
* If the kube2iam pod comes up first, it will start to intercept the AWS metadata calls and the other pods should get the correct permissions.
* If the other pods come up first, they will receive the standard controller/worker role and if that doesn't have the correct access they tend to restart. Depending on how the pod/app works, even on restart they may attempt to use the same controller/worker role that won't work. That in turn means they will go into the `CrashLoopBackoff` state. This can also happen if the node has many pods scheduled to begin with and kube2iam comes up last (I know as I've seen this happen as well).

# Workaround

Detect any pods in the crash loop backoff state, i.e. the ones that started prior to kube2iam. Delete them meaning fresh pods are started using the appropriate role links via kube2iam.

I'm not sure if there is any better workaround or how others are dealing with the same situation.

**Comment by mumoshu** [comment]
@c-knowles Good point 👍 
How about dealing it by adding a freshly started node an "Unschedulable" or "EC2MetadataServiceNotReady" taint to prevent pods other than kube2iam from scheduling?
After the kube2iam pod becomes ready, we can automatically untaint the node to start scheduling other pods. This way, no workaround would be required on user-side. WDYT?

**Comment by c-knowles** [comment]
No intervention from the user is the ideal state yes so if that's easy then we could try it. Another idea I was considering is to use a k8s Initializer to pause initialization of a pod until kube2iam is ready on the same node. That could also provide the ability for pods to not get initialized on nodes where kube2iam is down outside of node creation. Having written that I'm considering if this should be part of kube2iam rather than kube-aws.

**Comment by c-knowles** [comment]
I've contacted the creator of kube2iam in the hope they can shed some light on this problem.

**Comment by c-knowles** [comment]
@mumoshu what do you think about doing this as a Kubernetes Initializer? Doing it like you proposed as a taint won't add overhead to all pod startups but an Initializer will work if kube2iam fails also. I'm wondering when running kube2iam whether it failing should contribute to node health.

**Comment by mumoshu** [comment]
@c-knowles Thanks for your continuous efforts in this area!
Just curious but how would the initializer work when kube2iam was failing?
My guess was that it just pends the pod to start up until kube2iam becomes up and running - but the outcome would be as same as done with taints?
Probably I'm missing something 🤔

**Comment by c-knowles** [comment]
If kube2iam goes down not during node cycling, the initializer would ensure subsequent pods do not initialize until it's back online.

Overall I wanted this change to help clean up node start up. If we used an initializer maybe it is less clear we are targeting only that aspect. Perhaps apps would start to rely on it when they do not restart correctly if they have the wrong permissions. This problem makes me think your taint way is better as it specifically only covers node startup and not the extra use cases which would be bad for resiliency.

**Comment by c-knowles** [comment]
@mumoshu yes I agree with your assessment and also wondering if the kiam you mentioned would work better for us.
