### ISSUE TITLE
Question: Is Route53 required or optional?

### ISSUE THREAD

**Issue by ketzacoatl** [kubernetes-incubator/kube-aws#906]
Hello! I've been evaluating various tools for provisioning a kube cluster on AWS, and I'm wondering if `kube-aws` explicitly _requires_ using Route53, or if it's optional. Further, if it's optional, I'd be interested to know more about what is needed in that case, if anything.

Thanks!

**Comment by mumoshu** [comment]
@ketzacoatl Hi!

Basically, Route53 is not needed when you've somehow configured all the required DNS names to be resolvable from respective machines.

The DNS names includes:

1. Ones required by your k8s cluster components to discover each other(private/public K8S API endpoints)
2. Ones required by admins to contact the k8s API server(public K8s API endpoint)

Set `apiEndpoints[].createRecordSet` to `false` in `cluster.yaml` so kube-aws won't manage Route53 records for you.

Obviously, you probably need to manage your own DNS server other than Route53 and register DNS names to it. Finally, you point your worker and controller nodes to use your own DNS for discovering the API endpoints.

**Comment by ketzacoatl** [comment]
Great, thank you for the review and confirmation @mumoshu!
