### ISSUE TITLE
Make it possible to rotate etcd-trusted-ca.pem and ca.pem (Apiserver CA)

### ISSUE THREAD

**Issue by redbaron** [kubernetes-incubator/kube-aws#907]
Rotating ca.pem is currently not possible. This issue to track features need to be implemented to make CA rotation possible at all.  Exposing CA rotation UI to user is not part of this issue and should be tracked separately.

Currently identified missing features:
 - [ ]  Stop using ca-key.pem for `--service-account-key-file` apiserver param. Once rotated new APIServers wont be authenticating requests from serviceaccounts created before rotation happen. 
 - [ ] Expose fingerprints of all certificates in etcd-trusted-ca.pem to have visibility when it is safe to start issuing new etcd-client clients.

**Comment by mumoshu** [comment]
For anyone interested, see the upstream issue https://github.com/kubernetes/kubernetes/pull/34029 for service account signing key rotation

**Comment by mumoshu** [comment]
Also for etcd key/cert rotation in general, https://github.com/coreos/etcd-operator/issues/1033

**Comment by mumoshu** [comment]
Related: #1013 and #1146
