### ISSUE TITLE
Move flanneld + calico setup  to use Kubernetes storage

### ISSUE THREAD

**Issue by redbaron** [kubernetes-incubator/kube-aws#909]
Flanneld + calico, a.k.a. canal setup can use Kubernetes as storage instead of Etcd. This removes need to keep Etcd certificate on all nodes, making whole setup more secure, as access to etcd grants unlimited powers to malicious user.

**Comment by jeremyd** [comment]
I just enabled Calico on my cluster and a bunch of reading led me to believe that Kubernetes storage for calico does not support EGRESS.  Only INGRESS.  To get EGRESS support you must use the etcd backend.

**Comment by redbaron** [comment]
@jeremyd , Kubernetes network policy support ingress rules only and KDD is sufficient enough to implement it.

Egress rules is a calico-specific feature which has very little to do with Kubernetes.

**Comment by jeremyd** [comment]
@redbaron I realize that, just pointing out that users (such as myself) might want EGRESS and are only using calico for that specific feature.  Otherwise we don't need calico..

**Comment by mumoshu** [comment]
@jeremyd Hi, thanks for sharing the hard won info!

I think I understand your use-case.
Probably we need a switch for choosing a calico backend then?

Anyway, would you mind adding links to the related readings here so that everyone has chances to decide which backend one should use?

**Comment by redbaron** [comment]
@jeremyd , I was under the impression that Calico would let you run user controlled calico+node daemonset + k8s policy controller and etcd for them (probably managed by etcd-operator) alongside KDD setup managed by kube-aws, but it seems that endpoints i etcd are created by CNI plugin,not by policy-controller.

Thanks for heads up, we'll make datastore type switch to keep both options available.

**Comment by redbaron** [comment]
Egress rules in NetworkPolicy are part of 1.8  release https://github.com/kubernetes/kubernetes/pull/51351

Calico support is expected to arrive too.

**Comment by mumoshu** [comment]
Talking with @davidmccormick about implementing this.

See https://kubernetes.slack.com/archives/C5GP8LPEC/p1519213974000090 for more details, contexts.

**Comment by davidmccormick** [comment]
The Canal project has this 3 container setup which incorporates calico/flannel/cni-install into a DS deployed to each node.  Link here https://github.com/projectcalico/canal/blob/master/k8s-install/1.7/canal.yaml.

I used this model at Zopa for our home rolled clusters and it worked well.

**Comment by mumoshu** [comment]
@davidmccormick Thanks for the valuable info!

I believe that we're talking about the 3rd option of https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/hosted/kubernetes-datastore/#option-3-calico-policy-only-with-flannel-networking. Please correct me if I'm wrong.

**Comment by mumoshu** [comment]
I'm wondering what limitations exist after reading [old calico doc](https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/canal/#requirements--limitations) vs [the new one](https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/hosted/kubernetes-datastore/#option-3-calico-policy-only-with-flannel-networking).
For example, does ipam issue really exist even when we used canal?

**Comment by mumoshu** [comment]
This Canal setup is getting more important as it would solve ip addr exhaustion issue https://github.com/coreos/flannel/issues/954 in shorter term

**Comment by mumoshu** [comment]
Note: calicoctl doesn't work for Canal+K8S API backend setup. Thx to @davidmccormick for the info

**Comment by redbaron** [comment]
calicoctl works with k8s datastore starting from version 3.0.1

**Comment by mumoshu** [comment]
Thx for the info. Such a nice change for a patch version :)
