### ISSUE TITLE
Self hosted apiserver and controller-manager

### ISSUE THREAD

**Issue by redbaron** [kubernetes-incubator/kube-aws#910]
It is trivial to find if current controller node is coming up first in the cluster. Then we have 2 cases.

# First APIServer ever
 - move Apiserver and controller-manager manifests to kubelet's static manifests directory
 - wait for API server to start locally on a port 8081
 - Deploy daemonset with APIServer and controller-manager 
 - Wait for APIServer started by daemonset to start locally
 - remove static manifest  for APIServer and controller-manager
 - report cfn-signal success

# APIserver already exist
 - wait for Daemonset to recognise new node and fire APIServer and controller-manager
 - report cfn-signal success

Other changes to do:
 - [ ] Make controller kubelet to talk to ELBs.
 - [ ] Controller instances added to ELB need to to have 2 ports for APIServer: 8080 (daemonset) and (8081 bootstrapping one)

**Comment by mumoshu** [comment]
@redbaron Thanks for the proposal!

Sounds good overall. I agree to the general direction. However, any idea on how does this compare with/relate to bootkube and kubeadm(#654)?

Also, assuming we're generally going towards self-hosting, don't we need "kubelet check-pointing" at least to bootstrap apiserver not only when fresh-start but also restart of the whole set of controller nodes?

Relevant upstream issue: https://github.com/kubernetes/kubernetes/issues/489

**Comment by redbaron** [comment]
(1) bootkube and kubeadm dont have a luxury  of immutable userdata + cfn-signal + cloudformation rollbacks, therefore they have to address a lot of cases where we can just get away with ~50 lines bash. Choosing between small bash script and depending on completely different project I'd be choosing bash :) For reasons of agility and simplicity

(2) check pointing is exactly the case "First APIServer ever". Either way that check would detect that no live apiservers present and kick off bootstrapping sequence

**Comment by mumoshu** [comment]
@redbaron Thanks for the clarification 😄 

Ah, so

> move Apiserver and controller-manager manifests to kubelet's static manifests directory

this can happen on every controller node by detecting the unhealthy apiserver once on startup, and periodically afterwards?

**Comment by mumoshu** [comment]
> Choosing between small bash script and depending on completely different project I'd be choosing bash :) For reasons of agility and simplicity

Yea, I'm with you 👍 

On the other hand, I'm still wanting to find the middle of two ways so that we can still fix issues like #793 in long term while also retaining agility and simplicity 😃 
WDYT?

**Comment by redbaron** [comment]
> this can happen on every controller node by detecting the unhealthy apiserver once on startup, and periodically afterwards?

Yes, self healing is trivial to implement once we have bootstrapping solution in place.
