### ISSUE TITLE
Self hosted scheduller

### ISSUE THREAD

**Issue by redbaron** [kubernetes-incubator/kube-aws#911]
AFAIK Daemonsets don't require schedulers to run, therefore kube scheduler static pod can be trivially converted to daemonset with appropriate tolerations.

**Comment by mumoshu** [comment]
@redbaron Hi! Could you elaborate a bit more about the "Daemonsets don't require schedulers" part?
After reading https://github.com/kubernetes/kubernetes/issues/42002, it seems like daemonsets still require a scheduler to schedule daemonset pods.

**Comment by redbaron** [comment]
Discussion there proves my point that DaemonSet controller is capable of scheduling pods itself

**Comment by mumoshu** [comment]
@redbaron Thanks for the clarification!

Yes, you're correct - I've reread the discussion and understands that daemonset pods are scheduled by the daemonset controller(or more concretely, it's own scheduler).

The discussion seems to indicate that, in the future, the daemonsets' scheduler can be implemented using the default scheduler as a library. Even after that, daemonset controller seems like going to have its own scheduler(based on the default scheduler, but a separate one).

Am I reading correctly?

However, I'm now unsure about (1) the overall installation procedure of k8s core components and (2) implications and edge cases.

For (1), would it look like:

* Deploy apiserver and controller-manager as static pods as we do today
* Deploy kube-proxy and scheduler as daemonsets.
  * kube-proxy should have tolerations to be properly scheduled to not only worker but also controller nodes
  * scheduler should have appropriate nodeAffinity+tolerations to run only on controller nodes

For (2),

* Deploying an incorrect `controller-manager` may results in critical, daemonset-managed core k8s components to be unfunctional
   * This is just an impllication and not a defect, right? Anyway, we can "fix" the contorller-manager by our usual workflow of running `kube-aws update`

**Comment by redbaron** [comment]
For (1) self hosting apiserver and controller manager is covered in https://github.com/kubernetes-incubator/kube-aws/issues/910

(2) Deploy of incorrect controller manager is not detected now, so no matter what we do it can't be worse than that :) Possible solution would be to run https://github.com/kubernetes-incubator/kube-aws/issues/917 to evaluate cluster health
