### ISSUE TITLE
panic / runtime error: integer divide by zero (missing etcd)

### ISSUE THREAD

**Issue by ketzacoatl** [kubernetes-incubator/kube-aws#913]
I have run `kube-aws init` to generate a `cluster.yaml`, and then edited that to point at various existing resources (VPC, subnets, KMS key). When I go to `kube-aws render stack`, I get this gem:

```
ᐅ kube-aws render stack                            
panic: runtime error: integer divide by zero

goroutine 1 [running]:
github.com/kubernetes-incubator/kube-aws/model/derived.NewEtcdNodes(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/kubernetes-incubator/kube-aws/model/derived/etcd_nodes.go:16 +0x966
github.com/kubernetes-incubator/kube-aws/core/controlplane/config.Cluster.Config(0xc4201c2ff0, 0x1, 0x1, 0x0, 0x0, 0xe227ab, 0x9, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/kubernetes-incubator/kube-aws/core/controlplane/config/config.go:761 +0x341
github.com/kubernetes-incubator/kube-aws/core/root.StackAssetsRendererFromFile(0xe25a66, 0xc, 0xc4201c2e10, 0xe1e126, 0x4, 0xe1dfe6)
        /go/src/github.com/kubernetes-incubator/kube-aws/core/root/renderer.go:14 +0x10d
github.com/kubernetes-incubator/kube-aws/cmd.runCmdRenderStack(0x14d21c0, 0x14f6ab8, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/kubernetes-incubator/kube-aws/cmd/render.go:71 +0x3d
github.com/kubernetes-incubator/kube-aws/vendor/github.com/spf13/cobra.(*Command).execute(0x14d21c0, 0x14f6ab8, 0x0, 0x0, 0x14d21c0, 0x14f6ab8)
        /go/src/github.com/kubernetes-incubator/kube-aws/vendor/github.com/spf13/cobra/command.go:647 +0x3f8
github.com/kubernetes-incubator/kube-aws/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x14d23e0, 0xc420177f50, 0x0, 0x0)
        /go/src/github.com/kubernetes-incubator/kube-aws/vendor/github.com/spf13/cobra/command.go:726 +0x339
github.com/kubernetes-incubator/kube-aws/vendor/github.com/spf13/cobra.(*Command).Execute(0x14d23e0, 0xc4200001a0, 0xc4200001a0)
        /go/src/github.com/kubernetes-incubator/kube-aws/vendor/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
        /go/src/github.com/kubernetes-incubator/kube-aws/main.go:10 +0x2d
```

It looks like it's failing on etcd in the spec. By default, the `cluster.yaml` has the etcd params commented out, but it appears they are required or otherwise leading to this error.. after adding in a section for etcd, I get:

```
ᐅ kube-aws render stack                                                
Success! Stack rendered to ./stack-templates.

Next steps:
1. (Optional) Validate your changes to cluster.yaml with "kube-aws validate"
2. (Optional) Further customize the cluster by modifying templates in ./stack-templates or cloud-configs in ./userdata.
3. Start the cluster with "kube-aws up".
```

**Comment by mumoshu** [comment]
@ketzacoatl Hi, thanks for trying kube-aws!
Would you mind sharing us your `cluster.yaml`?
AFAICS at this moment, you’re perhaps missing `subnets:` in your cluster.yaml?

**Comment by ketzacoatl** [comment]
The `cluster.yaml` I received from `kube-aws init` had the `etcd` section fully commented out. Though it seems (at least with my spec, which includes references to existing VPC, subnets and route table), this section is required.

By adding the `etcd` section like:

```
etcd:
  instanceType: t2.medium
  rootVolume:
    size: 30
    type: gp2
  subnets:
    - name: foo-01-az-a
    - name: foo-02-az-b
```

The panic goes away. `kube-aws` should catch and throw a human readable message if the `etcd` section is missing, but required for one reason or another.

**Comment by mumoshu** [comment]
FYI, an etcd cluster requires one or more public subnets or private subnets by default according to your setup. The part of the setup involves very a confusing logic explained in #929 so I'm going to make it easier by removing the logic.
Explicitly setting `etcd.subnets[]` overwrites the defaults hence no error.

Anyway, emitting a panic instead of an useful error for a misconfiguration is an orthogonal problem to that. I'm fixing it in a PR corresponds to this issue 😉
