### ISSUE TITLE
Run kuberang at the end of cluster provisioning

### ISSUE THREAD

**Issue by redbaron** [kubernetes-incubator/kube-aws#917]
Kuberan is a set of tests to be confident that cluster is functional. https://github.com/apprenda/kuberang

Running Kuberang can be done either via custom resource or from kube-aws itself.

**Comment by mumoshu** [comment]
@redbaron Thanks for the suggestion again 👍 

Just curious but how does kuberang compare with [sonobuoy](https://github.com/heptio/sonobuoy) from heptio?

**Comment by redbaron** [comment]
sonobody takes much longer and looks more like a compliance check rather than "does it work at all" check which kuberang  is. Kuberang completes in just ~2 min and gives enough confidence that cluster isn't completely broken at the end of `kube-aws apply`

/cc @dvdthms

**Comment by mumoshu** [comment]
Made perfect sense!

Should we run it from within one of controller nodes, or from the machine where the kube-aws command was run?

**Comment by dvdthms** [comment]
I'll soon be opening PRs to the kuberang project to add a dockerfile, and helm charts too. I've included a manifest for a CronJob, so we can regularly monitor the basic cluster functionality, I can add one for just a Job too -- if you want to run it as a one-off smoke test?

Let me know what you think, I'll give any updates I make too :)
