### ISSUE TITLE
Create manifests directory where all the yamls we install are rendered to

### ISSUE THREAD

**Issue by redbaron** [kubernetes-incubator/kube-aws#920]
Instead of having yaml files inside userdata, we should have `./manifests` directory produced by `kube-aws render` where all of them are saved.

Files should be templated in the same way before they are injected into instances' userdata or custom cloudformation resource to apply them.

**Comment by mumoshu** [comment]
This would also help us smoothing the migration path from coreos-cloudinit to ignition because doing this result in less diffs in configs between the two.
