### ISSUE TITLE
Enable TLS bootstrap by default

### ISSUE THREAD

**Issue by danielfm** [kubernetes-incubator/kube-aws#922]
As mentioned in #721, enabling TLS bootstrap is something we would likely do in some future version of kube-aws, so I'm leaving this issue here so we can track this.

This would enable us to remove some code from kube-aws (which is always a good idea), such as:

- Code responsible for generating the worker certs
- RBAC roles and bindings associated with the `kube-worker` user
- Validation code that verifies whether some feature is eligible to be turned on, such as the node authorizer
- etc

**Comment by mumoshu** [comment]
@danielfm As a security enhancement, I believe the sooner is the better. I'd suggest to enable it by default starting v0.9.10-rc.1.
