### ISSUE TITLE
Is it hard for a first-time user to correctly configure `createRecordSet` + `hostedZone.id`?

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#928]
I have been occasionally asked to debug why one's cluster failed while creating worker nodes.

The cause tend to be `createRecordSet: false` in cluster.yaml - without suprises - which is the default when one run `kube-aws init` without `--hosted-zone-id`. Someone misses to set `apiEndpoints[].loadBalancer.hostedZoneId` altogether while someone does not, which seems hard to notice the difference for a first-time user.

How could we improve the situation?

My suggestion is:

1. Completely remove `apiEndpoints[].loadBalancer.createRecordSet` and make kube-aws creates a record set for you whenever `apiEndpoints[].loadBalancer.hostedZone.id` is specified
   * I can't remember why we had needed `createRecordSet` in the first place 😉
   * What could `hostedZone.id` be used for when `createRecordSet: false`. Similarly, what could `createRecordSet: true` do when `hostedZone.id` is not present? If nothing, shouldn't we just create the record set when the hosted zone id is present?

2. Make `kube-aws init` require `--hosted-zone-id` by default and allow it to be omitted when and only when a flag like `--bring-your-own-dns` is explicitly provided by the user.

@c-knowles @redbaron @danielfm @camilb WDYT?

**Comment by camilb** [comment]
@mumosho I agree with you. I believe the most users are using Route53, especially new users that are creating test clusters first and need a fast start.
Requiring the `--hosted-zone-id` flag and creating the record automatically it's a good choice. 
For users that have a different DNS provider we can use a different flag and show a warning to remind creating the record.

**Comment by mumoshu** [comment]
@camilb Thanks for expressing your interest 👍 
I've submitted #936 for this. Would you mind reviewing it?
