### ISSUE TITLE
Support GovCloud Deployments

### ISSUE THREAD

**Issue by philipsoutham** [kubernetes-incubator/kube-aws#930]
Please support deployments to [GovCloud](https://aws.amazon.com/govcloud-us/). Out of the box it doesn't work by simply specifying the region because the s3 endpoints and arn prefixes are different.

Thanks,
Philip

**Comment by mumoshu** [comment]
@philipsoutham Hi, thanks for trying kube-aws!

Yes, I believe kube-aws should support GovCloud OOB.

According to your info, it seems like all the necessary changes would be made in https://github.com/kubernetes-incubator/kube-aws/blob/master/model/region.go
We already have a support for China region there.

Anyway, I'd be happy to review and accept any contribution about this.
I guess I can do it for you if you could help testing. I'm afraid I can't test it myself as I don't have access to GovCloud.

**Comment by mumoshu** [comment]
@philipsoutham Hi. Would you mind confirming if kube-aws works in GovCloud now as #963 has been merged?

**Comment by weisjohn** [comment]
@mumoshu I'm happy to test for you, but am unsure how to proceed. The "Pre-requisites" section of https://kubernetes-incubator.github.io/kube-aws/tutorials/quick-start.html in step 4 says I need to "Have a Route 53 hosted zone ready to expose the Kubernetes API and record the hosted zone ID and domain name for step 2 in this guide".

**Comment by weisjohn** [comment]
Ok, I see the `--no-record-set` option from the CLI output, but I'm unsure how I'll go about configuring this.

```
WARN: the worker node pool "nodepool1" is associated to a k8s API endpoint behind the DNS name "test.mydomain.tech" managed by YOU!
Please never point the DNS record for it to a different k8s cluster, especially when the name is a "stable" one which is shared among multiple k8s clusters for achieving blue-green deployments of k8s clusters!
kube-aws can't save users from mistakes like that
```

At this point, I'm thinking I need to point `test.mydomain.tech` to something within the system? Any tips would be appreciated.

**Comment by weisjohn** [comment]
For those coming after me, you will need to point a CNAME DNS record for the value of `external-dns-name` to the DNS entry for the ELB for your k8s cluster, which you can find in your AWS Console in the EC2 > ELB settings area.
