### ISSUE TITLE
Support cri-o runtime

### ISSUE THREAD

**Issue by redbaron** [kubernetes-incubator/kube-aws#941]
With official Docker version support being frozen on 1.12.x, no so long there will be a  need for alternative.

It seems that there is  new player CRI-O, which is presented as a kubernetes compatible container runtime designed around kubernetes in mind. From https://www.projectatomic.io/blog/2017/06/6-reasons-why-cri-o-is-the-best-runtime-for-kubernetes/

> CRI-O directly implements the Kubernetes Container Runtime Interface and the only supported user is meant to be Kubernetes. CRI-O is entirely shaped around Kubernetes, you won’t ever see a feature being added if it isn’t strictly necessary for Kubernetes.
> We do run upstream Kubernetes node-e2e tests and e2e tests before accepting any patch. If our CI isn’t green you must fix your code. Test suites are also run before any release. In addition to the Kubernetes tests, CRI-O has its own integration tests and the CRI-O development community is continually adding to them. Unlike other container runtimes meant to work with other container orchestrators, CRI-O will block a release on any breakage of the Kubernetes test suites. You read it right, we’re going to block a release if it breaks Kubernetes.

"Kubernetes the hard way" guide was recently updated to use cri-o as a runtime too.

**Comment by Vrtak-CZ** [comment]
Just a note https://github.com/kubernetes/kubernetes/issues/42926

**Comment by resouer** [comment]
@redbaron Docker 1.13.x and 17.x will still be officially supported. Also, please check https://github.com/kubernetes-incubator/cri-containerd

**Comment by Vrtak-CZ** [comment]
CRI-O 1.0 released https://github.com/kubernetes-incubator/cri-o/releases/tag/v1.0.0

**Comment by camilb** [comment]
I think it's useful to know that e2e tests using Docker 17.09  are [passing](https://scanner.heptio.com/fe47f9cc7f15ea00d48530407227814a/diagnostics/) and that CoreOs will switch to Docker 17.09 in the stable channel starting December 6 2017.

`December 6, 2017: The stable channel defaults to Docker 17.09 unless /etc/coreos/docker-1.12 is set to yes.`

More info [here](https://coreos.com/blog/toward-docker-17-in-container-linux)

**Comment by c-knowles** [comment]
@mumoshu how do we feel about supporting containerd or even replacing docker with it?https://kubernetes.io/blog/2018/05/24/kubernetes-containerd-integration-goes-ga/

**Comment by jorge07** [comment]
I think containerd is the way to do. I've been fighting with docker bugs during the last year and it can be solved moving to containerd
