### ISSUE TITLE
Support drop-ins in customSystemdUnits

### ISSUE THREAD

**Issue by groner** [kubernetes-incubator/kube-aws#946]
I'd like to use drop-ins to modify existing systemd units, but the customSystemdUnits schema/template don't support them.

https://github.com/coreos/coreos-cloudinit/blob/master/Documentation/cloud-config.md#units

**Comment by jeremyd** [comment]
@groner, this PR adds the ability to create drop-ins inside the customSystemdUnits section of the cloud-config.  Does this meet your needs?

**Comment by groner** [comment]
@jeremyd, thanks for responding to my feature request.  I've responded on the PR.
