### ISSUE TITLE
--ami-id seems to be ignored

### ISSUE THREAD

**Issue by Savar** [kubernetes-incubator/kube-aws#948]
Running a command with `kube-aws --ami-id=AAAA` won't fail nor will it write AAAA anywhere into the `cluster.yaml`

`kube-aws version v0.9.7`

**Comment by Vrtak-CZ** [comment]
duplicate: https://github.com/kubernetes-incubator/kube-aws/issues/764

**Comment by Savar** [comment]
uh damnit.. my search didn't work then as expected 😞 sorry
