### ISSUE TITLE
Only public load balancer for kubernetes services

### ISSUE THREAD

**Issue by Huron** [kubernetes-incubator/kube-aws#953]
The controller creates an public load balancer for my Service object. But I wish to create internal load balancer. How cant I change this setting?

**Comment by camilb** [comment]
If you mean for your own services, then you have to add an annotation, similar to this one:

    [...]
    metadata:
        name: my-service
        annotations:
            service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    [...]

More info here: [internal-load-balancer](https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer)
