### ISSUE TITLE
Complication upgrade from 0.9.7 to 0.9.8

### ISSUE THREAD

**Issue by billyteves** [kubernetes-incubator/kube-aws#956]
Hi,

Will there be any complication upgrading the kube cluster from 0.9.7 to 0.9.8? What about the certificates? Do we also need to re-generate this? 

Thanks!

**Comment by redbaron** [comment]
which certificate?certs rotation is not supported right now AFAIK. It is possible, but detailed understanding is required and 2 phase rollout is necessary.

**Comment by billyteves** [comment]
The contents from the credentials folder, do I need to do `kube-aws render credentials --generate-ca` again? of I'll just save the contents then upgrade to kube-aws 0.9.8 and make sure that the cluster.yaml is almost same as the current config from my 0.9.7?

**Comment by jeremyd** [comment]
@billyteves I would try first not re-rendering the credentials.  Eg.
```
kube-aws render stack
kube-aws validate --s3-uri s3://mycluster
kube-aws up --export --pretty-print --s3-uri s3://mycluster
```
This will output the cloudformation templates which you can load into aws and see if the differences are as you expect before running an upgrade.

**Comment by whereisaaron** [comment]
Good @jeremyd. It would be a nice testing feature @mumoshu if `kube-aws update` had the option to create and export a CF Change Set. I miss no `terraform plan` option in `kube-aws`.

**Comment by mumoshu** [comment]
@whereisaaron I miss it badly, too. One thing blocking us is that the ChangeSet feature doesn't support Nested Stacks kube-aws' relying on.

**Comment by whereisaaron** [comment]
Yes that is quite a blocker @mumoshu, and as of Dec 2017, [not even on the AWS road map](https://forums.aws.amazon.com/thread.jspa?messageID=819980) 😞
