### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by Y-Less** [kubernetes-incubator/kube-aws#958]
This was already asked in #524; however, that was for Windows 10 and dismissed by pointing out that the existing builds can already run there.  Are there any plans for supporting other Windows OSes, or even Windows 10 natively, since I'm on 8.1?

**Comment by mumoshu** [comment]
@Y-Less Thanks for the feedback.
Unfortunately we don't have any plans but I'm eager to accept any kinds of contributions for that!
Anyway, if it is as easy as mentioned in https://github.com/golang/go/wiki/WindowsCrossCompiling#go-version--15, we can add the Windows support soon 😉
