### ISSUE TITLE
Error reading credential file with custom CA

### ISSUE THREAD

**Issue by Y-Less** [kubernetes-incubator/kube-aws#960]
Following the guide here:

https://kubernetes-incubator.github.io/kube-aws/getting-started/step-2-render.html

I have previously set up and run test clusters using a generated CA, but wanted to switch to using my existing one.  So following that, I did:

    kube-aws render credentials --ca-cert-path=/root/ca/pki/ca.crt --ca-key-path=/root/ca/pki/private/ca.key

As far as I can tell, by comparing outputs from different command varieties, this seems to generate all the important files (though it doesn't generate `.pem.enc` or `.pem.fingerprint` files) except one - `ca-key.pem`.  Looking at `ca.pem`, which is generated, this must relate to the provided CA.  Honestly I wouldn't even want a copy of my CA's private key in there, so the fact that it isn't is good.  Except for two issues:

1) I don't know how not having it there will affect the running of the cluster.  Have the generated keys been signed?

2) The crux of this issue - I get the following error:

```
Generating credentials...
-> Parsing existing TLS CA
-> Generating new assets
Error: Error reading credential file credentials/ca-key.pem: open credentials/ca-key.pem: no such file or directory
```

As I said, all the files seem to be generated, but I can't be sure in what state - I've not had a chance to run the cluster yet.

**Comment by mumoshu** [comment]
@Y-Less Hi, sorry for the long silence. Have you enabled the TLS bootstrapping feature?
If that's the case, could you disable it?

Enabling it requires you to upload the CA key to be used by the k8s control-plane to sign the bootstrapped certs.
