### ISSUE TITLE
Can't use custom CA with encrypted key

### ISSUE THREAD

**Issue by Y-Less** [kubernetes-incubator/kube-aws#961]
I have a password on my CA private key (obviously), when trying to use it with:

    kube-aws render credentials --ca-cert-path=/root/ca/pki/ca.crt --ca-key-path=/root/ca/pki/private/ca.key

It gives an error.  The error tends to vary slightly - I'm guessing because the system is trying to read an encrypted file as a regular file, so is interpreting essentially garbage data and so will throw whatever validation failure comes up first.  This is the current error:

```
Generating credentials...
-> Parsing existing TLS CA
Error: failed parsing ca key: asn1: structure error: length too large
```

**Comment by Y-Less** [comment]
Speaking of which, my CA is restricted to the root account for more security, but it would be nice if the generated stack was not owned by the same user.  I.e. if there was a way to specify the owner of the output.

**Comment by Y-Less** [comment]
OK, it turns out this causes a validation to fail, as the keys are not encrypted until later for some reason.

**Comment by redbaron** [comment]
Generally CA wouldn't allow key to be exported. Existing CAs can issue certs for you, but CA key is not available to users.

**Comment by Y-Less** [comment]
That is the problem.  The tutorial here: https://kubernetes-incubator.github.io/kube-aws/getting-started/step-2-render.html talks about so that's what I was doing.  If there's a way to encrypt everything without using that command, I couldn't find the documentation.
