### ISSUE TITLE
Generated credentials owner is not the current user

### ISSUE THREAD

**Issue by Y-Less** [kubernetes-incubator/kube-aws#965]
My CA is restricted to the root account for more security, but it would be nice if the generated stack was not owned by the same user. I.e. if there was a way to specify the owner of the output, or use the current user.  I did mention this here;

https://github.com/kubernetes-incubator/kube-aws/issues/961#issuecomment-333786912

But thought I should make a new issue for it.

**Comment by redbaron** [comment]
Do you mean written files? Why don't directory after you finish running kube-aws
