### ISSUE TITLE
Bump the default K8S version to 1.8.x

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#974]
After we release kube-aws v0.9.9 with K8S 1.7.8.

**Comment by c-knowles** [comment]
@mumoshu do you know what we are waiting for in kube-aws v0.9.9? I don't see any issues under that milestone but don't think we had any. I'm wondering if we can cut that release.

**Comment by mumoshu** [comment]
@c-knowles I had initially planned to address all the currently remaining issues in the [milestone](https://github.com/kubernetes-incubator/kube-aws/milestone/47), however nothing stops me from giving up and rescheduling them, so that we can ship what we have now.

**Comment by c-knowles** [comment]
@mumoshu ah, that's strange the milestone didn't appear for me before but now it's there. Anyway, I don't want to press for it if there are still issues - if there is anything I can pick up let me know. Maybe some of the items to drop deprecated config I could do.

**Comment by camilb** [comment]
@mumoshu Already a month running 1.8.x in 2 dev clusters. Didn't find any issue. I think it can be safely bumped. I'll create a PR if that's ok.

**Comment by mumoshu** [comment]
@camilb Yes, I greatly appreciate it!

**Comment by mumoshu** [comment]
Resolved via #996 thanks to @camilb
