### ISSUE TITLE
Support for the Initializers admission control

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#979]
As required by #978

**Comment by redbaron** [comment]
We should just have a list of initialiers in cluster.yaml, instead of enabling them one by one

**Comment by danielfm** [comment]
Agreed. Makes things simpler on kube-aws side, and it's easier for operators to customize/manage.

**Comment by mumoshu** [comment]
Agreed 👍

**Comment by mumoshu** [comment]
The original issue was resolved via #994 thanks to @camilb!
The improvement to the configuration syntax would be addressed in #998
