### ISSUE TITLE
Allow More flannel configuration options to pass through

### ISSUE THREAD

**Issue by RyPeck** [kubernetes-incubator/kube-aws#992]
Was looking to set the `SubnetLen` for Flannel in `kube-aws`. Noticed that we can only specify the `Network` configuration option for [flannel's configuration](https://coreos.com/flannel/docs/latest/configuration.html). As a work around we choosing a new network CIDR, from `/16` to `/14` to increase the number of subnets available to hosts.

Would be helpful to at least be able to specify `SubnetLen` and perhaps the other options. I dug around looking for a reason why this wasn't possible but was unable to find one.

**Comment by kiich** [comment]
I'd like this option too and would like to know what impact of doing this would have before submitting a PR for this.
